### ISSUE TITLE
PLP price filter refills values without chosen value

### ISSUE THREAD

**Issue by ejnshtein** [scandipwa/scandipwa#1001]
**Description**:
When choosing the filter option price "Up to 100$" filter options updates without checked option.

**Expected behavior**:
The chosen price filter should be present on updated filters.

**Screenshots, Video, Logs**
https://youtu.be/82QxiRWtDC0

**To Reproduce**:
1. Go to https://demo.scandipwa.com/audio-video-photo-equipment.html
2. Click on any price filter
3. See error

**Versions**:
- ScandiPWA: 2.17.0/3.0.2

**Comment by zans-laksa** [comment]
Cannot reproduce.

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/catalog-graphql/pull/99

**Comment by carinadues** [comment]
Closed after merging scandipwa/catalog-graphql#99
