### ISSUE TITLE
404 console error on reload

### ISSUE THREAD

**Issue by devselegento** [scandipwa/scandipwa#1018]
**Description**:
In the ```demo.scandipwa.com``` wesbite, when I sign up, go to my account ```my-account/dashboard``` and refresh the page, while the page loads normally I get a 404 GET error in the console with Request URL: ```https://demo.scandipwa.com/my-account/dashboard```

**Expected behavior**:
Not getting any console errors

**Versions**:
- v 3.0.0

**Comment by maddumarala** [comment]
The issue is my-account is not exempted from router validation like cart.
IMO 'my-account' also should be pass in router validations.

`    <type name="ScandiPWA\Router\ValidationManager">
        <arguments>
            <argument name="validators" xsi:type="array">
                <item name="my-account" xsi:type="string">ScandiPWA\Router\Validator\AlwaysPass</item>
            </argument>
        </arguments>
    </type>`

**Comment by Elena-Evsa** [comment]
Now issue absent
