### ISSUE TITLE
Sort order not working for layered filter at category page

### ISSUE THREAD

**Issue by santosh-gaggle** [scandipwa/scandipwa#1345]
**Description**:
I am trying to change the sort order of the price filter but it does not change

**Expected behavior**:
sort order  should work the according to the backend position value

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/56184739/94561815-297d1780-0282-11eb-8f00-98c644aeac81.png)
![image](https://user-images.githubusercontent.com/56184739/94561870-40236e80-0282-11eb-80e7-8da91f1d17dc.png)

**To Reproduce**:
on the category page, you can find the filters 
if you want to change the sort order of any filter attribute form admin then It will not work

**Versions**:
magento 2.3.5-p2
scandipwa 3.1.1

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/catalog-graphql/pull/96 + https://github.com/scandipwa/scandipwa/pull/2445

**Comment by carinadues** [comment]
Closing since both PRs are merged

**Comment by aleksandrakorolova** [comment]
The found issue for category attribute. It will be fixed in #2749 
Other attributes work well
