### ISSUE TITLE
Bundle product discount price problem

### ISSUE THREAD

**Issue by jari646** [scandipwa/scandipwa#1347]
**Description**:
Bundle product discount is calculated wrong and product page discounted price do not show up at all.
Also currency of bundled item list show $, even currency is €

Example:
If I make bundle with price 467€ (all prices here are including vat 24%) and give 50% discount.
- in category page discounted price is 188,50€ --- In Luma M2 theme price is correct 233,50€ (467€)
- in product page you can see only original price 467€ --- In Luma M2 theme you can see correct price 233,50€ (467€)
- when you add product to shopping cart, price will be 188,50 (total) --- In Luma M2 theme price will be 233,50€

**Versions**:
- ScandiPWA: 3.x-stable
- Magento 2.3.5
- All browsers and mobile

**Comment by VuThuan** [comment]
@lion152
