### ISSUE TITLE
Category filter Price and Category is not translated

### ISSUE THREAD

**Issue by jari646** [scandipwa/scandipwa#1348]
**Description**:
When I use different language than English, category page filter heading Price and Category will not be translated even I put these into translation files.

**Versions**:
- ScandiPWA: 3.x-stable
- Magento 2.3.5

**Comment by franconicolasocchi** [comment]
Same here
ScandiPWA 4.4.0
Magento 2.4.2

**Comment by carinadues** [comment]
Closing as a duplicate of https://github.com/scandipwa/scandipwa/issues/2562
