### ISSUE TITLE
PayPal not working on demo

### ISSUE THREAD

**Issue by yeegor** [scandipwa/scandipwa#1355]
**Description**:
Currently on demo is installed a wrong PayPal version. It is 3.0.1, but it's 3.0.1 from November 2019.
That tag's been not properly released, it shouldn't have 3.x major in its version.
Hence, this must be removed from the demo. The [actual 3.0.1](https://github.com/scandipwa/paypal-graphql/releases/tag/3.0.1) should be installed.  

**Expected behavior**:
The actual 3.0.1 is installed and the PayPal payment method can be used.

**Comment by aleksandrakorolova** [comment]
Closed task because this will be an extension available in the [marketplace](https://marketplace.scandipwa.com/paypal-payment-4.html)
