### ISSUE TITLE
iPad version demo issues

### ISSUE THREAD

**Issue by ejnshtein** [scandipwa/scandipwa#1357]
**Description**:
Currently on the demo, if enable iPad emulation in portrait menu items in the header can overflow ScandiPWA logo.
In PDP long breadcrumbs can overflow their block.

**Expected behavior**:
Issues above should be resolved

**Screenshots, Video, Logs**
Demo Home page.
<img width="1051" alt="Screenshot 2020-09-30 at 17 21 17" src="https://user-images.githubusercontent.com/18352350/94699302-d8812800-0342-11eb-82e7-e101c2a36e5b.png">

Demo PDP page.
<img width="972" alt="Screenshot 2020-09-30 at 17 21 49" src="https://user-images.githubusercontent.com/18352350/94699350-e6cf4400-0342-11eb-93b4-f046493b0703.png">

**To Reproduce**:
1. Go to https://demo.scandipwa.com/
2. Open Devtools (F12/ctrl+shift+i)
3. Enable mobile device emulation
3.1 Choose iPad (not iPad Pro)
4. See an error.

1. Go to https://demo.scandipwa.com/2-power-0t282h-power-adapter-i-5455039.html
2-4 from first reproduction.

**Versions**:
- ScandiPWA: 3.1.2

**Comment by aleksandrakorolova** [comment]
Closed task. 
Can't reproduce on the latest version. You can see it on demo website
![image](https://user-images.githubusercontent.com/73526235/104598335-21a18180-567f-11eb-8edf-7becd4b36618.png)
