### ISSUE TITLE
Form does no respect radio inputs

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/scandipwa#1371]
**Description**:
The Fields of type "radio" are not included in Form onSubmit callback.

**Expected behavior**:
The value of radio button should be respected. 

**Additional context**:
I think the issue is coming from this line in `Form.component.js`:

```javascript
if (current.type === 'checkbox') {
    const boolValue = checked;
    return { ...inputValues, [name]: boolValue };
}
```

After this function is fixed, I found out that sometimes the value does not get read at all.

**Comment by Elena-Evsa** [comment]
Closing after communication with developers as not actual
