### ISSUE TITLE
Shipping tax is added to cart total price even shipping cost is not added

### ISSUE THREAD

**Issue by jari646** [scandipwa/scandipwa#1374]
**Description**:
When you add product to shopping cart and go Checkout / Shipping
- select example Flat Rate shipping method 10€ including tax 25%  ( 25% tax from 10€ is 2€)
- go to billing
- remove product from shopping cart
- add product to shopping cart and total price is 2€ (previously selected shipping vat) more that added product price

**Should**
- Shipping tax should not be there in shopping cart with out actual shipping cost also.

**Versions**:
- ScandiPWA: 3.x stable
- Magento 2.3.5

**Comment by aleksandrakorolova** [comment]
Closed this task
Decided to show Estimated Shipping price. You can see it on demo website
![image](https://user-images.githubusercontent.com/73526235/104597561-26196a80-567e-11eb-8d64-98f28a64f8a4.png)
