### ISSUE TITLE
Newsletter configurations / M2 Support

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1400]
Newsletter configurations can be set in the Magento 2 Admin Panel on the store view level. None of the configurations we currently support in the ScandiPWA. 

**TODO**

Add support for the following Magento 2 configurations that can be found in admin->stores->configuration->customers->newsletter:
1. Enabled - Determines if newsletters are enabled for the store view scope. Options: Yes/No
Expected behavior when the setting is set to **yes**:
* Newsletter subscription is present in the footer
* Newsletter subscription is present in my account

Expected behavior when the setting is set to **no**:
* Newsletter subscription is not present in the footer
* Newsletter subscription is not present in my account

2. Allow Guest Subscription - Determines if unregistered guests can subscribe to a newsletter. Options: Yes / No
Expected behavior when the setting is set to **yes**:
* Newsletter subscription is present in the footer
* Newsletter subscription is present in my account
* All customer groups can subscribe to the newsletter 

Expected behavior when the setting is set to **no**:
* Newsletter subscription is present in the footer
* Newsletter subscription is present in my account
* Only logged in users can subscribe to the newsletter (no matter what email address is added to the footer newsletter field)
* When not logged in user click on the submit button when subscribing to the newsletter, the notification is shown with "You must login or register to subscribe to the newsletter" and the email should not get subscribed to the newsletter in the DB

3. Need to Confirm - Determines if subscription requests must be confirmed. This double-opt-in method is a validation measure that prevents people from being subscribed without their consent. Options: Yes / No
Expected behavior when the setting is set to **yes**:
* Newsletter subscription is present in the footer
* Newsletter subscription is present in my account
* The success message "You have been subscribed to the newsletter" is shown
** The message should be translatable

Expected behavior when the setting is set to **no**:
* Newsletter subscription is present in the footer
* Newsletter subscription is present in my account
* The success message "The confirmation request has been sent." is shown 
** The message should be translatable

EXPECTED RESULT

* The newsletter configurations are respected on the FE

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2419 + https://github.com/scandipwa/store-graphql/pull/22
