### ISSUE TITLE
Catalog price rules do not respect the customer group

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1404]
**ISSUE**

When setting the catalog price rule on a specific customer group, the setting is not respected on the FE and the discount is visible for all groups. 

**Steps to reproduce**

1. go to admin->marketing->catalog price rule
2. add a new rule
3. In the customer group setting, choose general only
4. Apply conditions and actions
5. Save the rule
6. Run reindex and flush cache
7. Open the needed product on the FE as not logged in user (the product that matches you rule)
8. Notice discount is visible
9. Add product to cart
10. Notice discount is not present

**Expected result**

Discount is not visible on the FE (PDP, PLP, product widgets) if the customer groups does not match the one specified in the rule

**Comment by aleksandrakorolova** [comment]
Can't reproduce on ScandiPWA 3.2.1

**Comment by aleksandrakorolova** [comment]
Still can't reproduce on the latest version
