### ISSUE TITLE
Disabled simple product breaks bundle product

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/scandipwa#1407]
**Description**:
If a bundle product has a disabled simple product then there coming a error/Notice in graphql:

```
Notice: Undefined offset: 6445 in vendor/scandipwa/catalog-graphql/src/Model/Resolver/Links/Collection.php on line 229
````

**Expected behavior**:
There should be no such error.

**Additional context**:
The query to test this:

```graphql
query{ products(filter: { sku: { eq: "Your SKU"} }){ items { name sku ... on BundleProduct { items { options { price id product { name sku price_range { minimum_price { regular_price { value } } } } } } } } } }
``` 

Originally reported by @teodormoq in https://github.com/scandipwa/catalog-graphql/issues/67

**Comment by carinadues** [comment]
The issue was closed because it couldn't be reproduced.
