### ISSUE TITLE
Product Compare / M2 Support

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1410]
**Description**:
Compare Products generates a detailed, side-by-side comparison of two or more products.

**DESIGN**
mobile - zpl.io/VQjEX4P
desktop - zpl.io/VDEnEDr & zpl.io/VKRlR0q

**TODO**
- Create a compare page
- Add the compare icon in the header 
-- The link to the compare page should be added to the icon
- Style the page as per the design on mobile and desktop 
- Clear compare, price, and compare labels are translatable 
- Products cards and attributes are scrollable (check tdkz behavior on both mobile and desktop)
- Products can be removed from compare on click on X button
- Products can be added to cart on click on add to cart button 
- Product name and product image are linked with the respected products page
- On the clear compare button, remove all items from compare
- All customer groups can add items to compare 
- On mobile, attribute label is sticky and always visible  

**Expected result**

- Users can add products for comparison through PDP / PLP
- Comparison page created
- Any number of products can be added, but more than 4 introduces horizontal scroll bar as in TDKZ: https://www.technodom.kz/compare
- 2 products are visible on mobile, the third is partially visible to indicate scrolling ability
- Setting in Admin → Stores → Attributes → Product → {attribute} → Storefront properties → Comparable on Storefront is respected
- Able to compare configurable products, default variant is selected
- Header extended with icon leading to compare page. 
- Responsive

**Comment by yeegor** [comment]
Related to https://github.com/scandipwa/base-theme/pull/385
