### ISSUE TITLE
It is impossible to hide images of configurable product

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/scandipwa#1419]
**Description**:
The configurable product images do not respect "hidden option".

**Expected behavior**:
Hidden images should not show :)

**Additional context**:
Originally reported by stevie@seoulwebdesign.com in community slack.

**Comment by aleksandrakorolova** [comment]
Can't reproduce on the latest version
![image](https://user-images.githubusercontent.com/73526235/104594279-9d98cb00-5679-11eb-8e4e-a6c0ec79d9cd.png)
![image](https://user-images.githubusercontent.com/73526235/104594294-a093bb80-5679-11eb-92b2-ce45880af039.png)
