### ISSUE TITLE
Purchase Order Payment Method Not Working

### ISSUE THREAD

**Issue by santosh-gaggle** [scandipwa/scandipwa#1422]
**Description**:
Magento 2 default "Purchase Order" payment method not working
getting an error "{"errors":[{"message":"Purchase order number is a required field.","extensions":{"category":"graphql-input"},"locations":[{"line":1,"column":67}],"path":["paymentMethod"]}],"data":{"paymentMethod":null}}"

**Expected behavior**:
it should show the purchase order number filed at checkout when selecting the Purchase order payment method

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/56184739/96116257-d05de680-0f05-11eb-9eb8-920320340820.png)

**To Reproduce**:
1. Add any product to cart and enable the purchase order payment method form Admin
2. on the checkout page when you select the purchase order payment method you will get the error "Purchase order number is a required field."

**Versions**:
- ScandiPWA: 3.1.3
- Magento 2.3.5-p2

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2319
