### ISSUE TITLE
Boolean Filters display one or zero

### ISSUE THREAD

**Issue by lion152** [scandipwa/scandipwa#1439]
**Description**:
When `eav attribute` is boolean then the filters return 1.

**Expected behavior**:

Boolean filters should not display anything near the checkbox or should display enable/disable

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/4339464/96256317-1af06900-0fc1-11eb-8b8c-264ce83d2ab4.png)

**Additional context**:

Originally reported by @danielsstabulis

**Comment by yeegor** [comment]
I believe something like [this](https://material.angular.io/components/slide-toggle/overview) will be perfect for the job.

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/catalog-graphql/pull/96

**Comment by carinadues** [comment]
Closing because both PRs were merged
