### ISSUE TITLE
Product option value is not visible in cart if Used in Product Listing is set to no

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1448]
**Description**:
The product option value is not visible in the cart/checkout /wishlist if Used in Product Listing is set to no to the attribute. 

**Expected behavior**:
Attribute values are always present in the product cards when added to cart/wishlist

**To Reproduce**:
1. Make sure you have config product with size and color to be selected
2. Open admin->stores->attributes->product->color attribute->storefront properties->set used in product listing as no
3. clear cache
4. open the config product
5. choose color and size and add it to cart
6. notice in cart you only have size value of the product that you added to cart

**Comment by carinadues** [comment]
Issue closed because it is the same as #2422.
