### ISSUE TITLE
Display Products Availability In Stock on Storefront / M2 Support

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1468]
**Description**:
The setting displays an "In Stock" or "Out of Stock" message on the product page based on the value set in Magento BE. 

**TODO**:
1. Implement support for admin->stores->configuration->catlaog->inventory->stock option->Display Products Availability In Stock on Storefront setting
2. if the value is no -> do not show "out of stock" / "in stock" labels on the product pages
3. if the value is yes -> show "out of stock" / "in stock" labels on the product pages

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/store-graphql/pull/18 + https://github.com/scandipwa/scandipwa/pull/2306
