### ISSUE TITLE
Product Alerts / M2 support

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1470]
**Description**:
Customers can subscribe to two types of alerts by email - price change alerts and in-stock alerts. For each type of alert, you can determine if customers are able to subscribe, select the email template that is used and identify the sender of the email. - https://docs.magento.com/user-guide/catalog/inventory-product-alerts.html

**TODO**:
Implement support for product alerts as per the default M2

**Comment by carinadues** [comment]
@aleksandrakorolova let's test it on the demos once they are updated to 5.0.5 :)
