### ISSUE TITLE
Checkout bug with guest customer email

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/scandipwa#1472]
**Description**:
Unable to complete the checkout with guest customer, when the customer automatic group assignment is turned on in admin.

**Expected behavior**:
I should be able to place the order!

**Screenshots, Video, Logs**
The video of issue happening: https://www.screencast.com/t/SnMVlmBef0d

**To Reproduce**:
Before completing steps on FE, it is required to go to BE and check enable ‘Create New Account Options’ setting:
![image](https://user-images.githubusercontent.com/29531824/96915522-01628c00-14af-11eb-97e0-cb938ddd8e09.png)

1. Add product to cart
2. Go to checkout
3. Fill in billing address and choose shipping
4. Next page checkout/billing
5. Try to order and getting message: Guest email is missing for cart
6. Notice you are unable to place order

**Additional context**:
After the order placement you can add any product to cart and go to checkout page after submit email and shipping details you will see email is not set. Even more, the guest email is not sent to FE in the first place. Here, is the response:
![image](https://user-images.githubusercontent.com/29531824/96915622-222ae180-14af-11eb-98ef-ac90c674860f.png)
 
Originaly reported by santosh and mediameta here: https://forum.scandipwa.com/t/guest-email-for-cart-is-missing/324

**Comment by carinadues** [comment]
The issue was closed because it couldn't be reproduced.
