### ISSUE TITLE
File input control type for customizable options / M2 support

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1473]
**Description**:
File input control type for customizable options that allows the customer to upload a file. - https://docs.magento.com/user-guide/catalog/settings-advanced-custom-options.html?itm_source=merchdocs&itm_medium=quick_search&itm_campaign=federated_search&itm_term=custom

**TODO**:
Implement support for file type for custom options so users are able to upload the images on the FE

**Comment by ivanzagoruiko** [comment]
@lianastaskevica I tried to implement it, and  you  will have a lot of problems. Also would like to ask to implement support for upload  files with vector graphic ( .eps , .ai). Running ahead will need to be customized Zend File Validator. I also think that Estimate  was assessed incorrectly. In my opinion more real 100+hours.
