### ISSUE TITLE
Bundle product option price is wrong  

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1476]
**Description**:
In the Magento, you can set the price for bundle product option that you will need to pay additionally if you select it - https://prnt.sc/v59ubk. 
On FE, you see Product option name + extra fee that is specified in the price setting (https://prnt.sc/v59ubk)

**Expected behavior**:
https://prnt.sc/v59w8f

**Actual result**
https://prnt.sc/v59xzw
The product option original price is shown instead of the one set in the price setting here - https://prnt.sc/v59ubk
Also, the wrong price is displayed for bundle itself it is has fixed price (bundle option original price is shown) 

**To Reproduce**:
1. open bundle product in admin
2. make sure it is a bundle with fixed price
3. Add price for bundle options
4. save
5. notice wrong price on the FE

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2317 + https://github.com/scandipwa/catalog-graphql/pull/90

More details are provided in PR description.
@aleksandrakorolova please, check that current change hasn't affected bundles with dynamic pricing, when verifying the task
