### ISSUE TITLE
Login Landing Page / M2 Support

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1496]
**Description**:
You can configure your store to redirect customers to their account dashboard after they log in, or let them continue shopping. https://docs.magento.com/user-guide/customers/login-landing-page.html?itm_source=merchdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=login%20langing

**TODO**:
Implement support for the feature

**Comment by aleksandrakorolova** [comment]
@lianastaskevica New forms are displayed but setting Redirect Customer to Account Dashboard after Logging in doesn't work
