### ISSUE TITLE
In-Store Delivery / M2 Support

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1506]
**Description**:
With the in-store delivery method, the customer can select a source to be used as a pickup location during the checkout. - https://docs.magento.com/user-guide/shipping/shipping-in-store-delivery.html

**TODO**:
Implement support for the shipping method

**Comment by aleksandrakorolova** [comment]
{"errors":[{"message":"Internal server error","extensions":{"category":"internal"},"locations":[{"line":1,"column":43}],"path":["getStores"]}],"data":{"getStores":null}}
![image](https://user-images.githubusercontent.com/73526235/120459212-a4ae4480-c3a0-11eb-96d1-eaff43fbc55d.png)

**Comment by carinadues** [comment]
See #2777 for updates on this.
