### ISSUE TITLE
Shopping Cart Tax Display Settings / M2 Support

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1509]
**Description**:
In Magento 2, there are multiple tax settings to determine how prices are displayed in the shopping cart - https://docs.magento.com/user-guide/configuration/sales/tax.html#shopping-cart-display-settings

**TODO**:
implement support for all shopping cart display settings

**Comment by lianastaskevica** [comment]
Better put on hold until we migrate to the default Magento cart

**Comment by aleksandrakorolova** [comment]
Closed task because it was implemented in #1364
