### ISSUE TITLE
Page Builder / M2 Support

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1523]
**Description**:
M2 EE provides Page Builder that makes it easy to create content-rich pages with custom layouts that enhance your visual storytelling, and drive customer engagement and loyalty. Learn more here - https://docs.magento.com/user-guide/cms/page-builder.html

**TODO**:
Implement support for maps in page builder as a plugin

**Comment by aleksandrakorolova** [comment]
Closed task because this will be an extension available in the [marketplace](https://marketplace.scandipwa.com/magento-2-page-builder.html)
