### ISSUE TITLE
Customizable options and values don't match options and values orders in the Admin panel

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1534]
**Description**:
Customizable options and values don't match options and values orders in the Admin panel

**Expected behavior**:
New values and options orders are displayed

**To Reproduce**:
1. Open product X
2. Change options order
3. Change value order
4. Save
5.Open website -> Open product X page

**Actual result:**:
Old values and options orders are displayed

**Notes"**:
Product: http://scandipwapmrev.indvp.com/default/simple-product-for-test-test.html
Product in the Admin panel: https://scandipwapmrev.indvp.com/admin/catalog/product/edit/id/2565/key/a482972b578e9180953122a590ed7fdbe2d020493896130a1363cc910b8c6023/

**Comment by artissegrums** [comment]
Tested the issue, but was unable to reproduce this in all of its scope. Probably it is magically fixed

Values changed accordingly and order on check-boxes did too, only the order of drop-down is sorted alphabetically.
Is this the desired order for drop-downs?
