### ISSUE TITLE
Layered Navigation Price Step doesn't change on website

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1539]
**Description**:
Layered Navigation Price Step doesn't work

**Expected behavior**:
Navigation Price Step is $20 on the left side on page

**To Reproduce**:
1. Open Admin panel -> Go to Catalog -> Categories -> Tap Category X
2. Tap Display settings
3. Enter some numbers in Layered Navigation Price Step field (for example, 20)
4. Tap 'Save'
5. Open website -> Open category X

**Actual result:**:
Navigation Price Step is NOT $20 on the left side on page. 

**Notes**
Women category

**Comment by tatiana-scandi** [comment]
The investigate showed that it is **Magento cache** that causes the issue. Flushing Magento cache helps to set correct values in filters. So I don't see what can be done on own side to improve the situation. The solution is just to remember to flush magento cache after changing filters configuration.

**Comment by aleksandrakorolova** [comment]
Still can reproduce
