### ISSUE TITLE
Page jumps on click on the sort by button on mobile category page

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1545]
**Description**:
When you scroll down on the mobile category page and click on the sort by button, the page "jumps". Reproduced on iOS devices.

**Expected behavior**:
No "jump" is present

**Screenshots, Video, Logs**
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/52198221/97469611-4410e200-194f-11eb-8a3c-d4f52a9aa903.gif)

**To Reproduce**:
1. Go to mobile category 
2. Scroll down 
3. Click on sort by button

**Comment by zans-laksa** [comment]
This is the default behaviour of inputs on ios.
Any input opens keyboard / picker, which causes window to scroll up.
Didn't find any solution.
Tried to save and restore scroll top position, prevent window scroll event before focus - this didn't help.
On the internet there are solutions like call window.scrollTo(0, 0) or set body position to fixed, but this scrolls page up to the start.
Found out that element.focus event has preventScroll option, but unfortunately it isn't supported by safary.
![image](https://user-images.githubusercontent.com/73945186/98518088-93bcab00-2277-11eb-9e31-5c77956f0f6d.png)
