### ISSUE TITLE
Not allowed HTML tags on product page 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1551]
**Description**:
Not allowed HTML tags on product page 

**Expected behavior**:
HTML allowed - this text is bold

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/73526235/97581996-ea1b2580-19fd-11eb-81c8-4a8b82eb6e15.png)

**To Reproduce**:
1. Open product X and enter HTML (for example <b> Bold text</b>)
2. Open website -> open product X

**Actual result:**:
'<b> Bold text</b>' is displayed

**Additional context**:
Product: https://scandipwapmrev.indvp.com/default/28-simple-product.html

**Comment by aleksandrakorolova** [comment]
Should be fixed in #4728

**Comment by aleksandrakorolova** [comment]
Should be fixed in #4728

**Comment by carinadues** [comment]
Closing as https://github.com/scandipwa/scandipwa/pull/4728 was merged.
