### ISSUE TITLE
Meta Description and Meta keywords for page are missing in the Inspect Element

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1553]
**Description**:
Meta Description is missing 
Default Meta keywords is displayed

**Expected behavior**:
Meta Title, Meta description and Meta keywords should be the same how in the Admin panel

**To Reproduce**:
1. Open Admin panel -> go to Content > Elements > Page -> Open page X -> Change URL key -> Add Meta Title, Meta description and Meta keywords
2. Tap 'Save'
3. Open website -> Open page X -> Open inspect Elements

**Actual result"**:
Meta Description and Meta keywords are missing in the Inspect Element
http://scandipwapmrev.indvp.com/default/test-page

**Comment by AleksandrsKondratjevs** [comment]
Can't reproduce issue with meta keywords. Only Meta description is not present.
