### ISSUE TITLE
Some settings for Basic Shipping Methods work for all website even if website X has different settings

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1568]
**Description**:
Some settings for Basic Shipping Methods work for all website/stores even if website/store X has different settings:
Title
Type
Price
Price Handling Fee
Ship to Specific Countries
Condition in Table Rate delivery

**Expected behavior**:
Settings work correctly on each website/store

**To Reproduce**:
1. Default config(website X and Y): Choose Flat rate Type per order
2. Website X: Choose Flate rate Type per item
3. Open website X -> Check flat rate type
4. Open website Y -> Check flat rate type

**Actual result:**:
Website Y: Flat rate type per item

**Notes**:
If Open website/store Y and then Open website/store X -Flat rate type per order on website/store X

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/quote-graphql/pull/52
