### ISSUE TITLE
Issues which connected with offline mode

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1618]
**Description**:
1. User will redirect to Ooops page if he taps account in offline mood (not logged in)
2. Mobile: Image and text are missing

**Expected behavior**:
1. User won't redirect to Ooops page
2. Image and text are displayed
![image](https://user-images.githubusercontent.com/73526235/98349339-88bd0d00-2022-11eb-9574-79809e7f4ec3.png)

1.**To Reproduce on Mobile and Desktop**:
1.Open website
2.Turn on offline mode
3.Open sign-in form

2.**To Reproduce on Mobile**:
1. Open website
2. Turn on offline mode
3. Open the about us page

**Actual result:**:
1. User will redirect to Ooops page
2. Image and text are missing
https://drive.google.com/file/d/1-eoZoB59uTYJlhe3qcUwmZEWfAe5XkuU/view?usp=sharing

**Notes:**:
1. Mobile: if a user opens the cart page, he will redirect to Ooops page too

**Comment by aleksandrakorolova** [comment]
1. Can't reproduce 
2. Still, issue exist

**Comment by Elena-Evsa** [comment]
1. Can't reproduce
2. Can't reproduce 
![image](https://user-images.githubusercontent.com/84388061/187216584-60d676ae-66df-4e67-9395-97bfa085f442.png)
