### ISSUE TITLE
Error message (#10002: Security error) appears if user selected 'PayPal Express Checkout' payment method

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1622]
**Description**:
Error message 'Unable to place order: PayPal gateway has rejected request. Security header is not valid (#10002: Security error).' appears if user selected 'PayPal Express Checkout' payment method
**Expected behavior**:
Opens PayPal page 

**To Reproduce**:
1. Open website
2. Add product to cart
3. Open cart
4. Complete shipping step
5. Choose 'PayPal Express Checkout'
6. Agree with T&C
7. Tap 'Complete order'

**Actual result:**:
Error message 'Unable to place order: PayPal gateway has rejected request. Security header is not valid (#10002: Security error).' appears

**Comment by riha112** [comment]
Plugin is disabled for all ScandiPWA versions to enable it, requires adding ether to local project or whole scandipwa repo line in scandipwa.json file under extensions:
