### ISSUE TITLE
Price including Tax is always displayed on category and product pages even we set excluding tax in admin panel

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1625]
**Description**:
Price including Tax is always displayed on category and product pages even we set excluding tax in admin panel

**Expected behavior**:
Price excluding Tax is displayed

**To Reproduce**:
1. Open Admin panel -> go to Stores -> Settings - > Configuration -> Sales and choose Tax
2. Select Excluding Tax in Display Product Prices in Catalog
3. Tap 'Save' -> Flush Cache Storage
4. Open website -> Open category -> open product page

**Actual result:**:
Price including Tax is always displayed

**Comment by AleksandrsKondratjevs** [comment]
Seems that default magento doesn't have option to get excl tax prices with graphql. Price range only goes with incl tax. Due to this I putted task on hold and watching same issue on magento2 repository for updates.

**Comment by lianastaskevica** [comment]
https://github.com/magento/magento2/issues/31313
