### ISSUE TITLE
Nothing happens on the storefront after creating an account if we set Require Emails Confirmation in the Admin panel

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1639]
**Description**:
Nothing happens on the storefront after creating an account if we set Require Emails Confirmation in the Admin panel

**Expected behavior**:
Register form disappears -> Success message appears (for example, Text 'Please, check your e-mail inbox for the verification link to confirm your account.')
Something looks like this 
![image](https://user-images.githubusercontent.com/73526235/98552428-20329200-22a7-11eb-884b-2a091c375ae9.png)

**To Reproduce**:
1. Open Admin panel -> go to Stores > Settings > Configuration -> Customers -> Customer Configuration
2. Expand Create New Account Options section
3. Select 'Yes' in Require Emails Confirmation field
4. Tap 'Save' -> Flush Cache Storage
5. Open website -> Tap 'Sign in' -> Tap 'Create an account' -> Enter email and password, confirm password -> Tap 'Create an account'

**Actual result:**:
Nothing happens on storefont (Success message or something else) - register form is displayed.
User received an email with a confirmation

**Comment by aleksandrakorolova** [comment]
@AleksandrsKondratjevs Please, add this notification message on /account/create page too

**Comment by Elena-Evsa** [comment]
Nothing happens on mobile devices when user full all necessary fields for registration and tap 'Sign up'. Registration pop-up stays.
Video of issue
https://www.loom.com/share/a1d16fc270004ac7a64144c23d4f2793

**Comment by carinadues** [comment]
New PR merged to branch 4.4.1-rc. Can you test again, please, @Elena-Evsa?
