### ISSUE TITLE
Price Navigation Steps don't include all product prices on category page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1646]
**Description**:
Price Navigation Steps don't include all product prices on category page

**Expected behavior**:
Up to $20
From $20, to $40
From $40, to $60
From $60

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/73526235/98664445-0fd7f100-2353-11eb-8ab0-10120a7a34ac.png)

**To Reproduce**:
1. Open http://scandipwapmrev.indvp.com/test/women.html

**Actual result:**:
We have a product with a price $170, but we don't have this price in the price navigation steps

**Additional context**:
http://scandipwapmrev.indvp.com/test/women.html
Default Price Navigation Step - 20
Maximum Number of Price Intervals - 4

**Comment by alfredsgenkins** [comment]
@zans-laksa update the composer with https://github.com/scandipwa/catalog-graphql/releases/tag/3.1.2 please. While I do not think the fix you did really helps, the bug I think is in something different. But let QA decide.
