### ISSUE TITLE
If user added all products from the wishlist to the cart and then refresh the page, products appear in the Wishlist

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1652]
**Description**:
If user added all products from the wishlist to the cart and then refresh the page, products appear in the Wishlist

**Expected behavior**:
Products are missing in Wishlist

**Screenshots, Video, Logs**
https://drive.google.com/file/d/1Heqg_1sugyVbjk8qpwkkYPSzFm4lc_p-/view?usp=sharing

**To Reproduce**:
1. Log in 
2. Add 2 different products to wishlist
3. Open Wishlist
4. Tap 'Add all to cart'
5. Refresh page

**Actual result**:
Products appear in wishlist

**Additional context**:
If user added one product to the cart and then refresh the page, this product doesn't appear

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/wishlist-graphql/pull/11
