### ISSUE TITLE
Mobile: The first letter is capital letter when user writes email

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1664]
**Description**:
The first letter is capital letter when user writes email

**Expected behavior**:
The first letter isn't capital letter

**To Reproduce**:
1. Open website
2. Open sign in page
3. Start to write email

**Actual result**:
The first letter is capital letter

**Notes**:
Mobile:
Android: Chrome, Opera
iOS: Safari, Opera

**Comment by Elena-Evsa** [comment]
Same issue reproducible on mobile in email field on pages:
- Create account
- Forgot password
- Shipping step
- Billing step
