### ISSUE TITLE
Samsung S7, Android 6: Ugly stars in write review form

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1673]
**Description**:
Ugly stars in write review form

**Expected behavior**:
Stars look like these:
![Screenshot_20201112-120203_Chrome](https://user-images.githubusercontent.com/73526235/98925674-f794dd00-24de-11eb-89a4-67e3b399b0d9.jpg)

**To Reproduce**:
1. Open product page
2. Tap 'Write a new review'
3. Select rate

**Actual result**:
Ugly stars in write review form
![image](https://user-images.githubusercontent.com/73526235/98925278-776e7780-24de-11eb-94ff-44722c84ba8e.png)

**Notes**:
Device: Samsung S7
Version: Android 6
Browser: Chrome
Tested here: https://live.browserstack.com/

**Comment by carinadues** [comment]
Closing this issue as this is a very specific case for a very old version of Android. They are in 12 already.
