### ISSUE TITLE
Sony Z3 compact: Firefox: Button 'Create an account' under menu on sign in page. Can't scroll this page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1676]
**Description**:
Button 'Create an account' under menu on sign in page. Can't scroll this page

**Expected behavior**:
Button 'Create an account' above menu
![Screenshot_20201112-090125](https://user-images.githubusercontent.com/73526235/98927991-e4374100-24e1-11eb-9da1-4c32ac7e6f69.png)

**To Reproduce**:
1. Open sign in page

**Actual result:**:
Button 'Create an account' under menu
The same situation on create account, wishlist pages
![Screenshot_20201112-090407](https://user-images.githubusercontent.com/73526235/98927998-e6999b00-24e1-11eb-9c52-0e820a3f954f.png)
![Screenshot_20201112-085935](https://user-images.githubusercontent.com/73526235/98928004-e7cac800-24e1-11eb-9094-5de27b50ddfb.png)

**Notes**:
Device: Sony z3 compact
Version: Android 6
Browser: Firefox

**Comment by Elena-Evsa** [comment]
A lot of changes after redesign and can not reproduce
