### ISSUE TITLE
Can't change a password via forgot password link

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1696]
**Description**:
Can't change a password via forgot password link

**Expected behavior**:
A success message appears -> Password is updated 

**To Reproduce**:
1. Open website - https://demo.scandipwa.com/
2. Open Sign in form
3. Tap 'forgot password'
4. Enter your email 
5. Tap 'Send reset link'
6. Open received email with a reset link
7. Enter new/confirm password
8. Tap 'Update password'

**Actual result**:
Error message appears -> user can't change password
https://drive.google.com/file/d/1ZYFhGWBk810RiwaXmjdN3UxQvmvJFquC/view?usp=sharing

**Comment by vromash** [comment]
Fix in this PR https://github.com/scandipwa/customer-graph-ql/pull/14

**Comment by aleksandrakorolova** [comment]
Still can't update password
![image](https://user-images.githubusercontent.com/73526235/107515395-9fd84180-6bb3-11eb-8f0b-657699ad4ab1.png)

**Comment by zans-laksa** [comment]
Related PRs, both merged.
BE: scandipwa/customer-graph-ql/pull/14
FE: #2074

I've pulled changes, tested on my local setup. Everything works fine.
Cannot test on pmrev, since was unable to get an email with the link.

**Comment by zans-laksa** [comment]
Did a little deeper investigation (since now i have access to pmrev =)).
Backend is not updated. At least `scandipwa/customer-graph-ql` package.
Current installed version is 2.3.0, while the latest (with fixes for this issue) is 3.0.0.

**Comment by zans-laksa** [comment]
Not sure why, but package couldn't be upgraded.
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - scandipwa/scandipwa 0.0.1 requires scandipwa/customer-graph-ql ^2.2.3 -> satisfiable by scandipwa/customer-graph-ql[2.2.3, 2.3.0, 2.x-dev] but these conflict with your requirements or minimum-stability.
    - scandipwa/scandipwa 0.0.1 requires scandipwa/customer-graph-ql ^2.2.3 -> satisfiable by scandipwa/customer-graph-ql[2.2.3, 2.3.0, 2.x-dev] but these conflict with your requirements or minimum-stability.
    - Can only install one of: scandipwa/locale[2.0.0, 1.2.0].
    - Can only install one of: scandipwa/locale[2.0.0, 1.2.0].
    - Can only install one of: scandipwa/locale[2.0.0, 1.2.0].
    - scandipwa/scandipwa 0.0.1 requires scandipwa/locale ^2 -> satisfiable by scandipwa/locale[2.0.0].
    - Installation request for scandipwa/scandipwa ^0.0.1 -> satisfiable by scandipwa/scandipwa[0.0.1].
    - Installation request for scandipwa/locale (locked at 1.2.0) -> satisfiable by scandipwa/locale[1.2.0].


Installation failed, reverting ./composer.json to its original content.
root@d825d842652b:/var/www/public# cat vendor/scandipwa/scandipwa/composer.json | grep -i customer
        "scandipwa/customer-graph-ql": "^3.0",
root@d825d842652b:/var/www/public# cat vendor/scandipwa/scandipwa/package.json | grep -i customer
            "scandipwa/customer-graph-ql": "^3.0",
```

**Comment by lianastaskevica** [comment]
The packages are updated now. @aleksandrakorolova you are now able to retest it:)
