### ISSUE TITLE
Never-ending loader if data is loading and internet connection is lost

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1710]
**Description**:
Never-ending loader if data is loaded and internet connection is lost

**Expected behavior**:
Data will load when the internet connection appears

**To Reproduce**:
1. Open website
2. Open Sign in form
3. Enter email and password
4. Turn on offline mode
5. Tap 'Sign in'
6. Turn off offline mode

**Actual result**:
Never ending loader

**Notes**:
The same situation when:
- Add the new address in my account 
- Save subscribe settings
- Go to the Shipping method
- Delivery methods are loading
- Go to billing step
- Complete order
- Add product to cart

**Comment by Elena-Evsa** [comment]
Can not reproduce https://vimeo.com/744496514/36528e235b
