### ISSUE TITLE
Coupon for free shipping doesn’t work if user enters it on billing step 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1712]
**Description**:
Coupon for free shipping doesn’t work if user enters it on billing step 

**Expected behavior**:
User has free shipping 

**To Reproduce**:
1. Open website
2. Add product to cart
3. Complete shipping step
4. Enter coupon for free shipping on the billing step (Coupon code - Free)
5. Complete order

**Actual result**:
Success message (Coupon valid). The shipping price disappears. Order amount stays the same
https://drive.google.com/file/d/1QkZAIqKjLmEsq6kSbKoCMokd4a9p0YnM/view?usp=sharing
Shipping price is displayed in Admin panel:
![image](https://user-images.githubusercontent.com/73526235/101335745-476a8800-3882-11eb-8a30-b31f9b149a6b.png)

**Notes**:
If user enters the same coupon on the shipping step or cart page, he has free shipping

**Comment by riha112** [comment]
Was unable to reproduce locally.

**Comment by aleksandrakorolova** [comment]
Closed because not actual task
