### ISSUE TITLE
Delivery methods don't update when the user enters/removes a coupon

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1717]
**Description**:
Delivery methods don't update when the user enters/removes a coupon

**Expected behavior**:
Delivery methods and total amount will update if user enters/removes coupon

**To Reproduce**:
1. Open website
2. Add product to cart
3. Fill the form in the shipping step
4. Enter coupon
5. Change address
6. Remove coupon

**Actual result:**:
Delivery methods don't update when the user enters/removes a coupon
https://drive.google.com/file/d/1stzrP1jWRHAvkE7iwGW5jLOhynCYS3Vn/view?usp=sharing

**Comment by zans-laksa** [comment]
Currently this works similar was as Luma.
On Luma we are able to enter coupon code and select the free shipping even if it is not applicable.
But on the certain stages we get an error. Same on scandipwa.

![image](https://user-images.githubusercontent.com/73945186/102983779-42aa0300-4515-11eb-8d41-16834851ff37.png)
![image](https://user-images.githubusercontent.com/73945186/102983930-7b49dc80-4515-11eb-86b4-cb44c44a24ce.png)
