### ISSUE TITLE
Buttons, comment field, quantity, and price are located at different heights in Wishlist if products with and without attributes were added

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1726]
**Description**:
Buttons, comment field, quantity, and price are located at different heights in Wishlist if products with and without attributes were added
**Expected behavior**:
Buttons are displayed on one line
The same situation with comment field, quantity and price

**To Reproduce**:
1. Open website
2. Log in
3. Add products without attributes to Wishlist
4. Add products with attributes to Wishlist
5. Open Wishlist

**Actual result**:
Buttons are located at different heights. The same situation with comment field, quantity and price
![image](https://user-images.githubusercontent.com/73526235/99375992-03ace000-28cd-11eb-8d7b-09eae27d5a0d.png)

**Additional context**:

**Comment by lianastaskevica** [comment]
Cannot reproduce on v3.2.5
