### ISSUE TITLE
Price Slider

### ISSUE THREAD

**Issue by maleksandr** [scandipwa/scandipwa#1729]
**Description**:
Provide Price Slider feature on PLP.

**Context**: 
We would like to provide the Price Slider feature on PLP as an extension to be published in the marketplace. It should not be a part of the default theme.

**Expected results**:
The user can define the max and min prices in the layered navigation. Only the products within this range will show up.

**Screenshots**:
![image](https://user-images.githubusercontent.com/82165392/149164713-b8551684-3807-4309-a602-78170e0df5c8.png)

![image](https://user-images.githubusercontent.com/82165392/149164553-d19c88ce-3fed-4653-8253-9ba413172e9e.png)

![image](https://user-images.githubusercontent.com/82165392/149164669-67db2f61-2a0b-47bf-a7da-aaaa934d31f1.png)

**Comment by satishgadhave** [comment]
Any progress here?

**Comment by johanroberthson** [comment]
Will this be fixed in the future?
It would be great if it could be included in standard.
