### ISSUE TITLE
Mobile: The search line has shifted to the right

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1734]
**Description**:
The search line has shifted to the right on Mobile

**Expected behavior**:
The search line has the same width as the categories
![image](https://user-images.githubusercontent.com/73526235/99650487-24f10600-2a5e-11eb-8cb2-e325ddcd580c.png)

**To Reproduce**:
1. Open website on Mobile
2. Open menu

**Actual result**:
The search line has shifted to the right
![image](https://user-images.githubusercontent.com/73526235/99650536-39350300-2a5e-11eb-83c8-a12b855aef00.png)

Version: 3.2.1

**Comment by lianastaskevica** [comment]
https://github.com/scandipwa/scandipwa/pull/1913
