### ISSUE TITLE
Unnecessary empty space in filter

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1737]
**Description**:
Unnecessary empty space in filter

**Expected behavior**:
Page scrolls up
Show matching categories without empty space
https://drive.google.com/file/d/1xZj7N2iCKNJYfGPM4xqmjaxjpWBOt_kw/view?usp=sharing

**To Reproduce**:
1. Open Women category
2. Tap 'Show more' categories
3. Select some option in New Multiple attributes
4. Tap 'Show more' categories

**Actual result**:
Unnecessary empty space in categories filter
https://drive.google.com/file/d/1M43DT1obwEz8AxafTMiHXzv22VoKJrY7/view?usp=sharing

**Notes**:
Version: 3.2.1

**Comment by lianastaskevica** [comment]
https://github.com/scandipwa/scandipwa/pull/1913

**Comment by aleksandrakorolova** [comment]
Closed because issue will be fixed in another task #2250
