### ISSUE TITLE
scandiweb_slider_slide' doesn't exist

### ISSUE THREAD

**Issue by jazib93** [scandipwa/scandipwa#1738]
Hello, 

I'm unable to run the php bin/magento setup:upgrade command successfully. 

It throws this error "Base table or view not found: 1146 Table 'dbname.scandiweb_slider_slide' doesn't exist". I checked the tables in the database. The table is there but the module is unable to pick up the table prefix. 

It should be like this "dbname.tableprefixtablename".

**Comment by Elena-Evsa** [comment]
Closing after conversation with developer
