### ISSUE TITLE
Currency and product price stay the same in the cart if we selected another currency

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1744]
**Description**:
Currency and price stay the same in the cart if we selected another currency

**Expected behavior**:
Currency is EUR in cart

**To Reproduce**:
1. Open some product - http://scandipwapmrev.indvp.com/default/n-81-hours-cashmere-pullover-black-extra-small-size.html
2. Add it to cart
3. Change currency to EUR
4. Open cart/mini-cart

**Actual result:**:
Currency is Dollars ($) in cart
Currency for Payment methods is dollars too
![image](https://user-images.githubusercontent.com/73526235/99798422-abc6e100-2b39-11eb-9db1-ae0d2ceec246.png)

**Notes**:
Order total on billing step $ = Product price EUR + Shipping
![image](https://user-images.githubusercontent.com/73526235/99799207-f85eec00-2b3a-11eb-93a3-b0e90082742b.png)

Version: 3.2.2

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/catalog-graphql/pull/83
