### ISSUE TITLE
Mobile: 'Select currency' option is displayed in the currency dropdown

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1745]
**Description**:
'Select currency' option is displayed in the currency dropdown

**Expected behavior**:
Delete option 'Select currency' in currency dropdown

**To Reproduce**:
1. Open website
2. Open menu 
3. Open currency dropdown

**Actual result:**:
Android: 'Select currency' option is displayed in the currency dropdown
![image](https://user-images.githubusercontent.com/73526235/99802466-6954d280-2b40-11eb-936c-3a4cab710611.png)
iOS: Empty option is displayed
![image](https://user-images.githubusercontent.com/73526235/99802517-838eb080-2b40-11eb-986c-3fdfab761064.png)

**Notes**:
Version: 3.2.2

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2212
