### ISSUE TITLE
The logo stays from the previous store when switching stores

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1758]
**Description**:
The logo stays from the previous store when switching stores

**Expected behavior**:
Default logo is displayed

**To Reproduce**:
1. Open store with default logo (Default store)
2. Switch to store with another logo (Default store 2)
3. Return to store - Default store

**Actual result**:
'Test' logo is displayed
https://drive.google.com/file/d/1Y0irXJsVTezctvgtn7SJkNRuTFl13B-u/view?usp=sharing

**Notes**:
Default logo is displayed when refreshing page

**Comment by lianastaskevica** [comment]
cannot reproduce on version 3.2.5
