### ISSUE TITLE
Long review looks ugly if there is one long word

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1773]
**Description**:
The long review looks ugly if there is one long word

**Expected behavior**:
Please, division of a word if it's possible -> review doesn't look ugly

**To Reproduce**:
1. Open product page - https://scandipwapmrev.indvp.com/default/jeans.html

**Actual result**:
Review looks ugly
https://drive.google.com/file/d/1n1tXuD6J5aS9ma5X5a7ePckwizkriKxX/view?usp=sharing

**Additional context**:
Product: https://scandipwapmrev.indvp.com/default/jeans.html

**Comment by teodormoq** [comment]
Hi @lianastaskevica created pr for this https://github.com/scandipwa/scandipwa/pull/1928
