### ISSUE TITLE
Error implementing a custom parent theme

### ISSUE THREAD

**Issue by RasmusMagnell** [scandipwa/scandipwa#1786]
**Description**:
Following the parent theme guide at https://docs.scandipwa.com/how-to-tutorials-introductory/implementing-a-parent-theme does not enables our custom theme as a parent. 

**Expected behavior**:
Setting parent root in scandipwa.json enables our custom theme as a parent theme. 

**Versions**:
- ScandiPWA: 3.2.0

**Additional context**:

Trying to fix this ourselves we have done the following:
- Changed parentRoot to parentTheme in the file `scandipwa.json`
- In the file `/src/config/Extensibility/plugins/FallbackPlugin/index.js` changed:
```
if (this.parentThemeExists) {
     const parentPath = constructPath(this.options.parentRoot);
     const parentExists = this.fileExists(parentPath);
}
```
To:
```                
let parentExists = false;
let parentPath = null;
if (this.parentThemeExists) {
       parentPath = constructPath(this.options.parentRoot);
       parentExists = this.fileExists(parentPath);
}
```
- Adding multiple files to our theme because the line `parentExists = this.fileExists(parentPath);` fails otherwise, e.g `/app/app/design/frontend/Ateles/fkra/src/sw/index.js`. I assume that it should fallback to the base theme here instead. 
- The current error we haven't solved is the "missing" file  `/app/app/design/frontend/Ateles/fkra/node_modules/webpack-dev-server/client/index.js?http:/magento-fkra.dev.ateles.se` it exists but that odd parameter is what is wrong.

The issue have been discussed with @yeegor

**Comment by lianastaskevica** [comment]
Hello @RasmusMagnell! This issue should be resolved in the new Create ScandiPWA App. Try to upgrade to the latest version and let me know if you still face this issue. 
Here is a guide on how to migrate from the legacy setup - https://docs.scandipwa.com/scandipwa-and-magento/migrating-from-the-docker-setup-legacy
