### ISSUE TITLE
Ooops page appears for a few sec if user switched currency on my profile page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1792]
**Description**:
Ooops page appears for a few sec if user switched currency on my profile page

**Expected behavior**:
Ooops page doesn't appear and the currency is switched

**To Reproduce**:
1. Open website
2. Log in
3. Open my profile
4. Switch currency

**Actual result**:
Ooops page appears for a few sec + Errors appears in the console
https://drive.google.com/file/d/1Hzh8DC376y0dICza2AurrXMPALxwf6EU/view?usp=sharing
Version: 3.2.3

**Comment by zans-laksa** [comment]
Cannot reproduce.

**Comment by aleksandrakorolova** [comment]
Can't reproduce too.
