### ISSUE TITLE
Error message appears when user is changing the quantity of the product in cart (if Backorders for product - Allow Qty Below 0)

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1793]
**Description**:
Error message appears when user is changing the quantity of the product in cart (if Backorders for product - Allow Qty Below 0)

**Expected behavior**:
User can change the quantity of the product in cart

**To Reproduce**:
1. Set Backorders - Allow Qty Below 0 for some product - Product: http://scandipwapmrev.indvp.com/default/travel-bag.html
2. Open this product page
3. Add product (qty 12) to cart
4. Change quantity in the mini cart

**Actual result**:
Error message  'Provided quantity exceeds stock limits' appears
https://drive.google.com/file/d/1GBaED46ZKSxCCYGvBc_rfDw69RGMLKNC/view?usp=sharing

**Additional context**:
Product: http://scandipwapmrev.indvp.com/default/travel-bag.html
Quantity: 10
Backorders: Allow Qty Below 0
Version: 3.2.3

**Comment by lianastaskevica** [comment]
The issue was fixed here https://scandiweb.atlassian.net/browse/MED-326. Code can be reused.
