### ISSUE TITLE
Issues connected with tax in mini-cart

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1795]
1.**Description**:
Order total without tax is missing if we set display order total including and excluding tax

**Expected behavior**:
Order total excluding and including tax is displayed

**To Reproduce**:
1. Open product page
2. Add product to cart
3. open mini-cart

**Actual result**:
Order total without tax is missing if we set display order total including and excluding tax
![image](https://user-images.githubusercontent.com/73526235/100740217-03d6d080-33e1-11eb-81ef-c88292355df8.png)

________________________________________________________________________________________________________
2.**Description**:
Zero tax is displayed in mini-cart if Display Zero Tax Subtotal is set to no

**Expected behavior**:
Zero tax is missing in mini-cart

**To Reproduce**:
1. Open product without tax - http://scandipwapmrev.indvp.com/default/n-max-co-mini-dress
2. Add product to cart
3. Open mini-cart

**Actual result**:
Zero tax is displayed in mini-cart
![image](https://user-images.githubusercontent.com/73526235/100740208-ffaab300-33e0-11eb-9330-d34581969b89.png)

**Comment by zans-laksa** [comment]
> 2. Zero tax is displayed in mini-cart if Display Zero Tax Subtotal is set to no

Couldn't reproduce this. Even on scandipwapmrev.
Likely this issue has been already fixed.
