### ISSUE TITLE
Wrong store is displayed in admin panel where order was completed

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1798]
**Description**:
Wrong store is displayed in the Admin panel where order was completed

**Expected behavior**:
Order Purchased From store 2

**To Reproduce**:
1. Create an account in store 1
2. Open store 2
3. log in to the account
4. Make an order
5. notice in admin that order created in store 1 not store 2

**Actual result:**:
Order Purchased From store 1

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/quote-graphql/pull/60
