### ISSUE TITLE
Error message 'CartID' is displayed on shipping step If user tried to pay via Braintree and it was failed

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1803]
**Description**:
Error message 'CartID' is displayed on shipping step If user tried to pay via Braintree and it was failed

**Expected behavior**:
Billing step is displayed and errors are missing

**To Reproduce**:
1. Add product to cart
2. Go to billing step
3. Select Braintree
4. Enter credit cart information for fail (for example - 4000000000000028; 01/2022)
5. Tap Complete order
6. Return to shipping step
7. Go to billing step

**Actual result**:
Error message is displayed
https://drive.google.com/file/d/1TY_IARNfJ4lS2af4FeZliSx_2WL6gBXw/view?usp=sharing

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/klarna-graphql/pull/3
