### ISSUE TITLE
Request to remove "a + a" style

### ISSUE THREAD

**Issue by nicolai-hoeks** [scandipwa/scandipwa#1822]
`a + a: margin-left 1.2rem;`
In: /vendor/scandipwa/source/src/app/style/base/_link.scss

This general rule for all `a` tags following an `a` tag seems wrong to have as a general rule. 

It can be a bit difficult to get around this properly, without having to overriding the style file and removing this.

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2325
