### ISSUE TITLE
Search does not work on v3.2.3

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1823]
**Description**:
Search does not work on v3.2.3
If I call graphql product query with search, it always answers empty, it doesn't give an error.
If I call elasticsearch directly with the search, it works.
The rest of the calls to the product query with filter works fine. Products index well.

Reported by community.

**Versions**:
ScandiPWA 3.2.3

**Comment by VuThuan** [comment]
@lianastaskevica @alfredsgenkins  I have same issue with you. I can't find any product detail on category. The query alway return empty when i load the page
![image](https://user-images.githubusercontent.com/43930046/101718524-f651d280-3ad3-11eb-87b8-481767b4e7eb.png)

**Comment by jsanchep** [comment]
Me too, 

are there any news? thanks

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/catalog-graphql/pull/81
