### ISSUE TITLE
Mobile: Category X does not match the design if it is Menu_HideOnDesktop

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1826]
**Description**:
Category X does not match the design

**Expected behavior**:
Category X is displayed by design

**To Reproduce**:
1. Open menu in Mobile mode
2. Change Menu-Link to  Menu_HideOnDesktop in Inspect Elements

**Actual result**:
Category X does not match the design
![image](https://user-images.githubusercontent.com/73526235/101014645-e0da2700-356e-11eb-92f1-b10725b420fd.png)

**Additional context**:
Can't check via Admin panel - 1825

**Comment by ahmad0salah** [comment]
`Menu_HideOnDesktop` is not meant to **only** control visibility `Menu-Item` should also be present

e.g
`<li class="Menu-Item Menu_HideOnDesktop">`

**Comment by lianastaskevica** [comment]
Cannot reproduce
