### ISSUE TITLE
Can't complete order if France selected in country field on billing step

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1829]
**Description**:
Can't complete order if France selected in country field on billing step.  Error message  'invalid value of "1" provided for the regionId field.' is displayed

**Expected behavior**:
Order completed -> Success order page opens

**To Reproduce**:
1. Add product to cart
2. Go to shipping step
3.  Fill form 
4. Go to billing step
5. Select France in Country field
6. Complete order

**Actual result**:
Error message 'Invalid value of "1" provided for the regionId field. appears'

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2263
This PR is likely to fix the issue.

**Comment by aleksandrakorolova** [comment]
Can reproduce this issue in #2263
