### ISSUE TITLE
Error message 'quote_id' is displayed on shipping step when order amount > Minimum Order Amount if In the beginning, user tried to buy products which price < Minimum Order Amount

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1835]
**Description**:
Error message 'quote_id' is displayed on shipping step when order amount > Minimum Order Amount if In the beginning, user tried to buy products which price < Minimum Order Amount

**Expected behavior**:
User goes to billing step

**To Reproduce**:
1. Open Admin panel -> go to Stores -> Settings -> Configuration  -> Sales -> Sales 
2. Expand the Minimum Order Amount section 
3. Enter ’50’ in the Minimum Order Amount field
4. Save -> clear cash
5. Open website -> Add product to cart (product price <50)
6. Go to shipping step -> fill form -> Go to billing step
7. Select payment method -> agree with T&C -> Tap 'Complete order'
8. Add one more product (order amount >50)
9. Go to shipping step -> fill form -> Go to billing step 

**Actual result:**:
Error message 'No such entity with quote_id = 4711'

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/klarna-graphql/pull/3
