### ISSUE TITLE
Firefox: Dropdown list is displayed behind the button and quantity field (Can't see all options in dropdown)

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1846]
**Description**:
Dropdown list is displayed behind the button and quantity field (Can't see all options in dropdown)

**Expected behavior**:
Dropdown is displayed in front of button and quantity field
![image](https://user-images.githubusercontent.com/73526235/101472005-ab5b8200-3950-11eb-8c03-28c543a72e6e.png)

**To Reproduce**:
1. Open product page (product has attribute with dropdown) - https://scandipwapmrev.indvp.com/default/n-hilfiger-denim-transitional-jacket.html?color=76
2. Open dropdown

**Actual result:**:
Dropdown list is displayed behind the button and quantity field => Can't see all options in dropdown
![image](https://user-images.githubusercontent.com/73526235/101471351-e1e4cd00-394f-11eb-99d4-93baa7395759.png)

**Additional context**:
v82-83
Version 3.2.4

**Comment by lianastaskevica** [comment]
https://github.com/scandipwa/scandipwa/pull/1913
