### ISSUE TITLE
Success message appears when entering not registered email in forgot password form

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1847]
**Description**:
Success message appears when entering not registered email in forgot password form

**Expected behavior**:
Error message 'This email does not exist.' appears 

**To Reproduce**:
1. Open website
2. Tap forgot password
3. Enter NOT registered email
4. Tap send

**Actual result**:
Success message 'If there is an account associated with the provided address you will receive an email with a link to reset your password.' is displayed

**Additional context**:

**Comment by krelo** [comment]
Seems to work as intended. It does say 'If there is an accout...'
This is standard practice as to not give any information about registered users.

**Comment by lianastaskevica** [comment]
Closing as this is the expected behavior
