### ISSUE TITLE
Validation for input fields on focus out

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1854]
**Description**:
Currently, we are validating the fields on the submit button, e.g., in the registration form. For better UX experience, we need to implement validation on focus out. 

Check out the solution here in their registration form - https://venia.magento.com/

TODO

- Make a solution for validating the fields on focus out
- Make sure the solution is implemented for email and password fields. 
- Make sure to implement it in the registration form, shipping and billing steps.

**Comment by teodormoq** [comment]
@lianastaskevica created a pr for this: https://github.com/scandipwa/scandipwa/pull/1927
