### ISSUE TITLE
Currency for some products doesn't change

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1860]
**Description**:
Currency for some products doesn't change

**Expected behavior**:
Currency EUR is displayed on website

**To Reproduce**:
1.Open website
2. Switch currency to EUR 
3. Open simple product with Customizable Options  - https://scandipwapmrev.indvp.com/default/testing-simple.html

**To Reproduce**:
1.Open website
2. Switch currency to EUR 
3. Open bundle product  - https://scandipwapmrev.indvp.com/default/test-bundle.html
4. Open dropdown

**Actual result**:
Currency $ is displayed in option
![image](https://user-images.githubusercontent.com/73526235/101870811-0aa4d680-3b8b-11eb-8b06-86e46e3b8d9a.png)
![image](https://user-images.githubusercontent.com/73526235/101870821-10022100-3b8b-11eb-9239-3a1cad86328a.png)

**Comment by tatiana-scandi** [comment]
Implemented fix for correct currency display, https://github.com/scandipwa/scandipwa/pull/2391, but found the issue that server returns prices in wrong currency (https://github.com/scandipwa/scandipwa/issues/2392). Will continue working on backend part.
