### ISSUE TITLE
Category X is displayed in filters on category X page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1863]
**Description**:
Category X is displayed in filters on category X page

**Expected behavior**:
Subcategories are displayed only. If this category/subcategory doesn't have subcategory - don't show category filter

**To Reproduce**:
1. open Category (for example - women)

**Actual result**:
Subcategories and women category are displayed in filters

**Comment by aleksandrakorolova** [comment]
Should be fixed after #2551 will be merge

**Comment by carinadues** [comment]
@aleksandrakorolova can you test if this issue was fixed after merging #2551, please?
