### ISSUE TITLE
iOS11: User redirects to Ooops page if he added specific product and opened cart

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1866]
**Description**:
User redirects to Ooops page if he added specific product and opened cart

**Expected behavior**:
User can open cart

**To Reproduce**:
1. Open product page - https://scandipwapmrev.indvp.com/default/n-light-blue-leather-belt
2. Add to cart
3. Open cart

**Actual result**:
Ooops page opens

**Additional context**:
Can reproduce only on iOS 11

**Comment by lianastaskevica** [comment]
https://github.com/scandipwa/create-scandipwa-app/pull/9
