### ISSUE TITLE
Buttons '-' and '+' and the number of quantity have incorrect offset in mini-cart

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1873]
**Description**:
Buttons '-' and '+' and the number of quantity have incorrect offset in mini-cart

**Expected behavior**:
Button '-' shouldn't overlap the product image
![image](https://user-images.githubusercontent.com/73526235/102066796-ee12d380-3e02-11eb-817a-07b9c78c1fe3.png)
![image](https://user-images.githubusercontent.com/73526235/102066310-544b2680-3e02-11eb-86da-83316a3e21c6.png)

**To Reproduce**:
1. Add product to cart
2. Open mini cart

**Actual result**:
Buttons '-' and '+' and the number of quantity have incorrect offset
![image](https://user-images.githubusercontent.com/73526235/102312565-9d70b700-3f77-11eb-858d-d56b7373b477.png)

**Additional context**:
Version 3.2.5

**Comment by k-gorod** [comment]
Is that solved?
![image](https://user-images.githubusercontent.com/58625453/102309581-21c43980-3f7a-11eb-8a3d-b0d7355b3636.png)
