### ISSUE TITLE
Grouped product: Default quantity of product always added to wishlist, don't matter what quantity user set

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1877]
**Description**:
Grouped product: Default quantity of product always added to wishlist, don't matter what quantity user set

**Expected behavior**:
Product X - 3; Product Y - 2,

**To Reproduce**:
1. Log in
2. Open grouped product - http://scandipwapmrev.indvp.com/default/28-grouped-product.html
3. Change quantity for products (For example, Default: Product X - 2; Product Y - 1, change to 3 and 2)
4. Add to Wishlist
5. Open Wishlist
6. Add this product to cart
7. Open cart

**Actual result**:
Product X - 2; Product Y - 1,

**Comment by tatiana-scandi** [comment]
Comparison with Luma for reference:

1. Product quantity is saved => we should save too
2. Quantity of each product is displayed => we don't support it
3. No possibility to change number of grouped products => we show quantity selector
4. Final price is displayed => we show base price in wishlist

<img width="639" alt="My Wish List Scandipwa 2021-03-10 15-01-12" src="https://user-images.githubusercontent.com/79456428/110626323-a2798700-81b1-11eb-9d2c-448db93b153f.png">

**Comment by tatiana-scandi** [comment]
PRs to fix the issue:
https://github.com/scandipwa/wishlist-graphql/pull/13
https://github.com/scandipwa/quote-graphql/pull/64
https://github.com/scandipwa/scandipwa/pull/2301

@aleksandrakorolova Please, check add to cart and add to wishlist basic flows for all product types when validating this issue.

Notes:
1. No changes regarding how the grouped item is displayed in wishlist have been made. If required - please create additional task with detailed description what and how exactly should be displayed. 
2. -/+ counter currently does nothing in wishlist. In Luma this counter is hidden for grouped products. Therefore, I was not sure if adding multiplication for product quantities already added to wishlist makes sense.
