### ISSUE TITLE
Some users can't complete order because of Error message 'No such entity with quote_id = 4389'

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1896]
**Description**:
Some users can't complete order because of Error message 'No such entity with quote_id = 4389' appears

**Expected behavior**:
Billing step opens

**To Reproduce**:
1. Website (default store)
2. Log in with new@new.new/Scandipwa123
3. Add product to cart
4. Go to shipping step
5. Tap PROCEED TO BILLING
 
**Actual result**:
Error message 'No such entity with quote_id = 4389' appears

**Additional context**:
The same situation with aaa@aa.aa/Scandipwa123 in test store

**Comment by riha112** [comment]
Klarna issue: PR: https://github.com/scandipwa/klarna-graphql/pull/3
