### ISSUE TITLE
Tax line is missing on billing step if product tax = 0, but shipping tax > 0

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1898]
**Description**:
Tax line is missing on billing step if product tax = 0, but shipping tax > 0

**Expected behavior**:
Tax line is displayed if tax > 0

**To Reproduce**:
1. Set Display Zero Tax Subtotal to NO
2. Set tax for shipping
3. Open website
4. Add product (without tax) in cart
5. Fill the form in shipping step
6. Go to billing step

**Actual result**:
Tax line is missing
+ Order total exl.tax wrong
![image](https://user-images.githubusercontent.com/73526235/102333746-81c8d900-3f96-11eb-9b21-6cf4f54784c0.png)

**Comment by winniepukki** [comment]
@aleksandrakorolova OK. Unable to reproduce on master

![image](https://user-images.githubusercontent.com/43637240/109966991-9006d580-7cf9-11eb-8b9c-dbad38dad0ad.png)

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce on master
