### ISSUE TITLE
Cart rules don't work if rule Buy X Get Y Free is enabled

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1899]
**Description**:
Cart rules don't work if rule Buy X Get Y Free is enabled

**Expected behavior**:
User gets 10% discount

**To Reproduce**:
1. Create 2 cart rules (one of rule should be Buy X Get Y Free (x=3, y=1)for example another 10% discount if subtotal >= 500)
2. Add 2 products to cart (subtotal >= 500)

**Actual result**:
Rule 10% if subtotal >= 500 doesn't work
Cart rules don't work if rule Buy X Get Y Free is enabled

**Additional context**:
Rules:
 Buy X Get Y Free - https://scandipwapmrev.indvp.com/admin/sales_rule/promo_quote/edit/id/4/key/9a130202e6f8d34c274face29e5ba3e1f58c630936d8576bd07b1312020eda5c/
10%discount if subtotal >= 500 - https://scandipwapmrev.indvp.com/admin/sales_rule/promo_quote/edit/id/9/key/9a130202e6f8d34c274face29e5ba3e1f58c630936d8576bd07b1312020eda5c/

**Comment by zans-laksa** [comment]
This is likely because `discard subsequent rules` option is enabled.
I've disabled this option for all rules and got expected discount value.
![image](https://user-images.githubusercontent.com/73945186/103215207-60afa300-491b-11eb-9cb2-000fc76956f7.png)
