### ISSUE TITLE
Favicon is missing on website

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1908]
**Description**:
Favicon is missing on website

**Expected behavior**:
Favicon is displayed on website and in admin panel

**To Reproduce**:
1. Create new instance in ReadyMage
2. Add favicon
2. Save
3. Look favicon in admin panel
4. Open website

**Actual result:**:
Favicon image is broken in Admin panel (on pmrev the same)
Favicon is missing on website

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/customization/pull/14
