### ISSUE TITLE
Related products (name, price) and tabs have incorrect offset on product page 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1910]
**Description**:
What is wrong? What happened?

**Expected behavior**:
Tabs/Product text haven't offset
![image](https://user-images.githubusercontent.com/73526235/102477980-b9528680-4065-11eb-84a0-8261515a64ba.png)
![image](https://user-images.githubusercontent.com/73526235/102477685-57921c80-4065-11eb-9ee1-c965559bdd6d.png)

**To Reproduce**:
1. Open product with related products
2. Scroll down

**Actual result**:
Products (name, price) have incorrect offset on product page 
![image](https://user-images.githubusercontent.com/73526235/102477416-fff3b100-4064-11eb-9636-eec6470915f0.png)
+ Tabs (product information/attributes/revies) have incorrect offset on product page too 
![image](https://user-images.githubusercontent.com/73526235/102477391-f9653980-4064-11eb-9aa6-e2a2e1a9d5a3.png)

**Additional context**:
The same situation with:
- Up-sell products on product page 
- Cross-sell products in the cart

**Comment by lianastaskevica** [comment]
cannot reproduce on latest ScandiPWA version
