### ISSUE TITLE
Can't add bundle product from wishlist to cart

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1911]
**Description**:
Can't add bundle product from wishlist to cart

**Expected behavior**:
Can add bundle product to cart
Price is displayed for bundle product

**To Reproduce**:
1. log in
2. add bundle product to wishlist
3. open Wishlist
4. Tap 'Add to cart'

**Actual result**:
Error and success messages appear but product didn't add to cart
+ Price for this product is missing
![image](https://user-images.githubusercontent.com/73526235/102478390-354cce80-4066-11eb-9320-7f3f7378d3e7.png)

**Comment by tatiana-scandi** [comment]
More precise description:
**Bundle product with option marked as Required can be added to wishlist or cart without selecting it** (option type: checklist, but other option types have to be checked as well).
Product example: https://scandipwapmrev.indvp.com//default/test-bundle.html
Config:
<img width="588" alt="Bundle+product+1++Products++Inventory++Catalog++Magento+Admin+Scandipwa+2021-03-23+13-25-37" src="https://user-images.githubusercontent.com/79456428/112132156-5b40bc80-8bdb-11eb-8b24-5f106f1e3a83.png">

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/wishlist-graphql/pull/15 + https://github.com/scandipwa/scandipwa/pull/2373

Recheck the issue after PRs for https://github.com/scandipwa/scandipwa/issues/1876 are merged.
