### ISSUE TITLE
Mobile: About us and contact are displayed between currency and store dropdowns

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1920]
**Description**:
About us and contact are displayed between currency and store dropdowns

**Expected behavior**:
About Us and Contact are displayed below the menu

**To Reproduce**:
1. Open menu 

**Actual result**:
About us and contact are displayed between currency and store dropdowns
![Screenshot_20201217-155614_Chrome](https://user-images.githubusercontent.com/73526235/102602138-c769db00-4129-11eb-8ffa-ad21438255f7.jpg)

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2253
