### ISSUE TITLE
Demo: Error message 'Internal server error' appears when user shares wishlist

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1925]
**Description:**
Error message 'Internal server error' appears when user shares wishlist

**Expected behavior:**
The wishlist is shared. User will receive an email

**To Reproduce:**
Open website
Log in
Open product -> Add to Wish List -> Open Wishlist
Tap 'Share Wish List'
Enter Email and message
Tap 'Share Wish List'

**Actual result::**
Error message 'Internal server error' appears
![image](https://user-images.githubusercontent.com/73526235/102611371-72cd5c80-4137-11eb-859a-ab0f5ebb0848.png)

**Comment by tatiana-scandi** [comment]
@aleksandrakorolova didn't manage to reproduce the issue, I was able to share the wishlist successfully, please, recheck
https://scandipwapmrev.indvp.com/default/wishlist/shared/SOYfrewPJ8W0761HtR1hWu1KdtWlfmnj

**Comment by aleksandrakorolova** [comment]
@tatiana-scandi it works on scandipwapmrev but this issue exists only on demo website - https://40kskudemo.scandipwa.com/

**Comment by aleksandrakorolova** [comment]
Closed task because can't reproduce
![Screenshot 2021-09-02 at 13 27 35](https://user-images.githubusercontent.com/73526235/131838203-f6a975d1-8de6-4556-adf5-845a4d80da42.png)
