### ISSUE TITLE
Long name for some product looks ugly

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1941]
**Description**:
Long name for some product looks ugly

**Expected behavior**:
Can see all product name
![image](https://user-images.githubusercontent.com/73526235/102772163-ba4e2580-438f-11eb-9a67-d5e6da35a6e3.png)

**To Reproduce**:
1. Open women category
2. Scroll down

**Actual result**:
Product name looks ugly
![image](https://user-images.githubusercontent.com/73526235/102772177-bfab7000-438f-11eb-9238-fe1fc016533a.png)

**Comment by lianastaskevica** [comment]
cannot reproduce on 3.3.0
