### ISSUE TITLE
Some images are missing on product page if user added video to this product

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1944]
**Description**:
Some images are missing on product page if user added video to this product

**Expected behavior**:
All images and video are displayed on product page

**To Reproduce**:
1. Open product X with images 
2. Add video to this product
3. Open product page

**Actual result**:
2 images are missing on product page
![image](https://user-images.githubusercontent.com/73526235/102880719-72dd9d00-4454-11eb-90d5-c0f12702bb52.png)
In Admin panel:
![image](https://user-images.githubusercontent.com/73526235/102880747-7cff9b80-4454-11eb-9464-c831c32cc6bc.png)

**Additional context**:
Product on website: https://scandipwapmrev.indvp.com/default/travel-bag.html
Product in Admin panel:https://scandipwapmrev.indvp.com/admin/catalog/product/edit/id/2671/set/4/key/a482972b578e9180953122a590ed7fdbe2d020493896130a1363cc910b8c6023/type/simple/store/0/back/edit/

**Comment by tatiana-scandi** [comment]
Additional details:
Backend issue.
Position property is not updated properly for an image/video after deleting previous images/videos.
![image](https://user-images.githubusercontent.com/79456428/108842076-c6ea3680-75e9-11eb-950c-4be83212997a.png)
