### ISSUE TITLE
ESLint shows errors on page creation

### ISSUE THREAD

**Issue by Scandi-Andy** [scandipwa/scandipwa#1946]
**Description**:
The website gives an error when following tutorial. Before showing and error, the button can be seen for a moment. 
Adding ```/* eslint-disable */ ``` comment solves the issue.

**Screenshots**
With export:
![image](https://user-images.githubusercontent.com/76476135/102879841-e044fa00-4463-11eb-88dc-85f5fecded58.png)
Without export:
![image](https://user-images.githubusercontent.com/76476135/102881307-197e6980-4466-11eb-8df4-751fb07fa261.png)

**To Reproduce**:
Follow the video till creation of index.js and rendering button
https://www.youtube.com/watch?time_continue=170&v=0cdrcAbzlr0&feature=emb_title&ab_channel=ScandiPWA

**Versions**:
- ScandiPWA: 3.2.5
- eslint: 7.16.0
- @scandipwa/eslint-config: 0.1.9

**Comment by alfredsgenkins** [comment]
Indeed, the ESLint rules were disabled for tutorial purposes. You can disable yours by adding following code to your `eslintConfig` field in `package.json`:

```
 "ignorePatterns": [
    "**/src"
]
```

Let me know if that helps.

**Comment by yeegor** [comment]
I think this is safe to close. All the assets created with `scandipwa-cli` are ESLint-safe.
