### ISSUE TITLE
Error message 'No results found!' appears if user search specific product

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1947]
**Description**:
Error message 'No results found!' appears if user searched specific product

**Expected behavior**:
Search script look up matches and  all products with 'T-shirts' appear

**To Reproduce**:
1. Enter 'Puma' in search line
2. Enter 'T-shirt' in the search line

**Actual result**:
Error message 'No results found!' appears 
![image](https://user-images.githubusercontent.com/73526235/102881381-6efe4a80-4455-11eb-9374-df80f18e22d8.png)

**Comment by aleksandrakorolova** [comment]
Closing as can't reproduce
![image](https://user-images.githubusercontent.com/73526235/104733714-cbe4dc00-5747-11eb-9851-76a70ff2260c.png)
![image](https://user-images.githubusercontent.com/73526235/104733728-d0a99000-5747-11eb-8805-ceae719e22a7.png)

**Comment by aleksandrakorolova** [comment]
Can reproduce this issue 
![image](https://user-images.githubusercontent.com/73526235/109281710-516aaa00-7825-11eb-933a-3bddb18a8c57.png)
![image](https://user-images.githubusercontent.com/73526235/109281727-54659a80-7825-11eb-9ad8-5a27fedd52f7.png)

**Comment by AleksandrsKondratjevs** [comment]
Hello!

I dumped DB from staging and locally there is no such issue appearing in search, so I suggested issue is elasticsearch indexing.
Reindex on staging resolved this issue at the moment and if this issue appears again please  note steps that are made to trigger this issue.
