### ISSUE TITLE
FireFox(Win): Every even delete icon is broken in cart and mini- cart

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1955]
**Description**:
Every even delete icon is broken in cart and mini- cart

**Expected behavior**:
Delete icon looks good for all products in cart/mini-cart
![image](https://user-images.githubusercontent.com/73526235/102971419-07ea9f80-4502-11eb-9111-0a89283cd154.png)

**To Reproduce**:
1. Open website
2. Add few products to cart
3. Open cart
4. Open mini-cart

**Actual result**:
Delete icon for the first product looks good, but icon is broken for the second product in cart and mini-cart
![deleteIconInCart](https://user-images.githubusercontent.com/73526235/102971428-0caf5380-4502-11eb-8d5c-6928b99a841a.PNG)

**Additional context**:
Every even delete icon is broken
FF: v83

**Comment by k-gorod** [comment]
I google this problem. It is normal. The same bug with line "- qty" square;
![image](https://user-images.githubusercontent.com/58625453/103036688-6869f300-457b-11eb-8223-27a75923b4f6.png)
In some positions of screen scroll it is happens.
It is not our bug but browsers. 
It is fixing by adding width to thin lines.

**Comment by aleksandrakorolova** [comment]
Closed task because Delete icon is missing after redesign
