### ISSUE TITLE
iOS 11 or less version: Error message in console and website doesn't open 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1959]
**Description**:
iOS 11 or less version: Error message in console and website doesn't open 
**Expected behavior**:
User sees homepage

**To Reproduce**:
1. Open website - https://master.d25kd40decjpue.amplifyapp.com/default/ on iOS 11 or less or iPhone 6s v12

**Actual result**:
Can't open website
![image](https://user-images.githubusercontent.com/73526235/102987169-9d922900-451a-11eb-8187-4d013d9e9c14.png)

**Comment by lianastaskevica** [comment]
https://github.com/scandipwa/create-scandipwa-app/pull/9
