### ISSUE TITLE
Config product is deleted from wishlist if user added this product to cart on product page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1961]
**Description**:
Config product is deleted from wishlist if user added this product to cart on product page

**Expected behavior**:
The product stays in wishlist

**To Reproduce**:
1. Log in
2. Add config product to wishlist
3. Open this conf product page
4. Select the same attributes 
5. Add to cart

**Actual result**:
Messages appear (success message and message 'Product has been removed from your Wish List!') 
Product is deleted from wishlist

**Additional context**:
Simple product stays in wishlist

**Comment by lianastaskevica** [comment]
this is the expected behavior for the wishlist functionality. When the products are added to the cart (from any place), they get removed from the wishlist.
