### ISSUE TITLE
Currency switcher doesn't work

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1966]
**Description**:
Currency switcher doesn't work

**Expected behavior**:
Currency EUR is displayed for all products

**To Reproduce**:
1. Open website - https://3-3-0-rc.d25kd40decjpue.amplifyapp.com/default/
2. Switch currency to EUR 

**Actual result**:
Currency $ is displayed for all products

**Comment by lianastaskevica** [comment]
cannot reproduce on scandipwa 3.3.0
