### ISSUE TITLE
Products don't sort by price on category page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1981]
**Description**:
Products don't sort by price on category page

**Expected behavior**:
Products sort by price (Low -High) on category page

**To Reproduce**:
1. Open category page https://3-3-0-rc.d25kd40decjpue.amplifyapp.com/default/women/women-dresses?sortKey=price&sortDirection=ASC
2. Sort by price

**Actual result**:
Products order changes but it not correct
![image](https://user-images.githubusercontent.com/73526235/103209777-8a150280-490c-11eb-8422-c5f7e554ca31.png)

**Comment by riha112** [comment]
Database issue on scandipwapmrev
