### ISSUE TITLE
Page title always displays 'Scandipwa'

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1992]
**Description**:
Page title always displays 'Scandipwa'

**Expected behavior**:
Product title is displayed for product page 
Category title is displayed for category page and etc

**To Reproduce**:
1. Open product page
2. Open category page

**Actual result**:
Page title always displays 'Scandipwa' for all pages
![image](https://user-images.githubusercontent.com/73526235/103289303-8ad29500-49ef-11eb-9980-00be6cf6a649.png)
![image](https://user-images.githubusercontent.com/73526235/103289333-9aea7480-49ef-11eb-9f51-60e2a658c02a.png)

**Comment by AleksandrsKondratjevs** [comment]
Hello!
Locally on scandipwa latests version I can't reproduce this issue. Default page title is not forcing to replacing category/product page title.

**Comment by aleksandrakorolova** [comment]
Closing as can't reproduce on pmrev 
![image](https://user-images.githubusercontent.com/73526235/104903956-50726d00-5989-11eb-9124-a59482e0bc4c.png)
