### ISSUE TITLE
Error message 'This field is required!' is displayed below each field if user entered valid data in create account form

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2015]
**Description**:
Error message 'This field is required!' is displayed below each field if user entered valid data

**Expected behavior**:
Error message is missing below field if user entered valid data

**To Reproduce**:
1. Open create account form
2. Tap 'Create account'
3. Fill form with valid data

**Actual result**:
Error message 'This field is required!' is displayed below each field
![image](https://user-images.githubusercontent.com/73526235/103522474-19796300-4e83-11eb-822f-689159da7bad.png)

**Comment by winniepukki** [comment]
@aleksandrakorolova @lianastaskevica Unable to reproduce
https://drive.google.com/file/d/1p_GYzu7Y4ODjs7YL7PTNwnF_m51jR0Rk/view?usp=sharing

**Comment by winniepukki** [comment]
@aleksandrakorolova could you please check whether the *Password match* issue should not be reopened? Looks like field match validation has flew away somewhere

**Comment by lianastaskevica** [comment]
@aleksandrakorolova Please retest and let us know if can be closed

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
