### ISSUE TITLE
iOS 9 or less version: Error message in console and website doesn't open

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2022]
**Description**:
 Error message in console and website doesn't open

**Expected behavior**:
User sees homepage

**To Reproduce**:
1. Open website on iOS9 

**Actual result**:
Can't open website
![image](https://user-images.githubusercontent.com/73526235/103526036-e3d77880-4e88-11eb-8fa0-2e5909644664.png)

**Comment by tatiana-scandi** [comment]
Will not be fixed due to technical limitations (custom properties are widely used in the project whilst iOS 9 Safari version doesn't support them)
