### ISSUE TITLE
Category names didn't display under each other in Layered Navigation

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2035]
**Description**:
Category names didn't display under each other in Layered Navigation

**Expected behavior**:
Category name should be under each other in Layered Navigation

**To Reproduce**:
1. Create new instance in ReadyMage
2. Create subcategories
3. Open Category which has subcategories

**Actual result**:
Category names show inline
![image](https://user-images.githubusercontent.com/73526235/103644240-b826c200-4f5e-11eb-94e9-9d8fb200f0a8.png)

**Comment by vromash** [comment]
Readymage uses ScandiPWA 3.2.3 version as default. Couldn't replicate this issue locally and haven't seen this problem on demo stores (demo stores use 3.2.4).

**Comment by Elena-Evsa** [comment]
Can not reproduce 
![image](https://user-images.githubusercontent.com/84388061/187434008-354be0b3-2611-40d7-badb-e2a5432ecd29.png)
