### ISSUE TITLE
Wrong price in cart after adding couponcode

### ISSUE THREAD

**Issue by magexpert** [scandipwa/scandipwa#2039]
Seems scandipwa is still with may issues and bugs. Even with simple magento 2 configuration.

Added a cart rule with coupon code of 20%. 
Order a product and go to cart page.
Add the coupon code and discount amount appears.
But calculation is wrong. 
Basicly subtotal is price exluding vat. Vat is 21% total is subotal incl. vat.
after adding coupon code subtotal stays same but discount and vat ????
So total is not correct.
total should be subtotal + vat minus discount.

to test and check rvssanitairgroothandel.nl use start2021 in cart page and see result.

**Comment by magexpert** [comment]
sample https://www.screencast.com/t/MMiFdOnp and https://www.screencast.com/t/R4R1nYIN

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
@magexpert you can recheck this on scandipwapmrev site (coupon code '20')
![Screenshot 2021-11-30 at 11 51 18](https://user-images.githubusercontent.com/73526235/144024738-5609ac26-a03c-43aa-b3e7-64c999c97142.png)
