### ISSUE TITLE
Excl. tax = incl. tax for config products on category and product pages if catalog rule is applied to this category

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2052]
**Description**:
Excl. tax = incl. tax for config products on category and product pages if catalog rule is applied to this category

**Expected behavior**:
Correct excl tax price is displayed = $112 on category and product pages

**To Reproduce**:
1. Create catalog rule 
2. Log in 
3. Open sunglasses category
3. Open config product in this category

**Actual result**:
If user didn't select attributes, excl. tax = incl. tax = $119
If user selected attributes (size and color), Correct excl tax price is displayed = $112 
https://drive.google.com/file/d/1W17KoyqsaGs67UWhPWbKKzhKdq8y0rig/view?usp=sharing

**Additional context**:
Rule in the admin panel: https://scandipwapmrev.indvp.com/admin/catalog_rule/promo_catalog/edit/id/5/key/51eb992810112fca787b0b08d070832d4d9a70439f8006595b5a84c4e672770f/

**Comment by tatiana-scandi** [comment]
https://scandipwapmrev.indvp.com/demo/n-black-sunglasses.html
![Black sunglasses Scandipwa 2021-06-24 16-53-20](https://user-images.githubusercontent.com/79456428/123294436-bf418c80-d50c-11eb-9017-cb14f465f184.png)
If you look at "Black sunglasses" product in Luma, you will see that:

1. Only one configuration is available
2. If you select this configuration, you see $116 incl. tax, $116 excl tax

What we expect, is to see the smallest price of the options available for purchase, and it works as expected.

P.S. I see, that all options are displayed as available, while only only one is available is Luma, but this is another bug (please, add to github, if not yet).

**Comment by carinadues** [comment]
I'd say this is still an issue. If you look below, on the left is the product as it opens. On the right is this product with the only option selected. The price for excluding tax does not match as it should.

![image](https://user-images.githubusercontent.com/82165392/123871419-1cbd4b00-d90a-11eb-81fa-f936c5c0c254.png)

P.S. About the options displayed as available, if you check in this link it should be fixed: https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/n-black-sunglasses.html

**Comment by tatiana-scandi** [comment]
Copying from DM for history:

https://monosnap.com/file/Y6pJIEkWjVH00DFGE2nctrdFvf4sKG
If you select the only available option in Luma, you have Price excl. tax equal to 150 USD.
So the issue seems to be that price is incorrect when we select an option. And this is a different issue.

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
![Screenshot 2021-10-04 at 14 30 08](https://user-images.githubusercontent.com/73526235/135844233-2767bfc6-def2-4c17-9156-3f4fb4837801.png)
![Screenshot 2021-10-04 at 14 30 13](https://user-images.githubusercontent.com/73526235/135844239-7ef3cdb3-e715-44fa-8880-bfb4af49c571.png)
