### ISSUE TITLE
Configurable attributes in product page always loading

### ISSUE THREAD

**Issue by devselegento** [scandipwa/scandipwa#2055]
**Description**:
In storefront product page for Configurable, the attributes cannot be selected and the loading above the - Choose attribute - dropdown is always showing

**Expected behavior**:
Be able to select configurable attributes

**Versions**:
- ScandiPWA: 4.0.0

**Additional context**:
Item configurable_options and  variants from graphql are properly fetched.

**Comment by lianastaskevica** [comment]
Hello @devselegento! Please make sure your attribute is marked as "Visible on Catalog Pages on Storefront" in admin -> Stores -> Attributes -> Product -> Attribute edit mode -> Storefront Properties. Otherwise, the attribute will be infinitely loading on the product page.

**Comment by devselegento** [comment]
Thank you @lianastaskevica ! Tried that and now is working fine.
