### ISSUE TITLE
Product with customizable options required field label display & toast message not consistent.

### ISSUE THREAD

**Issue by kyeng-vis** [scandipwa/scandipwa#2057]
**Description**:
`This field is required!` sign under customizable options shows on initial visit, not showing subsequent visit.
Toast notification display different message.

**Expected behavior**:
Both required field sign & toast notification show consistent message.

**To Reproduce**:
1. Go to https://scandipwapmrev.indvp.com/default/custom-product-test.html
2. Click on 'ADD TO CART' without selecting option
3. Notice the toast message & "This field is required!" 
4. Click on breadcrumbs 'Shoes'
5. Click on product 'BOTTESINI with customization'
6. Click on 'ADD TO CART' without selecting option
7. Check the toast message is different & "This field is required!" is gone

**Additional Information**
At Step 4, visit other product page then go back to catalog, revisit 'BOTTESINI with customization' show same result at initial visit

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2246
