### ISSUE TITLE
Product page is scrolled down when visiting it

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#2058]
**Description**:
The product page is scrolled down when visiting it

**Expected behavior**:
The product page is not scrolled down

**To Reproduce**:
1. Open https://scandipwapmrev.indvp.com/default/women/women-dresses
2. Select "Dress Rinascimento" product
3. Scroll down to "Recommeded for you" in the PDP
4. Select any of the recommended products

OR

1. Open the homepage
2. Scroll to the bottom of the page
3. Choose one of the products in "New Products"
4. Press back in the browser
5. Select any product from the "New Products" again.

**Comment by winniepukki** [comment]
Reopening issue, based on [the following](https://github.com/scandipwa/scandipwa/pull/2106#issuecomment-762108282) QA Status report
