### ISSUE TITLE
Password field and error message shifted when entering invalid password

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2060]
**Description**:
Password field and error message shifted if user entered invalid password

**Expected behavior**:
Error message appears above field and button
![image](https://user-images.githubusercontent.com/73526235/104015093-d4c03580-51bc-11eb-9861-d763b8b8098f.png)

**To Reproduce**:
1. Open Admin panel -> go to Stores > Settings > Configuration -> Customers -> Customer Configuration -> Create New Account Options section -> Select 'Yes' in Require Emails Confirmation field
2. Tap 'Save' -> Flush Cache Storage
3. Open website 
4. Create account 
5. Open the email
6. Open Confirmation link
7. Enter invalid password

**Actual result**:
Field and error message shifted
![image](https://user-images.githubusercontent.com/73526235/104014674-1f8d7d80-51bc-11eb-8673-0c6f2d68cfc9.png)

**Comment by tatiana-scandi** [comment]
@aleksandrakorolova looks like the issue is already fixed in master branch
<img width="283" alt="ScandiPWA+2021-03-10+10-42-05" src="https://user-images.githubusercontent.com/79456428/110594163-819f3a80-818d-11eb-93d6-72313dddff68.png">

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
