### ISSUE TITLE
Can't disable state/province from shipping address

### ISSUE THREAD

**Issue by Ylmzef** [scandipwa/scandipwa#2063]
**Description**:
Can't disable state/province from shipping address.

**Expected behavior**:
It's disabled from luma theme but not on scandipwa.

**To Reproduce**:
- Login to the back end of Magento 2.
- On the Admin sidebar, navigate to Stores > Settings > Configuration.
- Under the panel of General, select General.
- Scroll down to explore the State Option section.
- Choose the country where the State/ Region is required.
- In the box of Allow to Choose State if it is Optional for Country, select Yes if the state field is not compulsory including the optional State field, select No if the state field is not compulsory but omitting the State field.
- Click Save Config. to save all the process.

**Versions**:
scandipwa/cache ^1.1.1
scandipwa/catalog-graphql ^3.1.6
scandipwa/cms-graphql ^1.4.2
scandipwa/compare-graphql ^1.0.2
scandipwa/contact-graphql ^1.0.0
scandipwa/customer-graph-ql ^2.2.3
scandipwa/customization ^1.4
scandipwa/installer ^4.0
scandipwa/klarna-graphql ^1.1.2
scandipwa/locale ^1.2
scandipwa/menu-organizer ^2.0
scandipwa/performance ^1.4.2
scandipwa/persisted-query ^3.0
scandipwa/quote-graphql ^2.17.6
scandipwa/route717 ^2
scandipwa/slider-graphql ^2.0
scandipwa/store-graphql ^1.1.3
scandipwa/urlrewrite-graphql ^1.3.1
scandipwa/wishlist-graphql ^2

**Comment by lianastaskevica** [comment]
Hey @Ylmzef! This feature is actually not yet supported in the ScandiPWA (https://manual.scandipwa.com/basic-configuration/store-details/state-options). I will convert this issue to a feature:)
