### ISSUE TITLE
Add 'Add to Wishlist' icon for products in compare list 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2069]
**Description**:
Add 'Add to Wishlist' icon for products in compare list 

**Additional context**:
Default Magento:
![image](https://user-images.githubusercontent.com/73526235/104170224-73d96d00-5409-11eb-9a0c-a795c050b66f.png)

**Comment by Elena-Evsa** [comment]
1. 'Wish list' icon in Compare list is crossing the border of some items
![image](https://user-images.githubusercontent.com/84388061/124894727-96c59200-dfe4-11eb-94fc-36ee6629d5a3.png)

2. When click on 'Wish list' icon in Compare list at the simple product, it is added to Wish list, success message appear. But 'Wish list' icon stays grey.
Expected result: 
'Wish list' icon become orange if product added to Wish list. 
All items, that we have in Wish list, have orange 'Wish list' icon (as on PLP)
![image](https://user-images.githubusercontent.com/84388061/124895925-aa252d00-dfe5-11eb-9fbd-d4723aaf2c1c.png)

**Comment by carinadues** [comment]
Closing because this issue is solved by the new theme redesign https://github.com/scandipwa/scandipwa/pull/2783

**Comment by aleksandrakorolova** [comment]
Can reproduce the first issue - Wishlist icon overlaps to Add to cart button
![Screenshot 2021-07-19 at 15 26 07](https://user-images.githubusercontent.com/73526235/126159580-192401de-badd-4401-8f94-958699901a23.png)

Expected result:
![Screenshot 2021-07-19 at 15 28 47](https://user-images.githubusercontent.com/73526235/126159833-1b3d4b4e-035d-431c-834b-a9490ec8cedf.png)

**Comment by aleksandrakorolova** [comment]
Use compare list for user asd@asd.asdd/Scandipwa123

**Comment by carinadues** [comment]
Checked on Safari on mobile and Chrome on desktop and it is all good. 

cc: @aleksandrakorolova
