### ISSUE TITLE
iOS: Chrome and Android: Firefox: Page leads to Ooops page when opening empty cart for the first time

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2092]
**Description**:
Page leads to Ooops page when opening empty cart for the first time

**Expected behavior**:
Empty cart opens

**To Reproduce**:
1. Open website in incognito mode
2. Open empty cart

**Actual result**:
Ooops page opens

**Additional context**:
Notes: The "New Version Available" Notification is missing 
Can reproduce:
iOS: Chrome (real device and BrowserStack)
Android: Firefox v84.1.3 (real device only)

**Comment by winniepukki** [comment]
Checked with: **BrowserStack** iOS 12, 13, 14 and **Real device** iPhone XS iOS 14 with no such conflicts

**Comment by aleksandrakorolova** [comment]
Now can't reproduce too
