### ISSUE TITLE
Never-ending loader when user opens product which is sold out

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2098]
**Description**:
Never-ending loader when user opens product which is sold out

**Expected behavior**:
404 page opens

**To Reproduce**:
1. Open Admin panel -> go to Stores > Settings > Configuration -> Catalog -> Inventory -> Expand the Stock Options
2. Choose 'No' in Display Out of Stock Products field
3. Flush Cache Storage
4. Open product page (which out of stock) - https://master.d25kd40decjpue.amplifyapp.com/default/28-virtual-product.html

**Actual result:**:
Never-ending loader (Places for images blink on the product page)
![image](https://user-images.githubusercontent.com/73526235/104712070-d349bc80-572a-11eb-8073-334e518ddd83.png)

**Notes**
It was fixed in #1640. But I can reproduce it on the master

**Comment by winniepukki** [comment]
Might be fixed with [the following](https://github.com/scandipwa/urlrewrite-graphql/pull/3) pull request. QA is required after the Code Review

**Comment by aleksandrakorolova** [comment]
@winniepukki Information about product is missing in the network but user didn't redirect to not found page (404)
![image](https://user-images.githubusercontent.com/73526235/105709897-0821f480-5f1f-11eb-9e0e-30cab0a5138d.png)

**Comment by aleksandrakorolova** [comment]
The same situation if we set to 'yes' in Display Out of Stock Products field
