### ISSUE TITLE
Word UNDEFINED is displayed in the Address book

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2099]
**Description**:
Word UNDEFINED is displayed in the Address book

**Expected behavior**:
Word UNDEFINED is missing
![image](https://user-images.githubusercontent.com/73526235/104729475-27f83200-5741-11eb-9c70-a99c6c06cdb6.png)

**To Reproduce**:
1. Log in 
2. Open Address book
3. Add new address if user doesn't have address

**Actual result**:
Word UNDEFINED is displayed in the Address book
![image](https://user-images.githubusercontent.com/73526235/104729507-35152100-5741-11eb-95e9-f800af2a8b7e.png)

**Comment by vromash** [comment]
It was fixed in i18n package here: scandipwa/create-scandipwa-app@c04aa64
