### ISSUE TITLE
Issue with access site by direct url 

### ISSUE THREAD

**Issue by Stormdo** [scandipwa/scandipwa#2102]
**Description**:
Receive "somethings went wrong notification" sometimes when try to access by direct url 

**Expected behavior**:
Access normally to site by direct url 

**Screenshots, Video, Logs**
https://www.loom.com/share/d65eadf05e8d48d78ffd5fb04267b6f0

**To Reproduce**:

**Versions**:
- ScandiPWA: (use `composer info scandipwa/source`)
- Any other composer module, you thing could be related
- Browser version if relevant to the context
- OS version if relevant to the context

**Additional context**:

**Comment by lianastaskevica** [comment]
Hello @Stormdo! This issue is fixed in the latest release of ScandiPWA, see the reference [here](https://github.com/scandipwa/scandipwa/issues/2091).
