### ISSUE TITLE
Review Summary and Review Count is null

### ISSUE THREAD

**Issue by arangaw** [scandipwa/scandipwa#2105]
**Description**:
Review Summary and Review Count always returns null when customer on PDP.

**Expected behavior**:
Review Summary and Count should be populated with gql.

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/77598955/104869703-aa186e80-596c-11eb-9f33-24660913aefd.png)

**To Reproduce**:
1. Add a Review From FE
2. Verify the Review From BE
3. Check the GraphQl query

**Versions**:
- ScandiPWA: scandipwa/reviews-graphql 1.6.0

**Additional context**:
Issue is due to below file.
https://github.com/scandipwa/reviews-graphql/blob/1.6.0/src/Model/Resolver/Product/DataPostProcessor/ReviewSummaries.php

Code loads review summary collection and summary is added to the product data through the foreach if the loaded product id is matched with the review collection 'entity_pk_value' else the array is empty.

So the issue is if loads product is not the last element of the collection the array resets to empty. So we can add a break; after line no 96 on Product/DataPostProcessor/ReviewSummaries.php file after assign the summary to productData array. 

This will reduce the execution time as well.

`return function (&$productData) {
            $storeId = $this->storeManager->getStore()->getId();
            $reviewSummaries = $this->collectionFactory->create()
                ->addStoreFilter($storeId)
                ->getItems();

                $productId = $productData['entity_id'];

                foreach ($reviewSummaries as $summary) {
                    if ($productId === $summary->getData()['entity_pk_value']) {
                        $ratingSummary = $summary->getRatingSummary();
                        $reviewsCount = $summary->getReviewsCount();

                        $productData[self::REVIEW_SUMMARY] = [
                            'rating_summary' => $ratingSummary,
                            'review_count' => $reviewsCount
                        ];
                        break;
                    } else {
                        $productData[self::REVIEW_SUMMARY] = [];
                    }

                }
        };`

**Comment by AleksandrsKondratjevs** [comment]
Hello @arangaw  !

From described issue we understood that you have problems with getting review_count & rating_summary from GraphQl response.
As I see from attached screenshot you trying to query those fields wrapping them into review_summary field so this cause an issue with null values in response. To get those values manually you need to call them directly in product interface.

Example:
![reviews](https://user-images.githubusercontent.com/68007919/109841845-241d6200-7c52-11eb-9e82-0e966e1bc6af.png)

Please let us know if this resolves your issue.
