### ISSUE TITLE
Word 'undefined' on product page if product has tier price

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2107]
**Description**:
Word 'undefined' on product page if product has tier price

**Expected behavior**:
Text 'Buy 3 for €45.00 each and save 10%' is displayed
![image](https://user-images.githubusercontent.com/73526235/104888141-fe275100-5974-11eb-8f4f-3c2f383b6ff6.png)

**To Reproduce**:
1. Open product page - https://master.d25kd40decjpue.amplifyapp.com/default/jeans.html

**Actual result**:
Text 'Buy 3,€45.00 for **undefined** each and save 10%' is displayed
![image](https://user-images.githubusercontent.com/73526235/104888132-fa93ca00-5974-11eb-826d-e531ff00785b.png)

**Comment by winniepukki** [comment]
This will be fixed [with the following](https://github.com/scandipwa/create-scandipwa-app/pull/12) pull request
