### ISSUE TITLE
Not found page opens if user opened specific product

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2109]
**Description**:
Not found page opens if user opened specific product

**Expected behavior**:
Product page opens

**To Reproduce**:
1. Open product page - https://master.d25kd40decjpue.amplifyapp.com/default/travel-bag.html

**Actual result**:
Not found page opens
![image](https://user-images.githubusercontent.com/73526235/104905697-62550f80-598b-11eb-8d14-d8b8e4a5ca9d.png)

**Notes**
Can reproduce only with this product
I created duplicate of this product - https://master.d25kd40decjpue.amplifyapp.com/default/travel-bag-1.html
It user opens it, the product page will open (404 is missing)

**Comment by kghori36** [comment]
how did you fix that?
