### ISSUE TITLE
Products with original price are displayed in Wishlist if catalog price rule applies to these products

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2125]
**Description**:
Products with original price are displayed in Wishlist if catalog price rule applies to these products

**Expected behavior**:
Product with the actual price (with discount by catalog price rule) is displayed 

**To Reproduce**:
1. Log in 
2. Open Belts category
3. Open product from this category
4. Add product to Wishlist
5. Open Wishlist

**Actual result**:
Product with the original price is displayed

**Additional context**:
Special price is displayed

**Comment by zans-laksa** [comment]
What i've did:
1. Cannot reproduce this locally.
2. Added another cart rule to a different category on the pmrev server. A discount has appeared on the PLP, PDP and Wishlist pages.
3. Disabled / updated Belt category cart rule. No effect.
4. Created a new cart rule to the Belt category. A discount has appeared on the PLP, PDP and Wishlist pages.
5. Removed this new cart rule. No effect. Discount is appearing.
6. Enabled old cart rule. No effect. Removed cart rule discount is still appearing. Cache reset doesn't work.

Most likely this is the cache issue that is reproducible on the server only.

**Comment by aleksandrakorolova** [comment]
We need to do re-index after some changes in catalog price rule, then we can see changes on FE.
Also, sometimes catalog price rule doesn't work...It works correctly some time if we did re-index
