### ISSUE TITLE
Issues related to Safari v10

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2126]
**1. Description**:
Compare icon looks ugly on category and product pages

**Expected behavior**:
![image](https://user-images.githubusercontent.com/73526235/105848534-c315c500-5fe7-11eb-9a4c-336449ca6975.png)

**To Reproduce**:
1. Open Category page
2. Open product page

**Actual result**:
Compare icon looks ugly 
![image](https://user-images.githubusercontent.com/73526235/105848483-b3967c00-5fe7-11eb-95ed-1087f4141ac4.png)

**2. Description**:
Name of product has shifted + text overlays 

**Expected behavior**:
![image](https://user-images.githubusercontent.com/73526235/105848993-7088d880-5fe8-11eb-9cda-680f75fa56f0.png)

**To Reproduce**:
1. Open product page

**Actual result**:
Product page looks ugly 
![image](https://user-images.githubusercontent.com/73526235/105848949-6070f900-5fe8-11eb-9894-df2938957a76.png)

**3. Description**:
Breadcrumb navigation is missing

**Expected behavior**:
Breadcrumb navigation is displayed
![image](https://user-images.githubusercontent.com/73526235/105849194-b776ce00-5fe8-11eb-9e4e-e4394b7ae21f.png)

**To Reproduce**:
1. Open product page

**Actual result**:
Breadcrumb navigation is missing
![image](https://user-images.githubusercontent.com/73526235/105849284-d5dcc980-5fe8-11eb-9e27-bf9ddfeaf70a.png)

**4. Description**:
Rate (stars) has shifted from product card

**Expected behavior**:
Breadcrumb navigation is displayed
![image](https://user-images.githubusercontent.com/73526235/105849818-91056280-5fe9-11eb-8033-da0d47e5e33d.png)

**To Reproduce**:
1. Open product page

**Actual result**:
Rate (stars) has shifted from product card
![image](https://user-images.githubusercontent.com/73526235/105849838-9793da00-5fe9-11eb-980a-01fc831cf81b.png)
![image](https://user-images.githubusercontent.com/73526235/105849792-8a76eb00-5fe9-11eb-903b-ef412765a21e.png)

**5. Description**:
Small images on product page

**Expected behavior**:
Normal images are displayed
![image](https://user-images.githubusercontent.com/73526235/105850193-1557e580-5fea-11eb-8fce-a9fd1d3a9081.png)

**To Reproduce**:
1. Open product page

**Actual result**:
Small images are displayed on product page
![image](https://user-images.githubusercontent.com/73526235/105850183-10933180-5fea-11eb-9c87-249b3f6ea26e.png)

**6. Description**:
User can't see all products on the men category page

**Expected behavior**:
All page is displayed. User can see all products 

**To Reproduce**:
1. Open men category - https://master.d25kd40decjpue.amplifyapp.com/default/men
2. Scroll down

**Actual result**:
User can't see all products
![image](https://user-images.githubusercontent.com/73526235/105850696-bc3c8180-5fea-11eb-9c2a-33bf3f4c15d8.png)

**Additional context**:
the same situation with accessories catrgory
Others categories - ok

**7. Description**:
Word 'Account' has shifted

**Expected behavior**:
Word 'Account' is displayed on the same line as cart
![image](https://user-images.githubusercontent.com/73526235/105950359-ef2c5700-6076-11eb-9bd8-921facea216e.png)

**To Reproduce**:
1. Open website

**Actual result**:
Word 'Account' has shifted
![image](https://user-images.githubusercontent.com/73526235/105950270-c3a96c80-6076-11eb-9405-9186cb845092.png)

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2237

1. Fixed
2. Fixed
3. Fixed
4. Fixed
5. Not fixed
6. Not fixed
7. Fixed
