### ISSUE TITLE
Yarn build -> m2-theme 0.1.2

### ISSUE THREAD

**Issue by teodormoq** [scandipwa/scandipwa#2131]
**Description**:
Failing on build process

**Expected behavior**:
No Error

**Screenshots, Video, Logs**
`(node:50532) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Function.getFallbackPathname (/Users/teodormoquist/Documents/Solutions/example/node_modules/@scandipwa/m2-theme/node_modules/@scandipwa/webpack-fallback-plugin/index.js:45:36)
    at Object.overrideCracoConfig (/Users/teodormoquist/Documents/Solutions/example/node_modules/@scandipwa/m2-theme/build-config/craco.js:25:51)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:50532) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:50532) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**To Reproduce**:
1. yarn build

**Versions**:
"@scandipwa/m2-theme": "^0.1.2"

**Additional context**:
I Found a fix:
nano node_modules/@scandipwa/m2-theme/node_modules/@scandipwa/webpack-fallback-plugin/index.js
line: 44
static getFallbackPathname(pathname, sources = {}) {

**Comment by MagicLegend** [comment]
@teodormoq This is caused by a dependency mismatch. It can be solved by updating `@scandipwa/webpack-fallback-plugin` to `^1.2.0`. `@scandipwa/m2-theme` should be updated to accommodate this change (it is the package that requires the incompatible `webpack-fallback-plugin` version).

**Comment by teodormoq** [comment]
@MagicLegend fixed this issue closing it #2146
