### ISSUE TITLE
Issue with importing components into plugin

### ISSUE THREAD

**Issue by AleksandrsKondratjevs** [scandipwa/scandipwa#2150]
**Description**:
Can't import components from extension into plugins.

**Expected behavior**:
Can import and use components from extension in plugins.

**Screenshots, Video, Logs**
![extension](https://user-images.githubusercontent.com/68007919/106475558-bb09c980-64ae-11eb-9dd9-ea2dbd43b2a5.png)

**To Reproduce**:
1. Create plugin
2. Try to import component from same extension directory

**Versions**:
- ScandiPWA: last version

**Comment by alfredsgenkins** [comment]
Duplicate of https://github.com/scandipwa/scandipwa/issues/2018
