### ISSUE TITLE
Field validation is missing

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#2153]
**Description**:
Field validation is missing

**Expected behavior**:
Validation is present 

**To Reproduce**:
1. Open login overlay
2. Make sure all fields are empty
3. Click on login
4. Notice there is not field validation

**Comment by winniepukki** [comment]
@lianastaskevica @aleksandrakorolova should this issue be reassured by QA once again?

![image](https://user-images.githubusercontent.com/43637240/107047175-31b90680-67d0-11eb-8921-19e83335ccf9.png)

**Comment by aleksandrakorolova** [comment]
@winniepukki I can reproduce this issue on master and 4-1-0-rc

**Comment by winniepukki** [comment]
@lianastaskevica @aleksandrakorolova successfully reproduced this bug. Should be fixed ASAP.
