### ISSUE TITLE
Multistore URL structure bug

### ISSUE THREAD

**Issue by teodormoq** [scandipwa/scandipwa#2156]
**Description**:
Currently its not possible for the website to have another base-url than the storeview code, e.g. if the base_ul is `example.com/da-dk` and the storeview code is `da` then the website dont work.

**Expected behavior**:
Expected that the storeview code and base_url isn't dependent on each other.

**To Reproduce**:
1. Go to admin Panel
2. Stores -> Settings -> Configuration
3. General -> Web -> Base URLs
4. Change the Base URL to something that dont match the storeview code

**Versions**:
"@scandipwa/m2-theme": "^0.1.2"

**Comment by riha112** [comment]
Unable to reproduce when server is configured correctly: 

Based on Magento documentation about storeview url setup (https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_websites.html (step 6.)) When setting up URL that is not the same as store code requires manual server setup for it to work... For example nginx requires following config changes:
```
map $HTTP_HOST $MAGE_RUN_CODE {
    xample.com/da-dk da;
    <url> <storeview-code>;
}
```
For extra help about configuration you can check this article: https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_nginx.html
