### ISSUE TITLE
Use Categories Path for Product URLs / M2 Support

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#2161]
**Description**:
You can configure the URL to either include or exclude the category path. By default, the category path is included in all category and product pages. The following examples show the same product URL with, and without, the category path.

URL with category path
http://mystore.com/women/tops-women/hoodies-and-sweatshirts-women/helena-hooded-fleece.html
URL without category path
http://mystore.com/helena-hooded-fleece.html

More info - https://docs.magento.com/user-guide/catalog/catalog-urls.html

**Comment by winniepukki** [comment]
@carinadues @lianastaskevica @teodormoq based on the linked PR, it looks like the issue is resolved. Should I proceed, anyways?

**Comment by teodormoq** [comment]
Hi @winniepukki the linked PR should work.

**Comment by winniepukki** [comment]
@carinadues @lianastaskevica @teodormoq cool. I have assigned you to the issue to avoid duplicates! Thanks for a quick reply!!
