### ISSUE TITLE
Field frame stays green if user deleted text from mandatory field on product page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2162]
**Description**:
Field frame stays green if user deleted text from mandatory field on product page

**Expected behavior**:
Field frame becomes red

**To Reproduce**:
1. Open product page - https://4-1-0-rc.d25kd40decjpue.amplifyapp.com/default/testing-simple.html
2. Enter something in text field
3. Delete it

**Actual result:**:
Field frame is green
![image](https://user-images.githubusercontent.com/73526235/106742050-2a092e80-6625-11eb-8bee-ca5ffc53a8c3.png)

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2211
