### ISSUE TITLE
Sometimes strange symbol instead stars is displayed on product/category pages

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2163]
**Description**:
Strange symbol  instead stars is displayed on product/category pages

**Expected behavior**:
Stars are displayed

**To Reproduce**:
1. Open category page or product page ( product should have review)

**Actual result:**:
Stars based on rate are missing. The strange symbol is displayed
![image](https://user-images.githubusercontent.com/73526235/106737515-72255280-661f-11eb-8c14-6d69fd40cbac.png)
![image](https://user-images.githubusercontent.com/73526235/106737550-7b162400-661f-11eb-91f4-a96f5a5e55be.png)
![image](https://user-images.githubusercontent.com/73526235/106737564-7e111480-661f-11eb-873f-7ece04d5a8c0.png)

**Comment by riha112** [comment]
This issue should be solved by #2897

**Comment by carinadues** [comment]
Closed issue, as PR https://github.com/scandipwa/scandipwa/pull/2897 is merged.
