### ISSUE TITLE
Products disappear for 2-3sec in the cart when user applying valid coupon

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2164]
**Description**:
Products disappear for 2-3sec in the cart when user applying valid coupon

**Expected behavior**:
Products are displayed all time

**To Reproduce**:
1. Add products to Cart
2. Open Cart
3. Enter valid Coupon

**Actual result:**:
Products disappear and after some time these appear again
https://drive.google.com/file/d/1Oq5gBL6uGSqdIpXVtySTYCkkXFrfVGUa/view?usp=sharing

**Comment by zans-laksa** [comment]
Cannot reproduce.

**Comment by aleksandrakorolova** [comment]
Can't reproduce too
