### ISSUE TITLE
i18n custom translations now showing

### ISSUE THREAD

**Issue by devselegento** [scandipwa/scandipwa#2173]
**Description**:
Although I'm following [the steps](https://docs.create-scandipwa-app.com/building-your-app/internationalization) to create a new translation, when the app is built only english translations are showing. The same happens for development (even if I run ```npm start --locale en_GR```) and production build. Also, the translation json file is properly created.

**Versions**:
- ScandiPWA: 4.0.1

**Comment by lianastaskevica** [comment]
Hey @devselegento! Could you please update the version of ScandiPWA for the latest release - https://github.com/scandipwa/scandipwa/releases/tag/%40scandipwa%2Fscandipwa%404.0.2 and try to reproduce the issue once again?

**Comment by devselegento** [comment]
Hi @lianastaskevica, thank you for your answer. I have updated ScandiPWA to version 4.0.2 but still having the same issue.

**Comment by yeegor** [comment]
Please make sure every step of the instruction is ran.
I see that you use the `--locale` flag, which has been deprecated for a few months now.

**Comment by Elena-Evsa** [comment]
Closing after conversation with developer
