### ISSUE TITLE
Cannot play youtube video

### ISSUE THREAD

**Issue by devselegento** [scandipwa/scandipwa#2175]
**Description**:
When a youtube video is added from BE in product Images & Videos (Add Video) is shows properly in storefront as a thumbnail, 
but when I click to watch, it opens the full screen media gallery and then when I click to watch again, then full page media gallery closes - youtube video never plays.
Also, after the full page media gallery closes the PDP left side media gallery disappears.

**Versions**:
- ScandiPWA: 4.0.1

**Additional context**:
In mobile breakpoint the youtube video popup shows up

**Comment by lianastaskevica** [comment]
closing as a duplicate of https://github.com/scandipwa/scandipwa/issues/1855
