### ISSUE TITLE
ClickOutside does not work with Overlay

### ISSUE THREAD

**Issue by raivisdejus** [scandipwa/scandipwa#2181]
**Description**:
If `Overlay` component is placed in `ClickOutside` it does not work. 
Error is thrown that it "can't read property 'contains' of null" for this line https://github.com/scandipwa/scandipwa/blob/master/packages/scandipwa/src/component/ClickOutside/ClickOutside.component.js#L57

`Overlay` components ref.current is null in the function that checks if click was outside

**Expected behavior**:
`ClickOutside` works with `Overlay` and it is possible to create CategoryOverlayFilters that cover only half of the page  and that close clicking outside of them https://i.imgur.com/6k55rNA.png 

**To Reproduce**:
1. Implement `render` function in `CategoryFilterOverlay` component like this 
```
    return (
            <>
                <div
                  block="CategoryFilterOverlay"
                  elem="FilterBackground"
                  mods={ { isVisible: navigationState } }
                />
                <ClickOutside onClick={ onFilterOutsideClick }>
                    <Overlay
                      onVisible={ onVisible }
                      onHide={ onHide }
                      mix={ { block: 'CategoryFilterOverlay' } }
                      id={ CATEGORY_FILTER_OVERLAY_ID }
                      isRenderInPortal={ false }
                    >
                        <div
                          block="CategoryFilterOverlay"
                          elem="Content"
                        >
                            { this.renderContent() }
                            { this.renderLoader() }
                        </div>
                    </Overlay>
                </ClickOutside>
            </>
        );
```

2. Make sure overlay width is 50%
3. Click outside of the overlay

**Versions**:
- "@scandipwa/scandipwa": "4.0.0"

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2232
