### ISSUE TITLE
Group product attributes

### ISSUE THREAD

**Issue by arko-betersport** [scandipwa/scandipwa#2188]
**Description**:
Attributes are now retrieved as an array of an product so they can be displayed on the frontend. We would like to group the attributes on the frontend. For that we need to know which group an attribute belongs to.

**Additional context**:
The goal would be to group the attributes similar to the screenshot.
![image](https://user-images.githubusercontent.com/78349099/107616839-1a09d400-6c4f-11eb-83b3-668e788b0a28.png)

**Comment by joostm020** [comment]
This feature would very much be appreciated, the PR looks perfect to me. Tested and working on my side!

**Comment by joostm020** [comment]
@aleksandrakorolova This issue only added these groups to the GraphQL resolver providing the data, so you'd have to implement it on the front-end yourself as of now. However I can inform you that I'm currently working on the front-end implementation as we speak.
