### ISSUE TITLE
Product page gives 404 if using MSI 

### ISSUE THREAD

**Issue by drc0** [scandipwa/scandipwa#2193]
**Description**:
When using multiple source inventory the product page returns 404

**Expected behavior**:
Page visible

**Versions**:
- ScandiPWA: 4.0.2

**Comment by aleksandrakorolova** [comment]
Closed task because I can't reproduce

**Comment by drc0** [comment]
hi @aleksandrakorolova if you need more info I think many internal api use deprecated source inventory api and not the new one so various things breaks, please let me know the case you used to test the reproducibility of this issue.

**Comment by aleksandrakorolova** [comment]
Hi, @drc0 Please, share more info about your case.
I created new stocks and soures and checked PDP for products if product is assigned to another source and stock, assigned to one source of two/three sources in one and few stocks, assigned to different stocks and sources, assigned to one source and stock only.
