### ISSUE TITLE
404 page opens if user opened specific products (all data about this product are received in network)

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2196]
**Description**:
404 page opens if user opened specific products (all data about this product are received in network)

**Expected behavior**:
Product page opens

**To Reproduce**:
1. Open product page - https://master.d25kd40decjpue.amplifyapp.com/default/product-y.html

**Actual result**:
404 page opens but we receive all data about this product
![image](https://user-images.githubusercontent.com/73526235/108026582-4d72a700-7031-11eb-80d6-895468e04b6e.png)

**Additional context**:
For these products on the first 404 opens. Product page opens if user refreshed page:
https://master.d25kd40decjpue.amplifyapp.com/default/product-x.html
https://master.d25kd40decjpue.amplifyapp.com/default/n-cocktail-dress.html
![image](https://user-images.githubusercontent.com/73526235/108026596-52375b00-7031-11eb-87ba-658ca154732e.png)

**Comment by winniepukki** [comment]
Unable to reproduce on [master](https://master.d25kd40decjpue.amplifyapp.com/default/product-x.html) nor locally. Important note is that I have tested out with [this](https://github.com/scandipwa/urlrewrite-graphql/pull/4) improvements

For the local reproduction I have completed the following steps for [bundle, configurable, simple type of products]:
1. Forked 18.2.20 database from scandipwapmrev.indvp.com
2. Ensured the database contains products and investigated all stock properties for any type of product
3. Provided not stocked products with categories
4. Ensured not stocked products does not appear on categories
5. Ensured not stocked products return 404

**Comment by lianastaskevica** [comment]
Seems like something wrong with SKU. SKU is now "Product Y" and the product returns 404. When I checked it to "ProductY" this solved the issue and no 404 appeared.

**Comment by aleksandrakorolova** [comment]
Closed task because can't reproduce
![image](https://user-images.githubusercontent.com/73526235/119096959-e04e2380-ba1c-11eb-9541-0fd21e44880d.png)
![image](https://user-images.githubusercontent.com/73526235/119096971-e3e1aa80-ba1c-11eb-89c7-54f049e7b3cc.png)
