### ISSUE TITLE
question about how to install without docker

### ISSUE THREAD

**Issue by faisaljebali** [scandipwa/scandipwa#2200]
Hello,
How to install without using docker ?
I tried but couldn't install without using docker

- composer require scandipwa/installer
- bin/magento setup:upgrade (install installer module)

when I used this command I get error 
- php bin/magento scandipwa:theme:bootstrap Scandiweb/pwa

  There are no commands defined in the "scandipwa:theme" namespace.

  Did you mean one of these?
      dev:source-theme
      scandipwa
      scandipwa:pq

**Comment by yeegor** [comment]
Hello,

The "issues" tab is not a place for such questions. Please, use either "discussions" tab or our [community Slack](https://join.slack.com/t/scandipwa/shared_invite/enQtNzE2Mjg1Nzg3MTg5LTQwM2E2NmQ0NmQ2MzliMjVjYjQ1MTFiYWU5ODAyYTYyMGQzNWM3MDhkYzkyZGMxYTJlZWI1N2ExY2Q1MDMwMTk).

You can find the answer [here](https://docs.scandipwa.com/scandipwa-and-magento/magento-integration) though
