### ISSUE TITLE
Error appears in the console when a specific user opening cart

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2205]
**Description**:
Error appears in the console when a specific user opening cart

**Expected behavior**:
No errors

**To Reproduce**:
1. Log in new@new.new/Scandipwa123
2. Open cart

**Actual result**:
Error appears in the console
![image](https://user-images.githubusercontent.com/73526235/108183594-e7f6e700-7112-11eb-985d-86ce79ee9e09.png)

**Comment by tatiana-scandi** [comment]
@aleksandrakorolova 
Duplicate to https://github.com/scandipwa/scandipwa/issues/2197 (same reason for wishlist not loaded and error in console), please validate together.

**Comment by lianastaskevica** [comment]
@aleksandrakorolova Please recheck the issue and let us know if can be closed

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
