### ISSUE TITLE
Why "npm run build" not working in my theme magento

### ISSUE THREAD

**Issue by faisaljebali** [scandipwa/scandipwa#2206]
C:\laragon\www\magento-ce\app\design\frontend\Scandiweb\pwa>npm run build

> scandipwa-base@1.0.0 build C:\laragon\www\magento-ce\app\design\frontend\Scandiweb\pwa
> npm run build-sw && webpack --config ./src/config/webpack.production.config.js

> scandipwa-base@1.0.0 build-sw C:\laragon\www\magento-ce\app\design\frontend\Scandiweb\pwa
> webpack --config ./src/config/webpack.sw.config.js --mode=production

Hash: c05169a2029d813bbcd9
Version: webpack 4.44.1
Time: 500ms
Built at: 2021-02-18 0:27:02
 1 asset
Entrypoint main = sw-compiled.js
[0] multi ./src/sw/index.js 28 bytes {0} [built]

ERROR in multi ./src/sw/index.js
Module not found: Error: Can't resolve 'C:\laragon\www\magento-ce\app\design\frontend\Scandiweb\pwa\src\sw\index.js' in 'C:\laragon\www\magento-ce\app\design\frontend\Scandiweb\pwa'
 @ multi ./src/sw/index.js main[0]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! scandipwa-base@1.0.0 build-sw: `webpack --config ./src/config/webpack.sw.config.js --mode=production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the scandipwa-base@1.0.0 build-sw script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SP-Faisal\AppData\Roaming\npm-cache\_logs\2021-02-17T23_27_02_927Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! scandipwa-base@1.0.0 build: `npm run build-sw && webpack --config ./src/config/webpack.production.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the scandipwa-base@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SP-Faisal\AppData\Roaming\npm-cache\_logs\2021-02-17T23_27_02_974Z-debug.log

**Comment by lianastaskevica** [comment]
Hey @faisaljebali! Seems like you are using a Windows machine, however, the legacy setup you are using does not have support for it. Based on the information you have shared, unfortunately, we cannot really tell why the issue appeared for you. I would suggest considering updating to the new setup we have right now, check this guide on how to do it - https://docs.scandipwa.com/getting-started-1/depricated-docker-setup/migrating-from-the-docker-setup-legacy. If you have any questions, feel free to ask in the [community Slack channe](https://join.slack.com/t/scandipwa/shared_invite/enQtNzE2Mjg1Nzg3MTg5LTQwM2E2NmQ0NmQ2MzliMjVjYjQ1MTFiYWU5ODAyYTYyMGQzNWM3MDhkYzkyZGMxYTJlZWI1N2ExY2Q1MDMwMTk)l.
