### ISSUE TITLE
Rate and number of reviews shifted on the right on product page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2225]
**Description**:
Rate and number of reviews shifted on the right on product page

**Expected behavior**:
Rate and number of reviews are displayed on the left side (near stars)
![image](https://user-images.githubusercontent.com/73526235/109271241-ed8db480-7817-11eb-8f1a-8279b4c0ac97.png)

**To Reproduce**:
1. Open product with reviews - https://master.d25kd40decjpue.amplifyapp.com/default/n-cocktail-dress.html
2. Open review tab

**Actual result**:
Rate and number of reviews shifted on the right
![image](https://user-images.githubusercontent.com/73526235/109271217-e4044c80-7817-11eb-93e3-0168bc2c7cec.png)

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2233
