### ISSUE TITLE
While loading the page, the graphql response with error

### ISSUE THREAD

**Issue by Code0Zero** [scandipwa/scandipwa#2231]
**What is wrong? What happened?**
- While loading the page, the graphql response with error: 

Variable "$identifier0" got invalid value null; Expected non-nullable type String! not to be null. {"exception":"[object] (GraphQL\Error\Error(code: 0): Variable "$identifier0" got invalid value null; Expected non-nullable type String! not to be null. at /vendor/webonyx/graphql-php/src/Validator/Rules/QueryComplexity.php:251)"} []
main.ERROR: Variable "$menu_identifier_0" got invalid value null; Expected non-nullable type String! not to be null. {"exception":"[object] (GraphQL\Error\Error(code: 0): Variable "$menu_identifier_0" got invalid value null; Expected non-nullable type String! not to be null. at /vendor/webonyx/graphql-php/src/Validator/Rules/QueryComplexity.php:251)"} []

**Expected behavior:**
What did you expect to happen?
- It should be given the proper response so content can be load.

To Reproduce:
1. Go to 'Home Page'
2. Open Network in console
4. See error in the response

**Versions:**
- ScandiPWA: (use composer info scandipwa/source) : 3.1.0
- Any other composer module, you thing could be related:  "scandipwa/sample-data": "^1.1"
- Browser version if relevant to the context: Chrome 88.0.4324.182
- OS version if relevant to the context : linux

**Additional context:**
The newer version do not have the theme bootstrap console command.

The disk space quota is exceed,

failed: Disk quota exceeded (122) in /vendor/magento/framework/Session/SaveHandler/Native.php on line 22 {"report_id":"fa8a484dee6a65754d8d996deb829d99ed468ed288bdf35682f2f59ea7aca056","exception":"[object] (Exception(code: 0): Warning: SessionHandler::read(): open(/home/XXXX/tmp/sess_e3oienlfjvltd94li2g9h9d0jf, O_RDWR) failed: Disk quota exceeded (122) in /vendor/magento/framework/Session/SaveHandler/Native.php on line 22 at /vendor/magento/framework/App/ErrorHandler.php:61)"} []

**Comment by lianastaskevica** [comment]
Hey! We have updated the ScandiPWA installation recently. Please check it out here - https://docs.scandipwa.com/getting-started-1/getting-started. Here is the guide on how to migrate from legacy setup - https://docs.scandipwa.com/scandipwa-and-magento/migrating-from-the-docker-setup-legacy.

Disk quota - could be the issue with your server. You can try to troubleshoot this issue using google.

Regarding the menu issue you mentioned - as we can see, an empty menu identifier is sent. Could be that you misconfigured the menu manager in Magento. You can check this guide - https://manual.scandipwa.com/progressive-web-app/menu-manager
