### ISSUE TITLE
Scandipwa breaks on Safari v10.1 with the white screen

### ISSUE THREAD

**Issue by winniepukki** [scandipwa/scandipwa#2234]
**Description**:
Scandipwa breaks with the white screen on Safari v10.1

**Expected behavior**:
Scandipwa should open without errors

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/43637240/109504248-03170e80-7aa4-11eb-8dca-9795fadd92b5.png)

**To Reproduce**:
1. Open application in browser with Safari v10.1
2. See the white screen
3. Open console for more information

**Additional context**:
This problem prevents #2126 from being fixed

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce

**Comment by winniepukki** [comment]
Closing due to the ScandiPWA Safari 9-10 unmaintainable form-factor
