### ISSUE TITLE
Incorrect shipping methods when going from billing back to checkout

### ISSUE THREAD

**Issue by MagicLegend** [scandipwa/scandipwa#2245]
**Description**:
When a customer has selected a shipping method in the checkout step, continues to payment **and then goes back to checkout**, PWA will forget what state/province was selected. This makes PWA show the wrong shipping methods, and select the first one from the list.

**Expected behavior**:
PWA will remember the state/province and selected shipping methods.

**Screenshots, Video, Logs**
If applicable, add screenshots or screen-capture to help explain your problem. If you would like to share logs - please use [fenced code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).

**To Reproduce**:
1. Go to https://luma-demo.scandipwa.com
2. Add a product to the cart
3. Go to cart
4. Go to `Secure Checkout`
5. Select `Canada` as country, and a random state / province
6. Select the `Postal Shipping` rate ($30)
7. Fill in random information to complete form validation
8. Proceed to billing
9. Go back one step in browser history (in our project this is actually a button the customer can click)
10. Notice that the incorrect shipping method is selected. However, when inspecting the GraphQL calls you'll notice this:

**Request 1: Checkout > Billing** (truncated)
Notice that `region_id` is `67` here.
```json
"shipping_carrier_code": "tablerate",
"shipping_method_code": "bestway",
"shipping_address": {
    "firstname": "asdf",
    "lastname": "asdf",
    "telephone": "123456",
    "country_id": "CA",
    "region_id": "67",
    "city": "asdf",
    "postcode": "123",
    "street": ["asdf123", null, null]
},
```

**Request 2: Billing > Checkout**
Upon going to the checkout page, for some reason it requests the US shipping methods three times? (On my dev version this uses Canada three times, so I presume this is based on the configured base country / first allowed country?)
```json
"address_1": {
    "country_id": "US",
    "region_id": 1,
    "region": "",
    "city": "",
    "postcode": ""
},
```

**Request 3: Checkout > Billing**
Here it appeared to have forgotten the full address, except for the country. Notice that `region_id` is reset to the default first region again, resulting in the incorrect shipping methods.
```json
"address_1": {
    "country_id": "CA",
    "region_id": 1,
    "region": "",
    "city": "",
    "postcode": ""
},
```

**Versions**:
- ScandiPWA: Whatever the demo store uses + 4.0.1 in our project

**Comment by aleksandrakorolova** [comment]
Created separate tasks - #2953, #2954 and #2955
