### ISSUE TITLE
Error 'no such entity with customerId' appears in the console when confirming password

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2248]
**Description**:
Error 'no such entity with customerId' appears in the console when confirming password

**Expected behavior**:
No errors

**To Reproduce**:
1. Open Admin panel -> go to Stores > Settings > Configuration -> Customers -> Customer Configuration -> Create New 
2. Account Options section -> Select 'Yes' in Require Emails Confirmation field
3. Tap 'Save' -> Flush Cache Storage
4. Open website
5. Create account
6. Open the email
7. Open Confirmation link
8. Confirm password

**Actual result**:
Error 'no such entity with customerId' appears in the console
![image](https://user-images.githubusercontent.com/73526235/109927884-81a2c480-7ccd-11eb-8708-2dbefc86ede0.png)

**Comment by tatiana-scandi** [comment]
Get back to this issue after https://github.com/scandipwa/scandipwa/issues/1794 is resolved.
There is high probability they are related and Zans's fix will also help fix this one.

**Comment by tatiana-scandi** [comment]
Yes, the issue is gone. After Password confirm message "Your password is confirmed" appears and user is logged in.
@aleksandrakorolova the issue can be closed

**Comment by aleksandrakorolova** [comment]
@tatiana-scandi I see Internal server error
![image](https://user-images.githubusercontent.com/73526235/120773137-b5d68d00-c529-11eb-924f-3da136ee7bd0.png)
