### ISSUE TITLE
Shopping options filter inadequate height calculation on 'Show more' button reopening

### ISSUE THREAD

**Issue by winniepukki** [scandipwa/scandipwa#2250]
**Description**:
After products get filtered out on a certain Shopping options filter the 'Show more' button gets inadequately resized on reopening

**Expected behavior**:
The expandable contents height that gets togged by the 'Show more' button should be adequately recalculated on reopening

**Screenshots, Video, Logs**
https://drive.google.com/file/d/1oY0-4lGRLqt6L5wO2gl6U_qkJpjSRWju/view?usp=sharing

**To Reproduce**:
1. Go to the [demo store](https://40kskudemo.scandipwa.com/computers-peripherals-accessories.html) category
2. Shopping Options -> Category -> Click on 'Show more'
3. Choose 'Computers'
4. Click on 'Show more'
5. See error

**Additional context**:
This happens since the height of the Expandible content gets improperly calculated on reopening

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2279
