### ISSUE TITLE
Homepage is broken (Error message 'Error fetching config' appears)

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2255]
**Description**:
Homepage is broken

**Expected behavior**:
No errors

**To Reproduce**:
1. Open Home page

**Actual result**:
Homepage is broken 
Error message 'Error fetching config' appears
![image](https://user-images.githubusercontent.com/73526235/110107835-17b11a80-7db4-11eb-924c-137323b8daab.png)

**Comment by riha112** [comment]
***Unable to reproduce***
Issue was caused due to old ```store-graphql``` dependency, but it was already updated.

**Comment by aleksandrakorolova** [comment]
Closing because I can't reproduce
