### ISSUE TITLE
Never ending address loader in address book/dashboard/shipping step

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2257]
**Description**:
Never ending address loader in address book/dashboard/shipping step

**Expected behavior**:
Addreses are loaded

**To Reproduce**:
1. Open FE
2. Log in

**Actual result:**:
Never ending address loader
![image](https://user-images.githubusercontent.com/73526235/110108056-5e9f1000-7db4-11eb-9989-001012599e1c.png)

**Additional context**:
the same situation in address book, in shipping step

**Comment by riha112** [comment]
***Unable to reproduce***
Similarly as other issues, it may be caused due to old dependencies, that where ever since updated.

**Comment by aleksandrakorolova** [comment]
Closing because can't reproduce
