### ISSUE TITLE
Ooops page opens if user opened grouped/bundle product and one of products out of stock

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2266]
**Description**:
Ooops page opens if user opened grouped/bundle product and one of products out of stock

**Expected behavior**:
User can open this product but can't buy product which out of stock

**To Reproduce**:
1. Open - https://master.d25kd40decjpue.amplifyapp.com/default/28-grouped-product.html

**Actual result**:
Ooops page opens + errors in the console
![image](https://user-images.githubusercontent.com/73526235/110333313-21dc4e80-802a-11eb-87f6-ed11d5896b93.png)

**Additional context**:
If change settings to in stock, product page opens but errors stay in the console

**Comment by tatiana-scandi** [comment]
Empty product data is received from the server:
![image](https://user-images.githubusercontent.com/79456428/110587524-dc806400-8184-11eb-8eca-19d74b2f88fd.png)

**Comment by carinadues** [comment]
@aleksandrakorolova please test and close if it's ok
