### ISSUE TITLE
Error 'Cannot query field "currency_code" on type "BaseOrderInfo"' appears if user opened my orders in customer account

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2281]
**Description**:
Error 'Cannot query field "currency_code" on type "BaseOrderInfo"' appears if user opened my orders in customer account

**Expected behavior**:
My orders are displayed

**To Reproduce**:
1. Log in
2. Open my orders

**Actual result**:
Error Cannot query field "currency_code" on type "BaseOrderInfo". appears and never ending loader
![image](https://user-images.githubusercontent.com/73526235/110623761-fbdbb900-81a5-11eb-8091-4f2af232e486.png)
![image](https://user-images.githubusercontent.com/73526235/110623744-f8483200-81a5-11eb-829b-5c918f14fcc8.png)

**Comment by riha112** [comment]
Issue caused due to outdated quote-graphql version - waiting for new quote-graphql release to update.

**Comment by lianastaskevica** [comment]
@riha112 quote-graphql version was updated to the latest. Also, the BE of the test instance is updated. But still, the issue is there. Please point on the tasks from quote-graphql repo which fixes it, mb it was not merged.

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
