### ISSUE TITLE
SEO Suite Ultimate Extension

### ISSUE THREAD

**Issue by teodormoq** [scandipwa/scandipwa#2295]
**Description**:
Mageworx delivers the "GO-TO" SEO module for magento 2.
There is already made graphql support.

https://www.mageworx.com/magento-2-seo-extension.html

**TODO**:
Make ScandiPWA extension

**Comment by aleksandrakorolova** [comment]
Closed task because this will be an extension available in the [marketplace](https://marketplace.scandipwa.com/modules.html)
