### ISSUE TITLE
Some bundle products crash with property 'price_range' of 'item' as null

### ISSUE THREAD

**Issue by winniepukki** [scandipwa/scandipwa#2302]
**Description**:
Some bundle products crash with the 'price_range' of 'item' property as null

**Expected behavior**:
Bundle products should open as expected. The 'price_range' field should be justified with a supplementary checks to prevent null point exceptions

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/43637240/111236910-a156b880-85fc-11eb-956b-5ff9d788ea32.png)

**To Reproduce**:
1. Open [some bundle product](https://scandipwapmrev.indvp.com/default/new-test-product.html)
2. Click on 'Developer tools'

**Comment by winniepukki** [comment]
Some bundle products also alert of this
![image](https://user-images.githubusercontent.com/43637240/111272570-7cce0100-863b-11eb-9ab3-eab7bacb843f.png)

**Comment by aleksandrakorolova** [comment]
@winniepukki Can reproduce with these products https://4-2-0-rc.d25kd40decjpue.amplifyapp.com/default/test-bundle.html and https://4-2-0-rc.d25kd40decjpue.amplifyapp.com/default/bundle-product2.html
![image](https://user-images.githubusercontent.com/73526235/111958726-3fafb600-8af6-11eb-952c-da718d0ff875.png)
