### ISSUE TITLE
Issues on downloadable product page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2304]
**1. Description**:
Sample is displayed below SKU. Title is missing for sample

**Expected behavior**:
Sample title and sample with link are displayed as in luma
![image](https://user-images.githubusercontent.com/73526235/111305027-21ae0580-865f-11eb-8d30-174c1606c30b.png)

**To Reproduce**:
1. Open https://4-2-0-rc.d25kd40decjpue.amplifyapp.com/default/test-product.html

**Actual result:**:
Sample is displayed below SKU. Title is missing for sample
![image](https://user-images.githubusercontent.com/73526235/111305012-1d81e800-865f-11eb-9f82-29c87ac61067.png)

__________________________________________________
**2. Description**:
Link has sample link if it isn't set it in Admin panel

**Expected behavior**:
Link 'test2' doesn't have sample link because we didn't set it in Admin panel
![image](https://user-images.githubusercontent.com/73526235/111305492-b0bb1d80-865f-11eb-9c8b-256a69a75720.png)

**To Reproduce**:
1. Open https://4-2-0-rc.d25kd40decjpue.amplifyapp.com/default/test-product.html

**Actual result:**:
Link 'test2' has sample link. User redirects to homepage if he open this sample
![image](https://user-images.githubusercontent.com/73526235/111305482-adc02d00-865f-11eb-8436-e0cd16d3bd22.png)

__________________________________________________
**3. Description**:
Checkboxes are displayed after checkbox text 

**Expected behavior**:
Checkboxes are displayed before text
![image](https://user-images.githubusercontent.com/73526235/111305771-07c0f280-8660-11eb-8523-51466902d50f.png)
![image](https://user-images.githubusercontent.com/73526235/111305892-30e18300-8660-11eb-821b-2d5e538ba0e9.png)

**To Reproduce**:
1. Open https://4-2-0-rc.d25kd40decjpue.amplifyapp.com/default/test-product.html

**Actual result:**:
Checkboxes are displayed after checkbox text 
![image](https://user-images.githubusercontent.com/73526235/111305760-04c60200-8660-11eb-88da-73e6bb79517b.png)

__________________________________________________
**4. Description**:
Price doesn't change when selecting checkbox

**Expected behavior**:
Price changes (for example, price should be 100 if user selected test2 and etc)

**To Reproduce**:
1. Open https://4-2-0-rc.d25kd40decjpue.amplifyapp.com/default/test-product.html
2. Select test1 or/and test2

**Actual result:**:
Price doesn't change
![image](https://user-images.githubusercontent.com/73526235/111309580-bcf5a980-8664-11eb-852c-23ab193ce7c4.png)

__________________________________________________
**5. Description**:
Star that signifies mandatory checkbox is missing

**Expected behavior**:
Star is displayed near Links as in the screenshot
![image](https://user-images.githubusercontent.com/73526235/111307167-bdd90c00-8661-11eb-82c6-b650e2f2df0b.png)

**To Reproduce**:
1. Open https://4-2-0-rc.d25kd40decjpue.amplifyapp.com/default/test-product.html

**Actual result:**:
Star that signifies mandatory checkbox is missing
![image](https://user-images.githubusercontent.com/73526235/111307648-6b4c1f80-8662-11eb-9dfc-540079045c72.png)

__________________________________________________
**6. Description**:
Error message 'Cannot query field "downloadable_links" on type "TotalsItem".' is displayed when adding product to cart

**Expected behavior**:
Product is added to cart

**To Reproduce**:
1. Open https://4-2-0-rc.d25kd40decjpue.amplifyapp.com/default/test-product.html
2. Select the checkbox
3. Click on Add to cart

**Actual result:**:
Error message 'Cannot query field "downloadable_links" on type "TotalsItem".' is displayed

__________________________________________________
**7. Description**:
Product name is written in all caps lock + big indent between product name and sku

**Expected behavior**:
Make it the same as it was before
![image](https://user-images.githubusercontent.com/73526235/111308831-d77b5300-8663-11eb-9636-3bec51a90eef.png)

**To Reproduce**:
1. Open https://4-2-0-rc.d25kd40decjpue.amplifyapp.com/default/test-product.html

**Actual result:**:
Product name is written in all caps lock + big indent between product name and sku
![image](https://user-images.githubusercontent.com/73526235/111308817-d4806280-8663-11eb-9c9e-ad5760be799e.png)

**Comment by riha112** [comment]
6. issue is due to outdated qoute-graphql version
