### ISSUE TITLE
Different variants of Configurable Product from wishlist are added to the cart as one

### ISSUE THREAD

**Issue by Yulia-Malikova** [scandipwa/scandipwa#2305]
**Description**:
If you add several variants of Configurable Product to the wishlist, for example, different sizes/colors/tastes, and then click on the "add all to cart" button, then only one product will be added, which was the first in the list.

**Expected behavior**:
all products must be added

**Screenshots, Video, Logs**
https://www.loom.com/share/5f78ac470a604280996d1e433e031b56

**To Reproduce**:

1. open the site https://whey-fe-dhc-1611229426.readymage.com/
2. login/create an account 
3. open this product https://whey-fe-dhc-1611229426.readymage.com/whey-isolate.html
4. add to the wishlist 3+ type of product
5. go to the wishlist 
6. Click on the “add all to cart“

Result: adding only one product (the first product in the list is always added)

**Versions**:
- ScandiPWA: 4.1.x

**Additional context**:
Also tested here https://github.com/scandipwa/scandipwa/issues - there is a problem

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/wishlist-graphql/pull/14

**Comment by Elena-Evsa** [comment]
Still can reproduce 
https://vimeo.com/588755463/a16dfce717
