### ISSUE TITLE
Number of products in search results doesn't correspond to their `total_count`

### ISSUE THREAD

**Issue by tatiana-scandi** [scandipwa/scandipwa#2313]
**Description**:
Actual number of products is less than`total_count` and less than in Luma.

**Expected behavior**:
Actual number of products and `total_count` are equal.

**Screenshots, Video, Logs**
<img width="639" alt="ScandiPWA 2021-03-17 22-26-30" src="https://user-images.githubusercontent.com/79456428/111527246-c1a78400-8770-11eb-8ca7-217b3e5dca6a.png">

**To Reproduce**:
1. Go to 'https://scandipwapmrev.indvp.com/demo/catalogsearch/result/index/?p=2&q=bag' => 21 products are found. 21 products are displayed
2. Go to http://localhost:3000/default/search/bag => server returns "total_count" equal to 21, but items array contains only 19 items.

**Comment by tatiana-scandi** [comment]
Cannot reproduce any more.
@aleksandrakorolova please recheck and close the issue, if you can't as well

**Comment by aleksandrakorolova** [comment]
@tatiana-scandi I think you can't reproduce it because we did re-index yesterday. I noticed that sometimes we have issues with search (some products are not found as in #1947) but after re-index it works as expected. So, I will re-test this issue again after some time

**Comment by Elena-Evsa** [comment]
Qty of items corresponds: on FE, in GraphQL, on Luma
![image](https://user-images.githubusercontent.com/84388061/187456043-bf312cdd-b63a-480e-b4b6-c8d3916ecc14.png)
