### ISSUE TITLE
Checkboxes are displayed after checkbox text on product page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2324]
**Description**:
Checkboxes are displayed after checkbox text on product page

**Expected behavior**:
Checkboxes are displayed before text
![image](https://user-images.githubusercontent.com/73526235/111954858-63243200-8af1-11eb-985d-a17f0a8c3766.png)

**Screenshots, Video, Logs**
If applicable, add screenshots or screen-capture to help explain your problem. If you would like to share logs - please use [fenced code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).

**To Reproduce**:
1. Open product with checkboxes https://4-2-0-rc.d25kd40decjpue.amplifyapp.com/default/testing-simple.html or https://4-2-0-rc.d25kd40decjpue.amplifyapp.com/default/new-test-product.html

**Actual result**:
Checkboxes are displayed after checkbox text
![image](https://user-images.githubusercontent.com/73526235/111954885-6ddec700-8af1-11eb-9118-6ad6b6c3717f.png)

**Comment by carinadues** [comment]
Closing because this issue is solved in redesign https://github.com/scandipwa/scandipwa/pull/2783
