### ISSUE TITLE
Disable Guest Checkout if Cart Contains Downloadable Items / M2 Support

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2333]
**Description**:
You can require that purchasers register for a customer account and log in before purchasing a download

**Additional context**:
https://docs.magento.com/user-guide/catalog/product-download-options.html

**Comment by Elena-Evsa** [comment]
Issue 1: cart is not open if user click back on login page and page was open after click on secure checkout
Steps: 
1. Set 'Disable guest checkout' = Yes
2. Add not shareable product to cart
3. Click on Mini cart > View cart > Proceed to Checkout
4. Click back
https://vimeo.com/656060574/7ab51742a3
---
