### ISSUE TITLE
Product rate (stars) is shifted in product card on category page if user selected list view

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2340]
**Description**:
Product rate (stars) is shifted in product card on category page if user selected list view

**Expected behavior**:
Product rate (stars) is displayed as on product page
![image](https://user-images.githubusercontent.com/73526235/112114794-20318f80-8bc1-11eb-95f2-ba080244f550.png)

**To Reproduce**:
1. Open women category
2. Change view to list view

**Actual result:**:
Product rate (stars) is shifted
![image](https://user-images.githubusercontent.com/73526235/112099270-e0ac7880-8bab-11eb-9abc-7ab11b5b829d.png)

**Comment by tatiana-scandi** [comment]
@aleksandrakorolova gray vertical line in Safari has been removed

**Comment by carinadues** [comment]
@aleksandrakorolova can you please test and close the issue if it's ok?
