### ISSUE TITLE
Add to cart on Category Page

### ISSUE THREAD

**Issue by manikumaran1978** [scandipwa/scandipwa#2355]
Is that possible to have Add to cart button on the category page ?

I believe it was there in earlier version but not available in later releases.

**Comment by aleksandrakorolova** [comment]
Closed task because button Add to Cart is added on PLP. You can check it on [demo](https://40kskudemo.scandipwa.com/)
![Screenshot 2021-09-02 at 12 21 51](https://user-images.githubusercontent.com/73526235/131818759-ba1c216e-7352-4293-9235-02a1efd8ea7e.png)
