### ISSUE TITLE
Search terms are not updated when making search request

### ISSUE THREAD

**Issue by AleksandrsKondratjevs** [scandipwa/scandipwa#2363]
**Description**:
When using search to find products, search terms are not updated (recent and popular searches)

**Expected behavior**:
When using search field to search for something, search terms are updated with new request.

**To Reproduce**:
1. Try to search for some products via searchfield
2. Go to admin panel
3. See that search terms are not populated

**Versions**:
- ScandiPWA: last

**Comment by aleksandrakorolova** [comment]
@AleksandrsKondratjevs Please, investigate this issue. Sometimes search terms don't appear in Admin panel.
+ If we search the same term which was in 5 last search terms -> It doesn't update 
+ Top Search Terms updates if number of results changed from the last search

**Comment by AleksandrsKondratjevs** [comment]
@aleksandrakorolova  Hello! We have investigated described issue. This issue is related to server architecture. When we first time requesting search it proceeds with code and after getting response it is cache. In this case if we will request same search we will get it a lot faster, because code won't be executed (terms won't be populated either). In this case as a solution can be to disable cachable for this request what is not suggested, because it will lower performance of website. Anyway, it is not critical since this search will be populated on first time by this user and same expected behavior from default magento server;
