### ISSUE TITLE
Icons grid/list view don't change color

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2371]
**Description**:
Icons grid/list view don't change color

**Expected behavior**:
Icons grid/list view change color

**To Reproduce**:
1. Open Admin panel 
2. Go to stares -> configuration -> Scandipwa -> Color customization
3. Change colors
4. Save
5. Clear cache
6. Open FE

**Actual result**:
Icons grid/list view don't change color
![image](https://user-images.githubusercontent.com/73526235/112449754-6a02ad00-8d5c-11eb-98e9-56ae55ff1cb7.png)

**Additional context**:

**Comment by winniepukki** [comment]
@carinadues @aleksandrakorolova we expect a redesign to close this issue. Please notify me of the status, when it will be merged. Currently ignoring

**Comment by carinadues** [comment]
Closing because this issue is solved by the new theme redesign https://github.com/scandipwa/scandipwa/pull/2783

**Comment by winniepukki** [comment]
@carinadues @tatiana-scandi if [this](https://github.com/scandipwa/scandipwa/issues/2371) should be taken into the consideration, must simplify the job
