### ISSUE TITLE
Config option is visible if is assigned to another website

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#2375]
**Description**:
If a child of a configurable product is set to another store, default Magento still shows its options on the category filters but hides on the product page. In our current implementation, these options are visible but disabled. 

**Expected behavior**:
If a child of a configurable product is set to another store, we show its options on the category filters but hide on the product page.

**To Reproduce**:
1. Open a configurable product option in the admin
2. set one other to be available only in store A
3. Open store B on FE
4. Find the config product
5. Notice the option of product that is assigned to store A is disabled but visible

**Comment by aleksandrakorolova** [comment]
Option is hidden on PDP. Created separate task for PLP - #2913
