### ISSUE TITLE
Issues connected with file option for for customizable options

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2376]
**1. Description**:
Text is missing 

**Expected behavior**:
1. Text 'Compatible file extensions to upload:...' is displayed
2. Text 'This field is required!' is displayed if file option is required

**To Reproduce**:
1. Open https://master.d25kd40decjpue.amplifyapp.com/default/testing-simple.html

**Actual result**:
1. Text 'Compatible file extensions to upload:...' is missing
2. Text 'This field is required!' is missing if file option is required
![image](https://user-images.githubusercontent.com/73526235/112468303-c243aa00-8d70-11eb-8d86-694c7e440a2e.png)

_________________________________________
**2. Description**:
Price doesn't change if user upload file

**Expected behavior**:
Product price changes (default product price + file option price)

**To Reproduce**:
1. Open https://master.d25kd40decjpue.amplifyapp.com/default/testing-simple.html
2. Upload file

**Actual result**:
Product price doesn't change
______________________________________
**3. Description**:
Change field width

**Expected behavior**:
Field width is the same as text field/text area/dropdown

**To Reproduce**:
1. Open https://master.d25kd40decjpue.amplifyapp.com/default/testing-simple.html

**Actual result**:
Field width is not the same as text field/text area/dropdown
![image](https://user-images.githubusercontent.com/73526235/112468508-033bbe80-8d71-11eb-8bf2-e00c644a0421.png)

_______________________________________

**Additional context**:
Please, make sure the file name is displayed in the cart and mini-cart as default magento. Now I can check this because of different bug
![image](https://user-images.githubusercontent.com/73526235/112464746-89a1d180-8d6c-11eb-9a5f-01699e9887d3.png)

**Comment by aleksandrakorolova** [comment]
2. Still can reproduce
+ User can't add product to cart if he uploaded file - Close
Variable "$cartItem_1" got invalid value {"sku":"Testing Simple","product_type":"simple","quantity":1,"product_option":{"extension_attributes":{"customizable_options":[{"option_id":12,"option_value":"444"},{"option_id":1,"option_value":30},{"option_id":17,"option_value":23},{"option_id":18,"option_value":26},{"option_id":15,"option_value":"data:image\/jpeg;base64,\/9j\/4AAQSkZ....},"customizable_options_multi":[{"option_id":2,"option_value":"4"},{"option_id":2,"option_value":"16"}]}}}; Field "option_filename" is not defined by type CustomizableOptionsInput at value.product_option.extension_attributes.customizable_options[4]; did you mean option_value or option_id?

**Comment by tatiana-scandi** [comment]
2. please recheck after fix of https://github.com/scandipwa/scandipwa/issues/2239

Cart problem - will investigate and fix

**Comment by tatiana-scandi** [comment]
Adding to cart fixed on BE: https://github.com/scandipwa/quote-graphql/pull/69

**Comment by aleksandrakorolova** [comment]
Retested after #2239 fix
1.1. File extensions are missing #2523 
1.2 Ok
2. Not fixed #2519 
3. ok
Can add product to cart - Fixed
