### ISSUE TITLE
Error message appears when trying to change URL for CMS page if it is added to menu

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2377]
**Description**:
Error message appears when trying to change URL for CMS page if it is added to menu

**Expected behavior**:
No error
Changes is saved

**To Reproduce**:
1. Open Admin panel 
2. Scandipwa -> menu manager -> open menu -> Assigned Menu Items -> Add cms page -> Save
3. Open Content page -> Open this cms page -> change URL -> save 

**Actual result:**:
Error message appears 
[Page ID: 5] Could not save the page: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (magento.scandiweb_menumanager_item, CONSTRAINT FK_2058573FEB4C380B79E88A7E2C6B2FE1 FOREIGN KEY (cms_page_identifier) REFERENCES cms_page (identifier) ON DELETE SET NULL), query was: UPDATE cms_page SET title = ?, page_layout = ?, meta_keywords = ?, meta_description = ?, identifier = ?, content_heading = ?, content = ?, creation_time = ?, is_active = ?, sort_order = ?, layout_update_xml = ?, custom_theme = ?, custom_root_template = ?, custom_layout_update_xml = ?, layout_update_selected = ?, custom_theme_from = ?, custom_theme_to = ?, meta_title = ?, page_width = ? WHERE (page_id = ‘5’)

**Additional context**:
Can change URL if cms page is not added to menu

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/menu-organizer/pull/23

**Comment by carinadues** [comment]
Closing after merging PR.
