### ISSUE TITLE
All customizable options cost $0.00 id dropdown on product page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2379]
**Description**:
All customizable options cost $0.00 id dropdown on product page

**Expected behavior**:
Options cost:
green -$1.01
blue - $2.00
red - $3.00
![image](https://user-images.githubusercontent.com/73526235/112476663-cffe2d00-8d7a-11eb-813a-0c3c9de8567e.png)

**To Reproduce**:
1. Open https://master.d25kd40decjpue.amplifyapp.com/default/testing-simple.html
2. Open dropdown color

**Actual result:**:
All options cost $0.00
![image](https://user-images.githubusercontent.com/73526235/112476637-ca084c00-8d7a-11eb-828c-ce23daf291bc.png)

**Comment by tatiana-scandi** [comment]
recheck if issue still exists after https://github.com/scandipwa/scandipwa/pull/2317/ is merged

**Comment by tatiana-scandi** [comment]
Rechecked, issue not fixed yet.

**Comment by tatiana-scandi** [comment]
Recreating the same configurable option helped to get rid of the issue:
<img width="227" alt="ScandiPWA 2021-03-31 16-46-28" src="https://user-images.githubusercontent.com/79456428/113154423-aba1c500-9240-11eb-8bfe-eb9ab6dc1dbd.png">
Probably smth has not been synced to DB properly before.

**Comment by aleksandrakorolova** [comment]
Closed task because can't reproduce
![image](https://user-images.githubusercontent.com/73526235/114184410-76d2f380-994d-11eb-9a08-209f504c7574.png)
![image](https://user-images.githubusercontent.com/73526235/114184428-7b97a780-994d-11eb-9559-6b24c788151c.png)
