### ISSUE TITLE
Adyen PaymentMethods

### ISSUE THREAD

**Issue by teodormoq** [scandipwa/scandipwa#2385]
**Description**:
There should be supported a lot more payment methods for adyen.
Today we only support credit card and ideal, there needs to be supported more.

**Additional context**:
Examples on adyen payment methods there can be supported:
* Klarna
* Klarna Account
* Paypal
* Ratepay
* Ratepay Directdebit
* Direct Ebanking
.... and a lot more

**Comment by aleksandrakorolova** [comment]
Closed task because this will be an extension available in the [marketplace](https://marketplace.scandipwa.com/modules.html)
