### ISSUE TITLE
Bad quality images in image zoom

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#2428]
**Description**:
In the image zoom, we have bad quality images. The issue appears due to the image optimization on PDP. The images are compressed to the size of the main image on PDP, so when you open the image zoom, these small images are stretched out to the size of your screen.

**TODO**:

Create a new image type in the view.xml file, by default add there width: 1200px for it. Render the main image in zoom with these dimensions

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2438 + https://github.com/scandipwa/catalog-graphql/pull/95/files
