### ISSUE TITLE
Can't add products to the wishlist

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2446]
**Description**:
Can't add products to the wishlist

**Expected behavior**:
Products are added to the wishlist 

**To Reproduce**:
1. Log in 
2. Open grouped product
3. Add to wishlist
4. Open bundle product
5. Add to wishlist
6. repeat these steps with other product types

**Actual result:**:
Error message 'Error updating wish list!' appears 
For bundle and config products:
![image](https://user-images.githubusercontent.com/73526235/113691425-10dc3700-96d5-11eb-915c-dc8236bd6413.png)

For grouped product:
![image](https://user-images.githubusercontent.com/73526235/113691437-146fbe00-96d5-11eb-8d0a-5bb28742918c.png)

For virtual, simple and downloadable products:
Nothing happens

**Comment by riha112** [comment]
PR: 
* https://github.com/scandipwa/wishlist-graphql/pull/17
* https://github.com/scandipwa/quote-graphql/pull/68
