### ISSUE TITLE
Incorrect price filters behavior if product price if on overlap of price intervals

### ISSUE THREAD

**Issue by tatiana-scandi** [scandipwa/scandipwa#2450]
**Description**:
E.g. we have price intervals $20-$40, $40-$60, $60-$80.
Product has price of $60.
<img width="696" alt="ScandiPWA+2021-04-06+16-51-49" src="https://user-images.githubusercontent.com/79456428/113768346-6beb4980-9728-11eb-9ddf-0cce8d5ccf07.png">
Filters show count of 4.
Real number of matching products is 5.
One product gets to 2 intervals.

**Expected behavior**:
1. Intervals don't overlap. We have intervals 20-39.99, 40-59.99, 60-79.99.
2. Actual number of products matches number of products in filter.

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/catalog-graphql/pull/99

**Comment by carinadues** [comment]
Closed after merging scandipwa/catalog-graphql#99
