### ISSUE TITLE
Manually set filter intervals have ranges not including all products

### ISSUE THREAD

**Issue by tatiana-scandi** [scandipwa/scandipwa#2451]
**Description**:
1. Set intervals like this:
![image](https://user-images.githubusercontent.com/79456428/113769581-cd5fe800-9729-11eb-9479-92d07b2c1868.png)
2. Find a category with min and max product prices differing by more than 100 EUR (e.g. https://scandipwapmrev.indvp.com/default/accessories-1.html?sortKey=price&sortDirection=DESC) 

**Actual result**:
Price ranges in filter are 20-40, 40-60, 60-80, 80-100. We have bag that costs 1350 EUR and it is not included in any of the ranges.
<img width="640" alt="Accessories | Scandipwa 2021-04-06 22-43-07" src="https://user-images.githubusercontent.com/79456428/113770090-67279500-972a-11eb-8498-15f3fb9ed75b.png">

**Expected behavior**:
Based on Luma behavior: last range is "80 and above" and includes all the products that were not included in the first 3.

**Comment by carinadues** [comment]
Closed after merging scandipwa/catalog-graphql#99
