### ISSUE TITLE
Review tab is displayed on product page if reviews are disabled

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2454]
**Description**:
Review tab is displayed if reviews are disabled

**Expected behavior**:
Review tab is missing because we disabled reviews in Admin panel

**To Reproduce**:
Admin panel:
1. Open Admin panel -> go to Stores > Settings > Configuration
2. In the left panel, expand Catalog and select Catalog
3. Select 'No' in the Enabled field (product reviews section)
4. Save
5. Flush Cache Storage

FE:
6. Open product page

**Actual result**:
Review tab is displayed

**Comment by MaritaKochua** [comment]
Closing and reopening a PR due to an error when creating the branch.
