### ISSUE TITLE
Ooops page opens if user opened wrong url in my account (/my-account/{wrongUrl})

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2457]
**Description**:
Ooops page opens if user opened wrong URL in my account (/my-account/{wrongUrl})

**Expected behavior**:
Not found page opens

**To Reproduce**:
1. Log in
2. Change URL after /my-account/ -  https://master.d25kd40decjpue.amplifyapp.com/default/my-account/fgdfg

**Actual result**:
Ooops page opens
![image](https://user-images.githubusercontent.com/73526235/113836399-86a7d780-9795-11eb-80af-7e7ad2b844da.png)

**Comment by carinadues** [comment]
The issue was closed because it couldn't be reproduced.
