### ISSUE TITLE
Wrong subcategories are displayed in Layered navigation if the product belongs to few categories

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2461]
**Description**:
Wrong subcategories are displayed in Layered navigation if the product belongs to few categories

**Expected behavior**:
Only Kids subcategory are displayed as in default Magento
![image](https://user-images.githubusercontent.com/73526235/113976222-70f3ea00-9849-11eb-92aa-13894bfa420c.png)

**To Reproduce**:
1. Open category - kids (product 'virtual hat' is displayed in kids and accessories category)
2. Click show more for category filters 

**Actual result:**:
Accessories, tech, bags categories and etc which NOT kids subcategory are displayed
![image](https://user-images.githubusercontent.com/73526235/113864553-b1a12400-97b3-11eb-9337-0b7206b5e8bc.png)

**Comment by jithutj** [comment]
Please fix this issue ASAP

**Comment by jithutj** [comment]
#2551 fix tested and working
