### ISSUE TITLE
Dynamic prices are displayed for bundle items on FE if bundle product with fixed price is created

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2462]
**Description**:
Dynamic prices are displayed for bundle items on FE if bundle product with fixed price is created

**Expected behavior**:
Fixed prices are displayed (in this case 20$ and 30%)

**To Reproduce**:
1. Create bundle product with fixed price
2. Open this product on FE

**Actual result:**:
Dymamic prices are displayed 
![image](https://user-images.githubusercontent.com/73526235/113976264-8b2dc800-9849-11eb-8070-61cbbe294113.png)

**Additional context**:
Product URL: https://master.d25kd40decjpue.amplifyapp.com/default/8bunfixed.html

**Comment by lianastaskevica** [comment]
closing as duplicate of https://github.com/scandipwa/scandipwa/issues/2479

**Comment by aleksandrakorolova** [comment]
It's not duplicate

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
![Screenshot 2021-07-06 at 15 51 32](https://user-images.githubusercontent.com/73526235/124602933-1121d500-de72-11eb-8e35-979b334d1129.png)
