### ISSUE TITLE
'Image not specified' is displayed for one of groped product which doesn't have image

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2466]
**Description**:
'Image not specified' is displayed for one of groped product which doesn't have image

**Expected behavior**:
Show default image
![image](https://user-images.githubusercontent.com/73526235/114005055-de167800-9867-11eb-877a-c6484c574071.png)

**To Reproduce**:
1. Create grouped product where one of product doesn't have image 
2. Open this product on FE

**Actual result:**:
Image not specified is displayed
![image](https://user-images.githubusercontent.com/73526235/114005088-e66eb300-9867-11eb-8277-cfe73bbda451.png)

**Additional context**:
https://master.d25kd40decjpue.amplifyapp.com/default/8gr.html

**Comment by carinadues** [comment]
Same for this product:
![image](https://user-images.githubusercontent.com/82165392/132231630-4ad481ef-05e8-4140-9270-fc621c77b31e.png)

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce 
![Screenshot 2021-11-30 at 13 16 35](https://user-images.githubusercontent.com/73526235/144037883-37dde878-19b1-475a-b1f0-5ae21e7077c6.png)
