### ISSUE TITLE
Search page result inaccurate

### ISSUE THREAD

**Issue by kyeng-vis** [scandipwa/scandipwa#2468]
**Description**:
The search page result is inaccurate.
Search for 'huawei y9', related products only starting at 5th page

**Expected behavior**:
Show most relevant products first follow by less relevant products, just like search bar.

**To Reproduce**:
1. Go to https://tech-demo.scandipwa.com/
2. Click on search
3. Type 'huawei y9', hit enter
4. See the result is different from the search bar

**Comment by carinadues** [comment]
Also happens in master

**Comment by Elena-Evsa** [comment]
Now search result sort as 'none' to mach same results as in search bar.
Please, override current sort option "Best match" with the functionality of "None" but only for search result page
