### ISSUE TITLE
Mobile: Add product status on product page 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2469]
**Description**:
Add product status (In Stock/Out of stock) on product page

**Comment by winniepukki** [comment]
@aleksandrakorolova Should the issue be closed? 😇
![image](https://user-images.githubusercontent.com/43637240/116617824-f2213700-a946-11eb-99a3-cbd1fc979d10.png)

**Comment by aleksandrakorolova** [comment]
@winniepukki No, product status is missing on mobile. We need to show it

**Comment by winniepukki** [comment]
@aleksandrakorolova @lianastaskevica Should look as follows:
![screen](https://user-images.githubusercontent.com/43637240/116706545-69ea7280-a9d6-11eb-8b25-92dbcbc15226.png)
