### ISSUE TITLE
Error: Unknown locale! for all stores except default store 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2472]
**Description**:
Error: Unknown locale! for all stores except default store 

**Expected behavior**:
All stores work correctly

**To Reproduce**:
I think it caused because locale setting was changed to Brasil in Admin panel
I changed back to English (US) locale -> Still, stores don't work

**Actual result**:
Blank page opens + Error: Unknown locale! in console 
![image](https://user-images.githubusercontent.com/73526235/114136383-440c0980-9913-11eb-917b-10fe43085332.png)

**Comment by aleksandrakorolova** [comment]
Can't reproduce

**Comment by Garde85** [comment]
I have the same problem in a fresh installation. Anyone else has got this problems?
