### ISSUE TITLE
Add price excl. tax for bundle product with fixed price option

### ISSUE THREAD

**Issue by tatiana-scandi** [scandipwa/scandipwa#2479]
**Description**:
- Need to add new field to GQL schema + calculate price excl. tax
- Add logic to use price excl. tax on FE

Even though we don't show price excl. tax for bundle options now, when options are added, data on option prices excl. tax is required to recalculate total price of the selected options.

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2482 + https://github.com/scandipwa/catalog-graphql/pull/97/

To QA: Please test all prices on PDP for bundle and downloadable products. Including price rules, special discounts, tax rules configured, bundle options of type fixed and percent and customizable amount of selectable option. Actually I have checked all the cases mentioned on my local setup, so even if there are issues, there won't be many.

This PRs should also fix https://github.com/scandipwa/scandipwa/issues/2462, please check together.

**Comment by tatiana-scandi** [comment]
Closing this PR, because more actual one was created: #2602

**Comment by aleksandrakorolova** [comment]
Need to test after #2683 fix

**Comment by aleksandrakorolova** [comment]
Need to test after #2761 fix

**Comment by Elena-Evsa** [comment]
Need to test after #3449
