### ISSUE TITLE
Links are hardcoded for social icons in the footer

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2480]
**Description**:
Links are hardcoded for social icons in the footer

**Expected behavior**:
User can change links for social icons via Admin panel

**To Reproduce**:
1. Open Admin panel -> Content -> Blocks -> Open Footer block 

**Actual result:**:
Can't change links for social icons

**Comment by AleksandrsKondratjevs** [comment]
Can't reproduce.
Open settings -> Scandipwa -> content customizations -> select block for footer -> clean cache
Be sure that footer is set to all store views.
Go to footer block and remove src for img, In this case it won't display image on FE. So it can be changed as user wants.

**Comment by aleksandrakorolova** [comment]
Not images but links for icons

**Comment by AleksandrsKondratjevs** [comment]
https://github.com/scandipwa/sample-data/pull/9
