### ISSUE TITLE
Wrong product price is displayed for specific product

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2487]
**Description**:
Wrong product price is displayed for a specific product

**Expected behavior**:
Product price is 23 EUR 
![image](https://user-images.githubusercontent.com/73526235/114507197-73848400-9c3b-11eb-99a3-bac58a4a2668.png)

**To Reproduce**:
1. Open product - https://scandipwapmrev.indvp.com/default/virtual-product.html

**Actual result**:
Product price is 21 EUR
![image](https://user-images.githubusercontent.com/73526235/114507181-6ff0fd00-9c3b-11eb-8624-10f03cac323f.png)

**Comment by AleksandrsKondratjevs** [comment]
This is not an issue. Just for this specific store view price is set to be 21$
![price](https://user-images.githubusercontent.com/68007919/114659873-046f6400-9cfd-11eb-81fc-ba15ea481097.png)

**Comment by aleksandrakorolova** [comment]
Closed task because can't reproduce
