### ISSUE TITLE
Windows: Chrome: Price cuts on grouped product page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2493]
**Description**:
Price cuts on grouped product page

**Expected behavior**:
Price is displayed as in screenshot
![image](https://user-images.githubusercontent.com/73526235/114709807-b034a600-9d35-11eb-973a-bc0bd98d392f.png)

**To Reproduce**:
1. Grouped product page

**Actual result**:
Price is cuts
![image](https://user-images.githubusercontent.com/73526235/114709622-7e234400-9d35-11eb-94c7-37fb7fb74fae.png)

**Additional context**:
Windows: Chrome: v89

**Comment by carinadues** [comment]
@aleksandrakorolova can you please check if this is still happening?

**Comment by aleksandrakorolova** [comment]
@carinadues I can reproduce it if product has discount
![Screenshot 2021-07-22 at 14 43 38](https://user-images.githubusercontent.com/73526235/126634616-d409f638-4cd4-4d89-8557-04847b46efd8.png)
