### ISSUE TITLE
Checkout - Guest user has to re-enter e-mail

### ISSUE THREAD

**Issue by KrissOerts** [scandipwa/scandipwa#2496]
**Description**:
When the Guest user wants to make more than 1 purchase and all the “Shipping” forms have been filled in the previous purchase the E-mail form is reset.

**Expected behavior**:
The E-mail form behaves like the other forms on the “Shipping” step and the user does not have to re-enter it to make a purchase again.

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/77437826/114785528-80ad8a00-9d85-11eb-86c0-cdfcb369efc3.png)

**To Reproduce**:
1. Open https://tech-demo.scandipwa.com/
2. Make sure you are Logged OUT of the FE user account.
3. Place a order for any product on the site.
4. Place another order and observe the “Shipping step” E-mail form.

**Additional context**:
Found on the Whey-Protein Project.
https://scandiflow.atlassian.net/browse/WHEY-788

**Comment by glebsvrevskis** [comment]
@lianastaskevica fix can be taken from here:
https://github.com/scandipwacloud/readymage-whey-fe-dhc-1611229426/pull/1249
https://github.com/scandipwacloud/readymage-whey-fe-dhc-1611229426/pull/1219

**Comment by Elena-Evsa** [comment]
Closed because of new logic exist on master and created task #3697
