### ISSUE TITLE
Some cross-sell products disappear after a few seconds

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#2508]
**Description**:
Some cross-sell products disappear from the shopping cart page after a few seconds.

**Expected behavior**:
Cross-sell products are suggested under the "Frequently bought together" section in the shopping cart for determined products added to the cart.

**To Reproduce**:
1. Open Admin panel -> Go to Catalog -> Products
2. Open the desired product X -> Scroll to Related Products, Up-Sells, and Cross-Sells section -> Tap 'Add Cross-sell products'.
2. Add some Cross-sell products A and B -> Tap 'Save'
4. Open website -> Open product X page -> Add this product to cart -> Open checkout page -> Scroll down

**Actual results**:
Some cross-sell products disappear from the shopping cart page after a few seconds.

https://user-images.githubusercontent.com/82165392/115031113-31a74800-9e9e-11eb-822d-fd89c88c722b.mp4

**Additional context**:
Test with these products:

- https://master.d25kd40decjpue.amplifyapp.com/default/8conf.html?color=72&colors_with_images=5521&shoes_size=82&size=79
- https://master.d25kd40decjpue.amplifyapp.com/default/havaianas-blue.html

**Comment by linq2js** [comment]
I cannot duplicate the bug with the local theme and Magento app. After I attach the remote Magento app to the local theme, the bug occurs. I think there is something wrong with server configs rather than our codebase

**Comment by maddumarala** [comment]
This issues even happens in Scandi demo.

-Add this product to cart and go to cart page ,You'll see cross sell products.
 https://tech-demo.scandipwa.com/product-132614.html
-Refresh the page , cross sell products are missing
