### ISSUE TITLE
Ability to proxy all media requests to production server

### ISSUE THREAD

**Issue by raivisdejus** [scandipwa/scandipwa#2521]
**Context**
During development and support of clients website some time there are issues with content on their live or staging site. Some development workflows rely on importing live or staging database into local to get most up to date copy of the environment with some issue. Most of the time media is missing and to get it additional step to copy large amount of images may be needed. 
An unnecessary extra step...

It would be nice if some startup key or config parameter was available to proxy all media requests to some external server.

**Possible solution**
To illustrate server rewrite that would solve this see the following Apache .htaccess file example
```
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{HTTP_HOST}%{REQUEST_URI} ^my-dev-site\.local\/media\/(.*)$
RewriteRule ^/?(.*)$ https://www.my-prod-site.com/$1 [QSA,L]
```

**Comment by zans-laksa** [comment]
I guess this is more related to CMA, since SPWA is just a frontend theme and it doesn't have access to the web server configuration.
@ejnshtein maybe this can be implemented as a CMA feature?

**Comment by ejnshtein** [comment]
I think this can be done through an Nginx configuration file.

CMA allows you to use your own configuration file. Just add the `configTemplate` property to the Nginx configuration in a config file.

**Comment by carinadues** [comment]
Hey! So, should we close this issue?

**Comment by raivisdejus** [comment]
@carinadues Yes, there seems to be a solution with the existing code. Well done, good future-proofing and flexibility
