### ISSUE TITLE
1146 Table 'abcd_mage682.scandiweb_slider_slide' doesn't exist, query was: DESCRIBE `scandiweb_slider_slide`

### ISSUE THREAD

**Issue by AngeloZou** [scandipwa/scandipwa#2525]
**Description**:
I am using magento 2.4.2, install scandipwa, when I execute bin/magento setup: upgrade, the following error occurs.
Upgrading schema... SQLSTATE[42S02]: Base table or view not found: 1146 Table 'abcd_mage682.scandiweb_slider_slide' doesn't exist, query was: DESCRIBE `scandiweb_slider_slide`

Now the frontpage and admin url cannot be opened.
There has been an error processing your request
Exception printing is disabled by default for security reasons.

**SQL Table**:
There are the following three tables.
Table: mg_scandiweb_slider_slide
Table: mg_scandiweb_slider_slide_map
Table: mg_scandiweb_slider_slide_store

**Expected [behavior**:
How to fix this problem.

**Screenshots, Video, Logs**:
https://prntscr.com/11v41xs
https://prntscr.com/11v43n9
https://prnt.sc/11v6b4t
https://prnt.sc/11v6fk0
https://prnt.sc/11v6kkx

**Versions**:
- ScandiPWA: 0.0.1
- OS: CentOS Linux 7 (Core)
- Kernel: 3.10.0-1160.21.1.el7

**Comment by Elena-Evsa** [comment]
Closing after conversation with developer
