### ISSUE TITLE
Attributes are selectable if child products out of stock 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2531]
**Description**:
Attributes are selectable if child products out of stock 

**Expected behavior**:
Attributes are disabled for child out of stock products as default Magenta
![image](https://user-images.githubusercontent.com/73526235/115722737-f3bb8f80-a387-11eb-981c-062e779fb136.png)
http://scandipwapmrev.indvp.com/demo/n-comma-casual-identity-quilted-jacket.html

**To Reproduce**:
1. Open config product where some child products out of stock -https://master.d25kd40decjpue.amplifyapp.com/default/n-comma-casual-identity-quilted-jacket.html
2. Select red and extra small

**Actual result**:
Attributes are selectable 
![image](https://user-images.githubusercontent.com/73526235/115722275-83ad0980-a387-11eb-83f1-af69740bab4c.png)

**Additional context**:
User can select color - white and extra small size

**Comment by tatiana-scandi** [comment]
Didn't manage to reproduce the issue, after Magento upgrade.
But suggest to observe "out of stock" behavior for ~ 1 month, to see if the issue is really gone, or it is just quite rare and hard to reproduce.

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
