### ISSUE TITLE
Documentation repository

### ISSUE THREAD

**Issue by jbruni** [scandipwa/scandipwa#2536]
I want to send pull requests for typo fixes in the documentation.

For example, we can read "**Developement environemnt preparation**", at:

- https://docs.scandipwa.com/getting-started/where-to-start#4-developement-environemnt-preparation

It should be "**Development environment preparation**".

I have found two docs repository here at GitHub, but both are archived.

Where is the currently active documentation repository?

Thank you.

**Comment by carinadues** [comment]
Hello, @jbruni!

Thank you for reporting the issue. We currently manage the documentation with GitBook, so the access is private. 

Feel free to contact me [via Slack](https://scandipwa.slack.com/join/shared_invite/enQtNzE2Mjg1Nzg3MTg5LTQwM2E2NmQ0NmQ2MzliMjVjYjQ1MTFiYWU5ODAyYTYyMGQzNWM3MDhkYzkyZGMxYTJlZWI1N2ExY2Q1MDMwMTk#/) if you ever find anything else and I'll do the corrections :)
