### ISSUE TITLE
Product price is shifted to the right in mini-cart if file with long name is added as extra item for product with customization option

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2539]
**Description**:
Product price is shifted to the right in mini-cart if file with long name is added as extra item for product with customization option

**Expected behavior**:
Product price isn't shifted
![image](https://user-images.githubusercontent.com/73526235/115827483-fd3f0900-a414-11eb-81d3-0b5630a0fbd6.png)

**To Reproduce**:
1. Open Simple product with customization option - file
2. Add file with long name
3. Add to cart
4. Open mini-cart

**Actual result**:
Product price is shifted to the right
![image](https://user-images.githubusercontent.com/73526235/115827846-8a825d80-a415-11eb-881f-e71e6d5f73c5.png)

**Additional context**:
https://master.d25kd40decjpue.amplifyapp.com/default/testing-simple.html
https://master.d25kd40decjpue.amplifyapp.com/default/havaianas-green.html

Mobile:
User can't see all name of file. Please, division of a word if it's possible
![Screenshot_20210423-102616_Chrome](https://user-images.githubusercontent.com/73526235/115835020-81e25500-a41e-11eb-82cb-2a82ad18e837.jpg)

**Comment by carinadues** [comment]
This issue is fixed in the new redesign.

**Comment by aleksandrakorolova** [comment]
Can't reproduce 
![Screenshot 2021-07-21 at 13 51 29](https://user-images.githubusercontent.com/73526235/126477473-e0038fcd-0777-4de5-aae2-d37005df73e8.png)
