### ISSUE TITLE
Images in CMS pages won't align in the center and there's too much space before and after the image

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#2547]
**Description**:
The images in the CMS pages can't be aligned in the center of the page and there's too much space before and after the image.

**Expected behavior**:
The images should be centered in the page if the user configures this option in the BE and there shouldn't be so much extra space between the texts and the images, as it is in the admin:

![image](https://user-images.githubusercontent.com/82165392/116124659-f45f6900-a69a-11eb-90eb-727262a14df0.png)

**To Reproduce**:
1. Open admin -> Content -> Pages
2. Open a CMS page in Edit mode.
3. Insert an image in the Content box.
4. Mark the image and click on "Align center" in the tool box above.
4. Save and clear cache.
5. Open the page on FE.

**Actual results**:
The images in the CMS pages can't be aligned in the center of the page and there's too much space before and after the image.

![image](https://user-images.githubusercontent.com/82165392/116124990-5c15b400-a69b-11eb-85e0-c34e249210a5.png)

On a cellphone, the margins are also too thick and the image is cut. If the user slides to the right, he/she can't see the rest of the image:

![image](https://user-images.githubusercontent.com/82165392/116740861-f5aad180-a9cb-11eb-818f-7cda5c9665aa.png)

**Comment by Elena-Evsa** [comment]
Still can reproduce

![image](https://user-images.githubusercontent.com/84388061/129912027-9aaf5118-8be7-4a73-84e3-e10b429304ab.png)
![image](https://user-images.githubusercontent.com/84388061/129911944-11da38cf-080a-4d16-b48b-d39a8ea698ab.png)

**Comment by tatiana-scandi** [comment]
Appeared due to https://github.com/scandipwa/scandipwa/pull/3084 (incorrect merge conflict resolution, I suppose) => the new prop I added to solve the issue was lost. Will add it back and it will work as expected.
