### ISSUE TITLE
Title isn't cropped when going back to the previous page via swipe in the first time

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2563]
**Description**:
The previous page is shifted up when user went back to previous page via swipe in the first time

**Expected behavior**:
Title isn't cropped
![image](https://user-images.githubusercontent.com/73526235/116505203-fa379300-a8c2-11eb-90c5-d5896c167abe.png)

**To Reproduce**:
1. Open menu on mobile
2. Open women category -> dresses category -> summer dresses category -> Open product
3. Go back via a swipe
4. Go back via swipe

**Actual result**:
The previous page is shifted up when user went back via swipe in the first time
https://drive.google.com/file/d/1QaoMmqLZqgefD_5z3-hxGpCVQ18U6gmf/view?usp=sharing
![image](https://user-images.githubusercontent.com/73526235/116505077-aa58cc00-a8c2-11eb-918d-0b1ea90e04d4.png)
It looks good in next times

**Comment by zans-laksa** [comment]
Can reproduce this on pmrev only. Most likely this will go after update.
