### ISSUE TITLE
Rating isn't identified as mandatory though it is required for submitting the review

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#2574]
**Description**:
The product rating isn't identified as mandatory for the user, but it is required for submitting the review. This means that the user can't just write a comment, he/she has to rate the product giving it 1-5 stars.

**Expected behavior**:
The user should have a visual indication that the rating is mandatory. The text "This field is required!" should be displayed below each row of stars when the user tries to send a review without rating the product. 

This is how it looks in Luma:

![image](https://user-images.githubusercontent.com/82165392/116699161-a2208f80-a99b-11eb-94fe-c1d291e5bc5f.png)

**To Reproduce**:
1. Open a product description page.
2. Scroll down until Reviews.
3. Click on 'Write a new review'.

**Actual results**:
When the user clicks on Submit Review, he/she isn't notified that the rating is also mandatory.

![image](https://user-images.githubusercontent.com/82165392/116699289-c7ad9900-a99b-11eb-9c30-c6b310645bcd.png)

**Comment by aleksandrakorolova** [comment]
1. Different margin above and below error message 

**Actual result:**
Margin between star and error message is 12px 
Margin between error message and next rate is missing

**Expected result:**
Do the same margins as between field and error message
![Screenshot 2022-02-10 at 13 16 57](https://user-images.githubusercontent.com/73526235/153398146-203c0b02-63e5-4fe2-b381-2f0f8438d03f.png)

2. Delete red/green line for stars
![Screenshot 2022-02-10 at 13 31 02](https://user-images.githubusercontent.com/73526235/153403336-38d6c3b4-8bd3-48a8-b215-8f2b3efa01aa.png)
