### ISSUE TITLE
Better RTL styles

### ISSUE THREAD

**Issue by yeegor** [scandipwa/scandipwa#2580]
**Description**:
Currently used CSS directives `margin-top`, `margin-bottom`, `margin-left`, `margin-right` are not a good option for RTL webpages. `margin-left` will stay left even if inline flow is inverted (as in RTL).

**Additional context**:
Better options to use:

- `margin-inline-start` instead of `margin-left`
- `margin-inline-end` instead of `margin-right`
- `margin-block-start` instead of `margin-top`
- `margin-block-end` instead of `margin-bottom`

These options are dependent on `writing-mode`, `direction`, and `text-orientation` and hence will work better when e.g. `direction` is set to `rtl`. Whereas in `ltr` they coincide with their current replacements (from above)

**Comment by zans-laksa** [comment]
This is implemented in v5 with the redesign.
