### ISSUE TITLE
Scandipwa is not Installing on Existing Magento 2 Sever 2.3.4

### ISSUE THREAD

**Issue by prakash-subbaiah-codilar** [scandipwa/scandipwa#2585]
**Description**:
Scandipwa is not Installing on Existing Magento 2 Sever 2.3.4

**Expected behavior**:
I have the existing Magento 2 project version 2.3.4 in my local system. I tried to install the scandipwa on that.

I follow this scandipwa documentation.
https://docs.scandipwa.com/getting-started/getting-started/magento-integration

After I executed the below command getting error.
**composer require scandipwa/my-project-name**
Provide the guidance on installing scandipwa on magento 2.3.4

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/65328914/116998095-56ebe100-acfb-11eb-8515-76a2d94810c5.png)

**To Reproduce**:
Provide the guidance on installing scandipwa on magento 2.3.4

**Versions**:
- Magento 2 V-2.3.4

**Comment by carinadues** [comment]
Please see compatibility mapping: https://manual.scandipwa.com/pwa/magento-version-mapping
