### ISSUE TITLE
The Cookie Popup Text isn't aligned and the 'Read more' is separated by a line break

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#2587]
**Description**:
The Cookie Popup 'Read more' is separated by a line break. The Cookie Popup Text is displayed in the upper left corner of the box. It would look better if aligned to be vertically centralized.

**Expected behavior**:
The text is vertically centralized and there is no line break in between 'Read more'.

**To Reproduce**:
1. Open the website. Clear cache if necessary.
2. The popup is displayed at the bottom of the page.

**Actual results**:

![image](https://user-images.githubusercontent.com/82165392/117184002-9cb5b180-adae-11eb-8733-8bfc6f551e1a.png)

**Additional context**:
The same happens in Demo websites and in multiple browsers.

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce after redesign
![Screenshot 2021-09-02 at 11 51 53](https://user-images.githubusercontent.com/73526235/131813974-a5067708-6ee0-418c-9912-5f81cacf7b1b.png)
