### ISSUE TITLE
The file name is displayed outside the field

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2590]
**Description**:
The file name is displayed outside the field

**Expected behavior**:
File name is displayed in filed. Write name in two lines

**To Reproduce**:
1. Open simple product with customization - file type 
2. Upload file with long name

**Actual result:**:
The file name is displayed outside the field
![image](https://user-images.githubusercontent.com/73526235/117245205-1c8d5b80-ae43-11eb-9077-79c014e78d2c.png)

**Additional context**:
https://master.d25kd40decjpue.amplifyapp.com/havaianas-green.html

**Comment by NavaneethVijay** [comment]
@aleksandrakorolova Not able to see this issue with long uploaded file.
![image](https://user-images.githubusercontent.com/33292252/118259916-5b6c8280-b4cf-11eb-81e3-61b95feb575d.png)

Adding padding for the label tag looks better.

**Comment by carinadues** [comment]
The issue doesn't happen if the file name has "-", but if it's all letters and numbers, I can reproduce it:

![image](https://user-images.githubusercontent.com/82165392/118530299-e097a780-b71a-11eb-8563-3d0562f44530.png)

**Comment by aleksandrakorolova** [comment]
@NavaneethVijay I don't know how many lines we can display that it should look well and it shouldn't display outside the field
Maybe better do the same how it works by default Magento. Name of file is cut with '...' in the middle of name
![image](https://user-images.githubusercontent.com/73526235/119085391-58f8b400-ba0c-11eb-917f-5a9d3171d810.png)

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
![Screenshot 2022-02-28 at 14 12 26](https://user-images.githubusercontent.com/73526235/155981558-ed604220-1538-4ce2-b342-645c287c5560.png)
