### ISSUE TITLE
Permissions issue accessing cooldown.json

### ISSUE THREAD

**Issue by rMazeiks** [scandipwa/scandipwa#2593]
**Description**:
This bug cannot be reproduced if Node is installed specifically for the user, e.g. with `nvm`. However, if `root` owns the Node installation then:

Running
```
scandipwa override component Footer
```
Produces the following error:
```
UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/usr/lib/node_modules/scandipwa-cli/node_modules/@scandipwa/scandipwa-dev-utils/cooldown.json'
```

**Expected behavior**:
No errors; command works as expected.

**To Reproduce**:
1. Ensure the node installation belongs to `root`
2. Run `scandipwa override component Footer`, or any other command

**Versions**:
Latest Scandi CLI version

I have not run into this personally, this is merely a formalization of a bug reported by a couple of people. E.g [this slack message](https://scandipwa.slack.com/archives/CD8ETGY3Y/p1620272933451900)

**Comment by Elena-Evsa** [comment]
Closing after conversation with developer
