### ISSUE TITLE
Braintree Extension not working.

### ISSUE THREAD

**Issue by shivampmc** [scandipwa/scandipwa#2596]
**Description**:
What is wrong? What happened?
I have installed the Braintree extension, but I am facing issues with it.

**Expected behavior**:
What did you expect to happen?
Should not break any functionality and let the customers purchase using Braintree/PayPal.

**Screenshots, Video, Logs**
If applicable, add screenshots or screen-capture to help explain your problem. If you would like to share logs - please use [fenced code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).
When installed only Braintree GraphQL
![image](https://user-images.githubusercontent.com/77787433/117536600-88c1b800-b019-11eb-9a34-16628420e3f3.png)
When using both Braintree GraphQL and Vault-GraphQL
![image](https://user-images.githubusercontent.com/77787433/117536615-a7c04a00-b019-11eb-81ac-1b361ad760c3.png)

If we go to the checkout page then if the user selects the Credit Card (Braintree) and enters card details and presses complete purchase then we get this issue.
![image](https://user-images.githubusercontent.com/77787433/117536643-d0e0da80-b019-11eb-9f83-2f08cee2a51a.png)

**To Reproduce**:
Installed both FE and BE of Braintree and try to place an order. First on homepage you'll see an error popup(Look at the first and second image)

**Versions**:
- ScandiPWA: (use `composer info scandipwa/source`):- V4.3.0
- Any other composer module, you thing could be related:- Braintree?
- 

**Additional context**:
Link to the thread on Slack.
https://scandipwa.slack.com/archives/CD8ETGY3Y/p1620385449474400

**Comment by aleksandrakorolova** [comment]
Closed task because this will be an extension available in the [marketplace](https://marketplace.scandipwa.com/modules.html)
