### ISSUE TITLE
Rate (Stars) is shifted on the search result page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2609]
**Description**:
Rate (Stars) is shifted on the search result page

**Expected behavior**:
Stars are displayed as in screenshot 
![image](https://user-images.githubusercontent.com/73526235/118088580-f1b97f00-b3cf-11eb-8727-7306f2a6f5a0.png)

**To Reproduce**:
1. Enter 'Dress' in the search line
2. Click on enter
3. Scroll down search result page

**Actual result:**:
Rate (Stars) is shifted 
![image](https://user-images.githubusercontent.com/73526235/118088495-d77fa100-b3cf-11eb-9ab2-d7d2922de85a.png)

**Comment by carinadues** [comment]
Closing because this issue is fixed in redesign.
