### ISSUE TITLE
Very small images are displayed on the left side if product has a lot of images

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2623]
**Description**:
Very small images are displayed on the left side if product has a lot of images

**Expected behavior**:
Show images in normal size as we show images when product has 5 images. User sees other images when clicking arrow down
![image](https://user-images.githubusercontent.com/73526235/118250618-5566a980-b4af-11eb-8437-84a1f86dcb32.png)

**To Reproduce**:
1. Open product which has more than 4-5 images -  https://master.d25kd40decjpue.amplifyapp.com/default/travel-bag-1.html

**Actual result:**:
Very small images are displayed on the left side
![image](https://user-images.githubusercontent.com/73526235/118250183-da9d8e80-b4ae-11eb-812a-6a220f537ec6.png)

**Comment by carinadues** [comment]
Closed after merging https://github.com/scandipwa/scandipwa/pull/2808
