### ISSUE TITLE
Price per option/product is 0.00 for bundle product with dynamic price

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2638]
**Description**:
Price per option/product is 0.00 for bundle product with dynamic price

**Expected behavior**:
Actual prices per option are displayed 
Product price is displayed when selecting options/products

**To Reproduce**:
1. Open or create bundle product with dynamic price - https://master.d25kd40decjpue.amplifyapp.com/default/8bun.html
2. Select some option/product

**Actual product**:
Price per option/product is 0.00 but product price is missing
![image](https://user-images.githubusercontent.com/73526235/118760863-2e77f100-b87c-11eb-9820-d0b6cd687a29.png)

**Additional context**:
Сorrect price is displayed in mini-cart/cart if user added product to cart

**Comment by tatiana-scandi** [comment]
Looks like something is wrong with this product, because Luma shows same prices (0 for product and all it's options).
My changes definitely didn't affect Luma, because it doesn't use graphql packages.

Could you, please, try to setup new product from scratch?

![image](https://user-images.githubusercontent.com/79456428/118830756-d9fa6300-b8c7-11eb-8def-a742a6845789.png)

**Comment by aleksandrakorolova** [comment]
This issue appear after the latest changes because we don't have these changes on pmrev yet. It works as expected on pmrev - https://scandipwapmrev.indvp.com/default/8bun.html
![image](https://user-images.githubusercontent.com/73526235/118923693-a1e53580-b944-11eb-9c05-39b647a3d28e.png)

I created new product and I see the same problem:
Master - https://master.d25kd40decjpue.amplifyapp.com/default/bundle-product-with-dynamic.html
Pmrev - https://scandipwapmrev.indvp.com/default/bundle-product-with-dynamic.html

0 for product and all its options on Luma - I noticed this some time ago, before you did these changes

**Comment by aleksandrakorolova** [comment]
It happens if the setting Used in product listing is set to No for the price attribute. Correct prices are displayed if set this setting to yes. So it works by default Magento or it's a bug but I didn't find this case in Magento GitHub
![image](https://user-images.githubusercontent.com/73526235/119940107-69260b80-bf97-11eb-9643-87c9c6ec505d.png)
