### ISSUE TITLE
Empty cart appears for a few seconds when user changing currency and shopping cart contain product 

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#2642]
**Description**:
If changing currency on page of cart page with products then empty cart appears for a few seconds and after that appears cart with prices in different currency 

**Expected behavior**:
Nothing happened in cart view page when changing currency except changing prices

**To Reproduce**:
Preconditions: add to cart any product
1. Click on Cart -> View cart
2. Change currency in top right coner

**Actual result**
Empty cart appears for a few seconds when shopping cart contain products and user changing currency
https://www.loom.com/share/bade1c8bbd004a9aa37933537188ccaa

**Additional context**:
Here is performance profile https://drive.google.com/file/d/1HkVKcuXREpj6cvK3z9FSxXZUqKIjyrRa/view?usp=sharing

**Comment by carinadues** [comment]
Please check if the currencies change both in cart page and checkout page
