### ISSUE TITLE
'5584' option appears for color attribute in the Layered navigation on PLP if some product doesn't have color attribute

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2649]
**Description**:
'5584' option appears for color attribute in the Layered navigation on PLP if some product doesn't have color attribute

**Expected behavior**:
5584 option is missing

**To Reproduce**:
1. Open Admin panel -> Vatalog -> Products
2. Create new product
3. Stay empti Color attribute
4. Add product to the X category
5. Save
6. Open Category X on FE

**Actual result:**:
5584 option appears in the Layered navigation
![image](https://user-images.githubusercontent.com/73526235/119110171-87858780-ba2a-11eb-901d-b55dbc68a2d7.png)

**Comment by tatiana-scandi** [comment]
Figured out that it happens if you set swatch attribute to a product and then remove the swatch attribute from attribute values list (e.g. add turquoise color, add bag with color = turquoise, edit attribute and remove turquoise swatch).

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2787 + https://github.com/scandipwa/catalog-graphql/pull/104
