### ISSUE TITLE
Downloadable products loads as attachment even with configuration 'Inline'

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#2660]
**Description**:
If "Use Content Disposition" set as 'Inline' then file/link is not open in window. File loads as attachment all the time

**Expected behavior**:
If "Use Content Disposition" set as 'Inline' then file/link should be opened in window

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/119350737-5adea380-bca8-11eb-9ff2-e3d45e4be8ca.png)

**To Reproduce**:
1. Open Admin panel -> go to Stores -> Configuration -> Catalog -> Catalog -> Downloadable Product Options -> Set Use Content Disposition to Inline -> Save -> Clear cash
2. Open website -> Open Downloadable product 
(example of downloadable product: [https://scandipwapmrev.indvp.com/default/drawings-for-baggini.html](https://scandipwapmrev.indvp.com/default/drawings-for-baggini.html) )
3. Add to cart -> Log in -> Complete order -> Open my account -> Open My downloadable -> Click on link title

**Actual result**:
If "Use Content Disposition" set as 'Inline' then file/link is not open in window. Link loads as attachment all the time

**Additional context**:

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
https://vimeo.com/722146563/20194ce018
