### ISSUE TITLE
Link stays in 'My downloadable' if product is expired

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#2661]
**Description**:
Link is not missing in 'My downloadable' if downloadable product has status 'Expired'. If pointer is hovering on then link is underlined but not reacting on click.

**Expected behavior**:
Link is missing in 'My downloadable' if downloadable product has status 'Expired'. Product is not loading even if link stays.

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/119355373-da22a600-bcad-11eb-9fa8-131be513fc29.png)

**To Reproduce**:
1. Open Admin panel -> go to Catalog -> Products -> Create Downloadable Product
2. Complete the required settings
3. Open Downloadable Information
4. Enter 1 in Max. Downloads field
5. Complete product creation
6. Open website -> Open Downloadable product -> Log in -> Add product to cart -> Log in -> Complete order -> Open my account -> Open My downloadable
7. Download 1 product
8. Refresh page, try to hover a pointer on link and click

**Actual result**:
Link stays in 'My downloadable' if downloadable product is expired

**Additional context**:
Links stays after refresh of page if downloadable product has status 'Expired'. Expected: links absent after refresh.

**Comment by tatiana-scandi** [comment]
Fix: https://github.com/scandipwa/scandipwa/pull/2964
