### ISSUE TITLE
 Configurable product option with customisable option is always out of stock when the custom option has a SKU

### ISSUE THREAD

**Issue by jamestaylorSW** [scandipwa/scandipwa#2671]
**Description**:
When adding a customisable option with a sku to a configurable product, the product is always marked as out of stock when added to cart. 
If now SKU is added to the customisable option, it works. 
This is not reproducible on a simple product, because the custom option works fine there when it has a sku or no sku. 

**Expected behaviour**:
When adding customizable options with SKUs to a configurable product, the simple product options can be added to the cart and checked out.  

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/75443323/119534099-37daef00-bd8f-11eb-8c06-db6ed5fc44cd.png)

**To Reproduce**:
1. Go the admin panel 
2. Create a configurable product 
3. Add customisable options to the parent configurable product (enter option title, select dropdown as the option type)
4. Add titles and skus for the customisable options. 
5. Save the product
6. Navigate to the product on the FE and add to cart
7. See that it is marked as out of stock

**Versions**:
- ScandiPWA: 4.2.1

**Comment by kinowashere** [comment]
To add some extra information on the matter, the GraphQL query to get Cart Items shows that the bugged products have the `stock_status` property with a value of `null`. I assume this is a bug in the API since `stock_status` should only have `OUT_OF_STOCK` or `IN_STOCK` as a possible values.

**Comment by aleksandrakorolova** [comment]
Need to test after #3447 fix
