### ISSUE TITLE
First and last page is not shown constantly in pagination

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#2679]
**Description**:
First and last page is not shown constantly in pagination

**Expected behavior**:
First and last page is shown in pagination. 
For example, Luma pagination with 10 pages in total. 
Settings:  Pagination Frame = 3;  Pagination Frame Skip = 3;
If opened page  in middle (4th page) then showed like 
![image](https://user-images.githubusercontent.com/84388061/119777189-82af5080-bece-11eb-9e46-7ab6bd8e6b0f.png)
If opened page near the beginning (2nd page):
![image](https://user-images.githubusercontent.com/84388061/119777357-b68a7600-bece-11eb-94f5-dac28d8f0fd7.png)
If page is opened near the end (9th page)
![image](https://user-images.githubusercontent.com/84388061/119777513-f2254000-bece-11eb-87d7-1bd9856be8e2.png)

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/119777570-09642d80-becf-11eb-89f3-03b08e37a1dc.png)

**To Reproduce**:

1. Open Admin panel > go to Content > Design > Configuration > Open Design Configuration in edit mode
2. Open Pagination section
3. Enter '3' in the Pagination Frame field
4. Enter '3' in the Pagination Frame Skip field
5. Tap 'Save' > Flush Cache Storage
6. Open website > open category Women > Open page in the middle > Open page at the end

**Actual result**:
First and last page is not shown constantly in pagination

**Comment by Elena-Evsa** [comment]
Need to test after this pull-request will be merged #2791

**Comment by aleksandrakorolova** [comment]
Closed because it was fixed in #2800
