### ISSUE TITLE
Options price is displayed as percent for product with customization options

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2682]
**Description**:
Options price is displayed as percent for product with customization options

**Expected behavior**:
Options price is displayed as amount as by default Magento
![image](https://user-images.githubusercontent.com/73526235/119809821-29efb000-beee-11eb-8450-0ed5f7f9cfb8.png)

**To Reproduce**:
1. Open simple product with customization options where option price is set in percent 

**Actual result:**:
Options price is displayed as percent
![image](https://user-images.githubusercontent.com/73526235/119809786-252afc00-beee-11eb-825e-bf408e64b640.png)

**Comment by winniepukki** [comment]
@aleksandrakorolova shouldn't be using both the per cent and the price be more descriptive?
![image](https://user-images.githubusercontent.com/43637240/120466860-38374380-c3a8-11eb-8a58-5ad24496f714.png)
