### ISSUE TITLE
Checkout Account Registration - Order not added to Account when User creates Account after checkout

### ISSUE THREAD

**Issue by KrissOerts** [scandipwa/scandipwa#2685]
**Description**:
When a Guest User makes a Purchase and Decides to Create a Account after Checkout the Order is not visible in the User Account "Order History" tab.

**Expected behavior**:
After the User creates the Account after the "Billing" step he is able to see the Order he just made in the User Account "Order History" tab.

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/77437826/119903275-28a39f00-bf51-11eb-8f6e-3cba64a52535.png)
![image](https://user-images.githubusercontent.com/77437826/119903316-3b1dd880-bf51-11eb-8134-fb19e000573f.png)

**To Reproduce**:
1. Open https://tech-demo.scandipwa.com/
2. Make sure you are not logged into the FE User Account.
3. Navigate to any PLP and Add any Product to the Cart.
4. Complete the Checkout "Shipping" and "Billing" Steps using a E-mail that is not Already Registered on the Site.
5. Place the Order.
6. In the "Order Success" page click the "Create Account" button.
7. Create the User Account and Navigate to the "Order History" tab.
8. Observe the Order History.

**Additional context**:
Issue Found on the Whey-Protein project.
Fixed within the Scope of this ticket -  https://scandiflow.atlassian.net/browse/WHEY-857

**Comment by jithutj** [comment]
This issue also exist even if already exist and place order without login..Please fix it ASAP...

**Comment by raivisdejus** [comment]
This issue is resolved in latest versions of ScandiPWA. User will be created when he is moving from shipping to billing step. 

Function `createUserOrSaveGuest` will be used to do that https://github.com/scandipwa/scandipwa/blob/master/packages/scandipwa/src/route/Checkout/Checkout.container.js#L449

**Comment by carinadues** [comment]
Tested this after merging https://github.com/scandipwa/quote-graphql/pull/79 and https://github.com/scandipwa/quote-graphql/pull/97 but it didn't work. When I purchase something in pmrev as a guest and then create an account, the order isn't there, though it exists.
