### ISSUE TITLE
URL with Target Path leads to 404 page

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#2688]
**Description**:
404 page appears when open URL with Target Path. If user open URL with Request Path page opened.

**Expected behavior**:
If user open URL with Target Path page opened.
Here is example of page which is opened with help of Request Path
![image](https://user-images.githubusercontent.com/84388061/119980067-70afd980-bfc4-11eb-9733-c6ba2e28b8a8.png)

**Screenshots, Video, Logs**
![404](https://user-images.githubusercontent.com/84388061/119979940-42ca9500-bfc4-11eb-8890-5828802e49d7.png)

**To Reproduce**:

1. Open Admin panel -> go to Marketing -> SEO&Search -> URL Rewrites
2. Open product URL where Redirect Type NO
3. Open product with help of Target Path (for example, catalog/product/view/id/5117/category/35) and then Open website with Request Path (for example, accessories/drawings-for-baggini.html)

**Actual results**:
404 page appears when open URL with Target Path.

**Additional context**:
URL with Target Path opened on Luma

**Comment by Elena-Evsa** [comment]
If user open link with Target path then 404 shown constantly or first request loaded with 404, and 404 page shown for a few seconds https://vimeo.com/716716400/34ec3b90a3

**Comment by aleksandrakorolova** [comment]
Connected issue - 404 page when opening config product with selected configurations from wishlist
 https://vimeo.com/manage/videos/733171481/eb39f66f1a

**Comment by Elena-Evsa** [comment]
Can not reproduce
