### ISSUE TITLE
Internal server error for Catalog Product List if this widget has condition for price

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2692]
**Description**:
Internal server error for Catalog Product List if this widget has condition for price

**Expected behavior**:
All products are displayed in Catalog Product List
![image](https://user-images.githubusercontent.com/73526235/120181387-a992bd00-c215-11eb-9b59-d00747714ed0.png)

**To Reproduce**:
1. Open Admin panel -> Content -> Pages -> Open CMS page X
2. Expand Content section
3. Add widget -> Catalog Product List -> Add condition  for price (For example, price >=27)
4. Save
5. Open page X on FE

**Actual result**:
Products aren't loaded
![image](https://user-images.githubusercontent.com/73526235/120181324-9122a280-c215-11eb-9c11-09bb65d6641d.png)

**Comment by riha112** [comment]
Unable to reproduce locally

**Comment by carinadues** [comment]
Issue was rechecked and can still be reproduced

**Comment by Elena-Evsa** [comment]
Can not reproduce 
![image](https://user-images.githubusercontent.com/84388061/187874103-a0a9f815-5e34-45da-85d9-11fe04e6e323.png)
