### ISSUE TITLE
'PayPal Buy Now' button on FE

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#2694]
**Description**:
Add a “PayPal Buy Now” button that opens a pop-up for the PayPal payment. 
The button should be present in the PDP, mini cart overlay, and in the summary of the shopping cart. 

**Expected behavior**:

**PDP**
![image](https://user-images.githubusercontent.com/82165392/120244119-c2b06380-c23f-11eb-893b-edc448cb7568.png)
_______________________________________________________
**Mini Cart**
![image](https://user-images.githubusercontent.com/82165392/120244160-e1165f00-c23f-11eb-81c9-3b1b27cb1d4c.png)
_______________________________________________________
**Shopping cart**
![image](https://user-images.githubusercontent.com/82165392/120244194-f9867980-c23f-11eb-8b54-84cd3283eab8.png)
_______________________________________________________
**Pop-up**
![image](https://user-images.githubusercontent.com/82165392/120244496-bbd62080-c240-11eb-98c1-14e1568b4aa7.png)
_______________________________________________________
**Additional context**
Check the behavior in Luma: https://scandipwapmrev.indvp.com/luma/women/cropped-hoodie-black.html

**Comment by aleksandrakorolova** [comment]
Closed task because this will be an extension available in the [marketplace](https://marketplace.scandipwa.com/modules.html)
