### ISSUE TITLE
Billing address form is closed when logged user without saved address is going to the billing step

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2696]
**Description**:
Billing address form is closed when logged user without saved address is going to the billing step

**Expected behavior**:
Billing address form is opened when going to the billing step
![image](https://user-images.githubusercontent.com/73526235/120276947-11034800-c2bc-11eb-9039-730b771c561e.png)

**To Reproduce**:
1. Register an account or log in with an existing user (user shouldn't have addressed in the Address book)
2. Open virtual or downloadable product
3. Add to cart
4. Go to the checkout
5. Select payment method
6. Agree with T&C
7. Click on Complete order

**Actual result**:
message: "Variable \"$input_1\" got invalid value {\"guest_cart_id\":\"\",\"same_as_shipping\":false,\"billing_address\":{\"address\":{\"street\":[null,null]}}}; Field value.billing_address.address.city of required type String! was not provided.\n\nVariable \"$input_1\" got invalid value {\"guest_cart_id\":\"\",\"same_as_shipping\":false,\"billing_address\":{\"address\":{\"street\":[null,null]}}}; Field value.billing_address.address.country_code of required type String! was not provided.\n\nVariable \"$input_1\" got invalid value {\"guest_cart_id\":\"\",\"same_as_shipping\":false,\"billing_address\":{\"address\":{\"street\":[null,null]}}}; Field value.billing_address.address.firstname of required type String! was not provided.\n\nVariable \"$input_1\" got invalid value {\"guest_cart_id\":\"\",\"same_as_shipping\":false,\"billing_address\":{\"address\":{\"street\":[null,null]}}}; Field value.billing_address.address.lastname of required type String! was not provided.\n\nVariable \"$input_1\" got invalid value {\"guest_cart_id\":\"\",\"same_as_shipping\":false,\"billing_address\":{\"address\":{\"street\":[null,null]}}}; Field value.billing_address.address.telephone of required type String! was not provided."
![image](https://user-images.githubusercontent.com/73526235/120276803-d7324180-c2bb-11eb-9c46-2bbca7f0cdb4.png)

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2792

If product is virtual + user doesn't have saved addresses, address form will be shown on billing step now.
