### ISSUE TITLE
The selected link is missing for downloadable product in the wishlist 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2701]
**Description**:
The selected link is missing for the downloadable product in the wishlist 

**Expected behavior**:
The selected link is displayed
![image](https://user-images.githubusercontent.com/73526235/120313424-9a2d7580-c2e2-11eb-8398-eca0c5f53d4c.png)

**To Reproduce**:
1. Log in
2. Open downloadable product
3. Select link
4. Add to wishlist
5. Open Wishlist

**Actual result**:
Selected link is missing 
![image](https://user-images.githubusercontent.com/73526235/120313365-88e46900-c2e2-11eb-8cb6-eada0548e27f.png)

**Comment by Elena-Evsa** [comment]
Can not reproduce
![image](https://user-images.githubusercontent.com/84388061/132825290-555b648f-0b5c-4c5c-9054-6de8bc25c19b.png)
