### ISSUE TITLE
Checkout Login - Password form is not displayed when using "Autofill", "Paste" and "saved" E-mail

### ISSUE THREAD

**Issue by KrissOerts** [scandipwa/scandipwa#2716]
**Description**:
1. When Registered Users have made purchase while logged out proceed to the checkout "Shipping" step for a second time use "autofill or "Paste" their e-mail the password form is not displayed. 

2. When Registered Users have made purchase while logged out proceed to the checkout "Shipping" step for a second time and have their E-mail and shipping information already Saved and filled by their browser the password form is not displayed. 

**Expected behavior**:
The Password form is displayed every time a Registered user enters their E-mail in the "Checkout" shipping step while logged out.

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/77437826/120554100-05219e00-c402-11eb-9c23-48746429cf43.png)

**To Reproduce**:
1. Open https://tech-demo.scandipwa.com/
2. Make sure you are logged out of the FE User Account.
3. Place a Order using a Registered FE Account without logging in.
4. Add any product to the Cart.
5. Proceed to the checkout "Shipping" step.
6. Observe the "Password" form.
7. Repeat steps 3-6 for the "Paste" and "Autofill" functions. 

**Additional context**:
Issues found and resolved on the Whey-Protein project. 
https://scandiflow.atlassian.net/browse/WHEY-884

**Comment by aleksandrakorolova** [comment]
Still, can reproduce 
https://drive.google.com/file/d/1KUg3ZFklvDIBi0_XtGrHGmSI5TELHZW3/view?usp=sharing
