### ISSUE TITLE
Product quantity is not visible in Cart order summary

### ISSUE THREAD

**Issue by ilonasmatko** [scandipwa/scandipwa#2719]
**Description**:
Product quantity is not visible in Cart Order Summary. E.g. I add 2 the same products, 1 the different one. Cart summary shows that 3 items are in the cart, calculates prices right, but it is not clear which of the products are added in qty 2.

**Expected behavior**:
It should be possible to see amount of added products in order summary.

**Screenshots, Video, Logs**
[Screenshot](https://imgur.com/hqXtGna)

**To Reproduce**:
1. Add one product into cart, set quantity 2
2. Add another product
3. Click on cart button in header
4. Click Secure checkout button
5. See that there are 3 items in cart, but it is not possible to see how many of each product

**Versions**:
- ScandiPWA 2.13.2
- Any OS
- Any browser

**Comment by carinadues** [comment]
This issue will be fixed in milestone 5.0.0 by the end of July 2021, with the release of the theme redesign.
