### ISSUE TITLE
Ooops page opens when opening bundle product

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2721]
**Description**:
Ooops page opens when opening bundle product

**Expected behavior**:
Bundle product opens

**To Reproduce**:
1. Open bundle product - https://master.d25kd40decjpue.amplifyapp.com/default/baggini-without-dynamic.html

**Actual result**:
Ooops page opens
![image](https://user-images.githubusercontent.com/73526235/120793048-10c6af00-c53f-11eb-966f-9c10954a40ba.png)

**Notes:**
The same situation when opening product with customization options on mobile view

**Comment by aleksandrakorolova** [comment]
@winniepukki Still, ooops page opens when opening product with customization options on mobile view
![image](https://user-images.githubusercontent.com/73526235/121189714-04aa5c80-c873-11eb-9cb6-b98c94e6cba6.png)
Bundle products are fixed

**Comment by winniepukki** [comment]
@aleksandrakorolova @carinadues might have been fixed with [the following](https://github.com/scandipwa/scandipwa/pull/2740) PR. no longer able to reproduce

**Comment by aleksandrakorolova** [comment]
Closed task because issue was fixed by #2736
