### ISSUE TITLE
Ooops page opens when opening my account 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2730]
**Description**:
Ooops page opens when opening my account 

**Expected behavior**:
No errors

**To Reproduce**:
1. Log in
2. Open my account

**Actual result**:
Ooops page opens 
_TypeError: Cannot read property 'isSubmitted' of undefined_ appears in the console
![image](https://user-images.githubusercontent.com/73526235/121131321-42d65a80-c838-11eb-883c-0b4e6f7c00aa.png)

**Comment by AleksandrsKondratjevs** [comment]
Can't reproduce issue.
