### ISSUE TITLE
Sometimes error message: “Variable \“$key_1\” of required type \“String!\” was not provided.” appears when confirming an account

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2731]
**Description**:
Sometimes error message: “Variable \“$key_1\” of required type \“String!\” was not provided.” appears when confirming an account

**Expected behavior**:
No errors. Account is confirmed 

**To Reproduce**:
1. Open Admin panel -> go to Stores > Settings > Configuration -> Customers -> Customer Configuration -> Create New
2. Account Options section -> Select 'Yes' in Require Emails Confirmation field
3. Save  -> Flush Cache Storage
4. Open website
5. Create an account
6. Open the email
7. Open the Confirmation link
8. Confirm password

**Actual result:**:
Sometimes error message: “Variable \“$key_1\” of required type \“String!\” was not provided.” appears
![image](https://user-images.githubusercontent.com/73526235/121138185-20e0d600-c840-11eb-80d4-dccb63bdda46.png)

**Additional context**:
Do the same steps - sometimes password/account is confirmed but sometimes this error appears

**Comment by zans-laksa** [comment]
Same thing is happening on order info popup close. Will investigate it wider on all MyAccount pages.

**Comment by zans-laksa** [comment]
The issue is not reproducible.
But we can display an error message that email or key is not available so the user is clear why he cannot submit the form.
