### ISSUE TITLE
Issues connected with compare products

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2735]
**1. Description**:
Ooops page opens when opening compare list and grouped/virtual product was added to compare list

**Expected behavior**:
Compare list opens

**To Reproduce**:
1. Open FE
2. Add virtual or bundle products to compare list
3. Open compare list

**Actual result**:
Ooops page opens 
![image](https://user-images.githubusercontent.com/73526235/121168586-cbb2bd80-c85b-11eb-8305-4ad56f62460f.png)

**Notes:**
the same situation if user added this simple product - https://master.d25kd40decjpue.amplifyapp.com/default/9sim.html
_________________________
**2. Description**:
Image not specified is displayed instead product image in compare list

**Expected behavior**:
Product images are displayed

**To Reproduce**:
1. Open FE
2. Add products to compare list
3. Open compare list

**Actual result**:
Image not specified is displayed instead product image
![image](https://user-images.githubusercontent.com/73526235/121164841-804ae000-c858-11eb-8adc-aa4af08ca088.png)
____________________________
**3. Description**:
N/A is displayed instead '-' for product which doesn't have option for this attribute

**Expected behavior**:
Product images are displayed
![image](https://user-images.githubusercontent.com/73526235/121165740-272f7c00-c859-11eb-9939-63f577cc8f31.png)

**To Reproduce**:
1. Open FE
2. Add products to compare list
3. Open compare list

**Actual result**:
N/A is displayed instead '-' for product which doesn't have option for this attribute
![image](https://user-images.githubusercontent.com/73526235/121165773-2d255d00-c859-11eb-9d6d-233fe3c14586.png)
________________________________

**4. Description**:
All attributes which are set Comparable on Storefront to yes are displayed

**Expected behavior**:
Don't show attributes that these products don't have
![image](https://user-images.githubusercontent.com/73526235/121166051-6bbb1780-c859-11eb-81e0-bb030bf737b0.png)

**To Reproduce**:
1. Open FE
2. Add products to compare list
3. Open compare list

**Actual result**:
All attributes which are set Comparable on Storefront to yes are displayed
![image](https://user-images.githubusercontent.com/73526235/121165995-5e9e2880-c859-11eb-97f2-94eb74dfa910.png)
________________________________

**5. Description**:
Compare icon isn't painted over on PLP and PDP if user refreshed product

**Expected behavior**:
Compare icon is painted over for products which were added to compare list

**To Reproduce**:
1. Open FE
2. Add products to compare list From PLP
3. Refresh page
4. Add product to compare list from PDP
5. Refresh page

**Actual result**:
Compare icon isn't painted over but product is displayed in the compare list

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2771 + https://github.com/scandipwa/performance/pull/20

(No breaking changes, can be merged in random order.)

**Comment by tatiana-scandi** [comment]
Issue 5 fix: https://github.com/scandipwa/scandipwa/pull/2772

**Comment by tatiana-scandi** [comment]
1. Didn't reproduce
2. https://github.com/scandipwa/compare-graphql/pull/8
3. https://github.com/scandipwa/compare-graphql/pull/8
4. https://github.com/scandipwa/compare-graphql/pull/8
5. https://github.com/scandipwa/scandipwa/pull/2772

**Comment by carinadues** [comment]
@aleksandrakorolova can you please test and close this issue if it's all good?

**Comment by aleksandrakorolova** [comment]
@tatiana-scandi Can you check if your changes exist in 4-4-1 branch? because I can reproduce many issues

1. Also can't reproduce
2. Still, Image not specified is displayed instead placeholder for product without image
![Screenshot 2021-06-18 at 07 47 49](https://user-images.githubusercontent.com/73526235/122507836-99e2e900-d009-11eb-9926-8a1c3cb8e717.png)

3. Still, N/A is displayed for product which doesn't have option for this attribute
![Screenshot 2021-06-18 at 07 51 00](https://user-images.githubusercontent.com/73526235/122508081-0d84f600-d00a-11eb-8552-db2d1624f3d6.png)

4.Still, All attributes which are set Comparable on Storefront to yes are displayed
![Screenshot 2021-06-18 at 07 52 23](https://user-images.githubusercontent.com/73526235/122508251-5341be80-d00a-11eb-9672-bdfbc400d727.png)

5. Fixed

**Comment by aleksandrakorolova** [comment]
2.Fixed
3.Fixed
4.Fixed
![Screenshot 2021-06-21 at 15 09 24](https://user-images.githubusercontent.com/73526235/122759678-e3019a00-d2a2-11eb-872b-a467dab88511.png)
