### ISSUE TITLE
Wrong prices for bundle and simple product with customization options

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2736]
**Description**:
Wrong prices for bundle and simple product with customization options

**Expected behavior**:
Correct prices are displayed
![image](https://user-images.githubusercontent.com/73526235/121186945-3a9a1180-c870-11eb-983c-79b7fb1c322a.png)
![image](https://user-images.githubusercontent.com/73526235/121187018-4b4a8780-c870-11eb-8aae-deefe8c26cb4.png)

**To Reproduce**:
1. Open Simple product with customization - https://master.d25kd40decjpue.amplifyapp.com/default/jeans-for-girls.html
2. Open bundle product - https://master.d25kd40decjpue.amplifyapp.com/default/8bun.html

**Actual result**:
Wrong prices for options
![image](https://user-images.githubusercontent.com/73526235/121186813-2229f700-c870-11eb-8b85-d70f5ed5666a.png)
![image](https://user-images.githubusercontent.com/73526235/121186826-2524e780-c870-11eb-80b1-31ab808b2730.png)

**Comment by aleksandrakorolova** [comment]
@winniepukki 
1. Wrong prices for options if option price is set in percentages (bundle product and products with customization options)
![Screenshot 2021-06-10 at 09 33 18](https://user-images.githubusercontent.com/73526235/121476466-6089f800-c9cf-11eb-9314-e842ed14d93e.png)
2. Product price is displayed for option which should cost 0.00
![Screenshot 2021-06-10 at 09 41 12](https://user-images.githubusercontent.com/73526235/121477188-34bb4200-c9d0-11eb-87bf-f6c58fe74180.png)

**Comment by winniepukki** [comment]
@aleksandrakorolova please mind [the following](https://github.com/scandipwa/scandipwa/pull/2746) PR should close this issue

**Comment by winniepukki** [comment]
@aleksandrakorolova please recheck and update the status for both issues

**Comment by aleksandrakorolova** [comment]
@winniepukki 
1. Fixed
2. Still can reproduce
![Screenshot 2021-06-10 at 14 12 23](https://user-images.githubusercontent.com/73526235/121515577-02bcd680-c9f6-11eb-9ba0-75bd9630cb73.png)
