### ISSUE TITLE
User appears at the bottom of the page if user opened cart from scrolled down page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2741]
**Description**:
User appears at the bottom of the page if user opened cart from scrolled down page

**Expected behavior**:
Page opens on the top

**To Reproduce**:
1. Open FE
2. Add product to cart
3. Open PLP
4. Scroll down
5. Open mini-cart
6. Open cart

**Actual result**:
User appears at the bottom of the page
https://drive.google.com/file/d/1S8NHudBDKqOD9MwBmYgV2xS7XooKC-Pw/view?usp=sharing

**Notes**
The same situation from PDP or CMS page

**Comment by aleksandrakorolova** [comment]
Open Checkout - ok
Still, can reproduce if open cart
https://drive.google.com/file/d/1OemNO6yG1Lx7QaQgCEEhHdIC11QQdm3F/view?usp=sharing

**Comment by Elena-Evsa** [comment]
Reproducible on mobile devices of user goes to cart from bottom of:
  - PDP
  - PLP
  - CMS page
