### ISSUE TITLE
Default  ScandiPWA theme crashes while trying to display product page

### ISSUE THREAD

**Issue by PiotrekFilipecki** [scandipwa/scandipwa#2744]
When I try to display product page on localhost I have  React issue displayed (http://localhost:3000)

![Zrzut ekranu 2021-06-8 o 20 46 27](https://user-images.githubusercontent.com/9655458/121346598-9cb54e00-c926-11eb-8086-4ef6233ea8be.png)

When I'm trying network link it works as it is supposed to

**Comment by carinadues** [comment]
Hey! I'm closing this issue. If it is still happening, you can reopen it or ask for our help on Slack: https://docs.scandipwa.com/about/support#asking-for-help
