### ISSUE TITLE
Boolean attribute with option No is missing on PDP

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2748]
**Description**:
Boolean attribute with option No is missing on PDP

**Expected behavior**:
Attribute is displayed
![Screenshot 2021-06-10 at 08 18 51](https://user-images.githubusercontent.com/73526235/121469090-8d84dd80-c9c4-11eb-924e-62c0a22737d4.png)

**To Reproduce**:
1. Open Admin panel -> Go to Stores -> Attributes
2. Create boolean attribute where Visible on Catalog Pages on Storefront is set to Yes
3. Add this attribute to the attribute set
4. Save
5. Clear cache
6. Open some product
7. Set this attribute to No
8. Save
9. Open this product page
10. Open Detail tab

**Actual result**:
Boolean attribute with option No is missing
![Screenshot 2021-06-10 at 08 18 35](https://user-images.githubusercontent.com/73526235/121469062-8231b200-c9c4-11eb-9362-996779bd6ba1.png)

**Additional context**:
https://master.d25kd40decjpue.amplifyapp.com/default/virtual-product.html

**Comment by tatiana-scandi** [comment]
Checked that is works fine on Compare page - there could be a similar issue:
<img width="644" alt="ScandiPWA 2021-06-14 10-41-16" src="https://user-images.githubusercontent.com/79456428/121872494-fb573f00-cd0d-11eb-8d86-a3bcf533d6fc.png">

**Comment by tatiana-scandi** [comment]
Issue 5 fix: #2772

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/2771 + https://github.com/scandipwa/performance/pull/20

(No breaking changes, can be merged in random order.)

**Comment by carinadues** [comment]
@aleksandrakorolova can you please test and close this issue if it's all good?
