### ISSUE TITLE
The position for the price is applied to the category attribute in Layered Navigation

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2749]
**Description**:
The position for the price is applied to the category attribute in Layered Navigation

**Expected behavior**:
Caregory filter is displayed as the first filter, but price - the last filter
![Screenshot 2021-06-10 at 08 48 23](https://user-images.githubusercontent.com/73526235/121471595-a4c5ca00-c9c8-11eb-9e22-bc2ce0ca56c3.png)

**To Reproduce**:
1. Open Admin panel -> Stores -> Attributes -> Open Price attribute
2. Change its position in Layered navigation to 10000
3. Save
4. Clear cache
5. Open PLP

**Actual result:**:
The position for the price is applied to the category attribute too

FE: Price and Category filters are displayed at the end of Layered Navigation
![Screenshot 2021-06-10 at 08 41 38](https://user-images.githubusercontent.com/73526235/121471155-e73ad700-c9c7-11eb-966a-7ea3a9c7e79f.png)

In Admin panel:
![Screenshot 2021-06-10 at 08 42 41](https://user-images.githubusercontent.com/73526235/121471169-eace5e00-c9c7-11eb-8d18-836aa86082d5.png)

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/catalog-graphql/pull/104

**Comment by carinadues** [comment]
Closed after merging PR
