### ISSUE TITLE
Street address line 2 field becomes green when selecting country in the checkout

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2755]
**Description**:
Street address line 2 field becomes green when selecting country in the checkout

**Expected behavior**:
Field stays the same colors

**To Reproduce**:
1. Open PDP
2. Add product to cart
3. Go to checkout step
4. Change country

**Actual result**:
Street address line 2 field becomes green  
![Screenshot 2021-06-11 at 08 28 15](https://user-images.githubusercontent.com/73526235/121635493-051f3f00-ca8f-11eb-882d-879350812c1d.png)

**Notes:**
The same situation with Add/Edit address form

**Comment by carinadues** [comment]
@aleksandrakorolova The PR is merged to 4.4.1-rc. Can you QA and close the issue if it's ok?
