### ISSUE TITLE
Blank Page issue when prepare build

### ISSUE THREAD

**Issue by vikasebizon** [scandipwa/scandipwa#2784]
**Description**:
We are having blank page after i upgrade scandipwa to latest version.

**Expected behavior**:
App should be run 

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/52157625/122211915-e2dd5500-cec4-11eb-9831-1aa573583c7d.png)

**To Reproduce**:
1. Go to 'scandipwa app root folder'
2. Create build  'yarn build'
3. Deploy build to server
4. Blank page on accessing app

We are facing that issue after upgrade scandipwa from 4.2.0 to 4.4.0

**Versions**:
- ScandiPWA: (4.4.0)

**Comment by rMazeiks** [comment]
This issue has been reported by another on Slack: https://scandipwa.slack.com/archives/CD8ETGY3Y/p1623302371198400

This shows that most likely, it is indeed a bug.

**Comment by vikasebizon** [comment]
Hello @rMazeiks 
I found solution. 
![image](https://user-images.githubusercontent.com/52157625/122379675-b38e1d00-cf84-11eb-87b7-dfef2ff2ebe5.png)
