### ISSUE TITLE
Options price is missing for bundle product with dynamic prices

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2814]
**Description**:
Options price is missing for bundle product with dynamic prices

**Expected behavior**:
Options price is displayed for bundle product with dynamic prices

**To Reproduce**:
1. Open bundle product with dynamic price

**Actual result**:
Options price is missing
![Screenshot 2021-06-29 at 08 45 28](https://user-images.githubusercontent.com/73526235/123777635-12cf2400-d8d9-11eb-8b49-9f00d81e730f.png)

**Products:**
https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/8bun.html
https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/bundle-product-with-dynamic.html

OBS: It's also missing in Master

**Comment by carinadues** [comment]
Closed after merging PR
