### ISSUE TITLE
Bundle product with fixed price has discount on FE and old price = price with Base Currency from Admin panel

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2815]
**Description**:
Bundle product with fixed price has discount on FE and old price = price with Base Currency from Admin panel

**Expected behavior**:
Product doesn't have discount 

**To Reproduce**:
1. Open Admin panel -> Stores -> Configuration -> General -> Currency setup
2. Set Base currency to EUR
3. Set Default Display Currency to USD
4. Save
5. Clear cache
6. Open bundle product with fixed price

**Actual result**:
Discount is displayed and old price = price with Base Currency from Admin panel
![Screenshot 2021-06-29 at 08 53 39](https://user-images.githubusercontent.com/73526235/123778107-73f6f780-d8d9-11eb-84fb-a70450668ebf.png)

**Products**:
https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/8bunfixed.html
https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/fixed-bundle-jeans.html

**Comment by Elena-Evsa** [comment]
Price doesn't shown at all for product https://master.d25kd40decjpue.amplifyapp.com/default/kids/8bun.html
