### ISSUE TITLE
Some Bugs In Links With The Store Code

### ISSUE THREAD

**Issue by zans-laksa** [scandipwa/scandipwa#2818]
1. In the `Link.container.js` there is a `getTo` method, that detects whether is needed to add the store code to the url.
If `to` prop is object, this method should update the `pathname` and return this object.
But actually it overrides the new `pathname` before return.
```javascript
return {
    pathname: appendWithStoreCode(pathname),
    ...to
};
```

2. In the `Util/Url/Url.js` there is a `appendWithStoreCode` method, that adds the store code to the url.
But first it makes some tests in order to check whether this is needed.
But there is a bug in the regular expression. It checks the whole string, no the start of he string.
```javascript
if (pathname.match(`/(${window.storeList.join('|')})`)) {
    return pathname;
}
```
It is correct to check the start of the string only with slashes surrounded, and also check whether the pathname matches store code only. Like this:
```javascript
const storeList = window.storeList.join('|');

// match URLs which have the store code in pathname
if (new RegExp(`^/(${storeList})/`, 'i').test(pathname)) {
    return pathname;
}

// match exact if pathname contains store code only
if (new RegExp(`^/(${storeList})/?$`, 'i').test(pathname)) {
    return pathname;
}
```

**Comment by zans-laksa** [comment]
Also see `getUrlParam` function in the `Util/Url/Url.js`.
If there are two stores: `en` and `en_us`, on replace the first store code corrupts the second store code.

**Comment by Elena-Evsa** [comment]
Examples for test:
1. Code of store: en_us
Category: Engine
link should be displayed: https://scandipwapmrev.indvp.com/**en_us**/**en**gine.html
2. Code of store: BE
Category: Belts
link should be displayed: https://scandipwapmrev.indvp.com/**be**/accessories/accessories-**be**lts.html
