### ISSUE TITLE
For customizable option percent value is converted as currency is converted if base and default display currency are different

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2819]
**Description**:
For customizable option percent value is converted as currency is converted if base and default display currency are different

**Expected behavior**:
Percent is the same as in Admin panel -> correct price is displayed for options

**To Reproduce**:
1. Open Admin panel -> Stores -> Configuration -> General -> Currency setup
2. Set base currency to EUR
3. Set Default display currency to USD
4. Save
5. Clear cache
6. Open product with customization option percent type - https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/jeans-for-girls.html

**Actual result**:
The percent value is converted as EUR to USD with the same coefficient
![Screenshot 2021-06-30 at 09 27 47](https://user-images.githubusercontent.com/73526235/123912311-8b8bba00-d985-11eb-8ce3-8f304b964feb.png)

**Comment by tatiana-scandi** [comment]
Fixed by https://github.com/scandipwa/catalog-graphql/pull/107

**Comment by carinadues** [comment]
Closing as #107 has been merged.
