### ISSUE TITLE
Disable 'Add to cart' button and show 'out of stock' status for out of stock product in Compare list

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2822]
**Description**:
As we implemented a feature - disabled Add to cart button for out of stock products. We need to do the same in compare list.

**TO DO**:
- Disable Add to cart button for out of stock product in Compare list
- Show product status (Out of stock) instead of empty place in price column for out of stock product in Compare list

![Screenshot 2021-07-01 at 11 47 52](https://user-images.githubusercontent.com/73526235/124095311-3671a600-da62-11eb-97f6-b2177cc355a6.png)

**Comment by Elena-Evsa** [comment]
Button 'Add to cart' disabled for In-stock products 
![image](https://user-images.githubusercontent.com/84388061/129857433-9f43a081-fed0-43b4-ad0d-df0372936da2.png)
