### ISSUE TITLE
Uncaught Error: Class PriceTiers, does not compile magento 2.4.2-p1

### ISSUE THREAD

**Issue by corpsysgit** [scandipwa/scandipwa#2823]
**Description**:
Uncaught Error: Class PriceTiers, does not compile magento 2.4.2-p1

**Expected behavior**:
Command: bin/magento setup:di:compile

**Screenshots, Video, Logs**
AFTER COMPILATION MAGENTO 2:

PHP Fatal error:  Uncaught Error: Class 'Magento\CatalogCustomerGraphQl\Model\Resolver\PriceTiers' not found in /home/melbourne/public_html/vendor/scandipwa/catalog-customer-graphql/Model/Resolver/PriceTiers.php:28
Stack trace:
#0 /home/melbourne/public_html/vendor/composer/ClassLoader.php(444): include()
#1 /home/melbourne/public_html/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 [internal function]: spl_autoload_call()
#4 /home/melbourne/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists()
#5 /home/melbourne/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#6 /home/melbourne/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
#7 /home/melbourne/public_html/setup/src/Magento/Setup/Module/Di/App/Task/ in /home/melbourne/public_html/vendor/scandipwa/catalog-customer-graphql/Model/Resolver/PriceTiers.php on line 28

**To Reproduce**:
1. UBUNTU 20.04
2. Magento 2.4.2-p1
3. Command 'bin/magento setup:di:compile'

**Versions**:
- ScandiPWA: latest version

**Comment by Elena-Evsa** [comment]
Closing after communication with developer as not actual
