### ISSUE TITLE
Can't add bundle product with customizable option to cart

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2832]
**Description**:
Can't add bundle product with customizable option 

**Expected behavior**:
Product is added to cart

**To Reproduce issue 1**:
1. Add bundle product with fixed price and add **required** customizable option 
2. Open this product on FE - https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/8bunfixed.html
3. Select the required option
4. Add to cart

**Actual result**:
Notification message 'Please select required option!' is displayed
![Screenshot 2021-07-02 at 08 48 58](https://user-images.githubusercontent.com/73526235/124228207-84df7d00-db14-11eb-97d9-966fbfc4fe9d.png)
_______________________________
**To Reproduce issue 2**:
1. Add bundle product with fixed price and add **Not required** customizable option 
2. Open this product on FE - https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/fixed-bundle-jeans.html
3. Select Not required option
4. Add to cart

**Actual result**:
Error message '_Variable "$cartItem_1" got invalid value {"sku":"fixed bundle jeans","product_type":"bundle","quantity":1,"product_option":{"extension_attributes":{"bundle_options":[{"option_id":94,"option_value":110}]}}}; Field value.product_option.extension_attributes.bundle_options[0].id of required type Int! was not provided._' is displayed
![Screenshot 2021-07-02 at 08 49 31](https://user-images.githubusercontent.com/73526235/124228434-e0aa0600-db14-11eb-8d96-ff1984d5ccc5.png)

**Additional context**:
User can add product to cart if he/she:
1. Return back to previous page
2. Open again PDP 
3. Select all options
4. Add to cart
![Screenshot 2021-07-02 at 08 49 52](https://user-images.githubusercontent.com/73526235/124228452-e69fe700-db14-11eb-8049-7083cb1177b4.png)

**Comment by Elena-Evsa** [comment]
When user try to add to wishlist same products, sign of Wishlist (heart) is not highlighted as selected by orange color
