### ISSUE TITLE
New Version Popup on first visit

### ISSUE THREAD

**Issue by krelo** [scandipwa/scandipwa#2833]
**Description**:
When i visit a ScandiPWA page without any cached contet (ie. incognito or fresh browser) get the new version popup.
This means all first time visitors get this and it seem to pop up on Google pagespeed tests and i am worried it blocks content from googlebot indexing. 

**Expected behavior**:
New Version Popup should only show if the cached version has changed. If there is no cache version in my browser it should not pop up.

**To Reproduce**:
1. Open incognito browser.
2. Go to https://tech-demo.scandipwa.com/
3. See there's a new version

**Versions**:
- Reproduced on ScandiPWA versions 4.2, 4.3 and 4.4

**Additional context**:
For my tests it seems to only happen if i visit the site on https while on http it does not seem to be an issue.
NewVersionPopup

**Comment by rMazeiks** [comment]
Thank you for your report! I can reproduce this on Chromium.

(Note: could not reproduce on Firefox)

**Comment by ahmedalmulki** [comment]
is there any news regarding this issue?

**Comment by nnirmana** [comment]
Same issue ,
It seems controllerchange event triggers on latest chrome (v91) even for new users

**Comment by runedalton** [comment]
This is a major issue for us - it also forces any new visits from crawlers (Google etc.) to view the page incorrectly regarding render, due to the popup always being loaded on fresh visits.

Any update? This issue keeps getting pushed, but it seems there's a simple logic/event related to version comparison, that just needs to be adjusted.

Thank you.

**Comment by nnirmana** [comment]
We had the same SEO concern as well 

As a **temporally** solution we have disabled the new version popup  

I have added the below changes to disable the popup : 

NewVersionPopup.container.js extended to prevent rendering 

```javascript

import { PureComponent } from 'react';

/** @namespace AllHomePwafe/Component/NewVersionPopup/Container/NewVersionPopupContainer */
export class NewVersionPopupContainer extends PureComponent {
    /**
     * Temporally New version popup removed due to a bug
     * BUG : New version popup shows up for first time users
     * https://github.com/scandipwa/scandipwa/issues/2833
     */

    render() {
        return null;
    }
}
```

export default NewVersionPopupContainer;

**Comment by babybeddingdesign** [comment]
This is a big issue for us as well- This means all first time visitors get this and it seem to pop up on Google pagespeed tests and i am worried it blocks content from googlebot indexing.

Any update?
