### ISSUE TITLE
Product is displayed as out of stock product in cart/mini-cart if config product with customization options is added to cart

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2845]
**Description**:
Product is displayed as out of stock product in cart/mini-cart if config product with customization options is added to cart

**Expected behavior**:
Text 'Product is out of stock' is missing for this product in cart/mini-cart -> User can buy this product

**To Reproduce**:
1. Open config product with customization product on FE - https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/custom-options.html
2. Select attribute
3. Select the option
4. Add to cart
5. Open cart/mini-cart

**Actual result**:
Product is displayed as out of stock product
![Screenshot 2021-07-06 at 08 12 57](https://user-images.githubusercontent.com/73526235/124545841-6211d900-de32-11eb-87af-d1ab4ea2ce81.png)

**Additional context**:
The product can buy (text 'Product is out of stock' is missing) if user added product without customizable options

**Comment by websuits** [comment]
@carinadues Why is this in milestone 5.0.2 and css issues are in milestone 5.0.0 ?

**Comment by aleksandrakorolova** [comment]
Need to test after #3447 fix
