### ISSUE TITLE
'As low as' did not show in Price field in Compare list for products as on PLP

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#2850]
**Description**:
'As low as' did not show in Price field in Compare list for products with as on PLP

**Expected behavior**:
'As low as' price shown in compare list for product as on PLP
For Bundled products: should be shown like here https://github.com/scandipwa/scandipwa/issues/2417
![image](https://user-images.githubusercontent.com/84388061/124589701-f6942f80-de62-11eb-9882-1ff1de46b455.png)

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/124589648-e7ad7d00-de62-11eb-9f46-251cc608182f.png)

**To Reproduce**:
1. Add product to compare list (example of products find in additional info)
2. Open Compare List

**Actual result**:
Price did not show in compare list for products with 'As low as' as on PLP

**Additional context**:
You can add to compare list:
Product with catalog price rules: [https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/fur-bag.html](https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/fur-bag.html) 
Configurable product: [https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/accessories/baggini-bagpack-108.html](https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/accessories/baggini-bagpack-108.html) 
Bundle product: [https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/baggini-dyn-with-special-price.html](https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/baggini-dyn-with-special-price.html)

**Comment by aleksandrakorolova** [comment]
'As low as' is missing for products with tier price
**Product:** https://master.d25kd40decjpue.amplifyapp.com/default/fur-bag.html
![Screenshot 2021-08-13 at 08 29 16](https://user-images.githubusercontent.com/73526235/129309334-6f971146-91d6-4bca-ba7b-c419982bc128.png)

**Expected result:**
![Screenshot 2021-08-13 at 08 29 50](https://user-images.githubusercontent.com/73526235/129309348-c61ca91b-2b81-46bc-a142-02384068a823.png)

Also, created separate task - #3115
