### ISSUE TITLE
PWA MSI Issue

### ISSUE THREAD

**Issue by zans-laksa** [scandipwa/scandipwa#2855]
From Aleksandrs Mokans email:

> Issue is in ScandiPWA\Performance\Model\Resolver\Products\DataPostProcessor\Stocks
> 
> Main issue: it uses SourceItemRepositoryInterface to fetch data.
> That gets data from inventory_source_item, which has a one to many relation between sku and source_code's
> 
> Meaning if there's multiple sources on an sku, it ends up using only last source's stock_status etc.
> 
> Instead, it should be using the inventory index tables.
> (cataloginventory_stock_status for non-MSI legacy, and for MSI, inventory_stock_{website_id})
> 
> Example of the working code for Sportland attached (you'd need to remove a bunch of customizations for variants or reservation checks, those are project specific).
> 
> File should be used just to see how $stockItems are loaded based on MSI or non-MSI.

**Comment by carinadues** [comment]
https://github.com/scandipwa/inventory

**Comment by Elena-Evsa** [comment]
Closing after communication with developer as not actual
