### ISSUE TITLE
Breadcrumbs appear on Homepage if user switched stores and click on Back button

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#2859]
**Description**:
Breadcrumbs appear on Homepage if user switched stores and click on Back button

**Expected behavior**:
Breadcrumbs do not appear on Homepage in any case

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/124873758-8c4ccd80-dfcf-11eb-9714-c0bcbc2fbd6a.png)

**To Reproduce**:
1. Open Home page (Store: United states)
2. Select other store 
3. Click browser button Back

**Actual result**:
Breadcrumbs appear on Homepage if user switched stores and click on Back button

**Comment by riha112** [comment]
Unable to reproduce on the newest SPWA version.

**How I tested:**
1. Opened http://scandipwapmrev.indvp.com/ (firefox & chrome)
2. Switched to different store (Spain & UK)
3. Clicked back button on top of the browser
--------------------
4. Clicked forward button
5. Opened page containing breadcrumbs
6. Clicked back button

**Comment by Elena-Evsa** [comment]
Can reproduce with following conditions:
1. Clear cash
2. Open link without last '/'   - http://scandipwapmrev.indvp.com/default
3. Observe Breadcrumbs on Home page

If last '/' present, space for breadcrumbs appears for a moment every reload of page

https://vimeo.com/586653135/252ed00dd9

**Comment by Elena-Evsa** [comment]
Still can reproduce with following conditions:
1. Clear cash
2. Open link without last '/' - http://scandipwapmrev.indvp.com/default
3. Observe Breadcrumbs on Home page
