### ISSUE TITLE
iOS: Top bar with the done button (from the top of keyboard) appears when tapping qty control button on PDP

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2860]
**Description**:
iOS: Top bar with the done button (from the top of keyboard) appears when tapping qty control button on PDP

**Expected behavior**:
Nothing happens

**To Reproduce**:
1. Open PDP on mobile view 
2. Tap number in qty control button

**Actual result**:
Top bar with the done button (from the top of keyboard) appears
![IMG_0069](https://user-images.githubusercontent.com/73526235/124876945-3d089c00-dfd3-11eb-875b-f2db5b7aa365.PNG)

**Additional context**:
iOS: Safari, Chrome, FF and Opera

**Comment by winniepukki** [comment]
@aleksandrakorolova please keep adding the preview links. Those are extremely helpful 😇

**Comment by winniepukki** [comment]
Unable to reproduce iOS 14.6 iPhone XS real device [Master Branch Downloadable Product](https://master.d25kd40decjpue.amplifyapp.com/default/tech/song-of-ice-and-fire.html)

**Comment by aleksandrakorolova** [comment]
Closed and removed from milestone because it's not actual with new design
