### ISSUE TITLE
A new countdown for the slide does not start if user changes slides itself

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#2868]
**Description**:
A new countdown for the slide does not start if user changes slides itself
A lot situation of situation, there is no time even for click on button on new slide - specially on mobile

**Expected behavior**:
A new countdown for the slide starts if user changes slides itself and new slide loaded

**Screenshots, Video, Logs**
https://drive.google.com/file/d/190Dh0l7kkIxK45p432Ca_oteJh5XZ3IJ/view?usp=sharing

**To Reproduce**:
1. Open Home page
2. Try to go scroll slides

**Actual result**:
A new countdown for the slide does not start if user changes slides itself

**Comment by tatiana-scandi** [comment]
The PR has been updated to fix the issue with countdown, please recheck.
