### ISSUE TITLE
Back button in title is not clickable if user tap on button in CMS block on Home page on mobile

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#2876]
Back button in title is not clickable if user tap on button in CMS block on Home page on mobile
Fix after https://github.com/scandipwa/scandipwa/issues/2869

**Description**:
Back button in title is not clickable on mobile if user tap on button in CMS block on Home page

**Expected behavior**:
Back button in title is clickable and leads back if user tap on button in CMS block on Home page

**Screenshots, Video, Logs**
https://vimeo.com/573961488/83eae65e82

**To Reproduce**:
Open Home page
Tap on any button in CMS block
Tap on arrow Back button in title 

**Actual result**:
Back button in title is not clickable if user tap on button in CMS block on Home page

**Comment by tatiana-scandi** [comment]
Changed cms block configuration so that 1. links don't open in new tab 2. as a sequence back button works.
