### ISSUE TITLE
Plus symbol '+' is displayed instead of space in breadcrumbs on search result page if user searched more than one keyword

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2892]
**Description**:
Plus symbol '+' is displayed instead of space in breadcrumbs on search result page if user searched more than one keyword

**Expected behavior**:
Space is displayed between words
![Screenshot 2021-07-14 at 14 02 51](https://user-images.githubusercontent.com/73526235/125612090-06b61825-bf23-4c17-99f8-a755c16ce7d1.png)

**To Reproduce**:
1. Open FE
2. Open Search line
3. Enter few words (for example summer dress)
4. Press enter

**Actual result:**:
Breadcrumbs: Home > Summer**+**dress
Plus symbol '+' is displayed instead of space in breadrumbs
![Screenshot 2021-07-14 at 14 02 05](https://user-images.githubusercontent.com/73526235/125612073-69d1dac1-0ac5-411a-994a-17679ba0c902.png)

**Comment by carinadues** [comment]
I suppose this happened after merging https://github.com/scandipwa/scandipwa/pull/2535
