### ISSUE TITLE
Content (product name, status and etc) is displayed on the left side when page is loading

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2900]
**Description**:
Content (product name, status and etc) is displayed on the left side when page is loading. Then content jumps to the right side.

**Expected behavior**:
Content is displayed on the right side 

**To Reproduce**:
1. Open PDP

**Actual result**:
Content (product name, status and etc) is displayed on the left side when page is loading. Then content jumps to the right side.
![Screenshot 2021-07-15 at 09 08 29 1](https://user-images.githubusercontent.com/73526235/125737622-d93d629c-932f-449e-a33f-45a4ef3c53d2.png)

**Comment by carinadues** [comment]
@aleksandrakorolova could you retest, please? I'm unable to reproduce after merging https://github.com/scandipwa/scandipwa/pull/2910

**Comment by aleksandrakorolova** [comment]
@carinadues I can reproduce when refreshing page 
https://drive.google.com/file/d/1CPwv5GykfCSE02grUVfMUMJ9fp-u09sx/view?usp=sharing

**Comment by AleksandrsKondratjevs** [comment]
@carinadues set in browser Throttling slow 3G and you will see that gallery loads after product actions. While it loads product actions shifted left.
