### ISSUE TITLE
Wishlist is empty in my account if something went wrong with data

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2907]
**Description**:
Wishlist is empty in my account if something went wrong with data

**Expected behavior**:
Products are displayed.
No errors

**To Reproduce**:
1. Open FE
2. Log in with user who has products in Wishlist (asd@asd.asdd/Scandipwa123)
3. Open Wishlist

**Actual result:**:
Wishlist is empty
Error message is displayed in the network - _debugMessage: "Notice: Undefined offset: 2609 in /var/www/public/vendor/scandipwa/wishlist-graphql/src/Model/Resolver/WishlistItemsResolver.php on line 202"_
![Screenshot 2021-07-15 at 14 47 44](https://user-images.githubusercontent.com/73526235/125783124-506ef5e6-74ea-492a-820c-b59ae7648c0b.png)

**Notes:**
new@new.new/Scandipwa123

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/wishlist-graphql/pull/22

**Comment by carinadues** [comment]
Closing after merging PR.
