### ISSUE TITLE
LTR / RTL Switch

### ISSUE THREAD

**Issue by zans-laksa** [scandipwa/scandipwa#2917]
In the redesign branch we implemented support of LTR and RTL layouts.
Now we need to implement the switch, that sets page layout direction.
This switch should be controlled in the admin panel, per store.
On the store front it should set corresponding value into the <html> tag.
LTR is set by default.
```html
<html dir="ltr">
```

**Comment by aleksandrakorolova** [comment]
Can't set Layout Direction per store. This setting is global

**Comment by aleksandrakorolova** [comment]
Can set Layout Direction global and per store but NOT per website
![Screenshot 2021-07-23 at 08 29 42](https://user-images.githubusercontent.com/73526235/126740888-80590d84-b3b8-46ea-8754-4dee6406be11.png)

We have this logic:
if setting per store that we can set it globally, per website, and per store view
if setting per website that we can set it globally and per website
