### ISSUE TITLE
Mobile: Logo is missing when opening homepage the first time

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2919]
**Description**:
Logo is missing when opening homepage the first time on mobile layout

**Expected behavior**:
Logo is displayed

**Issue 1:
To reproduce:**
1. Open mobile layout in incognito tab
2. Go to https://master.d25kd40decjpue.amplifyapp.com/default (no slash at the end)

**Actual Result:** 
Empty title line with back button is displayed instead of logo
![Screenshot 2021-07-19 at 13 51 13](https://user-images.githubusercontent.com/73526235/126149236-ab267f7c-ca5f-4b30-976e-ca52e669dbe7.png)

**Issue 2:
To reproduce:**
1. Open mobile layout in incognito tab
2. Go to https://master.d25kd40decjpue.amplifyapp.com/default/

**Actual Result:** 
Logo is missing
![Screenshot 2021-07-19 at 13 51 21](https://user-images.githubusercontent.com/73526235/126149347-07d203de-f903-461b-8995-17ba86cbe390.png)

**Comment by tatiana-scandi** [comment]
Problem: Top navigation state is set to `cms-page` instead of `default` when omitting slash at the end (going to `<host>/default`).

**Comment by carinadues** [comment]
Closed after merging PR.
