### ISSUE TITLE
Ooops page when opening Add new/Edit address form in my account

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2926]
**Description**:
Ooops page when opening Add new/Edit address form in my account

**Expected behavior**:
No errors. Add new/Edit address form opens

**To Reproduce**:
1. Log in
2. Open Address book
3. Click on Add new Adress or Edit address

**Actual result:**:
Ooops page opens
![Screenshot 2021-07-20 at 08 53 40](https://user-images.githubusercontent.com/73526235/126269243-491e18bd-9ff9-44be-a209-b0ee9342c217.png)

**Comment by carinadues** [comment]
Fixed in https://github.com/scandipwa/scandipwa/pull/2972
