### ISSUE TITLE
Some elements don't change color 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2930]
**Description**:
Some elements don't change color 

**Expected behavior**:
Elements change color

**Elements:**
1. Wishlist and compare icons (On PDP and Product cart on PLP)
![Screenshot 2021-07-20 at 09 36 42](https://user-images.githubusercontent.com/73526235/126274704-2dbdbf0e-e41b-4887-8ec7-2d4259bf56a5.png)

2. Qty control button (on PDP, cart, mini, cart, wishlist)
![Screenshot 2021-07-20 at 09 37 15](https://user-images.githubusercontent.com/73526235/126274724-306f1812-2dea-4391-aa1d-e1462f1eb412.png)

3. Cross and pencel in product card in wishlist
![Screenshot 2021-07-20 at 09 40 39](https://user-images.githubusercontent.com/73526235/126274742-e8cec3bc-7c96-4631-a7e3-e448b81d1847.png)

4. Stars - reviews (PDP in review tab and below product name, on PLP, in Wishlist)
![Screenshot 2021-07-20 at 09 37 45](https://user-images.githubusercontent.com/73526235/126274763-89ac502f-b32a-4756-96cd-429d8ed9de8c.png)

5. Icon for Share button in wishlist
![Screenshot 2021-07-20 at 09 40 50](https://user-images.githubusercontent.com/73526235/126274778-1f3e0937-a057-44be-a105-bac1e9f79cd7.png)

6. Circle for saved address in shipping step (for logged user with saved address)
![Screenshot 2021-07-20 at 09 42 17](https://user-images.githubusercontent.com/73526235/126274795-830eb82c-1d2a-4ded-afc6-392d5bdb47d1.png)

**Actual result**:
Elements change color

**Comment by tatiana-scandi** [comment]
Fix https://github.com/scandipwa/scandipwa/pull/3049

Please, note that passing custom color values from Magento admin is not supported, if you open ScansiPWA in storefront mode. So, whichever colors you set up in Stores -> Configuration -> Scandipwa -> Color Configuration, you will see the default orange, until code is deployed to http://scandipwapmrev.indvp.com/.

All the icons have been redrawn as part of this PR*. So please check for all icons in the application that:
1. Icons are not missing
2. No odd icons are displayed
3. Icons size is acceptable (yet icon sizes may have change imperceptibly)
4. Icons are not shifted
5. Icons have correct color + correct color when selected + correct color when hovered
6. `cursor: pointer` is applied, where it should be.
7. RTL reflection
8. When you hover some hollow button with an icon, but not the icon itself, hover effect is applied to icon as well (so border color changes together with icon color).

*Only 3 icons have not been affected: the iOS Plus and iOS share displayed in "Add to Homescreen banner" on iOS and checkboxes (these ones are drawn via css, not imported as SVGs).

**Comment by aleksandrakorolova** [comment]
Created separate tasks - #3061, #3069, #3070 and doc
