### ISSUE TITLE
Text and checkbox aren't aligned in Layered navigation if option has long text

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2932]
**Description**:
Text and checkbox aren't aligned 

**Expected behavior**:
Text and checkbox are aligned 

**To Reproduce**:
1. Open PLP

**Actual result**:
Text and checkbox aren't aligned 
![Screenshot 2021-07-20 at 09 51 55](https://user-images.githubusercontent.com/73526235/126275129-0517ea17-a19a-446f-b350-db54a801c8f5.png)

**Comment by tatiana-scandi** [comment]
Fixed: https://github.com/scandipwa/scandipwa/pull/2980
