### ISSUE TITLE
Background for mini-cart block is white

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2933]
**Description**:
Background for mini-cart block is white

**Expected behavior**:
Mini-cart block is displayed as per design 
![Screenshot 2021-07-20 at 10 00 11](https://user-images.githubusercontent.com/73526235/126276119-3aea7468-c253-42e1-b873-b35ad2f4a1d4.png)

**To Reproduce**:
1. Open PDP
2. Add product to cart
3. Open Mini-cart

**Actual result**:
White text on white background in mini-cart block
 ![Screenshot 2021-07-20 at 09 59 30](https://user-images.githubusercontent.com/73526235/126276037-d5d63c1a-632c-4afd-ab0f-7301e529241e.png)

**Comment by carinadues** [comment]
The background of the block isn't white anymore.

![image](https://user-images.githubusercontent.com/82165392/127182634-6d687a39-a9e8-4186-997e-b9a0492b6031.png)
