### ISSUE TITLE
Layered navigation is missing on search result page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2934]
**Description**:
Layered navigation is missing on search result page

**Expected behavior**:
Layered navigation is displayed 

**To Reproduce**:
1. open FE
2. Enter 'Dress' in search line
3. Press Enter

**Actual result**:
Layered navigation is missing 
![Screenshot 2021-07-20 at 10 07 20](https://user-images.githubusercontent.com/73526235/126277061-8a1f73a0-6ae2-40c5-862d-c7336eb4162f.png)

**Comment by tatiana-scandi** [comment]
https://github.com/scandipwa/scandipwa/pull/3356 + https://github.com/scandipwa/catalog-graphql/pull/124

**Comment by aleksandrakorolova** [comment]
Layered navigation is missing on mobile view
![Screenshot 2021-09-27 at 10 48 20](https://user-images.githubusercontent.com/73526235/134866479-40cf58b6-f927-437d-a3a6-a481e4ade46a.png)

**Comment by tatiana-scandi** [comment]
> Layered navigation is missing on mobile view

Fixed.
