### ISSUE TITLE
Icons blink in navigation bar when going to another page via the navigation bar 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2948]
**Description**:
Icons blink in navigation bar when going to another page via the navigation bar 

**Expected behavior**:
Icons don't blink

**To Reproduce**:
1. Open FE
2. Tap menu/cart/my account/home in the navigation bar

**Actual result**:
Icons blink
iOS 12: https://drive.google.com/file/d/1JCaTyfKQ9cZXltDY6zkh8bmgZOkKkeQN/view?usp=sharing
iOS 14: https://drive.google.com/file/d/1Tav_qXks7ih8jDEz7jpUNvHu2V3HgTd7/view

**Additional context**:
iOS

**Comment by Elena-Evsa** [comment]
Blinking only on first tap
