### ISSUE TITLE
Cart icon is missing in the header

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2952]
**Description**:
Cart icon is missing in the header

**Expected behavior**:
Cart icon is displayed
![Screenshot 2021-07-21 at 07 47 29](https://user-images.githubusercontent.com/73526235/126432536-c64ae0c3-5dc8-46a9-9fe1-e45444f43827.png)

**To Reproduce**:
1. Open FE

**Actual result:**:
Cart icon is missing
![Screenshot 2021-07-21 at 07 46 26](https://user-images.githubusercontent.com/73526235/126432491-aacdb79b-4ef6-43a1-b934-93e7258f3377.png)

**Comment by tatiana-scandi** [comment]
Fix: https://github.com/scandipwa/scandipwa/pull/2957
