### ISSUE TITLE
Delivery methods are missing when opening checkout

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2953]
**Description**:
Delivery methods are missing when opening checkout

**Expected behavior**:
Delivery methods are displayed for default country

**To Reproduce**:
1. Open FE
2. Add product to cart
3. Open checkout 

**Actual result**:
Delivery methods are missing
![Screenshot 2021-07-21 at 08 44 55](https://user-images.githubusercontent.com/73526235/126437320-3adfeb44-fc80-4084-b00a-b22eae292672.png)

**Additional context**:
Delivery methods appear if user selected again country

**Comment by tatiana-scandi** [comment]
Fix: https://github.com/scandipwa/scandipwa/pull/2965
