### ISSUE TITLE
The first allowed country is displayed as default country

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2954]
**Description**:
The first allowed country is displayed as default country

**Expected behavior**:
The default country is Latvia

**To Reproduce**:
1. Open Admin panel -> Stores -> Configuration -> General -> General
2. Set Latvia to Default country (or another country)
3. Save 
4. Clear cache
5. Open FE
6. Add product to cart
7. Open checkout

**Actual result:**:
The default country is Afganistan

**Comment by tatiana-scandi** [comment]
Please, check also that regions dropdown is initialized according to default country setting.

**Comment by tatiana-scandi** [comment]
Fix: https://github.com/scandipwa/scandipwa/pull/2965

**Comment by aleksandrakorolova** [comment]
Created separate task - #2988
