### ISSUE TITLE
Internal server error appears if user used country without state

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2955]
**Description**:
Internal server error appears if user used default country or country without state

**Expected behavior**:
No errors. Billing step opens

**To Reproduce**:
1. Register user or log in with existing user but she/he shouldn't have saved addresses
2. Add product to cart
3. Open Shipping step
4. Click on Proceed to billing

**Actual result;**:
Internal server error appears
_debugMessage: "Notice: Undefined index: shipping_carrier_code in /var/www/public/vendor/scandipwa/quote-graphql/src/Model/Resolver/SaveAddressInformation.php on line 123"_
![Screenshot 2021-07-21 at 08 22 04](https://user-images.githubusercontent.com/73526235/126435890-58cd9bbd-2c5f-4160-8a08-bb75c27d3727.png)

**Additional context**:
The same issue appears with these steps:
To Reproduce2:
1. Open FE
2. Add product to cart
3. Open Shipping step
4. Fill form But don't change default country
5. Click on Procced to billing

Also, error message appears in the console when entering zip code
![Screenshot 2021-07-21 at 08 48 33](https://user-images.githubusercontent.com/73526235/126437776-5c880d41-ec79-494e-a7f7-0b8cdbf989c6.png)

To Reproduce3:
1. Open FE
2. Add product to cart
3. Open Shipping step
4. Fill form 
5. Select country without state (for example, Afganistan)
6. Enter state if you want
7. Click on Proceed to billing
8. Back
9. Click on Proceed to billing

**Comment by tatiana-scandi** [comment]
Fix https://github.com/scandipwa/scandipwa/pull/2965
