### ISSUE TITLE
Internal Server Error appears when adding all product to cart from wishlist and at least one product is out of stock or with required option

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2956]
**Description**:
Internal Server Error appears when adding all product to cart from wishlist and at least one product is out of stock or with required option

**Expected behavior**:
Error messages ('Please specify product option(s).' or 'Product that you are trying to add is not available.') appear. It depends on product (out of stock or with required options)

**How it looks in Luma:**
![Screenshot 2021-07-21 at 10 37 42](https://user-images.githubusercontent.com/73526235/126450221-7d3d7315-eb64-411d-a68e-a274d0b83c0a.png)

**To Reproduce**:
1. Log in 
2. Add out of stock product to wishlist 
3. Add product with required options to wishlist 
4. Open Wishlist
5. Click on Add All To Cart

**Actual result:**:
Internal Server Error appears
![Screenshot 2021-07-21 at 10 29 55](https://user-images.githubusercontent.com/73526235/126450801-30efcedf-e8f2-4538-a1d1-3edc4a43c132.png)

**Additional context**:
aleksandra+04@scandiweb.com/Scandipwa

**Comment by aleksandrakorolova** [comment]
Internal server error appears when adding all products to cart and setting Min Qty Allowed in Shopping Cart is set more than 1 

![Screenshot 2021-07-26 at 10 01 00](https://user-images.githubusercontent.com/73526235/126947073-3a85058f-23fd-47d3-a7a8-ddeee1fb8658.png)
**Product:** https://5-0-0-rc.d25kd40decjpue.amplifyapp.com/default/t-shirt-with-christmas-print.html
**Expected error message:** 'You can buy this product only in quantities of {minQtyAllowedInShoppingCart} at a time for {productName}'

Also, created separate tasks for wishlist issues - #2996 and #2997

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/wishlist-graphql/pull/24

**Comment by aleksandrakorolova** [comment]
Created separate task for error message #3027
