### ISSUE TITLE
PDP looks ugly when changing window size

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2959]
**Description**:
PDP looks ugly when changing window size

**Expected behavior**:
Move to Add to cart button in next line but compare and Add to wishlist icons in the same line with qty control button

**To Reproduce**:
1. Open PDP
2. Change window size

**Actual result:**:
Page looks ugly, especially Add to cart button 
https://drive.google.com/file/d/1fJLVXRc2VN5GgyHchJUJFjw1CrDipXC6/view?usp=sharing

**Comment by tatiana-scandi** [comment]
Fix: https://github.com/scandipwa/scandipwa/pull/2983
