### ISSUE TITLE
Button Sign in is not the same length on /account/login as email and password field 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2961]
**Description**:
Button Sign in is not the same length on /account/login as email and password field 

**Expected behavior**:
Button the same length as email and password form
![Screenshot 2021-07-21 at 14 28 05](https://user-images.githubusercontent.com/73526235/126482519-36b815ad-995e-44f7-bc3d-f8217df64bfc.png)

**To Reproduce**:
1. Open /account/login

**Actual result**:
Button Sign in is small 
![Screenshot 2021-07-21 at 14 28 05](https://user-images.githubusercontent.com/73526235/126482465-2a89d40b-4ea4-4efe-84d8-78b034b152ed.png)

**Comment by tatiana-scandi** [comment]
Fix: https://github.com/scandipwa/scandipwa/pull/2983
