### ISSUE TITLE
Customizable options are blocking product from adding to cart

### ISSUE THREAD

**Issue by websuits** [scandipwa/scandipwa#2963]
**Description**:
Customizable options are giving "internal server error" while trying to add to cart a product and checking a Customizable option. If you add to cart without them, everything works ok. Anyone experienced this ? Installed scandi as theme.

**Expected behavior**:
Product should add to cart normally.

**Screenshots, Video, Logs**
<img width="701" alt="Screenshot 2021-07-21 at 14 19 43" src="https://user-images.githubusercontent.com/42982977/126490175-432a16b8-7875-49f4-80f4-ccdbd814bd12.png">

debugMessage: "Return value of Magento\\QuoteGraphQl\\Model\\CartItem\\DataProvider\\CustomizableOptionValue\\PriceUnitLabel::getCurrencySymbol() must be of the type string, null returned" 

**To Reproduce**:
1. Go to a configurable product with Customizable options 
2. Click Customizable option
3. Add to cart
4. "internal server error"

**Versions**:
- ScandiPWA: 4.5.1
- Magento: 2.4.1 and 2.4.2

**Comment by websuits** [comment]
Magento issue. But can be updated as well in scandi pwa request.

**Comment by aleksandrakorolova** [comment]
Hello @jurvi,
Can you provide more information about this issue? because I couldn't reproduce it with SEK and RON currency. 
https://drive.google.com/file/d/1AWYoY8f1PlY5SGkbxb2pjRthrdHAurn5/view?usp=sharing
