### ISSUE TITLE
Block with shipping methods shrinks to half of original size when going from billing back to shipping

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2974]
**Description**:
Block with shipping methods shrinks to half of original size when going from billing back to shipping

**Expected behavior**:
Block with shipping methods stays the same size
**To Reproduce**:
1. Open PDP
2. Add product to cart
3. Open shipping step
4. Fill form
5. Go to billing step
6. Go back to shipping step

**Actual result**:
Block with shipping methods shrinks to half of original size
https://drive.google.com/file/d/131BMJ3RuJVEZ0dfGd-ALuyST-xX5zYeh/view?usp=sharing

**Comment by tatiana-scandi** [comment]
Fix: https://github.com/scandipwa/scandipwa/pull/2983

But actually is should always be 50% according to designs. So it is original size, which is wrong, not after going back from billing.

**Comment by Elena-Evsa** [comment]
Block with shipping methods shrinks looks not very nice then screen is sized, it looks very narrow. Original size better to make 100% of block of address fields width - agreed with Liana.

**Comment by tatiana-scandi** [comment]
@Elena-Evsa should I resize payment methods block to 100% for desktop layout as well?

**Comment by Elena-Evsa** [comment]
@tatiana-scandi 
The best way to solve this issue consists of two states of screen size:
1. Wide screen - block with fields for entering users data and address is in 2 columns - width of 'Shipping method' is 50% or under the 1 column [https://www.screencast.com/t/7ExhZRSfNFz8](https://www.screencast.com/t/7ExhZRSfNFz8) 
2. Small screen (but not yet mobile view) - block with fields for entering users data and address is in 1 column - width of 'Shipping method' is 100% or under the 1 column [https://www.screencast.com/t/g0T6QgdE](https://www.screencast.com/t/g0T6QgdE)
Please, do the same, as for Shipping methods block, for Payment methods block on Billing page
