### ISSUE TITLE
'Already have an account?' and Sign in' are shifted in forgot password form on checkout

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2975]
**Description**:
'Already have an account?' and Sign in' are shifted in forgot password form on checkout

**Expected behavior**:
'Already have an account? Sign in' is displayed in one line as in screenshot
![Screenshot 2021-07-22 at 10 43 39](https://user-images.githubusercontent.com/73526235/126605138-6ee04b08-2f6a-4d37-a0fb-9d7a30fe3ec0.png)

**To Reproduce**:
1. Add product to cart
2. Go the shipping step
3. Enter register email
4. Click on Forgot password

**Actual result**:
'Already have an account?' and Sign in' are shifted
![Screenshot 2021-07-22 at 10 37 17](https://user-images.githubusercontent.com/73526235/126604958-0d28468f-58e0-49f7-8c0e-9f15e3f993a9.png)

**Comment by tatiana-scandi** [comment]
Fix: https://github.com/scandipwa/scandipwa/pull/2983

**Comment by aleksandrakorolova** [comment]
@tatiana-scandi Mobile: 'Already have an account? Sign in' isn't aligned
![Screenshot 2021-07-27 at 14 51 22](https://user-images.githubusercontent.com/73526235/127148960-feab1861-881a-4dce-b905-14749aa0e153.png)

**Comment by carinadues** [comment]
QA Passed. Now 'Already have an account? Sign in' is aligned

![image](https://user-images.githubusercontent.com/82165392/127182033-97fa0721-fc9b-432c-ba48-93e69d4f2a5e.png)
