### ISSUE TITLE
Duplicates for links and samples are displayed on PDP when opening downloadable product

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2977]
**Description**:
Duplicates for links and samples are displayed when opening downloadable products. 

**Expected behavior**:
No Duplicates

**To Reproduce**:
1. Open downloadable product

**Actual result:**:
Duplicates for links and samples are displayed
![Screenshot 2021-07-22 at 11 18 35](https://user-images.githubusercontent.com/73526235/126616538-24e0d5b7-0740-4072-965f-71a5d6eeeedb.png)
https://drive.google.com/file/d/1E52gNy-hT4Rgl35JbwWYgLUQSqq9gWWp/view?usp=sharing

**Additional context**:
Duplicates disappear when refreshing the page.

**Comment by carinadues** [comment]
They are also duplicated if you open the downloadable product from the mini-cart.

**Comment by aleksandrakorolova** [comment]
Now it happens all the time
