### ISSUE TITLE
Country field is empty by default  in Add new address form

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2988]
**Description**:
Country field is empty by default  in Add new address form

**Expected behavior**:
Default country is displayed in country field

**To Reproduce**:
1. Log in
2. Open Address book
3. Click on Add new address

**Actual result**:
Default country is missing (country field is empty by default)
![Screenshot 2021-07-23 at 08 46 13](https://user-images.githubusercontent.com/73526235/126741829-d8a3a6e7-d750-4c9b-9777-a77dda490f73.png)

**Comment by tatiana-scandi** [comment]
Fix: https://github.com/scandipwa/scandipwa/pull/3001
