### ISSUE TITLE
Different prices shown in 'Now shopping by:' and selected price filter

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#2991]
**Description**:
Different prices shown in 'Now shopping by:' and selected price filter

**Expected behavior**:
Same prices shown in 'Now shopping by:' and selected price filter

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/126750596-63806619-d81c-4455-baf7-d7140a7a1464.png)

**To Reproduce**:
in admin:
1. Click Stores > Setting - Configurations > General > Currency setup
2. Set Base Currency = Euro
3. Set Default Display Currency = USD
4. Click Save 
5. Flush cash 

on FE
1. Open home page
2. Click on any category in menu (for example, Women)
3. Select any price filter 
4. Observe price in Now shopping by:' and selected price filter

**Actual result**:
Different prices shown in 'Now shopping by:' and selected price filter

**Comment by tatiana-scandi** [comment]
Fix: https://github.com/scandipwa/catalog-graphql/pull/114

**Comment by Elena-Evsa** [comment]
Still can reproduce 
![image](https://user-images.githubusercontent.com/84388061/129865971-0c59c657-2739-4a98-964b-ee48b76b8aa6.png)
