### ISSUE TITLE
Mobile: Word 'Price' is moving in the last column in Compare list when user is scrolling right on tablet

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3011]
**Description**:
Mobile: Word 'Price' is moving in the last column in Compare list when the user is scrolling right on tablet. Environments: 
- Huawei MediaPad M5 lite 10
- Iphone XS

**Expected behavior**:
Word 'Price' should stay at the beginning of the last column as 'SKU', 'Description' etc. in Compare list when user scrolling right on tablet

**Screenshots, Video, Logs**

https://user-images.githubusercontent.com/82165392/127140993-1502c398-1f8c-4083-8a67-beaebf9cc22c.MP4

**To Reproduce**:
1. Open Home page on Tablet
2. Add two products to Compare list
3. Open Compare list
4. Scroll to right
5. Observe name of field 'Price'

**Actual result**:
Word 'Price' is moving in the last column in Compare list when user scrolling right on tablet

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
