### ISSUE TITLE
Ooops page when opening downloadable product

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3015]
**Description**:
Ooops page when refreshing downloadable product

**Expected behavior**:
No errors

**To Reproduce**:
1. Open downloadable product
2. Refresh page

**Actual result**:
Ooops page
![Screenshot 2021-07-27 at 14 00 37](https://user-images.githubusercontent.com/73526235/127143853-40d41b7b-faac-4cb1-ab23-52cf5ace3f69.png)

**Comment by carinadues** [comment]
Opened and reloaded 9 out of 10 products in [this search result](https://5-0-0-rc.d25kd40decjpue.amplifyapp.com/default/search/downloadable) successfully. 

This product won't open: https://5-0-0-rc.d25kd40decjpue.amplifyapp.com/default/downloadable-product-1.html

Created a separate issue for it: https://github.com/scandipwa/scandipwa/issues/3019

**Comment by aleksandrakorolova** [comment]
@carinadues We have task for this issue #2847  It happens if Downloadable product has separate links and customization options
