### ISSUE TITLE
In Bundle Product's the assigned product name is null

### ISSUE THREAD

**Issue by sandy6666** [scandipwa/scandipwa#3022]
**Description**:
In the Bundle Product, Graphql in the bundle_options object in the selection_details product name is null

**Expected behavior**:
The assigned Product Name should come.

**Screenshots, Video, Logs**
![Screenshot from 2021-07-28 11-21-01](https://user-images.githubusercontent.com/42976993/127270918-906d24bc-12bb-4bfe-9ab2-ab36a6abdc26.png)
![Screenshot from  (1)](https://user-images.githubusercontent.com/42976993/127270930-ffd5cead-7f5d-48c8-a357-fff007b34216.png)

**To Reproduce**:
1. Go to any Graphql Client
2. Perform a product query for a bundle product 
3. add all of these options

```
bundle_options{
        option_id
        selection_details{
          final_option_price
          selection_id
          name
          regular_option_price
          regular_option_price_excl_tax
          final_option_price_excl_tax
        }
      }
```

**Comment by sandy6666** [comment]
I'm working on this issue

**Comment by sandy6666** [comment]
#https://github.com/scandipwa/catalog-graphql/pull/112

**Comment by aleksandrakorolova** [comment]
Still, product name is missing in graphql
![Screenshot 2021-08-04 at 09 45 33](https://user-images.githubusercontent.com/73526235/128149826-edc49402-8006-47df-8094-19d899b2d0b2.png)

**Comment by sandy6666** [comment]
The name has not been added in the js file can you please check that. From graphql perspective it is working fine

**Comment by zans-laksa** [comment]
Checked the API, everything is fine.
![image](https://user-images.githubusercontent.com/73945186/128309575-80d73d7a-6f5c-4f2a-85a4-ca32c9db0957.png)
