### ISSUE TITLE
Can't change qty for bundle product in cart/mini cart

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3023]
**Description**:
Can't change qty for bundle product in cart/mini cart

**Expected behavior**:
Product qty is changed

**To Reproduce**:
1. Open bundle product
2. Add to cart
3. Open Cart/mini-cart
4. Change qty for bundle product

**Actual result**:
Error message 'Provided quantity exceeds stock limits' appears
![Screenshot 2021-07-28 at 09 08 04](https://user-images.githubusercontent.com/73526235/127272745-77487e3e-f0db-4190-8332-be135ec45eb2.png)

**Notes:**
Can change qty for other types of products

**Comment by riha112** [comment]
PR: 
* https://github.com/scandipwa/quote-graphql/pull/80
