### ISSUE TITLE
Field CMS page is required when selecting Category in URL type field for menu manager in Admin Panel

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3024]
**Description**:
Field CMS page is required when selecting Category in URL type field for menu manager in Admin Panel

**Expected behavior**:
Field CMS page appears when selecting CMS page in URL type

**To Reproduce**:
1. Open Admin panel -> Scandiweb -> Menu manager -> Open menu -> Assigned menu items
2. Click on Add new item 

**Actual result:**:
Field CMS page is displayed and it's mandatory
![Screenshot 2021-07-28 at 09 22 36](https://user-images.githubusercontent.com/73526235/127277484-48c378f7-aba0-4fbe-ac14-3671d7ea9717.png)

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/menu-organizer/pull/24
