### ISSUE TITLE
Image is missing when opening PDP

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3054]
**Description**:
Image is missing when opening PDP

**Expected behavior**:
Image is displayed

**To Reproduce**:
1. Open PDP 

**Actual result**: 
Image is missing
Image appears when refreshing page
https://drive.google.com/file/d/1Q5dOmjLjmTYsdsis0iukV_1F3y8p9Jkk/view?usp=sharing

**Additional context**:
If user opens another image - it's missing too

**Comment by riha112** [comment]
Chunk issue, same with Logo

**Comment by aleksandrakorolova** [comment]
Also, images are missing in cart
![Screenshot 2021-08-04 at 13 31 03](https://user-images.githubusercontent.com/73526235/128166525-d56bc4e4-df33-47f0-90fd-b774bd13abc4.png)

**Comment by aleksandrakorolova** [comment]
Created separate tasks #3089, #3088
