### ISSUE TITLE
Names of fields and placeholders absent in 'Write a review' form

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3055]
**Description**:
Names of fields and placeholders absent in 'Write a review' form

**Expected behavior**:
Names of fields and placeholders present in 'Write a review' form

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/128174750-7979aa80-2d18-4d46-b748-7bc30ce904e7.png)

**To Reproduce**:
1. Open any PDP
2. Click Reviews > Write a review

**Actual result**:
Names of fields and placeholders absent in 'Write a review' form

**Comment by aleksandrakorolova** [comment]
The same situation with Sign is, create new account, forgot password, change my password form and etc
![Screenshot 2021-08-04 at 15 06 22](https://user-images.githubusercontent.com/73526235/128177904-a24ebffe-b47e-4b76-8d17-2fadbf6bcc0b.png)
