### ISSUE TITLE
'Finger' cursor appears if user hovers on sign of share and cart in empty Wishlist

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3061]
**Description**:
'Finger' cursor appears if user hovers on sign of share and cart in empty Wishlist

**Expected behavior**:
Red crossed circle cursor appears if user hovers on sign of share and cart in empty Wishlist

**Screenshots, Video, Logs**
https://vimeo.com/582955863/d6152b4d34

**To Reproduce**:
1. Log in
2. Click on Account > My wishlist 
3. Hover on Share sign and Cart sign
Wish list should be empty

**Actual result**:
'Finger' cursor appears if user hovers on sign of share and cart in empty Wishlist

**Comment by aleksandrakorolova** [comment]
Created separate task #3080
