### ISSUE TITLE
iOS: Page zooms in when tapping field

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3073]
**Description**:
iOS: Page zooms in when tapping field

**Expected behavior**:
Page doesn't zoom in 

**To Reproduce**:
1. Open FE
2. Tap field

**Actual result**:
Page zooms in
https://drive.google.com/file/d/1xyuLM9UAtzWJP4F3Bim5YJP8Wg1cihIp/view?usp=sharing

**Additional context**:
iOS

**Comment by tatiana-scandi** [comment]
Please, check on http://scandipwapmrev.indvp.com/  (not amplify branch) after code is merged and deployed there.
