### ISSUE TITLE
Can't open not default store

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3094]
**Description**:
Can't open NOT default store

**Expected behavior**:
Correct store opens

**To Reproduce**:
1. Open NOT default store
http://scandipwapmrev.indvp.com/scandi/
http://scandipwapmrev.indvp.com/test/
http://scandipwapmrev.indvp.com/en/

**Actual result**:
404 page because it thinks it's default store and /scandi, /test and /en are not found pages 
![Screenshot 2021-08-09 at 16 15 41](https://user-images.githubusercontent.com/73526235/128712200-b1597d28-cd66-4774-b02d-8ea5fcae10c7.png)

**Comment by carinadues** [comment]
Fixed in #3097
