### ISSUE TITLE
Old accounts can't log in system

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3099]
**Description**:
Old accounts can't log in system

**Expected behavior**:
User logged in

**To Reproduce**:
1. Open FE
2. Try to log in with old account 

**Actual result:**:
Error message 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.' appears

**Accounts**:
ddd@gmail.com / Scandipwa123
aleksandra.korolova@scandiweb.com / Scandipwa123
Pp@pp.pp / Scandipwa123
qwerty@aa.aa / Scandipwa123

**Notes:**
Accounts are NOT blocked
Did reset passwords - the same problem

**Comment by zans-laksa** [comment]
@AleksandrsKondratjevs this might be related to the issue you told me when between some versions magento changed the way to encrypt and validate passwords?

**Comment by AleksandrsKondratjevs** [comment]
@zans-laksa if there was successful attempt to reset password and it didn't helped, then problem not in password encrypt algorithm that I mentioned earlier.

**Comment by aleksandrakorolova** [comment]
Closed task because can't reproduce
