### ISSUE TITLE
Product page broken due to max graphql query complexity being more than 1000

### ISSUE THREAD

**Issue by dhrumil4u360** [scandipwa/scandipwa#3103]
**Description**:
On latest release version, when I visit the product page, it results in 404 page due to graphql query failed.

**Expected behavior**:
I should see product page with product details

**Screenshots, Video, Logs**
https://snipboard.io/jT2J9n.jpg

**To Reproduce**:
1. Go to : Product listing page
2. Click on : Any product
3. See error : 404 page

**Versions**:
- ScandiPWA: @scandipwa/scandipwa@5.0.2
- Any other composer module, you thing could be related : No. This scandi core feature
- Browser version if relevant to the context : Not relevant. Still it's Chrome 92
- OS version if relevant to the context : Not relevant. Still It's Windows 10

**Additional context**:
This is the payload of the query which is being marked as too complex!

https://snipboard.io/9fsc34.jpg

**Comment by sachin000** [comment]
Facing same issue with new version , its on mission critical product details page.

**Comment by LifeAsBook** [comment]
the same with you

**Comment by LifeAsBook** [comment]
message: "Max query complexity should be 1000 but got 1040."

**Comment by dhrumil4u360** [comment]
This is looks like more of related to `scandipwa/catalog-graphql`

**Comment by LifeAsBook** [comment]
https://luma-demo.scandipwa.com/graphql?hash=1198044144&filter_1={"sku":{"eq":"24-MB02"},"customer_group_id":{"eq":"0"}}&pageSize_1=20&currentPage_1=1&_currency=""

Why is the demo good？

**Comment by dhrumil4u360** [comment]
We can't say for sure about demo until we know the version of scandi Magento packages there. Like I mentioned issue seems to be coming from one of the scandi Magento package actually.

**Comment by LifeAsBook** [comment]
> This is looks like more of related to `scandipwa/catalog-graphql`

no

**Comment by dhrumil4u360** [comment]
> > This is looks like more of related to `scandipwa/catalog-graphql`
> 
> no

What do you think then ? Previous version and the latest version  is sending same query to graphql. Now in previous version graphql response was successful and in this version graphql response is error!

**Comment by LifeAsBook** [comment]
> > > This is looks like more of related to `scandipwa/catalog-graphql`
> > 
> > 
> > no
> 
> What do you think then ? Previous version and the latest version is sending same query to graphql. Now in previous version graphql response was successful and in this version graphql response is error!


no

> > > This is looks like more of related to `scandipwa/catalog-graphql`
> > 
> > 
> > no
> 
> What do you think then ? Previous version and the latest version is sending same query to graphql. Now in previous version graphql response was successful and in this version graphql response is error!

I use scandipwa@4.5.1 with the latest version scandipwa/catalog-graphql  is working

**Comment by AleksandrsKondratjevs** [comment]
@dhrumil4u360 Hello!

Try to increase Max query complexity value to fit your needs.

Better to make it by extending scandipwa/catalog-graphql module and writing in di.xml file:

```xml
<type name="Magento\Framework\GraphQl\Query\QueryComplexityLimiter">
    <arguments>
        <argument name="queryComplexity" xsi:type="number">VALUE</argument>
    </arguments>
</type>
```
Let us know if this won't help you.

**Comment by LifeAsBook** [comment]
> @dhrumil4u360 Hello!
> 
> In next versions we will optimize queries so we won't need to increase limits.
> 
> Only for now try to increase Max query complexity value to fit your needs.
> 
> Better to make it by extending scandipwa/catalog-graphql module and writing in di.xml file:
> 
> ```
> <type name="Magento\Framework\GraphQl\Query\QueryComplexityLimiter">
>     <arguments>
>         <argument name="queryComplexity" xsi:type="number">VALUE</argument>
>     </arguments>
> </type>
> ```
> 
> Let us know if this won't help you.

Yes,need to optimize query speed
