### ISSUE TITLE
Remove Scrollbar From CMS Widgets

### ISSUE THREAD

**Issue by zans-laksa** [scandipwa/scandipwa#3108]
Plrase investigate why a scrollbar appeared in CMS widgets and remove it if it's not necessary.

![image](https://user-images.githubusercontent.com/73945186/129202079-f5be6bb1-fde0-489b-91d3-e343b691a781.png)
![image](https://user-images.githubusercontent.com/73945186/129202097-c59dac82-ea4a-4fbb-abcd-c79d7762d378.png)

**Comment by tatiana-scandi** [comment]
Please, check no odd scrolls appear on Windows and(or) Linux for the following cases:
- Cart overlay vertical scroll
- Popup vertical scroll
- Search overlay vertical scroll
- Field select (dropdown with options)
- Widget on cms page (case on screenshot)
- Any Table
- MyAccount Overlay vertical scroll

**Comment by Elena-Evsa** [comment]
Task #2640 can be closed with this issue
