### ISSUE TITLE
Placeholder is displayed instead price in compare list if product assigned to another store

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3114]
**Description**:
Placeholder is displayed instead price in compare list if product assigned to another store

**Expected behavior**:
Price is displayed

**To Reproduce**:
**Admin panel:**
1. Open Admin panel -> Stores -> Stocks -> Open Not default stock
2. Assign Main website to this stock -> assign store but NOT default store
3. Save
4. Clear cache

**FE:**
1. Open product with assign to default store
2. Add product to compare list
3. Open compare list

**Actual result:**:
Placeholder is displayed instead price
![Screenshot 2021-08-13 at 08 03 59](https://user-images.githubusercontent.com/73526235/129308224-581f7d9e-6560-47a4-b8f8-9c3b1fc4464b.png)

**Notes:**
The same situation with PDP
![Screenshot 2021-09-06 at 11 09 32](https://user-images.githubusercontent.com/73526235/132183029-d0d42b81-48a6-4ad2-8881-5469b8c6804f.png)

**Comment by Elena-Evsa** [comment]
Can not reproduce 
![image](https://user-images.githubusercontent.com/84388061/187914190-d9672bad-1900-4fbc-b4af-3bae5dbb5973.png)
