### ISSUE TITLE
Old price is displayed in compare list for product on which catalog product rule applies

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3115]
**Description**:
Old price is displayed in compare list for product on which catalog product rule applies

**Expected behavior**:
Price with discount is displayed
![Screenshot 2021-08-13 at 08 36 08](https://user-images.githubusercontent.com/73526235/129310378-70ecbea7-7787-4893-b3e8-c01885924e7a.png)

**To Reproduce**:
1. Open FE
2. Log in 
3. Open product on which catalog price rule applies - https://master.d25kd40decjpue.amplifyapp.com/default/travel-bag-1.html
4. Add to compare list
5. Open compare list

**Actual result: **:
Old price is displayed
![Screenshot 2021-08-13 at 08 36 01](https://user-images.githubusercontent.com/73526235/129310362-a55d9f60-768a-4401-b742-acf17900e602.png)

**Comment by Elena-Evsa** [comment]
Catalog price rule shown in Compare 
![image](https://user-images.githubusercontent.com/84388061/187916304-1a5270e2-90d0-4905-b17c-1fcb4425939a.png)
