### ISSUE TITLE
Check mark is missing for selected checkbox options for product with customization options

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3117]
**Description**:
Check mark is missing for selected checkbox options for product with customization options

**Expected behavior**:
Check mark is displayed for selected option
![Screenshot 2021-08-13 at 09 07 07](https://user-images.githubusercontent.com/73526235/129312483-58bbb500-98a1-4e65-a340-4e865a044a9d.png)

**To Reproduce**:
1. Open Product with customization options (option type is checkbox) - https://master.d25kd40decjpue.amplifyapp.com/default/kids/28-virtual-product.html
2. Select some notion in checkbox

**Actual result**:
Check mark is missing
![Screenshot 2021-08-13 at 09 07 29](https://user-images.githubusercontent.com/73526235/129312525-7a1fc5e6-1a57-4fa5-92d5-7ee535e3f5c0.png)

**Additional content**
Same with checkbox near General Subscription in My account

**Comment by riha112** [comment]
If it helps issue is due to this line: https://github.com/scandipwa/scandipwa/blob/478840a4f05d8461b01991f0adf66c809d909a96/packages/scandipwa/src/component/Field/Field.container.js#L239
