### ISSUE TITLE
'Product is out of stock' is displayed for product in cart when adding product with all selected customization options (checkbox)

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3118]
**Description**:
'Product is out of stock' is displayed for product in cart when adding it with all selected customization options.

**Expected behavior**:
To show no 'Product is out of stock' is missing if the product is in stock.

**To Reproduce**:
1. Open product with customizable option (option type should be checkbox) - https://master.d25kd40decjpue.amplifyapp.com/default/kids/28-virtual-product.html
2. Select one option - black
3. Add product to cart
4. Open mini-cart
5. Select all options - black and white
6. Add product to cart
7.  Open mini-cart

**Actual result:**:
'Product is out of stock' is displayed for all products
https://drive.google.com/file/d/1Z8QpGPz7PFQaSidARZpkchRjlVCEyw2R/view?usp=sharing

**Obs**:
When you add the same product without all of the checkboxes being marked, the product that was said to be out of stock becomes in stock and shows the quantity in cart.

**Comment by riha112** [comment]
Might be solved by: https://github.com/scandipwa/scandipwa/pull/3179
