### ISSUE TITLE
Currency for old price is not the default display currency for products with customization options on PDP

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3119]
**Description**:
Currency for old price is not the default display currency for products with customization options on PDP

**Expected behavior**:
Currency EUR in this case
![Screenshot 2021-08-13 at 09 53 19](https://user-images.githubusercontent.com/73526235/129317614-a5f8487c-e9a6-4091-9ab3-cb079ac5cad8.png)

**To Reproduce**:
1. Open product with customization option and product has discount - https://master.d25kd40decjpue.amplifyapp.com/default/women/tops/test-category/simple-product-for-test-test.html

**Actual result:**:
Currency for old price is USD but currency for all products EUR 
![Screenshot 2021-08-13 at 09 52 54](https://user-images.githubusercontent.com/73526235/129317633-8c17b4c4-32f3-4d78-bc9b-334ae5973738.png)

**Additional context**:
Only on PDP
Currency is correctly on PLP

**Comment by carinadues** [comment]
Closed after merging https://github.com/scandipwa/scandipwa/pull/3236
