### ISSUE TITLE
Parent resolver is returning an empty wishlist model

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#3134]
**Description**:

https://puu.sh/I4wqa/ac5d0e11d5.png
this is on luma-demo

to reproduce - log in as customer that has no wishlist in DB
cause - ScandiPWA\WishlistGraphQl\Model\Resolver\Wishlist\CreatorResolver runs this:
<code>
 if (!$wishlist) {
    return null;
}

$customerId = $wishlist->getCustomerId();
/** @var CustomerInterface $customer */
$customer = $this->customerRepository->getById($customerId); 
</code>

if wishlist wasn't found by id/customer didn't have a wishlist, the parent resolver is returning an empty wishlist model. it still passes the if condition, then throws an exception on getById call, as $customerId is null. 

Simply running if (!$wishlist || !$wishlist->getCustomerId()) will do it

**Comment by Elena-Evsa** [comment]
Wish list is empty if user added product to it
mutation($wishlistId_1:ID!,$wishlistItems_1:[WishlistItemInput!]!){addProductsToWishlist(wishlistId:$wishlistId_1,wishlistItems:$wishlistItems_1){user_errors{message,code}}}
https://vimeo.com/616773475/9ec779321f

**Comment by tatiana-scandi** [comment]
@Elena-Evsa this issue will be fixed by https://github.com/scandipwa/scandipwa/pull/3417 (it has linked PR with fix for `wishlist-graphl` module).

**Comment by carinadues** [comment]
Closing again since #3417 is merged.
