### ISSUE TITLE
Mobile: Delete product by swiping left

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#3142]
**Description**:
Please, add some buffer space between the `X and price texts` and the `Delete` in the wishlist and cart so it isn’t glued when you swipe left to delete. 

**Actual behavior in wishlist**:

https://user-images.githubusercontent.com/82165392/129779196-34c5f82e-dc37-4ac3-b176-e47827ce4f79.mov

**Actual behavior in cart**:

https://user-images.githubusercontent.com/82165392/129779210-d3639e57-1aa3-4e44-9208-7ba2b0595082.mov

**To Reproduce**:
1. Open the site on mobile https://master.d25kd40decjpue.amplifyapp.com
2. Log in to your account
3. Open the wishlist with some products added
4. Swipe left to delete the product 
5. Check out how the price, X, as low as and price excluding tax are glued to the "Delete" in red.
6. Open the cart with some products added
7. Swipe left to remove and see the same issue.

**Versions**:
- ScandiPWA: 5.0.2

**Comment by aleksandrakorolova** [comment]
Created separate task - #3200
