### ISSUE TITLE
NaN is displayed instead of max range in price filter on PLP if Price Navigation Step Calculation is set to Automatic (equalize product counts)

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3157]
**Description**:
NaN is displayed instead of max range in price filter on PLP if Price Navigation Step Calculation is set to Automatic (equalize product counts)

**Expected behavior**:
no NaN. Price is displayed in xx.xx format (for example 14.99)

**To Reproduce**:
1. Open Admin panel -> Stores -> Configuration -> Catalog -> Catalog 
2. Open Layered navigation block
3. Set Automatic (equalize product counts) to Price Navigation Step Calculation
4. Save
5. Clear Cache
6. Open PLP

**Actual result**:
Some price max range is NaN if it is received in xx.xx.x format (14.99.6)![Screenshot 2021-08-19 at 13 57 27](https://user-images.githubusercontent.com/73526235/130062003-19d2a3ac-6c65-4b52-b30c-448de83d3b5b.png)

**Additional context**:

**Comment by Elena-Evsa** [comment]
Found related issue #3385 
But NaN fixed
