### ISSUE TITLE
Never disappearing loader instead of price for specific product on PLP

### ISSUE THREAD

**Issue by tatiana-scandi** [scandipwa/scandipwa#3158]
1. Open product https://scandipwapmrev.indvp.com/default/accessories/accessories-bags/bundle-bug-with-dynamic-price.html
2. Open corresponding category via breadcrumbs (or via direct link https://scandipwapmrev.indvp.com/default/accessories/accessories-bags.html)

**Result:** constantly blinking gray rectangle loader in place of price:
<img width="1393" alt="Bags 2021-08-19 18-11-29" src="https://user-images.githubusercontent.com/79456428/130113727-995d52ee-e067-415c-9113-6145314068ed.png">

**Comment by tatiana-scandi** [comment]
Doesn't reproduce for me any more: 
![image](https://user-images.githubusercontent.com/79456428/130630057-aa72756d-aa23-452f-ac32-f4939b880893.png)

**Comment by Elena-Evsa** [comment]
If user select option 0$ cost, price is not appear
example of product https://master.d25kd40decjpue.amplifyapp.com/default/women/women-shoes/sandals/downloadable-sandals.html

**Comment by aleksandrakorolova** [comment]
Closed task because can't reproduce
For issue products that cost zero is created separate task #4747
