### ISSUE TITLE
Blank pop-up when opening product image on full-screen

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3159]
**Description**:
Blank pop-up when opening product image on full-screen

**Expected behavior**:
image opens on full-screen

**To Reproduce**:
1. Open product with images
2. Open image on full-screen

**Actual result**:
Blank pop-up opens
![Screenshot 2021-08-20 at 07 57 19](https://user-images.githubusercontent.com/73526235/130181385-3b00ae49-50d4-48d8-9430-4627cc9adc6e.png)

**Additional context**:
if product has more than one image than small images are displayed in pop-up
![Screenshot 2021-08-20 at 07 57 01](https://user-images.githubusercontent.com/73526235/130181390-604c7c3a-0918-4568-b3b8-0e0f8c1cc4e5.png)

**Comment by Elena-Evsa** [comment]
Popup is shown fully now
But image is shown only after user hover cursor in space for image
https://vimeo.com/591567538/c341197c18
