### ISSUE TITLE
Arrow back near the search field is shifted up when click on the search field

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3169]
**Description**:
Arrow back near the search field is shifted up when click on the search field

**Expected behavior**:
Arrow is aligned by the center to the placeholder 'Search products' when click on the search field

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/130424558-23ebba59-495c-46c8-ba3f-85c789490080.png)

**To Reproduce**:
1. Open Home page on mobile
2. Tap on Menu sign > Search field
3. Observe the position of arrow

**Actual result**:
Arrow near the search field is shifted up when click on the search field

**Additional context**:

**Comment by tatiana-scandi** [comment]
Will be fixed by https://github.com/scandipwa/scandipwa/issues/3140
