### ISSUE TITLE
For all bundle products 'In stock' message 'Please, remove out of stock products from cart' appears in cart 

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3177]
**Description**:
For all bundle products 'In stock' message 'Please, remove out of stock products from cart' appears in cart 
If user click on step#4 on Mini cart > Secure Checkout, then Checkout step shown.

**Expected behavior**:
User can go to checkout from cart with bundle products 'In stock' 

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/130458094-4f087863-783f-4a41-a9e5-d251372165ad.png)

**To Reproduce**:
1. Open Home page
2. Add to cart any bundle product with any options, for example https://master.d25kd40decjpue.amplifyapp.com/default/women/women-shoes/sandals/bundle-sandals-with-fixed-prices.html
3. Click on Mini cart > View cart
4. Observe message 'Please, remove out of stock products from cart' and Checkout button absent

**Actual result**:
For all bundle products 'In stock' message 'Please, remove out of stock products from cart' appears in cart

**Comment by carinadues** [comment]
Message 'Please, remove out of stock products from cart' doesn't appear in cart anymore.

![image](https://user-images.githubusercontent.com/82165392/130813629-81d1db15-906c-4921-9fdc-a3b3f686f095.png)

![image](https://user-images.githubusercontent.com/82165392/130813678-d698e893-0305-418c-8e67-d4f441b04e5c.png)
