### ISSUE TITLE
User can not add to wish list configurable product which is 'out of stock' without choosing of options

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3207]
**Description**:
User can not add to wish list configurable product which is 'out of stock' without choosing of options

**Expected behavior**:
User can add to wish list configurable product which is 'out of stock' without choosing of options

**Screenshots, Video, Logs**
https://vimeo.com/592644800/b844c3a9cf

**To Reproduce**:
1. Open home page
2. Log in
3. Open any configurable product (for example, https://master.d25kd40decjpue.amplifyapp.com/default/accessories/accessories-bags/baggini-bagpack-108.html)
4. If product in stock, change it's status on 'Out of stock' in Admin and refresh page on FE
5. Click on heart sign

**Actual result**:
User can not add to wish list configurable product which is 'out of stock' without choosing of options

**Additional context**:
User can add following types of products to wish list which is 'out of stock' without choosing of options:
- bundle
- grouped 
- with customizable options

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
For grouped product created separate task - #4744
