### ISSUE TITLE
Arrow back is cut near the title on CMS pages on phones with physically rounded screens

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3222]
**Description**:
Arrow back is cut near the title on CMS pages on phones with physically rounded screens
And it is become too small, so it is hard to tap on button
Environment: portrait mode of
Huawei P30 PRO - real device
Samsung Galaxy S8 - browser stack

**Expected behavior**:
Arrow back is shown in full

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/131133412-21eccec4-6bf1-4416-980e-c0c8d889896c.png)

**To Reproduce**:
1. Open https://master.d25kd40decjpue.amplifyapp.com/default/about-us on devices from Environment or other with physically rounded screens

**Actual result**:
Arrow back is cut near the title on CMS pages

**Comment by pablobentivengo** [comment]
Hey! I think it is already fixed. 
Tried to reproduce on:
Samsung Galaxy s10 - real device
Samsung Galaxy s8 - browserstack
Huaweii P30 PRO - browserstack
