### ISSUE TITLE
Safari: RTL: Bracket is displayed in wrong place in Wishlist 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3228]
**Description**:
Safari: RTL: Bracket **(** is displayed in wrong place in Wishlist 

**Expected behavior**:
'My wishlist (6)'
![Screenshot 2021-08-27 at 16 47 07](https://user-images.githubusercontent.com/73526235/131294510-9f634b48-b8da-4a9e-8db5-9eea35e62c24.png)

**To Reproduce**:
**Admin panel**
1. Open Admin panel -> Stores -> Configuration -> ScandiPWA -> Layout direction
2. Set Layout Direction to RTL
3. Save
4. Clear cache

**FE:**
1. Open FE
2. Log in
3. Open Wishlist

**Actual result:**:
Bracket **(** is displayed in wrong place '(My wishlist (6'
![Screenshot 2021-08-27 at 16 46 31](https://user-images.githubusercontent.com/73526235/131294871-0b25cd7f-7ef5-4e9a-b0d4-29e03479b706.png)

**Additional context**:
Safari

**Comment by EriSilver** [comment]
The behaviour is not buggy - Browsers just behave differently
And here you can find the actual behaviors with an rtl language:
Safari:
![safari-ios-english (2)](https://user-images.githubusercontent.com/13037254/159702023-6b8edb2d-4130-4cd2-a64d-d358519cae21.PNG)
![safari-ios-arabic](https://user-images.githubusercontent.com/13037254/159702008-c6e886d5-7623-4a63-8bf1-930f1e5d8cda.PNG)

Chrome
![chrome-english](https://user-images.githubusercontent.com/13037254/159702015-19d132e5-07ac-4cb4-bd81-4b0702eac0e6.PNG)
![chrome-arabic](https://user-images.githubusercontent.com/13037254/159702019-fe6a1111-924d-4bab-8b14-51c4feffabab.PNG)
