### ISSUE TITLE
Newsletter Subscription disappears from My account if user twice refreshed page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3233]
**Description**:
Newsletter Subscription disappears from My account if user twice refreshed page

**Expected behavior**:
Newsletter Subscription is displayed

**To Reproduce**:
1. Open FE
2. Log in
3. Open My account 
4. Refresh page
5. Repeat 4 step

**Actual result:**:
Newsletter Subscription disappears from My account
https://drive.google.com/file/d/1zEvhgOTA6qu_78bpEd4T3Gmz6yoHMXLM/view?usp=sharing

**Comment by carinadues** [comment]
Tested here and if I refresh just once it already disappears. Also, when you click on one of the tabs (such as My Orders, Dashboard etc), the "Newsletter Subscription" tab reappears.

**Comment by aleksandrakorolova** [comment]
Created separate task for found issue #3296
