### ISSUE TITLE
Mobile: Checkbox compressed and price shifted if option has long name on PDP

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3234]
**Description**:
Mobile: Checkbox compressed and price shifted if option has long name on PDP

**Expected behavior**:
Checkbox isn't compressed and price isn't shifted

**To Reproduce**:
1. Open bundle product - https://scandipwapmrev.indvp.com/default/tech/bundle.html

**Actual result**:
Checkbox compressed and price shifted
![image](https://user-images.githubusercontent.com/82165392/131334322-6ffaadf7-3de8-4b85-a864-d7704be0fc60.png)

**Additional context**:

**Comment by Elena-Evsa** [comment]
Can not reproduce
