### ISSUE TITLE
Checkmark is missing for selected checkbox near 'Subscribe to newsletter' in create account form

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3237]
**Description**:
Checkmark is missing for selected checkbox near 'Subscribe to newsletter' in create account form

**Expected behavior**:
Checkmark is present for selected checkbox near 'Subscribe to newsletter' in create account form

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/131309448-9b54512d-2c2f-4023-bbb2-b4f0ff62e489.png)

**To Reproduce**:
1. Open home page
2. Click on Account sign > Create account
3. Click on 'Subscribe to newsletter' checkbox

**Versions**:
Checkmark is missing for selected checkbox near 'Subscribe to newsletter' in create account form

**Comment by aleksandrakorolova** [comment]
Created separate task for found issue #3298
