### ISSUE TITLE
FF: Buttons text 'View cart' and 'Secure checkout' are shifted up in mini-cart

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3239]
**Description**:
FF: Buttons text 'View cart' and 'Secure checkout' are shifted up in mini-cart

**Expected behavior**:
Text is aligned

**To Reproduce**:
1. Open PDP
2. Add product to cart
3. Open mini-cart

**Actual result:**:
Buttons text 'View cart' and 'Secure checkout' are shifted up 
![Screenshot 2021-08-30 at 17 47 00](https://user-images.githubusercontent.com/73526235/131358500-bd0feb7e-9811-414c-8cd2-82c58ffeb2aa.png)

**Comment by Elena-Evsa** [comment]
Can not reproduce 
![image](https://user-images.githubusercontent.com/84388061/188087414-da6715f3-09f1-42f9-b6e2-101a7a1a9ca5.png)
