### ISSUE TITLE
User can't logged in if he/she didn't confirm account but reseted password

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3243]
**Description**:
User can't logged in if he/she didn't confirm account but reseted password

**Expected behavior**:
User logged in as in default Magenta

**To Reproduce**:
**Admin panel:**
1. Open Admin panel -> Stores -> Configuration -> Customers -> Customer configuration
2. Set Yes to Require Emails Confirmation
3. Save
4. Clear cache

**FE**
1. Open FE
2. Create an account (do NOT confirm account)
3. Open forgot password form
4. Enter this email
5. Open Email -> Open reset password link
6. Reset password
7. Open Sign in form
8. Log in

**Actual result**:
Error message 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.' appears

**Comment by aleksandrakorolova** [comment]
Internal server error appears when resetting password
<img width="854" alt="Screenshot 2022-07-12 at 14 29 49" src="https://user-images.githubusercontent.com/73526235/178480300-ada8f44b-f6d3-4c3c-97aa-0437687cc683.png">
**debugMessage:** "Type Error occurred when creating object: ScandiPWA\\CustomerGraphQl\\Model\\Resolver\\ResetPassword\\Interceptor, Typed property ScandiPWA\\CustomerGraphQl\\Model\\Resolver\\ResetPassword::$confirmByToken must be an instance of Magento\\Customer\\Model\\ForgotPasswordToken\\ConfirmCustomerByToken, null used"

**Logs:**
[2022-07-12T10:40:02.174209+00:00] main.CRITICAL: Type Error occurred when creating object: ScandiPWA\CustomerGraphQl\Model\Resolver\ResetPassword\Interceptor, Typed property ScandiPWA\CustomerGraphQl\Model\Resolver\ResetPassword::$confirmByToken must be an instance of Magento\Customer\Model\ForgotPasswordToken\ConfirmCustomerByToken, null used [] []

**Comment by aleksandrakorolova** [comment]
Error message 'Your password reset link has expired.' appears
![Screenshot 2022-07-18 at 15 34 43 (2)](https://user-images.githubusercontent.com/73526235/179512285-702b486a-c4f2-4f80-814b-436831a7f411.png)

**Comment by IrinaZhadzinets** [comment]
Work on the task was carried out with magento 2.4.3, but magneto 2.4.4 does not support getting a customer by token, which is why it is necessary to change the function used (PR scandipwa/customer-graph-ql#40)
