### ISSUE TITLE
Navigate back button doesn't navigate back after closing popup via cross

### ISSUE THREAD

**Issue by tatiana-scandi** [scandipwa/scandipwa#3248]
1. Open PLP 
2. Click on product icon to open PDP
2. Click on image to open zoomed popup
3. Click on cross in top right corner of popup
4. Click back button in browser

Result: No action
Expected result: User is again on PLP

Same problem for all other popups (e.g. Edit addresses in MyAccount)

**Comment by aleksandrakorolova** [comment]
Created separate task for the found issue - #3350
