### ISSUE TITLE
Notice for Internet Explorer browser

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#3265]
**Description**:

Please create a notice for Internet Explorer browser to inform customers that they need to use some other browser, because PWA is not supported there.

**Steps to reproduce**:

Open http://scandipwapmrev.indvp.com/ in your Internet Explorer Browser.

**Current result**:

![image](https://user-images.githubusercontent.com/82165392/131897270-d8228256-7c3d-4ea6-94ea-a16541b5fe6a.png)

**Suggestion**:

Gather, for example, isn't supported in Opera, so when you try to open it, you get this page:

![image](https://user-images.githubusercontent.com/82165392/131897467-5f61f736-dad7-4996-aabd-40e6358ff1b2.png)

**Comment by pablobentivengo** [comment]
Hey! was checking this issue and saw that IE will stop working on June.

As I read Edge supports PWA

![image](https://user-images.githubusercontent.com/97158749/157270050-c5c7e69f-40ec-45a8-ac7a-3d25b1fa7a88.png)

**Comment by carinadues** [comment]
Closing since IE will stop working on June.
