### ISSUE TITLE
Internal server error appears when adding or editing address in my account

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3268]
**Description**:
Internal server error appears when adding or editing address in my account, (When second street is empty)

**Expected behavior**:
No errors. Address is saved

**To Reproduce**:
1. Log in
2. Open My account -> Address book
3. Add me address or Edit address
4. Fill form
5. Click on Save address

**Actual result**:
Internal server error
![Screenshot 2021-09-03 at 09 02 19](https://user-images.githubusercontent.com/73526235/131958108-99a2b0ab-9bcd-459b-a375-a6dbe3643f70.png)

**Additional context**:
debugMessage: "Notice: Array to string conversion in /var/www/public/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3170"

**Comment by riha112** [comment]
Same issue in checkout
