### ISSUE TITLE
Internal server error appears when changing qty for product with customizable options in cart

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3269]
**Description**:
Internal server error appears when changing qty for product with customizable options in cart

**Expected behavior**:
No errors. QTY is changed

**To Reproduce**:
1. Open product with customization options
2. Select options
3. Add to cart
4. Open cart or mini-cart
5. Change qty

**Actual result**:
Internal server error appears
![Screenshot 2021-09-03 at 09 32 20](https://user-images.githubusercontent.com/73526235/131960927-f7712891-c860-4d0e-9435-67bf3bb21723.png)

**Additional context**:
debugMessage: "Following products with requested skus were not found: Simple book--"

**Products:**
http://scandipwapmrev.indvp.com/default/tech/simple-book.html
http://scandipwapmrev.indvp.com/default/women/tops/test-category/testing-simple.html

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/quote-graphql/pull/83
