### ISSUE TITLE
Horizontal scroll bar on the compare page

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#3283]
**Description**:
Please add a horizontal scroll bar in the compare page on the top of the products, so that the user can understand that it is scrollable. Align it with the first div ProductCompareItem until the end of the page but leaving the same margin that is left for the last visible product (so it looks good on smaller screens too). Also, please remove the scroll bar at the end.

**Image**:
![image](https://user-images.githubusercontent.com/82165392/132054662-ba74da44-11c1-4412-8d72-3d10bd7994a5.png)

**Comment by Elena-Evsa** [comment]
Issue 1: horizontal scroll bar absent on Mac Safari 15 and iPhone 11 Pro v15.0 Safari/Chrome
![image](https://user-images.githubusercontent.com/84388061/147115238-9e5056d9-5ad8-41bb-b15d-3ee780aaf709.png)
