### ISSUE TITLE
Loader icon is shown at the beginning of mini-cart when changing product qty

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3294]
**Description**:
Loader icon is shown at the beginning of mini-cart when changing product qty

**Expected behavior**:
Loader is displayed for product which user is changing
![Screenshot 2021-09-07 at 07 59 29](https://user-images.githubusercontent.com/73526235/132332225-ee1911f7-7460-48d3-b18e-2cf63f1a8696.png)

**To Reproduce**:
1. Open PDP
2. Add product cart
3. Open mini-cart
4. Click on + (change qty)

**Actual result:**:
Loader icon is shown at the beginning of mini-cart
 https://drive.google.com/file/d/1ATgEANXyPvl7b9BY7S61KYPGI-ACybcy/view?usp=sharing

**Additional context**:
Loader is displayed for all products in cart 
Please, fix it also
![Screenshot 2021-09-07 at 08 00 44](https://user-images.githubusercontent.com/73526235/132332261-fe91276b-1c0e-41dc-a985-fb8bc04eb686.png)
Expected: 
![Screenshot 2021-09-07 at 08 00 54](https://user-images.githubusercontent.com/73526235/132332307-9003fb59-f909-4070-9af7-a7d15964fa65.png)

**Comment by Elena-Evsa** [comment]
Same if user delete product from mini cart and mini cart contain more then 2 products
