### ISSUE TITLE
Error message 'Please, select desirable option first!' appears when adding config product to wishlist from PLP if all attributes are selected

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3300]
**Description**:
Error message 'Please, select desirable option first!' appears when adding config product to wishlist from PLP if all attributes are selected

**Expected behavior**:
Product is added to cart if all attributes are selected

**To Reproduce**:
1. Log in
2. Open Kids category
3. Open the second page
4. Find **Straw shoulder bag** product
5. Select color attribute
6. Click on heart (Add to wishlist)

**Actual result**:
Error message 'Please, select desirable option first!' appears
https://drive.google.com/file/d/1Wzcb9e2prt6XSU3yX5zQVxPNWtfObH-0/view?usp=sharing

**Notes:**
Can add config product to Wishlist from PDP if all attributes are selected

**Comment by Elena-Evsa** [comment]
Can not reproduce
