### ISSUE TITLE
Data stays in the create account form after submitting if Require Emails Confirmation is set to yes

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3305]
**Description**:
Data stays in the create account form after submitting if Require Emails Confirmation is set to yes (same on Mobile)
User stay on create account page

**Expected behavior**:
User redirected to sign in page - same on Mobile

**To Reproduce**:
**Admin panel :**
1. Open Admin panel -> Stores -> Configuration -> Customers ->Customer Configuration
2. Set Require Emails Confirmation to yes
3. Save
4. Clear Cache

**FE:**
1. Open create an account page - https://scandipwapmrev.indvp.com/default/account/create
2. Fill form
3. Click on Create an account

**Actual result:**:
All information/data stay in the form

**Comment by pablobentivengo** [comment]
Hey!! I think this one is fixed already.

**Comment by aleksandrakorolova** [comment]
Closed because it was fixed in #4154
