### ISSUE TITLE
Ooops page when opening my account page in incognito mode

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3306]
**Description**:
Ooops page when opening my account page in incognito mode

**Expected behavior**:
No errors
User redirects to https://scandipwapmrev.indvp.com/ddefault/account/login/

**To Reproduce**:
1. Open one of My account pages in incognito mode

**Actual result:**:
Ooops page opens
_Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings._
![Screenshot 2021-09-08 at 11 03 49](https://user-images.githubusercontent.com/73526235/132472024-7f328c41-702a-452b-ba6f-e599895bfd0f.png)

**Notes:**
Errors are missing If user opened the second time or refreshed page

**Comment by Elena-Evsa** [comment]
Now Ooops page does not appear, but URL is wrong 
https://vimeo.com/603823814/2440fb73cb
