### ISSUE TITLE
User redirects to Homepage when logging in from /account/login page if Redirect Customer to Account Dashboard after Logging in is set to yes

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3310]
**Description**:
User redirects to Homepage when logging in from /account/login page if Redirect Customer to Account Dashboard after Logging in is set to yes

**Expected behavior**:
My account page opens

**To Reproduce**:
**Admin panel:**
1. Open Admin panel -> Stores -> Configuration -> Customer -> Customer configuration -> Login Option
2. Set Redirect Customer to Account Dashboard after Logging in to yes
3. Save
4. Clear cache

**FE:**
1. Open /account/login page
2. Log in

**Actual result**:
Homepage opens
https://drive.google.com/file/d/1RplyaW5E6KbCcjdOrxH5jfZ3YkFKOdIN/view?usp=sharing

**Notes**
User redirects to My account page if user logged in sign in form in overlay

**Comment by pablobentivengo** [comment]
Couldn't reproduce on PMREV.

- Overlay Login redirects to account
- LoginPage redirects to account

https://vimeo.com/678782625/a84498713c

**Comment by pablobentivengo** [comment]
Couldn't reproduce on Master.

- Overlay Login redirects to account
- LoginPage redirects to account

https://vimeo.com/678783840/8360a2b5c3

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
