### ISSUE TITLE
No min price is displayed in 'As low as' for config product on PDP and PLP if child of config product has special price

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3313]
**Description**:
No min price is displayed in 'As low as' for config product on PDP and PLP if child of config product has special price

**Expected behavior**:
Min price is displayed (As low as 39.00)
![Screenshot 2021-09-09 at 09 53 00](https://user-images.githubusercontent.com/73526235/132639079-3e1701c0-b7f7-4832-a140-890333a13a00.png)

**To Reproduce**:
**Admin Panel:**
1. Open Admin panel -> Catalog -> Products
2. Open child of config product
3. Click on Advanced Pricing
4. Enter Special price
5. Save

**FE:**
1. Open this product - https://master.d25kd40decjpue.amplifyapp.com/default/faux-leather-jacket.html
2. Open PLP where this product

**Actual result**:
No min price is displayed (As low as 51.99)
![Screenshot 2021-09-09 at 09 53 11](https://user-images.githubusercontent.com/73526235/132639095-25b4a4ce-4c94-4227-bac5-0264da897701.png)

**Additional context**:
The same on PLP

**Comment by Elena-Evsa** [comment]
Min price shown on PLP for product from case: https://vimeo.com/641823427/13f7b648e2
For product https://master.d25kd40decjpue.amplifyapp.com/default/metabo-powermaxx-bs-basic-600080500.html: 
 https://vimeo.com/641823972/36ed6f4b75
