### ISSUE TITLE
Error message 'Unique constraint violation found' appears when changing URL key for category in Admin panel

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3314]
**Description**:
Error message 'Unique constraint violation found' appears when changing URL key for category in Admin panel

**Expected behavior**:
No errors. 
URL key is saved
URL rewrite is created

**To Reproduce**:
1. Open Admin panel -> Catalog -> Categories
2. Open some category (for example summer dresses)
3. Open Search Engine Optimization block
4. Change URL key
5. Click on Save

**Actual result:**:
Error message 'Unique constraint violation found' appears 
![Screenshot 2021-09-08 at 15 19 25](https://user-images.githubusercontent.com/73526235/132648894-df5b4520-bb84-4dd8-94c3-7d21d3de5321.png)

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/catalog-graphql/pull/120
