### ISSUE TITLE
M2.4.3 + SPWA 5.0.4 fail to start right after the installation

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#3318]
**Description**:

There is an issue of M2.4.3 + SPWA 5.0.4 failing to start right after the installation.

As reported by Roy: 
He got the issue when setting up a new CMA 2.4.3. 

**Steps**:

- install CMA & CSA from scratch
- magento se:up
- magento se:di:co
- magento in:rei
- magento c:f
- visit `http://localhost/privacy-policy-cookie-restriction-mode`
- try to do an `Empty cache and Hard Reload` on your browser
- Got 404 page
- Error returned from CMS graphQL: `Missing required argument $variables of ScandiPWA\CmsGraphQl\Model\Template\VirtualFilter`

Then he went to `vendor/scandipwa/cms-graphql/src/etc/graphql/di.xml:11` and added this line `<argument name="variables" xsi:type="array" />`, everything works fine after that.

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/cms-graphql/pull/16
