### ISSUE TITLE
Qty of product changes not correctly in Wishlist:  the previous qty of product returns if double-click on ‘+’ or ‘-’ buttons

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3320]
**Description**:
Qty of product changes not correctly in Wishlist:  the previous qty of product returns if double-click on ‘+’ or ‘-’ buttons

**Expected behavior**:
Add loader icon when changing qty of product => user can't double click on '+' or '-' buttons

**To Reproduce**:
1. Open FE
2. Log in
3. Add product to Wishlist
4. Open wishlist
5. Double click on  '+' or '-' buttons

**Actual result**:
Qty of product changes correctly but then the previous qty of product returns
https://drive.google.com/file/d/1rD6G2DMrHGs8_lwanHGONvFflxWgepEI/view?usp=sharing

**Comment by Elena-Evsa** [comment]
Can not reproduce
