### ISSUE TITLE
Loader instead of breadcrumbs on PDP, if no category assigned to product

### ISSUE THREAD

**Issue by tatiana-scandi** [scandipwa/scandipwa#3330]
**To Reproduce**:
1. Open product without category (e.g. https://scandipwapmrev.indvp.com/default/product-no-category.html): 

**Result:**

Loader instead of breadcrumbs:

![image](https://user-images.githubusercontent.com/79456428/133276606-b903f7a8-d1b9-4dc2-9d2a-9ae7cd0e0189.png)

**Expected result:**

As in Luma - 2 breadcrumbs : `Home` and product name are displayed:

![product no category Scandipwa 2021-09-14 15-30-27](https://user-images.githubusercontent.com/79456428/133276988-ca361666-dd5c-4a3f-b899-34ec6ce10ab0.png)

**Comment by aleksandrakorolova** [comment]
Created separate task for the found issue - #3351
