### ISSUE TITLE
Ooops page when opening bundle product if two products come in graphql but exist only one

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3338]
**Description**:
Ooops page when opening bundle product if two products come in graphql but exist only one

**Expected behavior**:
No errors

**To Reproduce**:
1. Open bundle product - https://master.d25kd40decjpue.amplifyapp.com/accessories/bundle-bug-with-fixed-price.html

**Actual result:**:
Ooops page opens
Error message: TypeError: Cannot read property ‘name’ of null
![Screenshot 2021-09-15 at 15 29 05](https://user-images.githubusercontent.com/73526235/133433791-f0a6b813-c59d-406f-9e1f-a497c322c09c.png)
Two products come in graphQL but exist only one
![Screenshot 2021-09-15 at 15 48 04](https://user-images.githubusercontent.com/73526235/133436284-7ed77c2e-d6d2-4edc-b178-d4b7dc7b3c33.png)

Product in Admin paneL:
![Screenshot 2021-09-15 at 15 45 23](https://user-images.githubusercontent.com/73526235/133436268-d9136abe-4193-44ec-8896-27d9a658d8dc.png)

**Comment by riha112** [comment]
**Problem:**
* Non-visible options contains links to products with customizable options. Magento will not allow such options to exist in bundle products... not sure how they where added as magento outputs error msg when attempting to assign such product
* In short issue in DB.

**How I solved**
* Removed rows from table `catalog_product_bundle_selection`
