### ISSUE TITLE
User doesn't receive emails about price or status changing if user subscribed for notification

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3346]
**Description**:
User doesn't receive emails about price or status changing if user subscribed for notification
 
**Expected behavior**:
User received emails

**To Reproduce**:
**FE:**
1. Log in
2. Open PDP for product X
3. Click on Notify me when the price drops
4. Open out of stock product Y
5. Click on Notify me when this product is in stock

**Admin panel:**
1. Open Admin panel -> Catalog -> Products -> Open product X
2. Change price for product
3. Save
4. Open out of stock product Y
5. Change status to in stock
6. Save

**Email**
1. Wait for 'Product Alert run settings' start time
2. Open Email 

**Actual result**:
No emails

**Notes:**
Tested on pmrev and demo

**Comment by Elena-Evsa** [comment]
Found issue #3365
