### ISSUE TITLE
Breadcrumbs are displayed for the previous category when loading content if user opened PLP from another PLP

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3351]
**Description**:
Breadcrumbs are displayed for the previous category when loading content if user opened category page from another category page

**Expected behavior**:
Placeholder is displayed when loading content
![Screenshot 2021-09-20 at 09 04 56](https://user-images.githubusercontent.com/73526235/133963005-143481ba-a744-4ccb-b6f5-afa7a65b055c.png)

**To Reproduce**:
1. Open PLP
2. Open another category

**Actual result:**:
Breadcrumbs are displayed for the previous category when loading content
https://drive.google.com/file/d/1z5aoJgAvIlW05Eutw2OTbBGin6SSt9-_/view?usp=sharing

**Additional context**:
If user opens category page from NOT another category page - ok

**Comment by Elena-Evsa** [comment]
Issue fixed: Placeholders shown
