### ISSUE TITLE
Display Scandipwa version in the Magento admin panel

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#3361]
**Description**:

Please add a feature to display scandipwa version in magento admin panel.

**Additional context**:

The ScandiPWA version can be displayed the footer together with the Magento version:

![image](https://user-images.githubusercontent.com/82165392/134192812-3866f55f-7f0d-4fce-ab94-1cdf11e259ff.png)

**Comment by zans-laksa** [comment]
https://github.com/scandipwa/customization/pull/21#pullrequestreview-761609154
