### ISSUE TITLE
All fields in Add/edit address form are marked as validated after selecting 'This is default Billing Address' or 'This is default Shipping Address' checkbox

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3386]
**Description**:
All fields in Add new/edit address form are marked as validated after selecting 'This is default Billing Address' or 'This is default Shipping Address' checkbox

**Expected behavior**:
Required and not required fields stay grey after selecting checkbox

**To Reproduce**:
1. Open FE
2. Log in 
3. Open Address book
4. Click on button Edit for existing address or Add new address
5. Select 'This is default Billing Address' or 'This is default Shipping Address' checkbox

**Actual result**:
All fields in Add/edit address form are marked as validated after selecting 'This is default Billing Address' or 'This is default Shipping Address' checkbox
Not required fields become green
Required fields become red and text 'This field is required!' appears below each required field
https://drive.google.com/file/d/1fPlAs-zEa4UPUS6QRZm1LbFysMcHYVez/view?usp=sharing

**Comment by tatiana-scandi** [comment]
@aleksandrakorolova please recheck (it looks like the issue is gone after Richard's big PR merge)
