### ISSUE TITLE
Max price excl price is equal to min price excl tax in product card for bundle product

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3389]
**Description**:
Max price excl price is equal to min price excl tax in product card for bundle product

**Expected behavior**:
Max price excl price is displayed correctly
![Screenshot 2021-09-27 at 08 42 54](https://user-images.githubusercontent.com/73526235/134851181-49503138-2f8d-4521-8225-c5304db22822.png)

**To Reproduce**:
1. Open PLP or home page
2. Find Bundle product card

**Actual result**:
Max price excl price is wrong. It's equal to min price excl tax
![Screenshot 2021-09-27 at 08 40 01](https://user-images.githubusercontent.com/73526235/134851076-2313fac3-f34f-4593-ba54-f2c0656332da.png)

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/catalog-graphql/pull/125
