### ISSUE TITLE
Error message 'Cannot query field \"id\" on type \"QuoteData\".' appears when adding product to cart

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3391]
**Description**:
Success message 'Product was added to cart!' appears but product isn't added to cart

**Expected behavior**:
Product is added to cart

**To Reproduce**:
1. Open PDP
2. Add product to cart

**Actual result**:
Success message 'Product was added to cart!' appears but product isn't added to cart
_Error message in network: "Cannot query field \"id\" on type \"QuoteData\"."_
![Screenshot 2021-09-27 at 09 15 09](https://user-images.githubusercontent.com/73526235/134854623-b2ddb4ad-c833-42ac-a89a-d02583327d87.png)

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/quote-graphql/pull/85

**Comment by aleksandrakorolova** [comment]
Created separate task for found issue #3400
