### ISSUE TITLE
Error message 'Error fetching Product List Information!' appears for specific categories

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3435]
**Description**:
Error message 'Error fetching Product List Information!' appears for specific categories

**Expected behavior**:
No errors

**To Reproduce**:
1. Open Women category

**Actual result:**:
Error message 'Error fetching Product List Information!' appears. Placeholders are displayed instead layered navigation and Sort by dropdown
debugMessage in Network: _"Notice: Undefined variable: from in /var/www/public/vendor/magento/module-elasticsearch/Elasticsearch5/SearchAdapter/Aggregation/Interval.php on line 130"_
![Screenshot 2021-09-30 at 08 45 43](https://user-images.githubusercontent.com/73526235/135394539-9854c248-a297-4c45-b501-58d7dab97715.png)
![Screenshot 2021-09-30 at 08 44 54](https://user-images.githubusercontent.com/73526235/135394547-986a6624-7964-47f5-9bce-d3dbbbbf1eb3.png)

**Additional context**:
Categories: Women, Dresses, Jackets, Accessories, man and etc

**Comment by tatiana-scandi** [comment]
Seems to be same issue as https://github.com/scandipwa/scandipwa/issues/3385
