### ISSUE TITLE
Arrow near 'Sort' on PLP is missing on mobile

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3446]
**Description**:
Arrow near 'Sort' on PLP is missing on mobile

**Expected behavior**:
Arrow near 'Sort' on PLP is present on mobile

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/135439323-fff5d862-2ada-43cd-85ad-2b76a264cff7.png)

**To Reproduce**:
1. Open any PLP on mobile

**Actual result**:
Arrow near 'Sort' on PLP is missing on mobile

**Comment by aleksandrakorolova** [comment]
iOS: Arrow is shifted down
<img src="https://user-images.githubusercontent.com/73526235/156710682-8ddfae69-4ad2-4443-9749-5d274bc04a6e.PNG" width=“385” height="700">
