### ISSUE TITLE
Name of child product is 'Null' in some bundle products

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3448]
**Description**:
Name of child product is 'Null' in some bundle products
**For example:** 
https://master.d25kd40decjpue.amplifyapp.com/default/women/women-shoes/sandals/bundle-sandals-with-fixed-prices.html
https://master.d25kd40decjpue.amplifyapp.com/default/women/women-shoes/sandals/bundle-sandals-with-dynamic-price.html
Here null present only in dropdown options: 
https://master.d25kd40decjpue.amplifyapp.com/default/accessories/accessories-bags/baggini-dyn-with-special-price.html
Here price shown only for one option from dropdown:
https://master.d25kd40decjpue.amplifyapp.com/default/bundle-book-with-dynamic-price.html
Here name of options shown:
https://master.d25kd40decjpue.amplifyapp.com/default/accessories/accessories-bags/baggini-without-dynamic.html

**Expected behavior**:
Name of child product shown on PDP
![image](https://user-images.githubusercontent.com/84388061/135459575-60d7952a-fbf0-4f34-b1e8-9042afd1033b.png)

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/135459463-b2a47e80-5296-47b9-b5b3-5fcd1d8fff1e.png)

**To Reproduce**:
1. Open link from example

**Comment by aleksandrakorolova** [comment]
@riha112 We had this issue in 5.0.4 and it was fixed in #3278
