### ISSUE TITLE
Price of child option in bundle product is 0.00 or absent

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3449]
**Description**:
Price of child option in bundle product is 0.00 or absent
for example:
Here is 0.00: https://master.d25kd40decjpue.amplifyapp.com/default/women/women-shoes/sandals/bundle-sandals-with-fixed-prices.html
Here is absent https://master.d25kd40decjpue.amplifyapp.com/default/accessories/accessories-bags/baggini-without-dynamic.html

**Expected behavior**:
Price of child of bundle product is not 0.00

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/135461640-07ca0e5a-b402-41dc-875c-89cbc510d329.png)

**To Reproduce**:
1. Open any bundle product

**Comment by aleksandrakorolova** [comment]
Price is 0.00 for bundle products with fixed price
Pice is missing for bundle product with dynamic price
