### ISSUE TITLE
Advertising message for bundle products should be written without price if rule 'Buy X get Y discount' implemented

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3456]
**Description**:
Advertising message for bundle products should be written without price if rule 'Buy X get Y discount' implemented
User can select any options and total price will be changed, but not it the advertisement message

**Expected behavior**:
It's look nice on Luma, without mention of price
![image](https://user-images.githubusercontent.com/84388061/135614167-f3bd86a4-e643-442c-a5e0-cf83f1ae1702.png)

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/135614212-533ad706-bb08-420b-970b-1a275096b8ef.png)

**To Reproduce**:
1. Open bundle product with rule 'Buy X get Y discount'
for example: https://master.d25kd40decjpue.amplifyapp.com/default/bundle-book-with-fixed-price.html
2. Observe advertising message

**Actual result**:
Advertising message for bundle products should be written without price if rule 'Buy X get Y discount' implemented

**Comment by aleksandrakorolova** [comment]
Also, don't show 'As low as' in product card 
**Actual result:**
![Screenshot 2021-10-05 at 10 10 38](https://user-images.githubusercontent.com/73526235/135976730-3c5044c7-8888-4401-b664-6da2e2259a8e.png)
**Expected result:**
![Screenshot 2021-10-05 at 10 11 21](https://user-images.githubusercontent.com/73526235/135976742-852f9b42-637c-4b41-936e-eb81a56e4286.png)
