### ISSUE TITLE
Issues related to radio buttons - part 1

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3459]
**1. Description**:
Mobile: Radio buttons are stretched if option has long name

**Expected behavior**:
Radio buttons are not stretched
![Screenshot 2021-10-04 at 08 36 47](https://user-images.githubusercontent.com/73526235/135799354-ce0151c6-6292-46d5-9549-68094442b66c.png)

**To Reproduce**:
1. Open Product with radio buttons in mobile layout - https://master.d25kd40decjpue.amplifyapp.com/default/kids/t-shirts1/downloadable-product-with-required-radio-buttons.html

**Actual result**:
Radio buttons are stretched
![Screenshot 2021-10-04 at 08 35 51](https://user-images.githubusercontent.com/73526235/135799281-b9b69295-a5da-43f3-a500-ecd0972f642e.png)

_______________________________
**2. Description**:
'Add to wishlist' icon is not painted over if product is added product to wishlist

**Expected behavior**:
'Add to wishlist' icon is painted over

**To Reproduce**:
1. Open Product with radio buttons in mobile layout - https://master.d25kd40decjpue.amplifyapp.com/default/kids/t-shirts1/bundle-product-with-required-radio-buttons.html
2. Log in
3. Select options
4. Add product to wishlist

**Actual result**:
'Add to wishlist' icon is not painted over but product is added to wishlist
![Screenshot 2021-10-04 at 09 05 13](https://user-images.githubusercontent.com/73526235/135801852-75f06807-5fed-4127-94f4-f0942d210389.png)

**Comment by Elena-Evsa** [comment]
Issue 1: Passed
Issue 2: Passed
