### ISSUE TITLE
Swatches are disabled when selecting 'Choose {attributeName}' in the dropdown for config product on PDP

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3462]
**Description**:
Swatches are disabled when selecting 'Choose {attributeName}' in the dropdown for config product on PDP

**Expected behavior**:
User can't select 'Choose {attributeName}' if it's selected
Swatches are active

**To Reproduce**:
1. Open config product
2. Select 'Choose {attributeName}'

**Actual result**:
Swatches are disabled
https://drive.google.com/file/d/1rtxKbKAkQZcE9I3A_O4IZPuWwFFVCOG4/view?usp=sharing

**Additional context**:
If user selects again 'Choose size' -> Swatches will be active

**Comment by carinadues** [comment]
Closed because we can't reproduce it.
