### ISSUE TITLE
Product price on PDP = Product price + 0.01 for specific products 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3463]
**Description**:
Product price on PDP = Product price + 0.01 for specific products 

**Expected behavior**:
Product price is displayed correctly

**To Reproduce**:
1. Open  products - https://master.d25kd40decjpue.amplifyapp.com/default/accessories/accessories-sunglasses/n-black-sunglasses.html or https://master.d25kd40decjpue.amplifyapp.com/default/accessories/accessories-sunglasses/n-dark-blue-sunglasses.html
2. Select attributes
3. Add product to cart

**Actual result:**:
Product price on PDP = Product price + 0.01
![Screenshot 2021-10-04 at 13 41 13](https://user-images.githubusercontent.com/73526235/135840731-e7bff668-5e36-4df7-90d3-108751b4f76e.png)

**Additional context**:
For price incl tax and price excl tax
Catalog price rulу is applied for these products

**Comment by tatiana-scandi** [comment]
@aleksandrakorolova can't reproduce on mentioned products any more. Please, suggest how to reproduce the issue now.

**Comment by aleksandrakorolova** [comment]
@tatiana-scandi Try now, I changed catalog price rule
