### ISSUE TITLE
Text 'Now shopping by:' with selected option are missing in Layered navigation when selecting price filter

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3491]
**Description**:
Text 'Now shopping by:' with selected option are missing in Layered navigation when selecting price filter

**Expected behavior**:
Price filter, 'Now shopping by:' with selected option are displayed in Layered navigation

**To Reproduce**:
1. Open Accessories category
2. Select price filter From 0.00 to 14.99

**Actual result**:
Price filter disappears and 'Now shopping by:' with selected option are missing in Layered navigation
![Screenshot 2021-10-07 at 08 44 07](https://user-images.githubusercontent.com/73526235/136326916-1d83922e-e66c-40b7-a3ab-acf0eb3d2267.png)

**Additional context**:
Selected price is displayed when filter is applying and content is loading
![Screenshot 2021-10-07 at 08 50 39](https://user-images.githubusercontent.com/73526235/136327232-c3c76f1f-b68e-4257-bef2-ffbd64398dd2.png)

**Comment by Elena-Evsa** [comment]
It shows '0 filters selected' in filters on mobile if user choose any price filter 
![image](https://user-images.githubusercontent.com/84388061/136541474-9590fd35-5cee-4a0f-bb41-b86219748ed9.png)
