### ISSUE TITLE
User can not add product to cart from PLP

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3498]
**Description**:
User can not add product to cart from PLP, error appear in console
User can add product to cart from PDP

**Expected behavior**:
User can add product to cart from PLP

**Screenshots, Video, Logs**
https://vimeo.com/625344431/f4c0196404

**To Reproduce**:
1. Open any PLP
2. Try add to cart simple product

**Actual result**:
User can not add product to cart from PLP, error appear in console

**Comment by aleksandrakorolova** [comment]
Error message appears in the console when adding downloadable product from PLP if Links can be purchased separately
https://pr-3485.d25kd40decjpue.amplifyapp.com/default/tech/downloadable-book2.html  
![Screenshot 2021-10-12 at 07 59 49](https://user-images.githubusercontent.com/73526235/136914951-15bdd58b-c192-4922-ab24-f085f8b0ebdd.png)
