### ISSUE TITLE
Buttons minus or plus are not disabled for limit Qty of product with Min or Max Qty Allowed in Shopping Cart

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3516]
**Description**:
Buttons minus or plus are not disabled for limit Qty of product with Min or Max Qty Allowed in Shopping Cart

**Expected behavior**:
Buttons minus or plus are disabled for limit Qty of product with Min or Max Qty Allowed in Shopping Cart

**Screenshots, Video, Logs**
https://vimeo.com/628991257/ba931ec2ff

**To Reproduce**:
1. Log in
2. Add to wishlist product with Min or Max Qty Allowed in Shopping Cart
For example: https://master.d25kd40decjpue.amplifyapp.com/default/baggini-elephant.html
https://master.d25kd40decjpue.amplifyapp.com/default/cardigan-in-brown.html

**Actual result**:
Buttons minus or plus are not disabled for limit Qty of product with Min or Max Qty Allowed in Shopping Cart

**Comment by carinadues** [comment]
From what I checked it is fixed now. QA, please double-check and close the second PR if it won't be needed :)
