### ISSUE TITLE
Mobile: Share button is active in empty Wishlist

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3530]
**Description**:
Mobile: Share button is active in Wishlist

**Expected behavior**:
Don't show Share button in mobile if wishlist is empty

**To Reproduce**:
1. Open FE in mobile layout
2. Log in
3. Open Wishlist
4. Clear Wishlist if user has products

**Actual result**:
Share button is active
User can share empty wishlist
![Screenshot 2021-10-12 at 12 24 40](https://user-images.githubusercontent.com/73526235/136930358-63a0720a-7e5b-41e3-a46b-b88988ffbd33.png)

**Additional context**:
Desktop - Button is disabled

**Comment by VanilStorm** [comment]
I can't reproduce it. There is no "share" button in the mobile app.

**Comment by aleksandrakorolova** [comment]
Where did you check?
I can reproduce it on master
![Screenshot 2022-03-22 at 12 13 09](https://user-images.githubusercontent.com/73526235/159457996-397da41a-c35c-4115-82cb-25442a705946.png)

**Comment by VanilStorm** [comment]
When I was writing this, I couldn't reproduce it.
Sometimes I can, sometimes I can't, and shows it. (the same situation was in my app)
Perhaps this is another bug. 

<img width="1440" alt="Снимок экрана 2022-03-22 в 13 26 16" src="https://user-images.githubusercontent.com/77737846/159461422-ae5ac100-383d-4ee0-bc12-31bdb7215ba8.png">

**Comment by aleksandrakorolova** [comment]
Yes, it's another bug. It happens when refreshing page
