### ISSUE TITLE
No  required options selected client side validation, when adding configurable product to cart from PLP

### ISSUE THREAD

**Issue by tatiana-scandi** [scandipwa/scandipwa#3537]
**To Reproduce**:
1. Go to https://master.d25kd40decjpue.amplifyapp.com/default/tech/phone.html
2. Hover product https://master.d25kd40decjpue.amplifyapp.com/default/tech/phone/apple-iphone-11-128gb-thx-6-1-12-4.html
3. Don't select options
3. Click `Add to cart`

**Actual result:**
AddProductToCart mutation is executed, error is received from the server

**Expected result:** 
Client side validation is applied: product has required options, but hasn't selected any => he is redirected to PDP, info message saying "Please, select required options" is shown

**Comment by aleksandrakorolova** [comment]
Closed task because can't reproduce
