### ISSUE TITLE
'Image is not specified' shown for child of configurable product in cart / mini cart

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3542]
**Description**:
'Image is not specified' shown for child of configurable product in cart / mini cart

**Expected behavior**:
Image shown for child of configurable product in cart / mini cart

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/137087499-19fbcc8f-c857-4043-997c-320719ee5285.png)

**To Reproduce**:
1. Open config products with pictures assigned to child products
https://master.d25kd40decjpue.amplifyapp.com/default/baggini-bagpack-108.html
https://master.d25kd40decjpue.amplifyapp.com/default/straw-shoulder-bag.html
2. Select option
3. Add to cart
4. Open cart / mini cart

**Actual result**:
'Image is not specified' shown for child of configurable product in cart / mini cart

**Comment by tatiana-scandi** [comment]
Can't reproduce:
![ScandiPWA 2021-10-14 15-49-01](https://user-images.githubusercontent.com/79456428/137320474-35ab4f62-f5fb-417e-b298-d99d36950409.png)
![ScandiPWA 2021-10-14 15-49-59](https://user-images.githubusercontent.com/79456428/137320606-8489f234-c1a4-442b-88bd-3483baff8c5e.png)
