### ISSUE TITLE
Stars near the review rating is moved down on Windows

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3546]
**Description**:
Stars near the review rating is moved down on Windows
It is ok on Mac

**Expected behavior**:
Stars is aligned to the review rating 

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/137119293-e54a0c50-2cff-4edd-b374-2d6aad9390cf.png)

**To Reproduce**:
1. Open product with rating on PDP, for example:
https://master.d25kd40decjpue.amplifyapp.com/default/bundle-bug-with-fixed-price.html
2. Click on 'REVIEWS'

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
![image (7)](https://user-images.githubusercontent.com/73526235/166195111-3763541d-e465-4cb0-aefc-d45a1b935150.png)
