### ISSUE TITLE
Space is absent between promotion block and summary block on shipping and billing steps

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3551]
**Description**:
Space is absent between promotion block and summary block on shipping and billing steps

**Expected behavior**:
Space is present between promotion and summary block on shipping and billing steps, as in cart
![image](https://user-images.githubusercontent.com/84388061/137136343-8a68a3bf-3d07-4882-8dc3-15f9a6eade58.png)

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/137136404-291cc1a0-dce6-4f4d-938a-ef985ec55fac.png)

**To Reproduce**:
in Admin: 
1. Admin panel > Stores > Settings - Configuration > SnandiPWA > Content customization
2. Assign Promotion block to shipping and billing steps
3. Click Save
4. Clear cash
On FE:
1. Add any product to cart
2. Go to shipping and billing steps

**Comment by aleksandrakorolova** [comment]
Please, read carefully the expected result - 'Space is present between promotion and summary block on shipping and billing steps, **as in cart**' (15x from summary block + 24px from CMS block)

**Actual result:**
Only margin 15px is added to the summary block
