### ISSUE TITLE
Success message 'Product added to wish-list!' appears on FE when adding product to wishlist with invalid extension

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3622]
**Description**:
Success message 'Product added to wish-list!' appears on FE when adding product to wishlist with invalid extension

**Expected behavior**:
User can't add product to wishlist with invalid extension
Error message: "The file {fileName} for {optionName} has an invalid extension." appears on FE

**To Reproduce**:
1. Open FE
2. Log in 
3. Open product with file option - https://master.d25kd40decjpue.amplifyapp.com/default/havaianas-green.html
4. Add file with invalid extension (for example, .jpeg)
5. Add to Wishlist

**Actual result:**:
Success message 'Product added to wish-list!' appears BUT product isn't added to wishlist

Error message: "The file '07a6f8712ee22e3ebd84e5555d283f5a3e780297_178275_1.jpeg' for 'Add file' has an invalid extension." appears in network
https://drive.google.com/file/d/1l7NcmcZrS859TTPV0xaFCWaH945ypKxI/view?usp=sharing

**Comment by Elena-Evsa** [comment]
Error message shown on FE and product is not added to Wishlist 
![image](https://user-images.githubusercontent.com/84388061/188410294-dace4cb7-f8db-42a6-8800-da9257371555.png)
