### ISSUE TITLE
Shipping and billing page are not scrolled up if user made a mistake or not filled required field

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3636]
**Description**:
Shipping and billing page are not scrolled up if user made a mistake or not filled required field

**Expected behavior**:
Shipping and billing page are scrolled up to the upper field with error if user made a mistake or not filled required field (in second part of video shown how it works on 5.0.0)

**Screenshots, Video, Logs**
https://vimeo.com/639540268/102f8e007d

**To Reproduce**:
1. Open any product 
2. Add to cart
3. Go to shipping step
4. Full all field except one (or make mistake)
5. Click on Proceed to billing

**Actual result**:
Shipping and billing page are not scrolled up if user made a mistake or not filled required field

**Comment by aleksandrakorolova** [comment]
Created separate task for found issue #3657
