### ISSUE TITLE
Space is absent between option name and + price in all products with checkboxes

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3647]
**Description**:
Space is absent between option name and + price in all products with checkboxes

**Expected behavior**:
Space is present between option name and + price in all products with checkboxes

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/139262835-66bcf4a2-71d2-4c14-a1da-29da561a9317.png)

**To Reproduce**:
1. Open products with checkboxes 
for example, https://master.d25kd40decjpue.amplifyapp.com/default/bundle-sandals-with-fixed-prices.html
https://master.d25kd40decjpue.amplifyapp.com/default/baggini-without-dynamic.html

**Actual result**:
Space is absent between option name and + price in all products with checkboxes

**Comment by aleksandrakorolova** [comment]
The same problem with radio buttons
![Screenshot 2021-11-01 at 10 13 58](https://user-images.githubusercontent.com/73526235/139641775-8c9808b8-6b64-443f-af34-18cfbf77f494.png)

**Comment by Elena-Evsa** [comment]
Can be fixed with #3906
