### ISSUE TITLE
Options of configurable products is disabled on PLP

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3655]
**Description**:
Options of configurable products is disabled on PLP

**Expected behavior**:
Options of configurable products is enabled on PLP

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/139443780-659ce960-bd90-4840-9da7-25a38d283a74.png)

**To Reproduce**:
1. Open PLP
2. Hover on config rpoducts

**Actual result**:
Options of configurable products is enabled on PLP

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/catalog-graphql/pull/131
