### ISSUE TITLE
Payment Methods: PayPal (or Stripe or Braintree)

### ISSUE THREAD

**Issue by uandiweb** [scandipwa/scandipwa#3656]
**Description**:
ScandiPWA is great, but I'm surprised to see that an e-Commerce solution comes with virtually 0 payment methods. I wish ScandiPWA would add native support for at least 1 (or 2) popular payment methods such as PayPal (best solution as it works in all countries & highly trusted) or Stripe or Braintree. Since payment methods are such an important part of e-Commerce it should not be left for 3rd party extensions.

**Additional context**:
I do see in the market place a few solutions. However, those solutions are out dated, and don't support the latest version of Magento 2.4.3-p1. I tried the PayPal extension for ScandiPWA version 5.x, and I encountered multiple issues with Magento 2.4.3-p1. Also, many important PayPal features are missing. For example: No guest checkout, No option to checkout from product page or cart page. No option to pay with credit cards directly on website etc.

>>> Right now I feel the best solution is to just not use ScandiPWA for the checkout page, and switch to Magento default. This is what Puma chose to do: https://mx.puma.com/ (and I guess many more). However, this is not really a solution, rather a workaround. To my opinion it should be at the top of the "To-Do" list.

**Comment by carinadues** [comment]
Hello, @uandiweb 
Thank for the feedback! 
It was a business decision to have payment methods as separate extensions. Please revisit the marketplace and you'll find the updated extensions for SPWA version 5.x!
