### ISSUE TITLE
Date & Time Custom Options / M2 support

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3658]
**Description**:
User can customize the format of date and time fields, and select the input control that is used for data entry. Date values can be selected from a drop-down list, or pop-up calendar

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/139648203-3c4e35c8-5c4e-44e0-989c-f9f18800ac15.png)

**To Do**:
Implement the feature for our theme. Go to `Stores > Settings - Configuration > Catalog > Catalog > Date & Time Custom Options`

Settings to be supported:

- Use JavaScript Calendar 
- Date Fields Order  
- Time Format 
- Year Range - there's a separate task for this one: #3720

**Additional context**:
https://docs.magento.com/user-guide/stores/attribute-date-time-options.html

**Comment by tatiana-scandi** [comment]
To QA, a couple of moments to note:
1. If starting year in year range is provided, end year is in the past (year Y), the range applied should be start of year Y till end of year Y (discussed with Carina).
2. React datepicker library is used for useCalendar = yes now. It is a a third-party library, so only customisations it allows are possible. E.g. it supports no separate selects for hours and minutes (I set 15 minutes interval, 1 minute interval would create a too long select). Also manually entering datetime values is not possible, if you want you use this library with custom input and ScandiPWA validation applied.

**Comment by carinadues** [comment]
Please check also https://github.com/scandipwa/scandipwa/issues/3720
