### ISSUE TITLE
Issues related to date & time option of product - Part 1

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3659]
**1st issue:** 
The number of the day is cut in date & time filed.

**Expected behavior**:
The number of the day is shown fully in the date & time filed.

**Screenshots, Video, Logs**

![image](https://user-images.githubusercontent.com/84388061/139641273-0a5c0a2c-c641-475b-a4ff-a17e4913386c.png)

**To Reproduce**:
1. Open https://master.d25kd40decjpue.amplifyapp.com/default/baggini-time-date.html
2. Enter date and time in corresponding field

---

**2nd issue:** 
Can not add to cart from wishlist with selected options.
The user is redirected to PDP and an error message is shown.

**Expected behavior**:
Can add to cart from wishlist with selected options

**Screenshots, Video, Logs**
https://vimeo.com/641080321/6665ae55ce

**To Reproduce**:
1. Open https://master.d25kd40decjpue.amplifyapp.com/default/baggini-time-date.html
2. Log in
3. Add product to wishlist
4. Open wishlist
5. Click on 'Add to cart'

**Actual result**:
Can not add to cart from wishlist with selected options

**Comment by carinadues** [comment]
May be fixed after merging https://github.com/scandipwa/scandipwa/pull/3834. Please check
