### ISSUE TITLE
Order of products is not changed on PLP if user select new in 'Sort by' on mobile

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3676]
**Description**:
Order of products is not changed if user select new in 'Sort by' on mobile

**Expected behavior**:
Order of products is changed if user select new in 'Sort by' on mobile

**Screenshots, Video, Logs**
https://drive.google.com/file/d/17fMtCjx2ZJe6ASB7w732VtJP_nNlHvSc/view?usp=sharing

**To Reproduce**:
1. Open any PLP on mobile
2. Tap on Sort
3. Select any other type of sorting
4. Observe order of products

**Actual result**:
Order of products is not changed if user select new in 'Sort by' on mobile

**Comment by aleksandrakorolova** [comment]
I suppose the same problem:
- can't switch Store in mobile layout
- can't switch currency in mobile layout
https://drive.google.com/file/d/1OGYQ0PHXeZ8pNLNwaUN2oFTwRVjbscoQ/view?usp=sharing
