### ISSUE TITLE
Green line does not appear in checkboxes after first click in downloadable product

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3689]
**Description**:
Green line from left side does not appear in checkboxes after first click in downloadable product

**Expected behavior**:
Green line appear near checkboxes after first click in downloadable product, same as in products with bundle products with checkboxes

**Screenshots, Video, Logs**
https://vimeo.com/642230825/bdaf35bda4

**To Reproduce**:
1. Open product https://master.d25kd40decjpue.amplifyapp.com/default/downloadable-havaianas.html
https://master.d25kd40decjpue.amplifyapp.com/default/song-of-ice-and-fire.html
2. Click on options with checkboxes

**Actual result**:
Green line from left side does not appear in checkboxes after first click in downloadable product

**Comment by Elena-Evsa** [comment]
If user click on 'Add to cart' without selected options and select first option then it is not highlighted by red too

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
