### ISSUE TITLE
User appears at the bottom of the sign in page when customer token lifetime expires

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3695]
**Description**:
- User appears at the bottom of the page when completing order and customer token lifetime expires
- User appears at the bottom of the page when switching pages in my account and customer token lifetime expires

**Expected behavior**:
Sign in page opens on the top

**To Reproduce**:
1. Log in 
2. Open PDP
3. Add product to cart
4. Go to shipping step
5. Fill form
6. Go to billing step
7. Select payment method
8. Wait for customer token lifetime expires
9. Click on Complete order

**Actual result**:
Sign in page is not scrolled up
The same situation if user switching pages in my account
https://drive.google.com/file/d/1XdPU0rdYcrI4Jq2DCvKpbP5csD1wAhxK/view?usp=sharing

**Notes:**
Default Customer token lifetime is 1h
Change this setting can here:
Open Admin panel -> Stores -> Configuration -> Services -> OAuth -> Access Token Expiration section -> Customer token lifetime

**Comment by Elena-Evsa** [comment]
Page scrolled up now in both cases
