### ISSUE TITLE
If user make a second purchase in guest mode email is saved on shipping step but button 'Proceed to billing' stay not clickable 

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3697]
**Description**:
If user make a second purchase in guest mode, email is saved on shipping step but button 'Proceed to billing' stay not clickable till user will not redact email

**Expected behavior**:
User can make a second purchase in guest mode, on Luma: fields stay empty, except default country

**Screenshots, Video, Logs**
https://vimeo.com/642636244/8307f26f95

**To Reproduce**:
1. Open home page and not login
2. Finish first purchase with any products 
3. Add to cart product 
4. Click 'Proceed to checkout' 
5. Observe that email field is full
6. Full all fields from address form
7. Click on Proceed to billing

**Actual result**:
If user make a second purchase in guest mode, email is saved on shipping step but button 'Proceed to billing' stay not clickable

**Comment by aleksandrakorolova** [comment]
Also, can reproduce if user tries complete order with the second try
1. Open PDP
2. Add to cart
3. Go to shipping step
4. Fill form
5. Go to billing
6. Open another page (PDP, PLP ....)
7. Go to shipping step

**Comment by biuro-mirat** [comment]
I have logged the same error. When can the problem be resolved?
https://vimeo.com/649906912

There is one more error in my video.
After clicking "Proceed to Billing" the page is reloaded, but it remains at the same height, I was confused myself whether the action was performed or whether I should wait further.

**Comment by aleksandrakorolova** [comment]
@biuro-mirat 
About the second issue in the video - It's already reported  #3290
