### ISSUE TITLE
Error message 'Uncaught (in promise)' appears in the console when customer token lifetime expires

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3700]
**Description**:
Error message 'Uncaught (in promise)' appears in the console when customer token lifetime expires

**Expected behavior**:
No errors 

**To Reproduce**:
1. Open FE
2. Log in
3. Wait for customer token lifetime expires
4. Go to another page

**Actual result**:
Error message 'Uncaught (in promise)' appears in the console
![Screenshot 2021-11-05 at 15 34 02](https://user-images.githubusercontent.com/73526235/140518948-1fd417bb-6b81-4ee9-ad3c-ad0a49e37125.png)

**Comment by zans-laksa** [comment]
Fixed in https://github.com/scandipwa/scandipwa/pull/3704 ?
@AleksandrsKondratjevs

**Comment by aleksandrakorolova** [comment]
Created separate task for found issue - #3707
