### ISSUE TITLE
Send Cart Token On Each Cart Related Request

### ISSUE THREAD

**Issue by zans-laksa** [scandipwa/scandipwa#3701]
Right now we have a param named `guest_quote_id`. In fact, it's a cart token and both guests and authorized customers can have it.
We send it to the backend as a param when we are performing some cart actions as guests.
But if a customer is authorized, we pass an empty string and at the backend, we check whether there is an empty string and we should get the authorized customer from the session and get its quote, or, if the string isn't empty, we can use this token in order to look up the quote.
Since `guest_quote_id` isn't guest-only and authorized has their own cart token that is related to an active cart, we should pass this token on every request, even for authorized users, and remove the check whether a string is empty or not. It should never be empty and it will always point to the active quote.

1. Please rename `guest_quote_id` and give it a less confusing name.
2. Send cart token on every request, even if a customer is authorized.
3. Check wishlists and compare pages, as they might relate to this task.
4. Update backend and remove unnecessary checks. Standardize the way how we get the quote by token along with all cart related resolvers.
5. Use as much Magento default implementation as you can.

**Comment by aleksandrakorolova** [comment]
Created separate task for found issue #5112
