### ISSUE TITLE
Turn the Menu Manager into an extension

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#3703]
**Context**: 
We would like to exclude all 3rd party modules from ScandiPWA core. Please remove the Menu Manager and turn it into an extension to be published in the marketplace. This extension should not be a part of the default theme.

**To Do**:
- Remove the Menu Manager from SPWA core and serve it separately as an extension.
- Create support for Magento's default Top Navigation (Category Tree). It will be displayed in the FE instead of the Menu Manager.
- Create support for the setting **Include in Menu**. If set to yes, the category needs to appear in the menu on FE.
Link: https://docs.magento.com/user-guide/catalog/navigation-top.html

**Expected results**:
- The Menu Manager is served as an extension and is no longer part of the default theme.
- We support the default [Magento Category Tree](https://docs.magento.com/user-guide/catalog/navigation-top.html), including the setting "Include in Menu".
- Disabled categories are not present in FE menu.
- If a parent category is disabled/not included in menu, nothing is broken and children menu items also do not appear in the menu.

**Print**:
![image](https://user-images.githubusercontent.com/82165392/140527043-2499a544-1a9d-4769-8e3d-ba7092c301bc.png)

**Comment by Elena-Evsa** [comment]
Issue 1: While CMS page loads, placeholders from PLP shown
https://vimeo.com/778070768/57a8606108
in settings of page set:  Display Mode = Static block only
Issue 2: Scandiweb menu manager stays in Admin
![image](https://user-images.githubusercontent.com/84388061/205638294-428f9b99-0d9d-4bfc-a7a1-63c6d6eaab59.png)

**Comment by Elena-Evsa** [comment]
Issue 1 - created new ticket
Issue 2 - solved

**Comment by Elena-Evsa** [comment]
PRs:
https://github.com/scandipwa/scandipwa/pull/5309
https://github.com/scandipwa/catalog-graphql/pull/143
https://github.com/scandipwa/customization/pull/33
