### ISSUE TITLE
Incorrect data is displayed for product option time or date&time in the cart if user selected time from 12 to 24

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3709]
**Description**:
Incorrect data is displayed for product option time or date&time if user selected time from 12 to 24

**Expected behavior**:
Correct time is displayed (23.02 or 11.02 PM)
On luma user can select: 
hours from 1 to 12
minutes from 00 to 59
AM or PM
![Screenshot 2021-11-08 at 08 48 20](https://user-images.githubusercontent.com/73526235/140696431-a10c1bb3-4b88-4e04-93e9-37d969c45135.png)

**To Reproduce**:
1. Open PDP for product with customizable option time or date & time - https://master.d25kd40decjpue.amplifyapp.com/default/bundle-product-with-required-radio-buttons.html
2. Select time after 12 (for example, 23.02)
3. Add to cart
4. Open mini cart

**Actual result**:
Option time: 11.02 **AM**
![Screenshot 2021-11-08 at 08 38 05](https://user-images.githubusercontent.com/73526235/140696359-685393bf-c0d2-4586-813f-d693064eb8cf.png)

**Comment by tatiana-scandi** [comment]
Please, check the fix with Date format = 12h (it worked fine with 24h before the fix) https://user-images.githubusercontent.com/84388061/139648203-3c4e35c8-5c4e-44e0-989c-f9f18800ac15.png

**Comment by Elena-Evsa** [comment]
If user set Time Format = 24h, then it is still offering to enter time on PDP in AM/PM format
![image](https://user-images.githubusercontent.com/84388061/145560618-00effe42-f02d-411d-87e4-4afd767cd8f5.png)

**Comment by tatiana-scandi** [comment]
@Elena-Evsa this issue has nothing to do with support of 12h/24h format for datetime select. It is about saving correct value in DB, if correct value is passed in GQL request. So the only thing you should check here, if value in cart matches value you entered.
