### ISSUE TITLE
Safari, FF: Can't add product to cart with date option 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3717]
**Description**:
Safari, FF: Can't add product to cart with date option 

**Expected behavior**:
Product is added to cart

**To Reproduce**:
1. Open Product with Date option - https://master.d25kd40decjpue.amplifyapp.com/default/baggini-time-date.html
2. Select date/time
3. Add to cart

**Actual result**:
Error message ' Invalid format provided. Please use 'Y-m-d H:i:s' format.' appears
![Screenshot 2021-11-08 at 14 53 28](https://user-images.githubusercontent.com/73526235/140746716-8f9ab25e-0a7d-4823-807b-b3a3f2084109.png)

**Additional context**:
Mac: Safari and FF

**Comment by carinadues** [comment]
May be fixed after merging https://github.com/scandipwa/scandipwa/pull/3834. Please check
