### ISSUE TITLE
Header block above/below the menu is missing on FE after redesign.

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3718]
**Description**:
Header block above/below the menu is missing on FE after redesign.

**To do**:
- Header block above menu will be 'Check new arrivals here!'. User can edit it in Admin panel
![Screenshot 2021-11-08 at 15 21 01](https://user-images.githubusercontent.com/73526235/140749242-1c0523d8-e3f3-491c-bf7a-dd76c64b548a.png)

- Header block below menu: Delete setting for this block in Admin panel
Stores -> Configuration -> Content customization -> Header and Menu -> Promotion CMS block (bellow menu)
![Screenshot 2021-11-08 at 15 24 09](https://user-images.githubusercontent.com/73526235/140749710-407b9aba-ebbf-48f3-90b5-db5a9afc5118.png)

**Comment by aleksandrakorolova** [comment]
Reopen task because Promotion CMS block (block above the menu) isn't changed on FE. Still, user sees  'Check new arrivals here!'
![Screenshot 2022-04-20 at 11 04 41](https://user-images.githubusercontent.com/73526235/164181044-ff124c18-60ab-46b3-bd48-34949e2ad32c.png)

**Comment by carinadues** [comment]
It's working now :)
![image](https://user-images.githubusercontent.com/82165392/169825528-3725b768-16cb-4644-a421-eae955fafcad.png)
