### ISSUE TITLE
iOS: Fields are narrow for date/time/date&time fields on PDP 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3738]
**Description**:
iOS: Fields are narrow for date/time/date&time fields

**Expected behavior**:
Fields are the default size

**To Reproduce**:
1. Open product with date field - https://master.d25kd40decjpue.amplifyapp.com/default/config-product-with-not-required-radio-buttons.html

**Actual result**:
Fields are narrow for date/time/date&time fields
These become standard size if user selected date/time
https://drive.google.com/file/d/1dAG3vTTpUI-KcnJmv7XCcOEFR3jpTYVx/view?usp=sharing

**Additional context**:
iOS: Safari, Chrome, FF, Opera

**Comment by Elena-Evsa** [comment]
Please, implement the height of fields for date and time same as for other input fields: 44.6px
Now it is about 51.7 px and 51.8 px

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce (now current date/time is selected by default)
