### ISSUE TITLE
Error message 'Password should be at least 8 characters long' is missing below password field in sign in form if user entered less than 8 characters

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3750]
**Description**:
Error message 'Password should be at least 8 characters long' is missing below password field in sign in form if user entered less than 8 characters

**Expected behavior**:
Password frame becomes red and Error message 'Password should be at least 8 characters long' appears below field
![Screenshot 2021-11-11 at 15 12 16](https://user-images.githubusercontent.com/73526235/141304732-896b9eff-22be-4296-b2be-b01cd55f201c.png)

**To Reproduce**:
1. Open Sign in form
2. Enter valid email
3. Start enter password

**Actual result**:
Password field frame becomes green
![Screenshot 2021-11-11 at 15 12 33](https://user-images.githubusercontent.com/73526235/141304721-52ef680c-4fd0-4097-97f7-4a0c79e11cae.png)

**Notes:**
The same situation on:
-  Confirm you account page
-  Reset password page
-  Change password in my account

**Comment by Elena-Evsa** [comment]
Error message 'Password should be at least 8 characters long' applied only to New password fields (Create account, Change password)
