### ISSUE TITLE
Block added to CMS page should appear to user without reloading

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#3755]
**Description**:
We want the blocks that are added to any CMS page to appear to the user without them having to reload the page, but simply browse around the site.

**Steps to reproduce**:
1. Open homepage.
2. Open admin and add a new block to the homepage.
3. Go back to the site and browse around.
4. See if the new block appears without reloading the page.

**Additional info**:
Sometimes Special price, price, name, and reviews in PDP update automatically while browsing the app installed on the home screen on mobile, but sometimes they don't. They should appear without the need of a refresh or closing and reopening the app.

**Comment by aleksandrakorolova** [comment]
Changes appear from the first reloading or visiting page
Created separate task for found issue - #4376

**Comment by aleksandrakorolova** [comment]
Reopened because slider doesn't update from the first reloading or visiting page after changes in #4376
