### ISSUE TITLE
After installing ScandiPWA the ALL configurable product from Magento sample data are OUT_OF_STOCK

### ISSUE THREAD

**Issue by bbtimx** [scandipwa/scandipwa#3772]
**Description**:
After installing ScandiPWA the Magento GraphQL for configurable product show the stock status as OUT_OF_STOCK.

**Expected behavior**:
GraphQL configurable product stock status: IN_STOCK

**Screenshots, Video, Logs**
Before installing ScandiPWA App:

![IN_STOCK](https://user-images.githubusercontent.com/4718129/141841887-b2e9232f-009e-45ac-903b-4d8b7ee23483.png)

After installing ScandiPWA App:

![OUT_OF_STOCK](https://user-images.githubusercontent.com/4718129/141841918-669c1229-9983-46f3-96ac-824895c546ff.png)

**To Reproduce**:
1. Install Magento 2.4.3 (Mode: developer)
2. Install Magento Sample Data
3. Reindex
4. GraphQL configurable product stock status: IN_STOCK
5. Install ScandiPWA App (src/localmodules)
```
npm init scandipwa-app pwa
BUILD_MODE=magento yarn build
composer config repo.theme path src/localmodules/pwa
composer require scandipwa/pwa
php bin/magento setup:config:set --pq-host=127.0.0.1 --pq-port=6379 --pq-database=5 --pq-scheme=tcp
php bin/magento setup:upgrade
php bin/magento cache:disable full_page
php bin/magento cache:flush
php bin/magento indexer:reindex
```
6. GraphQL configurable product stock status: OUT_OF_STOCK

**Versions**:
- ScandiPWA: 5.1.1
```
magento/framework *
scandipwa/cache 1.1.4
scandipwa/catalog-customer-graphql 1.0.0
scandipwa/catalog-graphql 3.2.9
scandipwa/cms-graphql 1.4.4
scandipwa/compare-graphql 1.0.9
scandipwa/contact-graphql 1.0.0
scandipwa/customer-downloadable-graphql 1.0.2
scandipwa/customer-graph-ql 3.1.8
scandipwa/customization 1.5.8
scandipwa/directory-graphql 1.0.1
scandipwa/installer 4.0
scandipwa/klarna-graphql 1.1.2
scandipwa/locale 2
scandipwa/menu-organizer 2.1.5
scandipwa/performance 1.5.2
scandipwa/persisted-query 3.0.2
scandipwa/product-alerts-graphql 1.0.0
scandipwa/quote-graphql 2.19.20
scandipwa/route717 2.0.1
scandipwa/service-worker 1.0.2
scandipwa/slider-graphql 2.1.0
scandipwa/store-graphql 1.2.6
scandipwa/urlrewrite-graphql 1.3.7
scandipwa/wishlist-graphql 2.0.15
```
- Any other composer module, you thing could be related
  - ScandiPWA_Performance
- Browser version if relevant to the context
  - Chrome: 95.0.4638.69
  - Altari GraphQL: 4.1.0
- OS version if relevant to the context
  - Ubuntu: 20.04.3 LTS
  - PHP: 7.4.25
  - Elasticsearch: 7.15.2
  - Redis: 5.0.7
  - Varnish: 6.2.1
  - Node: 14.18.1
  - Composer: 2.1.12

**Additional context**:
Varnish Cache not enabled (Caching Application: Built-in Cache)

**Comment by EagleSH** [comment]
Confirmed, i have also such issue but i haven't sample data, all my configurable products is showing Out of Stock when scandi theme is applied, but if i change scandi theme to the Luma, all working good, my configurable products working as expected.
