### ISSUE TITLE
Checkout Guest Form not remove after login

### ISSUE THREAD

**Issue by kyeng-vis** [scandipwa/scandipwa#3790]
**Description**:
Add product to cart, proceed to checkout shipping step, use the top right login popup to login, after successful login, still showing guest email input.
(switch to Mobile view) Header title still show Sign In, along with close button.

**Expected behavior**:
Guest email input should disappear
(Mobile view) Back to Checkout Shipping State

**Screenshots, Video, Logs**
![checkout desktop](https://user-images.githubusercontent.com/22570843/142564853-19471799-d5fb-4f02-bd88-dac6b43819db.JPG)
![checkout mobile](https://user-images.githubusercontent.com/22570843/142564859-fe4ace6d-c3c2-4599-b950-d47cbf6e344c.JPG)

**Comment by Elena-Evsa** [comment]
Exist issue 'Email field stays after user is Logged In on Shipping step' #2665
