### ISSUE TITLE
Wrong color and font settings on cart page

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3794]
**Issue 1**:  Color of boarder of Promotion CMS block is #d8d8d8 and inherited from (--cart-page-divider-background);

**Expected behavior**:
Color of background table header is inherited from (--secondary-base-color);

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/143221536-7aaf02b8-2994-4b45-ab1a-c43cc8834361.png)

**To Reproduce**:
1. Open FE
2. Add available products to cart
3. Click on Mini Cart > View Cart
4. Observe the boarder of Promotion CMS block

---

**Issue 2**:  Price of product in Cart is not h3 style

**Expected behavior**:
Price of product in Cart inherit h3 style
font-family: Mulish; 
font-style: normal; 
font-weight: bold; 
font-size: 18px; 
line-height: 24px;

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/143241972-74ea600f-1e18-4193-be93-1d0a27789b5b.png)

**To Reproduce**:
1. Open FE
2. Add available products to cart
3. Click on Mini Cart > View Cart

---

**Issue 3**:  Excl.tax price Line-Height is 20px

**Expected behavior**:
Excl.tax price Line-Height is 16px

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/143242752-ecb2e7e6-96d1-4f75-81b7-2576e85eb5b0.png)

**To Reproduce**:
1. Open FE
2. Add available products to cart
3. Click on Mini Cart > View Cart

---

**Issue 4**:  Line-height of text in Delete button is 24px

**Expected behavior**:
Line-height of text in Delete button is 20px

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/143243942-a6c07f67-975e-4be5-ad1f-95a05b2038ca.png)

**To Reproduce**:
1. Open FE
2. Add available products to cart
3. Click on Mini Cart > View Cart

---

**Issue 5**:  Line Height of style Order total and Price of order total is 20px

**Expected behavior**:
Line Height of style Order total and Price of order total is 24px

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/143244427-f63b6543-ec0e-44eb-bdd4-fe185178e382.png)

**To Reproduce**:
1. Open FE
2. Add available products to cart
3. Click on Mini Cart > View Cart

---

**Issue 5**:  Line Height of Name of Product in Cart and mini cart is 16.8px

**Expected behavior**:
Line Height of Name of Product in Cart and mini cart is 20px

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/143245357-5d2848b7-9507-4bde-9350-1088e330b897.png)

**To Reproduce**:
1. Open FE
2. Add available products to cart
3. Click on Mini Cart > View Cart

**Comment by aleksandrakorolova** [comment]
1. Fixed
2. Fixed
3. Fixed
4. Failed. I suppose it's broke after #3944
![Screenshot 2022-01-13 at 10 50 29](https://user-images.githubusercontent.com/73526235/149297068-add2d201-4a53-456c-b6af-05ea3c799883.png)
5. Fixed
