### ISSUE TITLE
Mixed content serving when products without category avaible

### ISSUE THREAD

**Issue by Ylmzef** [scandipwa/scandipwa#3798]
When a product is created without a category or under the root category SPWA serving wrong products or no content category pages from frontend.

**Comment by carinadues** [comment]
Hello, @Ylmzef!
Could you please provide us with more details?
- Steps to reproduce
- Screenshots

**Comment by Elena-Evsa** [comment]
Hey, @Ylmzef! We are not able to reproduce.
Could you please provide us with more details?

**Comment by Ylmzef** [comment]
I think it is because of this problem: https://github.com/scandipwa/scandipwa/issues/3731

**Comment by Elena-Evsa** [comment]
Please, @Ylmzef provide more details or we should close the task
