### ISSUE TITLE
Price incl. and excl.tax is displayed on FE (don't matter what user set in Admin panel)

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3804]
**Description**:
Price incl. and excl.tax is displayed on FE (don't matter what user set in Admin panel)

**Expected behavior**:
Price incl.tax is displayed on FE
![Screenshot 2021-11-22 at 15 16 45](https://user-images.githubusercontent.com/73526235/142868307-574d13c0-bac8-4090-817f-06c7a0b4aab9.png)

**To Reproduce**:
**Admin panel:**
1. Open Admin panel -> go to Stores -> Settings - > Configuration -> Sales -> Tax
2. Select Including Tax in Display Product Prices In Catalog field
3. Save'
4. Clear cache

**FE:**
1. Open PLP
2. Open PDP

**Actual result**:
Price incl. and excl.tax is displayed
![Screenshot 2021-11-22 at 15 16 57](https://user-images.githubusercontent.com/73526235/142868322-b55dda5a-ab73-4ebf-b197-594e8468703c.png)

**Additional context**:
The same situation with Excluding tax

**Comment by Ylmzef** [comment]
same!
