### ISSUE TITLE
iOS12: Price for customizable options is shifted down on PDP

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3827]
**Description**:
iOS12: Price for customizable options is shifted down on PDP

**Expected behavior**:
Price is aligned with option text
![Screenshot 2021-11-29 at 14 28 38](https://user-images.githubusercontent.com/73526235/143868199-6709c45d-1ba5-42bf-ad96-34e2c89d1ab0.png)

**To Reproduce**:
1. Open product with customizable options -  https://master.d25kd40decjpue.amplifyapp.com/default/cardigan-in-brown.html

**Actual result**:
Price for options is shifted down
![IMG_0109](https://user-images.githubusercontent.com/73526235/143867786-7ae7acbc-3eef-458f-b1df-1341a69e0dc3.PNG)

**Additional context**:
iOS 12, iPhone 7

**Comment by GiorgiPasieshvili** [comment]
Cannot reproduce

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce. Probably it was fixed by #3906
<img src="https://user-images.githubusercontent.com/73526235/152477586-bc04a706-640e-4f46-9d2c-5b9a09e72e96.PNG" width="385" height="700">
