### ISSUE TITLE
Options are displayed as one and zero for boolean attribute in Layered Navigation 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3847]
**Description**:
Options are displayed as one and zero for boolean attribute in Layered Navigation 

**Expected behavior**:
Options are displayed as 'Yes' and 'No'
![Screenshot 2021-12-02 at 14 18 39](https://user-images.githubusercontent.com/73526235/144420713-3ddcc61d-a5d4-4ef2-a084-f7b363e7381f.png)

**To Reproduce**:
1. Open PLP - https://master.d25kd40decjpue.amplifyapp.com/default/kids.html
2. Scroll down to the boolean attribute in layered navigation 

**Actual result**:
Options are displayed as zero or one
![Screenshot 2021-12-02 at 14 18 19](https://user-images.githubusercontent.com/73526235/144420680-1580379b-64fc-4bca-a8b1-297490ea0206.png)

**Comment by S-Arturs** [comment]
It looks like it is fixed already, works correctly on my local instance and on provided amplify instance too. Please check again @aleksandrakorolova

**Comment by aleksandrakorolova** [comment]
Closeв because can't reproduce
