### ISSUE TITLE
Scandi 5.0.4 can not edit shipping/billing address in customer account

### ISSUE THREAD

**Issue by romeof1980** [scandipwa/scandipwa#3851]
**Description**:
If you have set a customer address without flagging "This is my default billing address" or "this is my default shipping address" you can not flag it anymore when editing the address from the customer account (you must insert a new address).

Also you can not edit, for example, the "province" field.
No error appears, but when you reopen it, the field has not been saved. Logging out and re-logging in confirms the fields can not be edited. Probably an error in the mutation.

Scandipwa 5.4.0
Magento 2.4.3

**Comment by romeof1980** [comment]
in reality it turns out that even if adding another address the field "State / Province" remains always populated with the first field of the list.
then when checking out with paypal the following "`Shipping Address Invalid City State Postal Code`"  error for gets thrown

`[2021-12-03 11:53:04] main.ERROR: PayPal gateway has rejected request. A match of the Shipping Address City, State, and Postal Code failed (#10736: Shipping Address Invalid City State Postal Code). {"exception":"[object] (GraphQL\\Error\\Error(code: 0): PayPal gateway has rejected request. A match of the Shipping Address City, State, and Postal Code failed (#10736: Shipping Address Invalid City State Postal Code). at /vendor/webonyx/graphql-php/src/Error/Error.php:174, Magento\\Framework\\GraphQl\\Exception\\GraphQlInputException(code: 0): PayPal gateway has rejected request. A match of the Shipping Address City, State, and Postal Code failed (#10736: Shipping Address Invalid City State Postal Code). at /app/code/ScandiPWA/PayPalGraphQl/Model/Resolver/PaypalExpressToken.php:156)"} `

**Comment by aleksandrakorolova** [comment]
These issues were fixed in #3217 and #3671
