### ISSUE TITLE
Guest checkout allowed for downloadable products

### ISSUE THREAD

**Issue by romeof1980** [scandipwa/scandipwa#3852]
**Description**:
When checking-out, if a simple product and a downloadable product are present in cart the customer should be prompted for signin/signup even if guest checkout is allowed in backend.
Having guest checkout possible if the products in cart are NOT downloadable is a default magento 2 feature.
Instead with Scandi 5.4.0 the checkout goes on as if all products were simple products.

**Versions**:
- ScandiPWA 5.4.0
- Magento 2.4.3

**Comment by aleksandrakorolova** [comment]
If you want to require that purchasers register for a customer account and log in before purchasing a download, you need to set 'Disable Guest Checkout if Cart Contains Downloadable Items' to Yes. But we don't support it yet.
It's added to 5.1.4 milestone. Please, find it here #2333
