### ISSUE TITLE
scandipwa marketplace incomplete instructions for manual installation scandi v5.x

### ISSUE THREAD

**Issue by romeof1980** [scandipwa/scandipwa#3865]
**Description**:
installing a Scandipwa 5.x extension (manual installation) following the steps indicated below isn't enough to make the extension work properly:
https://marketplace.scandipwa.com/extension-manual-installation-guide

**To Reproduce**:
to the marketplace instructions above should be added what detailed here: https://docs.scandipwa.com/developing-with-scandi/extensions/installing-an-extension#install-from-a-local-source
points 4, 5 and 6 of the docs link are not indicated in https://marketplace.scandipwa.com/extension-manual-installation-guide causing extension issues.
There is no indication that points 4, 5 and 6 above refer only to version 4.x installation

New users aren't expected to know that they must perform other steps that what indicated here: https://marketplace.scandipwa.com/extension-manual-installation-guide

**Versions**:
- ScandiPWA: 5.x

**Comment by romeof1980** [comment]
link to slack: https://scandipwa.slack.com/archives/CD8ETGY3Y/p1638813949233400
this can be closed but following docs should specify they refer ONLY to version 4.x and not 5.x
https://docs.scandipwa.com/developing-with-scandi/extensions/installing-an-extension#install-from-a-local-source

**Comment by carinadues** [comment]
Thank you, Romeo! I've updated the manual and the marketplace guide
