### ISSUE TITLE
Error message 'Minimum 8 characters!' is displayed when user try to submit empty form in 'Create account' popup

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3884]
**Description**:
Error message 'Minimum 8 characters!' is displayed when user try to submit empty form in 'Create account' popup
Same on Create account page

**Expected behavior**:
Only  'This field is required' is displayed when user try to submit empty form in 'Create account' popup

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/145052448-7bb2449d-b127-41e5-8a02-545c1cff5dda.png)

**To Reproduce**:
1. Open home page
2. Click on Account sign > Create  account > Sign up

**Actual result**:
Error message 'Minimum 8 characters!' is displayed when user try to submit empty form in 'Create account' popup

**Comment by aleksandrakorolova** [comment]
Duplicate of #3687
