### ISSUE TITLE
Account is locked when changing password in my account and user entered invalid current password

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3886]
**Description**:
Account is locked when changing password in my account and user entered invalid current password

**Expected behavior**:
User automatically log out and Error message 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.' appears 

**To Reproduce**:
1. Open Sign in form
2. Log in
3. Open Account information page in my account 
4. Select 'Change password' checkout 
5. Enter invalid current password
6. Enter new and confirm password

**Actual result**:
Error message 'The account is locked.' appears
![Screenshot 2021-12-07 at 14 14 05](https://user-images.githubusercontent.com/73526235/145156622-e7cdd631-1abf-4b73-9436-ddcde8a11f5f.png)

**Comment by iman-sujamiko** [comment]
Is there any limit to how many wrong passwords can be done? I do it 5 to 6 times before it shows like that

**Comment by Elena-Evsa** [comment]
1. Two error messages are shown when user is redirected to 'Sign in' page
https://vimeo.com/680376033/01df6ad163
Only Error message 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.' should appear
2. Mobile: extra error and success messages appears. Only Error message 'The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.' should appear.
https://vimeo.com/680377529/f1f2029860 - IOS, on Android success message absent
