### ISSUE TITLE
Add base cart item row total info to getCartForCustomer query

### ISSUE THREAD

**Issue by tatiana-scandi** [scandipwa/scandipwa#3932]
**Description**:
Projects often have the need of feature to show product price before discount in cart:
<img width="965" alt="ScandiPWA 2021-12-14 11-45-17" src="https://user-images.githubusercontent.com/79456428/145992357-9bc20b49-fba0-4dfc-ab5a-2809408c0b59.png">

But there is no such info in getCartForCustomer query response:
<img width="1386" alt="Altair 2021-12-14 11-46-13" src="https://user-images.githubusercontent.com/79456428/145992543-3d00154a-d0f6-47fa-8acf-92b3a629e5d5.png">
Field returning row total before discount is needed (for case on the screen = 32).

https://luma-demo.scandipwa.com/savvy-shoulder-tote.html

**Comment by Elena-Evsa** [comment]
Now functionality of discounts in cart works the same as on Luma 
![image](https://user-images.githubusercontent.com/84388061/188595492-1ea8dee8-4a3a-4bf5-8e53-c472bf4a5f95.png)
