### ISSUE TITLE
Add comment in order in my account if user left comment in Admin panel 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#3933]
**Description**:
Add comment in order in my account if user left comment in Admin panel 

**Additional context**:
![Screenshot 2021-12-14 at 14 06 35](https://user-images.githubusercontent.com/73526235/145995387-8daec447-6825-44af-b2bc-984f950a2d14.png)

**Comment by carinadues** [comment]
Closing after merging #3992

**Comment by aleksandrakorolova** [comment]
Created separate task for found issues - #4092
