### ISSUE TITLE
In fields for minutes placeholder 'Minutes' present on PDP in fields for Date&time 

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3947]
In fields for minutes placeholder 'Minutes' present

**Expected behavior**:
In fields for minutes placeholder same as in other dropdowns, current time (minutes) present

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/146379114-c670509c-387a-4650-8183-d34a88583a8f.png)

**To Reproduce**:
1. Open https://master.d25kd40decjpue.amplifyapp.com/default/baggini-time-date.html

In admin:
1. Open Stores > Settings - Configuration > Catalog > Catalog > Date & Time Custom Options
2. Set 'Use JavaScript Calendar' = No

**Additional info:**
Some time it is not minutes but hours
![image](https://user-images.githubusercontent.com/84388061/146382242-9629168c-591e-486d-8666-1d107fc7f418.png)

**Comment by tatiana-scandi** [comment]
@QA: The issue seems to be reproduced when hours < 10 or minutes < 10 (zero based valued were handled incorrectly)
