### ISSUE TITLE
Error fetching Product List! when searching specific terms

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#4007]
**Description**:
Some searches are resulting in Error fetching Product List! even if you search for a product that exists.

**Expected behavior**:
The products appear and no errors are thrown.

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/82165392/147755778-611ac22a-5ecd-4186-9264-0ff0c753b820.png)

![image](https://user-images.githubusercontent.com/82165392/147755943-e550f6b7-c0cb-4cd4-92f5-b476d9391ade.png)

**To Reproduce**:
1. Go to master or pmrev
2. Click on the search bar
3. Search for "Cocktail Dress", press enter
4. See the error
5. Repeat the steps but don't press enter: you get 'No Results Found'

**Additional context**:
Here is the existing product: https://master.d25kd40decjpue.amplifyapp.com/default/n-cocktail-dress.html

Other things you can search for: 

- Red dress (error)
- Dress (error)
- Yellow red (infinite loading)
- Virtual shirt (it works)
- Blue shorts (it works)
- blue short dress (it works)
- cocktail shirt (it works)
- red short (it works)

**Comment by carinadues** [comment]
Might be related https://github.com/scandipwa/scandipwa/issues/3972

**Comment by aleksandrakorolova** [comment]
Can reproduce when searching 'Yellow red' and pressing enter. Search result appears in overlap if user didn't press enter
https://drive.google.com/file/d/1gCZzaDBVxMCRj_c9HrqwuwAh7y9uePj4/view?usp=sharing
