### ISSUE TITLE
Customizable product is added to cart from Wishlist without entered required options if earlier it was added to cart from PDP

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4023]
**Description**:
Customizable product is added to cart from Wishlist without entered required options if earlier it was added to cart from PDP

**Expected behavior**:
Error message appears when user try to add customizable product to cart from Wishlist without entered required options, even if earlier it was added to cart from PDP

**Screenshots, Video, Logs**
https://vimeo.com/manage/videos/662228341/42d107e6f0

**To Reproduce**:
1. Open customizable products with required options:
https://master.d25kd40decjpue.amplifyapp.com/default/baggini-12.html
https://master.d25kd40decjpue.amplifyapp.com/default/cardigan-in-brown.html
2. Select required option
3. Add to cart
4. Add to Wishlist same product without selected options
5. Go to wish list
6. Click 'Add All to cart'

**Actual result**:
Customizable product is added to cart from Wishlist without entered required options if earlier it was added to cart from PDP

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
https://drive.google.com/file/d/1MNEDsefJF5Jgwbbr_n0BYrOuMx9zF9lm/view?usp=sharing
