### ISSUE TITLE
Bundle out of stock product is displayed as in stock in compare list

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4027]
**Description**:
Bundle out of stock product is displayed as in stock product in compare list

**Expected behavior**:
Product is out of stock => button 'Add to cart' is disabled and text 'Out of stock' is displayed instead price 

**To Reproduce**:
1. Open out of stock bundle product
2. Add it to compare list
3. Open compare list

**Actual result**:
Product is displayed as in stock
Status in stock is received from BE
![Screenshot 2022-01-04 at 15 41 47](https://user-images.githubusercontent.com/73526235/148069133-10ec861a-aba5-47e8-9f64-a3f01886d054.png)

**Additional context**:
8bun is out of stock 
![Screenshot 2022-01-04 at 15 41 55](https://user-images.githubusercontent.com/73526235/148069458-68d1c2c9-5850-412e-8ac6-bacaeebb6ecd.png)

**Comment by aleksandrakorolova** [comment]
The same situation with config products
![Screenshot 2022-05-30 at 10 15 26](https://user-images.githubusercontent.com/73526235/170937682-7a9a3688-a2a5-4bcd-9085-d4fbe6ccd937.png)

**Comment by Elena-Evsa** [comment]
![image](https://user-images.githubusercontent.com/84388061/188612967-3f2391f0-3569-4aa9-aa0f-9244e1406f0b.png)
Bundle and Config product displayed 'out of stock' in compare
