### ISSUE TITLE
'As low as' is shown on PDP for specific product if user select options

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4034]
**Description**:
'As low as' is shown on PDP for specific product if user select options
Product: Virtual Shorts

**Expected behavior**:
'As low as' is not shown on PDP for specific product if user select options

**Screenshots, Video, Logs**
https://vimeo.com/662607740/6559a655a5

**To Reproduce**:
1. Open https://master.d25kd40decjpue.amplifyapp.com/default/virtual-shorts.html 
2. Select option of product

**Actual result**:
'As low as' is shown on PDP for specific product if user select options
Product: Virtual Shorts

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce 
I think it happened because we didn't show 'none' option
![Screenshot 2022-05-02 at 11 15 15 (2)](https://user-images.githubusercontent.com/73526235/166204845-4f4cb61c-5162-4342-8f71-22a086403a11.png)
