### ISSUE TITLE
Orders are missing in my account from other stores

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4040]
**Description**:
Orders are missing in my account from other stores

**Expected behavior**:
Order is displayed from other stores

**To Reproduce**:
1. Open Store X
2. Log in with account X
3. Complete order
4. Open store Y
5. Log in with account X
6. Open my orders

**Actual result**:
Order is missing from store X

**Comment by Elena-Evsa** [comment]
Issue 1: user can not make reorder, nothing appear on FE
message in console: "Order number "4000000059" doesn't belong to the current customer"
https://vimeo.com/671173727/3e5d3b0a48
