### ISSUE TITLE
Include a vertical scroll bar for dropdowns in desktop mode

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#4055]
**Description**:
Let's include a vertical scroll bar for dropdowns for the case when there are more than 4 options.

**Actual behavior**:
(Please make it so that the 5th item isn't partially showing)

![image](https://user-images.githubusercontent.com/82165392/148439347-b8266984-6b08-4f33-8983-38e85b54655e.png)

**Expected behavior**:
If there are more than 4 options for the person to choose, the dropdown should have a vertical scroll like the one below:

![image](https://user-images.githubusercontent.com/82165392/148439270-d4e5e0c5-1c30-4e18-99f8-ec4d22570649.png)

**To Reproduce**:
1. Open a product with many dropdown options: https://master.d25kd40decjpue.amplifyapp.com/default/bundle-jeans-with-dynamic.html
2. Click on the dropdown.

**Additional context**:
Here you can see how the dropdowns behave: https://semantic-ui.com/modules/dropdown.html
If the dropdown is closer to the end of the screen, it should open going up:

![20220106_162522](https://user-images.githubusercontent.com/82165392/148439768-127e3ebf-fe8f-4c68-aeb4-9c35d0c9b36b.gif)

**Comment by Elena-Evsa** [comment]
Small part of background visible from the left side of scroll 
![image](https://user-images.githubusercontent.com/84388061/153414982-94b0230a-1f02-4dde-85e2-a81e21edf27c.png)

**Comment by aleksandrakorolova** [comment]
Left bord of dropdown is missing on Mac if show scroll bar is set to when scrolling 
![Screenshot 2022-02-24 at 09 26 57](https://user-images.githubusercontent.com/73526235/155479725-f91d907e-3b89-4629-abdc-a299a98ddc3a.png)

**Comment by aleksandrakorolova** [comment]
Created separate task for issue - Small part of background visible from the left side of scroll #4364
