### ISSUE TITLE
Shipping/billing form is validated when logging in on checkout

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4077]
**Description**:
Shipping/billing form is validated when logging in on the checkout

**Expected behavior**:
Shipping/billing form isn't validated

**To Reproduce**:
1. Open PDP
2. Add product to cart
3. Open checkout
4. Enter register email
5. Enter password when password field appering 
6. Click on 'Sign in' button

**Actual result**:
Shipping/billing form is validated when clicking on 'Sign in'
https://drive.google.com/file/d/1jQZtj2OAZaA_3greCdvIbbGbvsj3oZtF/view?usp=sharing

**Comment by Elena-Evsa** [comment]
Can reproduce on master (but it is ok on 5.2.7)
