### ISSUE TITLE
Loader is missing for summary block on checkout page when logging in on checkout 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4078]
**Description**:
Loader is missing for summary block on checkout page when logging in on checkout 

**Expected behavior**:
Loaded displayed for summary block 

**To Reproduce**:
1. Open PDP
2. Add product to cart
3. Open checkout
4. Enter register email
5. Enter password when password field appering 
6. Click on 'Sign in' button

**Actual result**:
Loader is missing 
https://drive.google.com/file/d/1jQZtj2OAZaA_3greCdvIbbGbvsj3oZtF/view?usp=sharing

**Comment by aleksandrakorolova** [comment]
1. Mobile: Duplicate of loader is displayed in summary block
![Screenshot 2022-02-08 at 11 41 07](https://user-images.githubusercontent.com/73526235/152960188-4068de8b-961d-4add-85a3-b22dc5ba024a.png)
2. User doesn't see loader if he has a lot of products in the cart. Show loader within screen
![Screenshot 2022-02-08 at 11 28 51 (2)](https://user-images.githubusercontent.com/73526235/152960325-c0509b74-f7fe-461b-b62f-4eddf207b698.png)

**Comment by aleksandrakorolova** [comment]
Reopened task because the loader disappeared for summary block
https://drive.google.com/file/d/1khYpe8qoTl2k_CWH0g8OOOj8K9oLbavR/view?usp=sharing

**Comment by leonazava** [comment]
On master, there isn't a sing-in form at the checkout, only an email input field. Is this still relevant?

**Comment by aleksandrakorolova** [comment]
Closed task and linked PR because can't reproduce
