### ISSUE TITLE
"Не число" or Nan appears instead of price for a wile if user login on shipping step on mobile

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4091]
**Description**:
"Не число" or Nan appears instead of price for a wile if user login on shipping step

**Expected behavior**:
Price is refreshed without showing "Не число" or Nan if user login on shipping step

**Screenshots, Video, Logs**
<img src= "https://user-images.githubusercontent.com/84388061/149505413-f37e65fe-4237-4784-af2e-c28a843c0ec9.png" width="250" />

**To Reproduce**:
1. Open FE on **mobile**, not login
2. Add some products to cart
3. Click Mini cart > Proceed to checkout
4. Login
5. Observe price in 'Order total'

**Actual result**:
"Не число" or Nan appears instead of price for a wile if user login on shipping step on mobile

**Additional info**
Related tasks #4077 and #4078

**Comment by EriSilver** [comment]
Couldn't reproduce the Nan
https://drive.google.com/file/d/1LLA1mnTPT66G9rgS5N-iAUFB7aZ9KbIE/view?usp=sharing

**Comment by Elena-Evsa** [comment]
Can not reproduce
