### ISSUE TITLE
Issues related to order comments

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4092]
**1. Description**:
Time is displayed 2 hours behind for comments

**Expected behavior**:
The correct time is displayed 
![Screenshot 2022-01-14 at 11 20 45](https://user-images.githubusercontent.com/73526235/149491099-69e4d494-7a31-4a47-8710-d6aef8fa1cd4.png)

**To Reproduce**:
1. Log in
2. Open My orders
3. Open order with comments

**Actual result**:
Time is displayed 2 hours behind 
![Screenshot 2022-01-14 at 11 21 00](https://user-images.githubusercontent.com/73526235/149491243-70c58dde-3cbf-4e03-99f7-2032b36dd8a0.png)
_____________________
**2.Description**:
Invoices comments are sorted by publication date from the first to the last

**Expected behavior**:
Comments are sorted by publication date from the last to the first as comments in Item Ordered tab 

**To Reproduce**:
1. Log in
2. Open My orders
3. Open order with invoice comments

**Actual result**:
Comments are sorted by publication date from the first to the last
![Screenshot 2022-01-14 at 11 18 46](https://user-images.githubusercontent.com/73526235/149490915-96745593-9250-4637-9a09-6601c13f2d7f.png)

**Notes:**
The same situation with comments in Order Shipments tab
_____________________
**3.Description**:
Line below the last product is missing in Order Shipments tab

**Expected behavior**:
Line below the last product is displayed
![Screenshot 2022-01-14 at 12 39 01](https://user-images.githubusercontent.com/73526235/149504166-d24e1637-c2a8-4096-9c15-8463eaa67bd0.png)

**To Reproduce**:
1. Log in
2. Open My orders
3. Open order with Shipments comments
4. Open Order Shipments tab

**Actual result**:
Line below the last product is missing
![Screenshot 2022-01-14 at 12 52 54](https://user-images.githubusercontent.com/73526235/149504182-2991bf70-5adb-4338-8db8-1dcdd8152d2c.png)

**Notes:**
It's displayed in Mobile view
_____________________
**4.Description**:
Horizontal scroll appears if order has long comment

**Expected behavior**:
No horizontall scroll

**To Reproduce**:
1. Log in
2. Open My orders
3. Open order with long comment

**Actual result**:
Horizontal scroll appears
https://drive.google.com/file/d/1Ti8PORSYvuiBHd7OCu9cnfDP-tQfgTe3/view?usp=sharing
______________________________
**5.Description**:
Please, add lines for comments on the left side like in a screenshot
![Screenshot 2022-01-14 at 12 50 02](https://user-images.githubusercontent.com/73526235/149503962-7d8cdede-dd24-4fdb-8e93-22a918208a04.png)

**Comment by aleksandrakorolova** [comment]
1. Fixed
2. Can reproduce for Refund tab
![Screenshot 2022-02-10 at 10 43 08](https://user-images.githubusercontent.com/73526235/153375649-546a0e12-f7b1-4fbd-8fc5-f5cbdfab487b.png)
3. Fixed
4. Fixed
5. Fixed

**Comment by Elena-Evsa** [comment]
1. Passed
2. Falied: wrong order of comments on shipment tab on IOS (same for invoice and refund)
![image](https://user-images.githubusercontent.com/84388061/155093158-7a0e355d-e057-49b3-bbdb-19d6915b15aa.png)

expected: 
![image](https://user-images.githubusercontent.com/84388061/155093257-e32ceabf-803c-4997-ab4c-5d65c74d4f01.png)
3. Passed
4. Passed
5. Passed
