### ISSUE TITLE
Add URL parameters to the homepage to track InApp sessions

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#4123]
**Description**:
Please implement UTM parameters (`utm_source` and `utm_medium`) for the start page of the application with the following values:

- utm_source=homescreen
- utm_medium=scandiPWA

**How to test**:

1. Install the app on the home screen
2. Launch it 
3. Copy the URL. 
4. When you paste the URL it should have the UTM parameters that were supposed to be applied. Example of a URL: https://beautyworksonline.com/en_US/?utm_source=homescreen&utm_medium=scandiPWA
5. Click on the logo to go to the homepage again
6. Now it should be the normal URL without the UTM parameters e.g. https://beautyworksonline.com/en_US

**Questions we want to answer**:

- How many people are using the InApp PWA version using the home screen icon?
- How many transactions are being placed in such a way?

**Additional context**:
Requested by the Analytics team.
Read here for more detail: https://www.notion.so/scandiweb/How-to-track-InApp-sessions-traffic-that-uses-the-website-via-App-saved-on-homescreen-d6d4a9fe8d914cd388aaf681751c74bb

**Comment by riha112** [comment]
PR: https://github.com/scandipwa/customization/pull/24
