### ISSUE TITLE
Extension installation causes default theme styles to break

### ISSUE THREAD

**Issue by ramona-cunska** [scandipwa/scandipwa#4127]
**Description**:
Recently we have encountered an issue on our project that styles are rendered differently when theme is build in production mode compared to development mode. In production mode some of the base styles have taken priority over their overrides. This is caused by installing PWA extensions.

The reason behind this seems to be that style files are split into chunks per areas and PWA extensions affect the order in which these chunks are loaded.

So far I have found 2 reasons why this happens:
1. Adding and importing a new stylesheet inside extension (file name should contain any of the keywords listed below, e.g. ProductGiftCardAttributes.style.scss)
2. Importing a core component inside extension (imported component should contain any of the keywords listed below, e.g. ProductCard)

Keywords: product, checkout, cart, widget, account, category, wish

**Expected behavior**:
1. Styles are rendered in the same order in development and product modes
2. main_styles chunk file is always loaded first when theme is built in production mode

**Screenshots, Video, Logs**
Before module installation:
![issue_before](https://user-images.githubusercontent.com/15155867/150100861-7e4752b5-c1eb-4994-ac88-95b681ef15bd.jpg)

After module installation:
![issue_after](https://user-images.githubusercontent.com/15155867/150100891-c0b43ebb-4ea5-4e91-890e-b427a57e6aec.jpg)

**To Reproduce**:
1. Install GTM extension: https://marketplace.scandipwa.com/google-tag-manager-3.html (issue is not limited to this specific extension)
2. Build theme in production mode
3. Observe that main_styles.chunk.css is not the first css file loaded in head
4. Observe that PDP page styles are affected on mobile

**Versions**:
- ScandiPWA: 5.0.3

**Comment by chatart** [comment]
@ramona-cunska 
Unfortunately, we have the same issue with GTM extension on scandiPWA 5.0.3. Did you manage to find any solution?

**Comment by alfredsgenkins** [comment]
Hey! It might be solved using the https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroupscachegrouppriority specified in this line: https://github.com/scandipwa/scandipwa/blob/ee24ab47fceff4fe8abdde7c10e6d37265ccee5b/packages/chunk-optimizer/build-config/craco.js#L162

I think the exceptions must be made for main chunk 🤔

**Comment by carinadues** [comment]
Fixed in #4212
