### ISSUE TITLE
Install app instead of create a shortcut

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#4144]
**Description**:
When clicking on the button to Install app, we want it to do so instead of creating a shortcut.

**Expected behavior**: 
![image](https://user-images.githubusercontent.com/82165392/150540610-c5ffa355-d68e-4a7e-b2e8-3e25352a6114.png)

**Actual behavior**: (sorry for the low quality)
![image](https://user-images.githubusercontent.com/82165392/150539796-99c4cac9-daa2-43ae-a187-56fe3ab4313d.png)

**Detailed demonstration in Video**:
https://www.loom.com/share/c1d46c4d687641f2b9b922c6997edb44

**To Reproduce**:
1. Go to https://scandipwapmrev.indvp.com/
2. Install it as a chrome app
3. Click on the triple points
4. Click on Copy URL

**Additional context**:
Necessary for issue https://github.com/scandipwa/scandipwa/issues/4123

**Comment by pablobentivengo** [comment]
The problem was that Service worker was not being installed. Service worker is one of the requirements to install a PWA.

Issue was fixed on 5.2.4 where SW is now being installed.
