### ISSUE TITLE
Error message 'Cannot read properties of undefined (reading 'props')' appears in the console when changing quantity for grouped product

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4225]
**Description**:
Error message 'Uncaught TypeError: Cannot read properties of undefined (reading 'props')' appears in the console when changing quantity for grouped product

**Expected behavior**:
No errors

**To Reproduce**:
1. Open Grouped product 
2. Change quantity for one of products

**Actual result**:
Error message 'Uncaught TypeError: Cannot read properties of undefined (reading 'props')' appears in the console
![Screenshot 2022-02-02 at 14 18 50](https://user-images.githubusercontent.com/73526235/152152597-318f65ee-0fb1-4a4e-90fe-a4e2033a0522.png)

**Comment by EriSilver** [comment]
Unable to reproduce the error 
https://drive.google.com/drive/folders/1lbW1MwgyPC_raO6IjWjNlTMPEV3ur857

PDP url 
https://scandipwapmrev.indvp.com/default/grouped-sunglasses.html

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce on the latest version
