### ISSUE TITLE
Grouped product is not added to cart if it contains Out of stock child product

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4233]
**Description**:
Grouped product is not added to cart if it has Out of stock child product
message: "There are no source items with the in stock status"

**Expected behavior**:
Grouped product is added to cart if it has Out of stock child product

**Screenshots, Video, Logs**
https://vimeo.com/672758116/b7da09b661

**To Reproduce**:
1. Open https://scandipwapmrev.indvp.com/default/grouped-sandals.html
2. Click 'Add to cat'

**Actual result**:
Grouped product is not added to cart if it contains Out of stock child product

**Comment by aleksandrakorolova** [comment]
The same situation if child product has setting Minimum Qty Allowed in Shopping Cart and user tries to add product to cart with quantity less than Minimum Qty Allowed in Shopping Cart but not zero (for child product)
Product: https://master.d25kd40decjpue.amplifyapp.com/default/grouped-sunglasses.html
Set quantity for Config Sunglasses-Large size to 1
