### ISSUE TITLE
Placeholders for layered navigation looks ugly

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4235]
**Description**:
Placeholders for layered navigation look ugly.

**Expected behavior**:
Placeholders for layered navigation look like:

<img width="960" alt="Sem título" src="https://user-images.githubusercontent.com/82165392/156371543-1738caae-cf5d-4b84-ba73-8dae7c373627.png">

**Screenshots, Video, Logs**

![image](https://user-images.githubusercontent.com/84388061/152169709-a701b2e0-8308-4e67-9d8f-29fed6a6ca89.png)

**To Reproduce**:
1. Open any PLP

**Comment by carinadues** [comment]
It could also be a large rectangle like 
![image](https://user-images.githubusercontent.com/82165392/156359522-f1186971-c7dd-4b3f-8303-4c451f72b38a.png)
