### ISSUE TITLE
Mobile: Menu disappears fast on CMS pages

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4243]
**Description**:
Menu disappears fast on CMS pages when user scrolling

**Expected behavior**:
Menu disappears on CMS pages same as on PLP, PDP etc

**Screenshots, Video, Logs**
https://drive.google.com/file/d/1mXqdcBuJUhixXwp4wBh7o9-xQPjSAPQy/view?usp=sharing

**To Reproduce**:
1. Open on mobile
https://master.d25kd40decjpue.amplifyapp.com/default/about-us
https://master.d25kd40decjpue.amplifyapp.com/default/hakuna-matata-2

**Actual result**:
Mobile: Menu disappears fast on CMS pages

**Comment by SalimMersally** [comment]
I checked this issue with @AleksandrsKondratjevs and we found out that there is no problem with the navigation menu. it is actually related to the content of the CMS page, there is something wrong with the content and it is not parsed correctly, this caused the menu to be pushed out of view.

**Comment by neeeeecka** [comment]
Can't reproduce on real Android also tested on browserstack iphone: https://drive.google.com/file/d/15LQhI3CaYuuIOY_j1fde5dRVK_7VhtvH/view?usp=sharing

**Comment by Elena-Evsa** [comment]
Can not reproduce
