### ISSUE TITLE
Duplicate of success message appears when logging in on shipping step

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4271]
**Description**:
Duplicate of success message appears when logging in on shipping step

**Expected behavior**:
No duplicate

**To Reproduce**:
1. Open PDP
2. Add product to cart
3. Open Shipping step
4. Log in (Click on 'Sign in' button few times)

**Actual result**:
Duplicate of success message appears when logging in (User see success message when address appear on shipping step and then success message appears when summary block is loaded)
https://drive.google.com/file/d/146dU7v35DKZutsaJv2RmE4Ss_Rk5kPPx/view?usp=sharing

**Comment by VanilStorm** [comment]
I can't reproduce duplicate of success message

**Comment by aleksandrakorolova** [comment]
Please, try to click on button 'Sign in' a few times
