### ISSUE TITLE
Mobile: Navigation bar disappears for few sec and then appears again when adding product to cart

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4272]
**Description**:
Mobile: Navigation bar disappears for few sec and then appears again when adding product to cart

**Expected behavior**:
Navigation bar doesn't disappear

**To Reproduce**:
1. Open PDP in mobile view
2. Tap 'add to cart'

**Actual result**:
Navigation bar disappears for few sec and then appears again
https://drive.google.com/file/d/1VD6vjj9WkhnopG9HfKFmM8q6bgM_nBMa/view?usp=sharing

**Comment by leonazava** [comment]
On master, no longer replicable.
