### ISSUE TITLE
Footer jumps when PLP is loading if user opened it from block on homepage

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4273]
**Description**:
Footer jumps when PLP is loading if user opened it from block on homepage

**Expected behavior**:
Footer doesn't jumps when page loading

**To Reproduce**:
1. Open Homepage
2. Click on button 'Shop Women' in Homepage category preview block

**Actual results**:
Footer jumps 
https://drive.google.com/file/d/15_NUJb9Lyy0CgWDFzQeDgtTYPkecQHZW/view?usp=sharing

**Comment by Elena-Evsa** [comment]
Footer jumps if user click on Button on CMS page which leads to PLP
https://vimeo.com/696031293/fee6d1d059
