### ISSUE TITLE
Cart token isn't updated when switching website 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4277]
**Description**:
Cart token isn't updated when switching website 

**Expected behavior**:
Product is added to cart

**To Reproduce**:
1. Open Store X in Website A
2. Open Store Y in Website В
3. Open PDP
4. Add product to cart

**Actual result**:
Cart token isn't updated when switching website => Error message: "Can't assign cart to store in different website." appears
https://drive.google.com/file/d/1iANHvv6YF3VXQg-0bGjUFwWczepu_JV7/view?usp=sharing

**Comment by zans-laksa** [comment]
1. Fetch the website for the current store.
2. Save website and cart token in the localstorage as key-value pairs. `{"base": "1sdsadsad"}`
3. Adjust the `setGuestQuoteId` and `getGuestQuoteId` functions so they will get the cart token for the current website.
4. If the token is missing, the scandipwa will send the request to get it and will store it to the local storage using the `setGuestQuoteId` function.
