### ISSUE TITLE
ScandiPWA 5.2.4 fails to compile

### ISSUE THREAD

**Issue by raivisdejus** [scandipwa/scandipwa#4306]
**Description**:
Followed steps from quick setup https://docs.scandipwa.com/quick-start-guide
Build fails with error:
```
Failed to compile.

Failed to load config "@scandipwa" to extend from.
Referenced from: BaseConfig
```

**Expected behavior**:
App builds and loads in the window opened by `yarn start`

**To Reproduce**:
```
npm init scandipwa-app my-first-app
cd my-first-app/
npm start
```

**Versions**:
- ScandiPWA: 5.2.4
- Node: v14.19.0
- OS: Ubuntu 20.04.3 LTS

**Comment by carinadues** [comment]
Closing as the issue couldn't be reproduced again.
