### ISSUE TITLE
Height of dropdown fields is 44.6 px 

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4314]
**Description**:
Height of all dropdown fields is 44.6 px 

**Expected behavior**:
Height of dropdown fields is 48 px 

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/154677961-e7d086dc-85bb-4873-810b-d26dd5828225.png)

**To Reproduce**:
1. Open any page with dropdown https://master.d25kd40decjpue.amplifyapp.com/default/bundle-sandals-with-dynamic-price.html 

**Actual result**:
Hight of all dropdown fields is 44.6 px

**Comment by aleksandrakorolova** [comment]
On Android: Dropdown is 45.222px
![Screenshot 2022-02-24 at 15 15 09](https://user-images.githubusercontent.com/73526235/155530934-9deb6609-5578-4270-8d2b-0a5ecd676ae2.png)

On iOS: Dropdown is 51px
![Screenshot 2022-02-24 at 15 11 34](https://user-images.githubusercontent.com/73526235/155530503-e8a2269e-dc37-44b4-8a33-b52524123f22.png)
