### ISSUE TITLE
'Nickname' is not aligned with 'Price' in write a review popup

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4325]
**Description**:
'Nickname' is not aligned with 'Price' in write a review popup

**Expected behavior**:
'Nickname' is aligned with 'Price' in write a review popup
![image](https://user-images.githubusercontent.com/82165392/172505555-acfd0785-66a5-47a3-aafc-36f9e8eaca46.png)

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/155084732-1c40549a-5737-4dfe-a8df-2cba67b16ab3.png)

**To Reproduce**:
1. Open any PDP 
2. Click on 'Write a review'

**Actual result**:
'Nickname' is not aligned with 'Price' in write a review popup

**Comment by aleksandrakorolova** [comment]
Reopened because can reproduce issue 
![Screenshot 2022-04-20 at 08 33 06](https://user-images.githubusercontent.com/73526235/164157699-c7b6ceec-41dd-420c-a5ec-772df39ad6f6.png)
