### ISSUE TITLE
Fix buttons in 40kSKU

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#4329]
**Description**:
Please fix the buttons in 40kSKU. Make the whole text fit in one single line and centralize the buttons in relation to the images.

**Expected behavior**:
The whole text should fit in one single line and the buttons are to be centralized in relation to the images.

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/82165392/155158931-bd9edae6-c05a-48c5-a354-798234697b4f.png)

**To Reproduce**:
1. Go to https://40kskudemo.scandipwa.com
2. Scroll down a bit.

**Comment by Mohamed-Ahmed711** [comment]
It is working fine on my browser, I opened it with google chrome and firefox. 
![Screenshot from 2022-02-22 20-19-34](https://user-images.githubusercontent.com/99433797/155194797-62bdce31-5ba3-4f48-afd0-e9bd4556fd35.png)

**Comment by carinadues** [comment]
@Mohamed-Ahmed711 test it with a smaller window, or more zoom. Also, please centrally align the buttons.
