### ISSUE TITLE
Redundant <meta title=""> tag

### ISSUE THREAD

**Issue by PeterAtger** [scandipwa/scandipwa#4341]
**Description**:
According to Google, only the <title> tag is taken into consideration, and the `<meta title>` tag, which we manually remove is redundant.

**Expected behavior**:
Only the <title tag is rendered>

**To Reproduce**:
1. Go to any page
2. Inspect the page
3. Notice there are two tags, one is <title> and the other is `<meta title>`

**Additional context**:
This is caused by updateMeta function in the Meta component.

**Comment by aleksandrakorolova** [comment]
Closed because Meta title can be optional but someone might need it
