### ISSUE TITLE
Mobile: line is missing under currency and line under compare is bold

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4350]
**Description**:
Mobile: line is missing under currency and line under compare is bold

**Expected behavior**:
Mobile: line is present under currency and line under compare is normal (same as in 5-0-0 version)
<img src= "https://user-images.githubusercontent.com/84388061/155681416-232ac46d-b83c-4dd6-82b7-e2ba2a558042.png" width="250" />

**Screenshots, Video, Logs**
<img src= "https://user-images.githubusercontent.com/84388061/155681083-3acaf81e-7fb9-4f90-9fb8-3ff2fcd20dfc.png" width="250" />

**To Reproduce**:
1. Open FE
2. Tap on menu

**Actual result**:
line is missing under currency and line under compare is bold

**Comment by aleksandrakorolova** [comment]
Lines between currency and store switchers, store switcher and compare list are bold
Notes: Line is displayed below all dropdowns on the website (PLP, PDP, Checkout, My account)
![Screenshot 2022-03-04 at 08 10 15](https://user-images.githubusercontent.com/73526235/156709781-b1003cf6-6eaa-4309-a9ce-ecd4788b91ac.png)
