### ISSUE TITLE
Placeholder for Layered navigation is missing on PLP when opening page for the first time

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4375]
**Description**:
Placeholder for Layered navigation is missing on PLP when opening page for the first time

**Expected behavior**:
Placeholder with loader is displayed 

**To Reproduce**:
1. Open PLP in incognito mode

**Actual result**:
Placeholder for Layered navigation is missing when opening page for the first time
https://drive.google.com/file/d/1imeCQR8J5znV1ij6djmpPv5--wQXBNuj/view?usp=sharing

**Comment by Elena-Evsa** [comment]
Still can reproduce: after first open of PLP in incognito Layered navigation is missing  https://vimeo.com/694883293/04b09043da
