### ISSUE TITLE
Mac: Option is cropped in the dropdown on the website 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4478]
**Description**:
Mac: Option is cropped in the dropdown on the website 

**Expected behavior**:
Option isn't cropped in the dropdown 

**To Reproduce**:
1. Open PDP with dropdown

**Actual result**:
Option is cropped in the dropdown 
![Screenshot 2022-03-16 at 14 24 09](https://user-images.githubusercontent.com/73526235/158589885-43d659b1-e45c-4769-b109-8983761b06ee.png)

**Additional context**:
Mac, iOS
the same situation on PLP, checkout, my account

**Comment by florianf22** [comment]
Can I get more perspective on this? cropped horizontally or vertically?

**Comment by aleksandrakorolova** [comment]
Vertically, especially letters g, j, y, p
![Screenshot 2022-03-16 at 14 24 09](https://user-images.githubusercontent.com/73526235/158743872-240e43a2-95de-40a6-b922-3b57a6fd345a.png)

**Comment by aleksandrakorolova** [comment]
Still, can reproduce
![Screenshot 2022-04-01 at 11 32 16](https://user-images.githubusercontent.com/73526235/161226538-b4e5d136-2c7f-4770-b840-298c739844cd.png)
