### ISSUE TITLE
Safari: Dropdown closes gradually on PDP

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4498]
**Description**:
Safari: Dropdown closes gradually on PDP

**Expected behavior**:
Dropdown closes as in Chrome 

**To Reproduce**:
1. Open PDP with Dropdown
2. Open dropdown
3. Select option

**Actual result**:
Dropdown closes gradually (it comes transparent and user can see background through it)
https://drive.google.com/file/d/11HZlY9ihqqXULyvdqjJWeQ4Tb7izJvX8/view?usp=sharing

**Additional context**:
Safari

**Comment by florianf22** [comment]
Could you please verify what version of safari you're using, it seems very to hard to reproduce this. seems like Apple made some changes and it's no longer an issue. I've made a PR already, can you please check?

**Comment by aleksandrakorolova** [comment]
Safari version - Version 14.1.2 (14611.3.10.1.7)
ok, I will check
