### ISSUE TITLE
User is redirected to billing step if user didn't fill form in shipping step

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4501]
**Description**:
User is redirected to billing step if user didn't fill form in shipping step

**Expected behavior**:
Required empty fields become red and error message 'This field is required!' appears below field + page scrolls to the field with error
 
**To Reproduce**:
1. Open PDP
2. Add product to cart
3. Go to the shipping step
4. Don't fill form
5. Click on Proceed to Billing

**Actual result**:
User is redirected to the billing step
https://drive.google.com/file/d/1q02Tpubs-fDs86y-HE3xO2ktz8WhLLmb/view?usp=sharing

**Additional context**:
User can't complete order

**Comment by carinadues** [comment]
Can't reproduce anymore.
