### ISSUE TITLE
PDP's stuck after the second page load 

### ISSUE THREAD

**Issue by Ylmzef** [scandipwa/scandipwa#4513]
**Description**:
PDP's not loading for the second visits.

**Expected behavior**:
On PLP open product page from new window wait until load after that open another one product page from new window. It will be loading too.
But after that other product page's will be stuck for product informations.

This also applies to external visitors.
Example:
if someone clicks on the ads or from the search results and visits the PDP, page's does not load for next visits..

**To Reproduce**:
1. Go to https://luma-demo.scandipwa.com/women.html
2. Open some product page's from new window

**Comment by Elena-Evsa** [comment]
Can not reproduce on current version of ScandiPWA. Let check demo websites after update to current version

**Comment by Ylmzef** [comment]
I tested it on https://luma-demo.scandipwa.com/women.html
The PDP still stuck on loading product details.

**Comment by carinadues** [comment]
Test after updating the demos with 5.2.7

**Comment by Ylmzef** [comment]
Still same..

**Comment by carinadues** [comment]
Yes, I can reproduce it too
