### ISSUE TITLE
Qty = 'Default Stock' shown on PDP if Default Stock less than 0

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4625]
**Description**:
Qty = 'Default Stock' shown on PDP if Default Stock less than 0
Numbers is changing if user change the size of screen

**Expected behavior**:
Qty = 1 or 'Minimum Qty Allowed in Shopping Cart' shown on PDP if Default Stock less than 0

**Screenshots, Video, Logs**
https://vimeo.com/693932406/7b0975aa8a

**To Reproduce**:
1. Open https://master.d25kd40decjpue.amplifyapp.com/default/simple-watch.html
https://master.d25kd40decjpue.amplifyapp.com/default/honor-smart-min-2.html
2. Change the size of screen

**Actual result**:
Qty = 'Default Stock' shown on PDP if Default Stock less than 0

**Comment by aleksandrakorolova** [comment]
Still, number changes when resizing window if product quantity in stock is less than minimum salable quantity
**Product:** https://master.d25kd40decjpue.amplifyapp.com/default/virtual-shorts.html
**Video:** https://drive.google.com/file/d/1cpTFDwQmPOESQTwcOhjSHlMMrdmfu_jZ/view?usp=sharing
