### ISSUE TITLE
Currency without set rate is displayed in currency switcher on the website

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4637]
**Description**:
Currency without set rate is displayed in currency switcher

**Expected behavior**:
New currency without rate is missing in currency switcher as in default magenta
![Screenshot 2022-03-31 at 13 12 50](https://user-images.githubusercontent.com/73526235/161032231-afa95bc9-561d-4b1f-8942-28766497a042.png)

**To Reproduce**:
**Admin panel:**
1. Open Admin panel -> Go to Stores -> Configuration -> Feneral -> Currency Setup
2. Select new currency in Allowed Currencies
3. Save
4. Go to Stores -> Currency Rate
5. Make sure that rate is missing for new currency
6. Clear cache

**FE:**
1. Open Website
2. Open Currency switcher

**Actual result**:
New currency without rate is displayed in currency switcher
![Screenshot 2022-03-31 at 13 13 02](https://user-images.githubusercontent.com/73526235/161032259-89534520-1a9c-48d0-b40b-9ae1d2a30e10.png)

**Comment by Elena-Evsa** [comment]
recheck also after #3748
