### ISSUE TITLE
Loaders shown twice if user login on billing step

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4660]
**Description**:
Loaders shown twice if user login on billing step

**Expected behavior**:
Loaders shown once if user login on billing step

**Screenshots, Video, Logs**
https://vimeo.com/694895781/6bca603b05

**To Reproduce**:
1. Open FE
2. Add virtual product to cart
3. Click mini cart > Secure checkout
4. Enter email
5. Login

**Actual result**:
Loaders shown twice if user login on billing step

**Comment by aleksandrakorolova** [comment]
Can reproduce related issue
https://vimeo.com/718656133/d9cb9dec3d

**Comment by Elena-Evsa** [comment]
Fields for login is not disappear on checkout step if user logged in on checkout step with help of 'My account' icon
https://master.d25kd40decjpue.amplifyapp.com/default/
