### ISSUE TITLE
Background for first image in carousel on PDP painted by Secondary color 'Highligh'

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4710]
**Description**:
- Background for first image on PDP painted by Secondary color 'Highligh'
- Highligh color shown in image popup is user click on default image (if custom image is absent)
- Also Highligh color is blinking if user zoom first image
https://vimeo.com/700408470/498f281acd

**Expected behavior**:
- The background for the first image in the carousel on PDP is the same as all the images in the carousel
- The default image is shown in the popup
- The background doesn't blink when the user opens the popup, right before the image appears

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/163797318-874cc190-48f2-4836-8e64-e70fcfe412ec.png)

**To Reproduce**:
Admin: 
1. Stores > Configuration > SCANDIPWA > Color customization > Secondary colors (preferably grey)
3. Change color for 'Highlight'
FE:
5. Open any PDP on pmrev: http://scandipwapmrev.indvp.com/default/elary-watch-tier.html
6. Click on image

PDP without images http://scandipwapmrev.indvp.com/default/bag-empty-simple.html

**Actual result**:
Background for first image on PDP painted by Secondary color 'Highligh'

**Comment by aleksandrakorolova** [comment]
1. Fixed
2. Still, Product Image Placeholder isn't displayed
![Screenshot 2022-07-18 at 15 02 11](https://user-images.githubusercontent.com/73526235/179506970-6b206a1d-8bd9-4c80-91cb-922f6ba51604.png)
3. Still, blank pop-up is displayed for few sec and then image appears
https://vimeo.com/730974071/b39ed50eb6
