### ISSUE TITLE
PDP isn't loaded until refreshing page if user opened page in incognito after clearing cache in admin panel

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4742]
**Description**:
PDP isn't loaded until refreshing page if user opened page in incognito after clearing cache in admin panel

**Expected behavior**:
PDP is loaded

**To Reproduce**:
**Admin panel:**
1. Open Admin panel -> Go to Cache Managment 
2. Clear cache

**FE:**
1. Open PDP in incognito mode
2. Wait 

**Actual result**:
PDP isn't loaded until refreshing page

**Comment by Elena-Evsa** [comment]
Same for Home page
Page loaded after step 3

1. Open PDP in incognito mode
2. Wait
3. Reload page

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce on the latest version
