### ISSUE TITLE
Ooops page opens for few sec and not selected currency is displayed for products if user switched currency on PLP

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4782]
**Description**:
Ooops page opens for few sec and not selected currency is displayed for products if user switched currency on PLP

**Expected behavior**:
No errors
Actual currency is displayed for products and in currency switcher

**To Reproduce**:
1. Open PLP
2. Switch currency

**Actual result**:
Ooops page for few sec and not selected currency is displayed for products and in currency switcher
Error message ‘RangeError: Invalid currency code’ appears in the console
![Screenshot 2022-05-13 at 15 23 09 (2)](https://user-images.githubusercontent.com/73526235/168285804-78866957-3f3a-49e0-b4a0-4d9ff6caeece.png)
https://drive.google.com/file/d/197YkXrvF9_xnQl7b2G9U20Rmd2HSbt45/view?usp=sharing

**Comment by Elena-Evsa** [comment]
Ooops page absent but issue #3748 (from Carina's comment) still present
