### ISSUE TITLE
Info in address card on Shipping are shown not the same as on Luma

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4800]
**Description**:
Info in address card on Shipping are shown not the same as on Luma
Name of region and country is absent

**Expected behavior**:
Same as on Luma Info in address card on Shipping are shown, but ScandiPWA styling and names of rows

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/169242050-f2df1cd5-556e-487c-871e-522b59661194.png)

**To Reproduce**:
1. Open FE
2. Login to account with saved address
3. Add product to cart
4. Open shipping step

**Comment by aleksandrakorolova** [comment]
**Null** is displayed if Saved address doesn't have State. 
![Screenshot 2022-06-03 at 11 30 28](https://user-images.githubusercontent.com/73526235/171819002-6e58e41c-3efd-4921-9216-a7a9734f1dee.png)
Please, don't show anything if state isn't selected/entered
