### ISSUE TITLE
Default Rating Value is displayed in Write a Review form if for this store is set specific Rating Title in Admin panel

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4814]
**Description**:
Default Rating Value is displayed in Write a Review form if for this store is set specific Rating Title in Admin panel

**Expected behavior**:
'Rating Title' for Store X (United States Price) is displayed for existing reviews and in 'Write a Review' form 
If 'Rating Title' for specific Store isn't set that shows default value 

**To Reproduce**:
Admin Panel:
1. Stores -> Rating 
2. Open Rate Y
3. Enter Rating Title for Store X
4. Save
5. Clear cache

FE:
6. Open Store X
7. Open PDP with Reviews
8. Open Write a Review form

**Actual result**:
Rating Title for Store X (United States Price) is displayed for existing reviews - correct
Default Rating Value (Price 3) is displayed in Write a Review form - issue
![Screenshot 2022-05-23 at 12 36 06](https://user-images.githubusercontent.com/73526235/169791900-cbf239ea-8ffe-4318-8385-ad282a179ec9.png)

**Comment by carinadues** [comment]
Fixed in https://github.com/scandipwa/review-graphql/commit/b8bf620a892ddaa0b367aadc8e1e7abef30e055d
