### ISSUE TITLE
Ooops page when logged in user is opening /wishlist page if wishlist is disabled

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4850]
**Description**:
Ooops page when logged in user is opening /wishlist page if wishlist is disabled

**Expected behavior**:
404 page 

**To Reproduce**:
1. Stores -> Customer -> Wishlist
2. Set Enabled to No 
3. Save
4. Clear Cache

FE:
5. Open Sign in form
6. Log in
7. Open wishlist page /wishlist

**Actual result**:
Ooops page opens
Error message 'TypeError: Cannot read properties of undefined (reading 'title')' appears in the console
![Screenshot 2022-05-30 at 12 30 02](https://user-images.githubusercontent.com/73526235/170962649-1a2b587d-e859-4318-a214-18c907b9edda.png)

**Comment by Elena-Evsa** [comment]
404 page - appears again
![image](https://user-images.githubusercontent.com/84388061/174323783-8d0704ae-3388-4217-ba0d-4b4be8f78022.png)
