### ISSUE TITLE
Mobile: 0 tax and 0 subtotal are shown in Cart if there are no products

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4922]
**Description**:
0 tax and 0 subtotal are shown in Cart if there are no products.

**Expected behavior**:
0 tax and 0 subtotal are absent in Cart if there are no products.
Text 'There are no products in cart.' is shown.
![image](https://user-images.githubusercontent.com/84388061/173537506-ea985123-001b-4e1b-a2c4-a2440b29195b.png)

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/173538068-3abfadc8-1d25-4a78-9c64-ebe1ec2c620f.png)

**To Reproduce**:
1. Open https://scandipwapmrev.indvp.com/default/cart on mobile

**Actual result**:
0 tax and 0 subtotal are shown in Cart if there are no products

**Comment by aleksandrakorolova** [comment]
Subtotal 0 is displayed when refreshing page
