### ISSUE TITLE
Can't add other products to cart if a product already added to the cart becomes out of stock

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#4940]
**Description**:
Users can't add products to the cart if a product already in the cart becomes out of stock. An error message appears saying 'Some of the products are out of stock' and the user can't add any product. It is not clear to the user which product is out of stock (which is the one already added to the cart). Also, the user only finds out that his product is OOS when he reaches the billing step.

**Expected behavior**:
- The user can add other products to the cart without errors.
- An error message 'Product is out of stock.' is displayed in the cart near out of stock product
- The checkout button is disabled

![image](https://user-images.githubusercontent.com/82165392/174604662-d03f549b-0774-43bc-a355-5d445469d1b2.png)

**Actual result**
![image](https://user-images.githubusercontent.com/82165392/174595044-eaa95566-6be3-4253-852e-b56badd28d68.png)

**To Reproduce**:
1. Add a config product to the cart https://scandipwapmrev.indvp.com/default/baggini-bagpack-108.html
2. Add another product X to the cart - it should work.
3. Open the config product in the admin panel and set the parent product to Out of Stock
4. Try adding the same product X to the cart - error message appears.

**Additional Info**:
Related issue: https://github.com/scandipwa/scandipwa/issues/4940

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce 
https://vimeo.com/746806777/d99478055f
