### ISSUE TITLE
Can't add an specific config parent product to cart

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#4941]
**Description**:
Can't add an specific config parent product to cart.

**Expected behavior**:
The product is in stock so it should be added to the cart.

**Actual result**:

Error message ‘Product that you are trying to add is not available.‘  appears:

![image](https://user-images.githubusercontent.com/82165392/174609981-4d9bd941-4f46-44e7-b566-2846a5d81370.png)

**To Reproduce**:
1. Go to https://master.d25kd40decjpue.amplifyapp.com/default/baggini-bagpack-108.html
2. Click "Add to cart"

**Comment by carinadues** [comment]
Error appears for products on screenshots if user adding it to cart:
https://master.d25kd40decjpue.amplifyapp.com/default/n-chiffon-dress.html
https://master.d25kd40decjpue.amplifyapp.com/default/baggini-bagpack-108.html
![image](https://user-images.githubusercontent.com/84388061/178244889-a8b7e224-bdce-42f7-87e8-bfc1f7c319fc.png)
 
 
 Copied Elena's comment from https://github.com/scandipwa/scandipwa/issues/5009

**Comment by Elena-Evsa** [comment]
https://5-3-2-rc.d25kd40decjpue.amplifyapp.com/default/monitor-config-cross.html

**Comment by zans-laksa** [comment]
@carinadues 
Checked all these products on the pr test instance with Mokans stock status fixes.
All of these products are out of stock there. This explains why it's not possible to add them to the cart.

https://scandipwapmrevprtest-dev.indvp.com/default/n-chiffon-dress.html

**Comment by aleksandrakorolova** [comment]
Closed because it's [Magento issue](https://github.com/magento/magento2/issues/35724)
