### ISSUE TITLE
User can not add to cart Grouped product options from PLP: message shown and user redirected to PDP

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4957]
**Description**:
User can not add to cart Grouped product from PLP: message shown and user redirected to PDP
message: Please, select product options 

**Expected behavior**:
User able not add to cart Grouped product from PLP: message shown and user redirected to PDP

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/175282819-a0e344c7-c9ce-4d8e-ab26-882bf13e4342.png)

**To Reproduce**:
1. Open grouped find here: https://master.d25kd40decjpue.amplifyapp.com/default/kids/jeans.html
bundle product: https://master.d25kd40decjpue.amplifyapp.com/default/bundle-product-with-not-required-radio-buttons.html
2. Hover on 'Grouped jeans' (or find any other grouped product)
3. Click 'Add to cart'

**Actual result**:
Step 3: User redirected to PDP and warning message show

**Comment by aleksandrakorolova** [comment]
Created separate task for found issue - #5016

**Comment by aleksandrakorolova** [comment]
Please, do the same when adding product to cart from compare list
https://vimeo.com/731722239/de959fe559
