### ISSUE TITLE
Button Add to Cart has different size for products in the compare list

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4964]
**Description**:
Button Add to Cart has different size for products in the compare list

**Expected behavior**:
Buttons look as in the screenshot
![Screenshot 2022-06-27 at 10 00 05](https://user-images.githubusercontent.com/73526235/175878829-9a5fc69b-611a-4c2f-a5d8-5aaca059ef32.png)

**To Reproduce**:
1. Open PLP
2. Add products to compare list
3. Open compare list

**Actual result**:
Button add to cart is a different size for products
![Screenshot 2022-06-27 at 09 57 51](https://user-images.githubusercontent.com/73526235/175878714-3829e745-845a-4cf7-9246-41a617d83625.png)

**Comment by Elena-Evsa** [comment]
Same for windows: 
![image](https://user-images.githubusercontent.com/84388061/175898740-499ec1d7-91b5-4090-a9eb-57a44d2a2cee.png)
