### ISSUE TITLE
Circle and rectangle near corresponding radio and checkboxes options are resized if child product has long name

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4970]
**Description**:
Circle and rectangle near corresponding radio and checkboxes options is resized if product has long name

**Expected behavior**:
Circle and rectangle near corresponding radio and checkboxes options saves it's sizes if product has long name

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/175918525-1083e396-08bc-46fe-8da0-bd814ef3bd96.png)

**To Reproduce**:
1. Open https://master.d25kd40decjpue.amplifyapp.com/default/camera-bundle-fixed-price.html

**Actual result**:
Circle and rectangle near corresponding radio and checkboxes options is resized if product has long name

**Comment by aleksandrakorolova** [comment]
Please, do the same for customizable options too
![Screenshot 2022-07-18 at 11 21 00](https://user-images.githubusercontent.com/73526235/179471872-f61fc5bb-ca03-4c34-9be6-e280ff59469b.png)
