### ISSUE TITLE
When Search for product keywords, system redirect into "Something went Wrong" Page

### ISSUE THREAD

**Issue by AprilNJ** [scandipwa/scandipwa#5003]
**Description**:
when input search it's  "Something went Wrong"
**Expected behavior**:

**Screenshots, Video, Logs**
![Screen Shot 2565-07-05 at 16 27 02](https://user-images.githubusercontent.com/108717422/177296891-36a32c00-c3f1-4216-9fe1-ff7a6dbda40b.png)

**To Reproduce**:
1. first time to search can query result 
<img width="318" alt="Screen Shot 2565-07-06 at 08 42 05" src="https://user-images.githubusercontent.com/108717422/177449125-722cccc9-33ff-4c1a-93a2-bbcb0c030afd.png">

<img width="318" alt="Screen Shot 2565-07-06 at 08 43 53" src="https://user-images.githubusercontent.com/108717422/177449343-c3154c5a-228e-41d8-a06f-0bb3353017fc.png">

3. if i want to search again, when i input first word it's redirect to something went wrong page 

** i not find this issue another env. it's happen only on production

**Comment by carinadues** [comment]
Hi, @AprilNJ! 
We couldn't reproduce this issue. Can you describe in detail the steps you took?

**Comment by AprilNJ** [comment]
> Hi, @AprilNJ! We couldn't reproduce this issue. Can you describe in detail the steps you took?

thanks i update reproduce again

**Comment by AprilNJ** [comment]
[](url)> > thanks i update reproduce again
> 
> We tested on our master and couldn't replicate it. We will update the demo sites (production) and test on them. Also, if you could send us a video, it will help a lot :D

**Comment by AprilNJ** [comment]
> > thanks i update reproduce again
> 
> We tested on our master and couldn't replicate it. We will update the demo sites (production) and test on them. Also, if you could send us a video, it will help a lot :D

https://user-images.githubusercontent.com/108717422/178457297-80143b0e-55a1-4caf-8ec9-50b0762d480c.mov
