### ISSUE TITLE
PDP layout is broken if description contain long word without spaces

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#5005]
**Description**:
PDP layout is broken if short or long description contain long word without spaces
Also Right scroll appears on mobile too

**Expected behavior**:
PDP layout is not broken if short description contain long word without spaces
Mobile: Right scroll absent on PDP 

**Screenshots, Video, Logs**

![image](https://user-images.githubusercontent.com/84388061/177333001-91fc5c28-6888-4a91-8b6e-50104e1e9b35.png)

**To Reproduce**:
1. Open https://master.d25kd40decjpue.amplifyapp.com/default/1-simple-product.html or add to other product short description with long word 

**Actual result**:
PDP layout is not broken if short description contain long word without spaces
Mobile: Right scroll absent on PDP

**Comment by aleksandrakorolova** [comment]
Created separate task for found issue - #5099
