### ISSUE TITLE
Can't add products to cart + error fetching product list

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#5009]
**Description**:
Can't add products to cart + error fetching product list

**Expected behavior**:
Products are added to the cart and no error messages appear.

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/82165392/177598791-d074bc03-2252-4799-82ec-87e8552d7a63.png)

![image](https://user-images.githubusercontent.com/82165392/177599040-77a32537-187f-4233-96c0-7a46ea4f0e0b.png)

**To Reproduce**:
1. Go to pmrev
2. Open PDP
3. Try adding a product to the cart

**Additional context**:
The issue appeared after merging one of the following:
https://github.com/scandipwa/customer-graph-ql/pull/36
https://github.com/scandipwa/catalog-graphql/pull/140
https://github.com/scandipwa/store-graphql/pull/34
https://github.com/scandipwa/customization/pull/29
https://github.com/scandipwa/customization/pull/27

**Comment by Elena-Evsa** [comment]
Error appears for products on screenshots if user adding it to cart:
https://master.d25kd40decjpue.amplifyapp.com/default/n-chiffon-dress.html
https://master.d25kd40decjpue.amplifyapp.com/default/baggini-bagpack-108.html
![image](https://user-images.githubusercontent.com/84388061/178244889-a8b7e224-bdce-42f7-87e8-bfc1f7c319fc.png)
