### ISSUE TITLE
Refactor History Usage In SPWA

### ISSUE THREAD

**Issue by zans-laksa** [scandipwa/scandipwa#5043]
We have some inconsistencies in the project.
There are multiple uses of the History API:
* we get the history object from the react router
* we get the history object from the `Util/History`

Both objects are similar, but not 100%. Also `Util/History` can be used to set the location change event listener. But when we push a new location to the router history, the `Util/History` handler isn't fired.
Also, the router history is deeply prop-drilled, while the `Util/History` is accessible globally.

So I suggest refactoring the code, removing prop drilling, and using the `Util/History` only.

**Comment by Elena-Evsa** [comment]
issues related to refactoring here #5173
