### ISSUE TITLE
Error message 'The current customer isn’t authorized' appears when time goes which set in Customer token Lifetime setting

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#5072]
**Description**:
Error message 'The current customer isn’t authorized' appears when time goes which set in Customer token Lifetime setting

**Expected behavior**:
User redirects to Sign in form with the notification message 'Your session is over, you are logged out!'

**To Reproduce**:
1. Open Sign in form
2. Log in
3. Wait some time (for example, 20min)
4. Do some action (go to another page/add product to car and etc)
5. Wait for more than 1h from log in
6. Go to another page in my account

**Actual result**:
Error message 'The current customer isn’t authorized' appears
![Screenshot 2022-07-21 at 16 40 37 (2)](https://user-images.githubusercontent.com/73526235/180228002-89dde0ea-255e-4ca8-9946-cfc3f893fc64.png)

**Additional context**:
By default Customer Token Lifetime (hours) is set 1h
if user logs in and does nothing for an hour -> and then goes to another page -> Works ok

**Comment by neeeeecka** [comment]
I think we will need to merge: https://github.com/scandipwa/scandipwa/issues/5042
before we can fix this.
