### ISSUE TITLE
Can't add specific config products to the cart if product in stock and Product Salable Quantity > 0

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#5148]
**Steps to reproduce:**
1. Open Config product on pmrevprtest-dev instance https://scandipwapmrevprtest-dev.indvp.com/default/straw-shoulder-bag.html
2. Select white color
3. Add to cart
4. Open Config product on pmrev instance https://scandipwapmrev.indvp.com/default/straw-shoulder-bag.html
5. Select white color
6. Add to cart
7. Open Config product on pmrev-dev instance https://scandipwapmrev-dev.indvp.com/default/straw-shoulder-bag.html

**Actual result**
1.Product is in stock
3.Error message "Product that you are trying to add is not available." appears
4.Product is in stock
6.Product is added to cart
7.Product is out of stock

**Expected result**
Product Salable Quantity is 75 in stock => Logically, user can add product to cart

**Testing details**
In this case: Backorders - allow qty below 0 

**Additional context**
pmrevprtest-dev instance with Mokans changes -  https://scandipwapmrevprtest-dev.indvp.com/default/straw-shoulder-bag.html

**Comment by aleksandrakorolova** [comment]
Looks like Magento bug - https://github.com/magento/magento2/issues/35724

**Comment by aleksandrsm** [comment]
@aleksandrakorolova 
It is a Magento bug; changes to in stock resolver don't affect any of the DB data or resolvers handling add2cart events. 
Can close this.
