### ISSUE TITLE
Infinite scroll doesn't work on PLP with mobile

### ISSUE THREAD

**Issue by Ylmzef** [scandipwa/scandipwa#5152]
**Steps to reproduce:**
1. Go to category page
2. Scroll down to bottom slowly
3. After the 20th product it will be infinity loop content
4. You can try same steps with fast scroll too.

**Versions**
- ScandiPWA: 3.2.3
- Magento: 2.4.4
- Android Chrome browser

https://user-images.githubusercontent.com/8562514/184948839-bb7c7839-dc6d-4153-b60f-6ede00469302.mp4

**Comment by ajeetsonkar** [comment]
Hi,
It is not working properly

**Comment by Ylmzef** [comment]
Yes still on 5.3.6

**Comment by Ylmzef** [comment]
Any update about this issue?

**Comment by Ylmzef** [comment]
any update about this bug please? it's still not working properly..
