### ISSUE TITLE
Ooops page appears 

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#5164]
**Steps to reproduce:**
1. Open Home page
2. Enter any search query, for example: Grouped, top

**Actual result**
Ooops page appears any page

**Expected result**
Page opened

**Testing details**
**Screenshot/Screencast**
For search
![image](https://user-images.githubusercontent.com/84388061/185941951-cd6570bd-0286-4155-9685-69128a01c987.png)
For home page:
![image](https://user-images.githubusercontent.com/84388061/185947686-de2ace9a-9d55-4d3c-a64c-a064eacc1049.png)

**Additional info**

> react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'path')
>     at Url.js:51:27
>     at Object.apply (mosaic.js:1:1935)
>     at Proxy.value (CmsPage.container.js:223:24)
>     at Proxy.value (CmsPage.container.js:90:29)
>     at mosaic.js:1:2639
>     at new f (mosaic.js:1:2408)
>     at Object.construct (mosaic.js:1:2710)
>     at n.<anonymous> (createSuper.js:12:24)
>     at new n (CmsPage.container.js:59:8)
>     at new f (mosaic.js:1:2670)

> react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'params')
>     at Proxy.value (SearchPage.container.js:194:26)
>     at Proxy.value (SearchPage.container.js:156:29)
>     at Proxy.value (CategoryPage.container.js:438:40)
>     at Proxy.value (SearchPage.container.js:220:25)
>     at Ba (react-dom.production.min.js:182:192)
>     at Wa (react-dom.production.min.js:181:224)
>     at _u (react-dom.production.min.js:263:490)
>     at bc (react-dom.production.min.js:246:265)
>     at mc (react-dom.production.min.js:246:194)
>     at uc (react-dom.production.min.js:239:172)

**Comment by aleksandrakorolova** [comment]
Issue appeared after #5043
