### ISSUE TITLE
PUT request is never called for `putPersistedQuery` if `graphql` requests return 410 status code.

### ISSUE THREAD

**Issue by neeeeecka** [scandipwa/scandipwa#5181]
**Steps to reproduce:**
1. Run `magento scandipwa:pq:flush` command to clear existing queries caches from redis
2. Run `magento c:f`
3. Open the webpage

**Actual result**
![Screenshot from 2022-09-01 19-25-41](https://user-images.githubusercontent.com/22796372/187952471-36e43a6a-889c-4ad6-bab7-38b2d3888e09.png)

PUT requests are not sent after 410 status received.

**Expected result**
PUT requests should be sent and data should be cached successfully.

**Testing details**
Problem is caused by `Request.js` `executeGet` method try/catch block. Logic is referencing `res` which is an array, instead of an actual `getFetch` result + incorrect handling of try/catch for fetch, fetch only throws error in case of network error, not http error.

**Versions**
- ScandiPWA: 5.3.4

**Comment by Ylmzef** [comment]
How can i apply this patch to the current ScandiPWA installation?

**Comment by AzizKHAN030** [comment]
> How can i apply this patch to the current ScandiPWA installation?

Hello there! for applying these changes you can:
- [override](https://docs.scandipwa.com/developing-with-scandi/override-mechanism) the classes that are changed and apply them in your theme 

Or

- you can create plugin that applies changes into methods and connect it to your theme, and after the release you can disable or delete the [plugin](https://docs.create-scandipwa-app.com/extensions/application-plugins)

**Comment by Ylmzef** [comment]
I have still same issue on 5.3.6

**Comment by Ylmzef** [comment]
> > I have still same issue on 5.3.6
> 
> Hi!, are you able to log in to the admin?

Hi, Yes im able to login to the admin.
