### ISSUE TITLE
Wrong URL opens after user clicked on Share wishlist link in Email

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#5183]
**Steps to reproduce:**
1. Open FE
2. Login 
3. Add products to wish list
4. Open Wishlist
5. Click 'Share'
6. Enter necessary data 
7. Click 'SHARE WISHLIST'

Mailbox:
8. Click on Link in email 'View all Wish List items'

**Actual result**
Wrong URL (without name of store) opens after user clicked on Share wishlist link in Email

**Expected result**
URL opens after click on 'View all Wish List items'

**Testing details**
**Screenshot/Screencast**
https://vimeo.com/745705210/8e7afb218f

**Comment by Elena-Evsa** [comment]
Ralated issues: #4811, #3253, #2352

**Comment by aleksandrakorolova** [comment]
Closed task because link was with http://... 
It works good is open link with http**s**://...
