### ISSUE TITLE
'Products are loading...' is shown on place of number of items on PLP if user is changing type of sorting

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#5190]
**Steps to reproduce:**
1. Open any PLP
2. Select any other type of sorting in 'Sort by...'

**Actual result**
'Products are loading...' is shown on place of number of items on PLP if user is changing type of sorting

**Expected result**
'Products are loading...' is not shown on place of number of items on PLP if user is changing type of sorting
It is enough to show placeholders on place of products while products are changing it's order

**Testing details**
**Screenshot/Screencast**
https://vimeo.com/747560587/2ddf7f1848

**Comment by AleksandrsKondratjevs** [comment]
Should be fixed in 6.1.1
