### ISSUE TITLE
Ooops page when logged in user when to cart

### ISSUE THREAD

**Issue by johanroberthson** [scandipwa/scandipwa#5266]
This is only happening for logged in user. Work good for not logged in user.

**Steps to reproduce:**
1. Logged in as a customer.
2. Add product to cart.
3. Go to checkout page

**Actual result**
Oops page, something get wrong is showing.

**Expected result**
Checkout page should be visible.

**Versions**
- ScandiPWA:6.0.1

**Comment by Elena-Evsa** [comment]
Duplicate of #5244
