### ISSUE TITLE
Mobile: wishlist layout moved right

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#5280]
**Steps to reproduce:**
1. Open FE on mobile
2. Login
3. Open wishlist

**Actual result**
wishlist layout moved right

**Expected result**
wishlist layout centered

**Testing details**
**Screenshot/Screencast**
<img src= "https://user-images.githubusercontent.com/84388061/199561875-a067ea99-eae0-4126-97de-c9c1372366b0.png" width="250" />

**Versions**
- ScandiPWA: 6.0.0

**Comment by aleksandrakorolova** [comment]
Horizontal scroll appears and Menu is cropped when opening wishlist
https://drive.google.com/file/d/1JT1an9gZRgB4CR3sC_b-NGbHTxG2_vmw/view?usp=sharing
