### ISSUE TITLE
Argument for '--jsx' option must be: 'preserve', 'react-native', 'react'. 

### ISSUE THREAD

**Issue by AleksandrsKondratjevs** [scandipwa/scandipwa#5282]
**Steps to reproduce:**
1. Create new project with npx create-scandipwa-app package name.
2. Try to override any typescript component in js.
3. See error on compile

**Actual result**
After making override of tsx files in js compiling is broken.
![image](https://user-images.githubusercontent.com/68007919/199917491-60ded82d-6be4-47ad-90cb-7e3bdba44400.png)

**Expected result**
Should compile without this error.

**Versions**
- ScandiPWA: 6.0.1

**Comment by ukashif2** [comment]
i am getting this error if i am trying to install by npx create scandipwa-app pwa. it is being successfull afte that second command when i run this BUILD_MODE=magento npm run build i am getting this error (error TS6046: Argument for '--jsx' option must be: 'preserve', 'react-native', 'react'.) can you please fix this issue?. also tell me for latest npx what should be requirement like

node version
redis
varnished
scandipwa
typescript

thank you

**Comment by tim-breitenstein-it** [comment]
```
$ BUILD_MODE=magento npm run build

> test-scandipwa@6.0.3 build
> scandipwa-scripts build


NOTE!

     Building as a Magento theme!
     The public/index.html file content will not be taken into account!
     Using content of public/index.php instead!

error TS6046: Argument for '--jsx' option must be: 'preserve', 'react-native', 'react'.
```
