### ISSUE TITLE
eror occor on scandi version 5.3.6 and higher in 

### ISSUE THREAD

**Issue by satyam224152** [scandipwa/scandipwa#5288]
!
**Steps to reproduce:**
1. Open '...'

**Actual result**
[Screenshot from 2022-11-05 13-26-56](https://user-images.githubusercontent.com/76769857/200109943-723ed1e6-8257-416b-b8a8-bd5751c7e22f.png)
![Screenshot from 2022-11-05 13-27-53](https://user-images.githubusercontent.com/76769857/200109964-53ff9f96-d16b-47a3-a015-eef18d2e9899.png)
![Screenshot from 2022-11-05 13-34-42](https://user-images.githubusercontent.com/76769857/200110204-cb5ed070-81c5-43d4-a1b7-d44d909cc25a.png)

1 .layered navigation not working with single or multi select ,
2 .error on product list during to filter ,
3 .404 occer on mens category 

**Expected result**
![Screenshot from 2022-11-05 13-39-59](https://user-images.githubusercontent.com/76769857/200110346-7548b40b-824e-4c46-b426-36e1d8f7dc09.png)

What did you expect to happen?
Screenshot/Screencast can be here

**Testing details**
**Screenshot/Screencast**
If applicable, add screenshots or screen-capture to help explain your problem. If you would like to share logs - please use [fenced code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).

**Versions**
- ScandiPWA: (5.3.6 and higher version)
- Any other composer module, you thing could be related
- Browser version  "Google Chrome";v="99"
- OS Linux ubantu

**Additional context**

**Comment by AleksandrsKondratjevs** [comment]
Please structure issue as required per template.
What proxy you use in package.json?
