### ISSUE TITLE
Product List fetching failed

### ISSUE THREAD

**Issue by ukashif2** [scandipwa/scandipwa#5293]
The Content-Security-Policy directive 'frame-ancestors' does not support the source expression ''unsafe-inline''
espresso-grinders.html:65          GET https://react.jebelz.com/media/webmanifest/manifest.json 404
370Manifest: Line: 1, column: 1, Syntax error.
manifest.json:1          GET https://react.jebelz.com/media/webmanifest/manifest.json 404
manifest.json:1          GET https://react.jebelz.com/media/webmanifest/manifest.json 404
manifest.json:1          GET https://react.jebelz.com/media/webmanifest/manifest.json 404
VM5:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
h @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
a @ service-worker.js:1
o @ service-worker.js:1
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
handleRequest @ service-worker.js:1
(anonymous) @ service-worker.js:1
VM6:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
h @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
a @ service-worker.js:1
o @ service-worker.js:1
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
handleRequest @ service-worker.js:1
(anonymous) @ service-worker.js:1
dispatchers.2c5ebe84.chunk.js:1          GET https://react.jebelz.com/graphql?hash=1464631677&filter_1={%22price%22:{},%22category_id%22:{%22eq%22:1634},%22customer_group_id%22:{%22eq%22:%220%22}}&_currency=%22%22 500
(anonymous) @ dispatchers.2c5ebe84.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
(anonymous) @ dispatchers.2c5ebe84.chunk.js:1
(anonymous) @ dispatchers.2c5ebe84.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
(anonymous) @ dispatchers.2c5ebe84.chunk.js:1
value @ dispatchers.2c5ebe84.chunk.js:1
requestProductListInfo @ category.0a038a9d.chunk.js:1
(anonymous) @ category.0a038a9d.chunk.js:1
value @ category.0a038a9d.chunk.js:1
lu @ main.457cf722.chunk.js:1
Oc @ main.457cf722.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
Qo @ main.457cf722.chunk.js:1
wc @ main.457cf722.chunk.js:1
uc @ main.457cf722.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
Qo @ main.457cf722.chunk.js:1
Xo @ main.457cf722.chunk.js:1
F @ main.457cf722.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
dispatchers.2c5ebe84.chunk.js:1 Can not transform JSON!
(anonymous) @ dispatchers.2c5ebe84.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
(anonymous) @ dispatchers.2c5ebe84.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
Promise.then (async)
(anonymous) @ dispatchers.2c5ebe84.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
Promise.then (async)
(anonymous) @ dispatchers.2c5ebe84.chunk.js:1
(anonymous) @ dispatchers.2c5ebe84.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
(anonymous) @ dispatchers.2c5ebe84.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
(anonymous) @ dispatchers.2c5ebe84.chunk.js:1
value @ dispatchers.2c5ebe84.chunk.js:1
requestProductListInfo @ category.0a038a9d.chunk.js:1
(anonymous) @ category.0a038a9d.chunk.js:1
value @ category.0a038a9d.chunk.js:1
lu @ main.457cf722.chunk.js:1
Oc @ main.457cf722.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
Qo @ main.457cf722.chunk.js:1
wc @ main.457cf722.chunk.js:1
uc @ main.457cf722.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
Qo @ main.457cf722.chunk.js:1
Xo @ main.457cf722.chunk.js:1
F @ main.457cf722.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
VM7:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
h @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
a @ service-worker.js:1
o @ service-worker.js:1
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
handleRequest @ service-worker.js:1
(anonymous) @ service-worker.js:1
VM8:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
h @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
a @ service-worker.js:1
o @ service-worker.js:1
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
Promise.then (async)
a @ service-worker.js:1
o @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
handleRequest @ service-worker.js:1
(anonymous) @ service-worker.js:1
dispatchers.2c5ebe84.chunk.js:1          GET https://react.jebelz.com/graphql?hash=2370674064&sort_1={%22name%22:%22ASC%22}&filter_1={%22price%22:{},%22category_id%22:{%22eq%22:1634},%22customer_group_id%22:{%22eq%22:%220%22}}&pageSize_1=24&currentPage_1=1&_currency=%22%22 404
(anonymous) @ dispatchers.2c5ebe84.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
(anonymous) @ dispatchers.2c5ebe84.chunk.js:1
(anonymous) @ dispatchers.2c5ebe84.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
(anonymous) @ dispatchers.2c5ebe84.chunk.js:1
value @ dispatchers.2c5ebe84.chunk.js:1
(anonymous) @ category.0a038a9d.chunk.js:1
Promise.then (async)
requestProductList @ category.0a038a9d.chunk.js:1
value @ category.0a038a9d.chunk.js:1
(anonymous) @ category.0a038a9d.chunk.js:1
value @ category.0a038a9d.chunk.js:1
lu @ main.457cf722.chunk.js:1
Oc @ main.457cf722.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
Qo @ main.457cf722.chunk.js:1
wc @ main.457cf722.chunk.js:1
uc @ main.457cf722.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
Qo @ main.457cf722.chunk.js:1
Xo @ main.457cf722.chunk.js:1
F @ main.457cf722.chunk.js:1
(anonymous) @ main.457cf722.chunk.js:1
manifest.json:1          GET https://react.jebelz.com/media/webmanifest/manifest.json 404
manifest.json:1          GET https://react.jebelz.com/media/webmanifest/manifest.json 404
manifest.json:1          GET https://react.jebelz.com/media/webmanifest/manifest.json 404
manifest.json:1          GET https://react.jebelz.com/media/webmanifest/manifest.json 404
manifest.json:1          GET https://react.jebelz.com/media/webmanifest/manifest.json 404
manifest.json:1          GET https://react.jebelz.com/media/webmanifest/manifest.json 404
manifest.json:1          GET https://react.jebelz.com/media/webmanifest/manifest.json 404
manifest.json:1          GET https://react.jebelz.com/media/webmanifest/manifest.json 404
manifest.json:1          GET https://react.jebelz.com/media/webmanifest/manifest.json 404
manifest.json:1          GET https://react.jebelz.com/media/webmanifest/manifest.json 404
manifest.json:1          GET https://react.jebelz.com/media/webmanifest/manifest.json 404
manifest.json:1          GET https://react.jebelz.com/media/webmanifest/manifest.json 404

**Comment by AleksandrsKondratjevs** [comment]
Hello!

Please structure issue as per template.

**Comment by ukashif2** [comment]
sorry could not understand. what do you mean?

**Comment by AleksandrsKondratjevs** [comment]
Issue description is structured not correctly. This information doesn't gives nothing on where to start look at issue.
Please check how other issues description written.

**Comment by ukashif2** [comment]
![image](https://user-images.githubusercontent.com/38689288/200479903-61e267d2-4086-4cec-b3ce-94db51162715.png)

![image](https://user-images.githubusercontent.com/38689288/200479992-9eff7da0-8cf8-4a3b-b95b-70b4e03a86e6.png)

See our attachment screenshot that is the problem when i am trying to open category page also on home page is not showing product continue loading with same issue.

**Comment by ukashif2** [comment]
@AleksandrsKondratjevs can you provide me details? what are the solution?.
thank you

**Comment by AleksandrsKondratjevs** [comment]
There is not enough information in issue description, it can be related to BE, FE or just incorrect matching of ScandiPWA theme and Magento. Right now those error messages are not saying much.

Closing this issue due to not correct description structure.
