### ISSUE TITLE
Product List fetching failed with scandipwa 5.0.7

### ISSUE THREAD

**Issue by ukashif2** [scandipwa/scandipwa#5302]
Hi
i have installed scandipwa with my existing magento which is multi store.
this is my store on staging -- https://react.jebelz.com/

i have installed successfully but problem is when i am trying to load pages it shows error product fetching list failed. after that when i inspect element error show about graphql.

![image](https://user-images.githubusercontent.com/38689288/200849430-f246592c-aa4c-4909-bace-3d27bcfef918.png)

If you have any solution?.

**Comment by AleksandrsKondratjevs** [comment]
It says internal server error on request preview.
1. Magento is in production mode and that's why error shown as 'internal server error'
2. Error is on BE side. Please check magento logs to see why it fails to load products.
