### ISSUE TITLE
Does not show Products or Categories on the Home Page

### ISSUE THREAD

**Issue by ErikssonHerlo** [scandipwa/scandipwa#5303]
**Steps to reproduce:**
Install Magento, deploy Sample Data and then install ScandiPWA as indicated in the documentation.
1. Install Magento 
2. Deploy Sample Data
3. Install ScandiPWA as Magento Mode: https://docs.scandipwa.com/getting-started-1/magento-theme-mode

**Actual result**
Now, when I enter the home page, it does not show categories or products of any kind, including the default ones that are Men and Women, it gives me a 404 Not Found error.
However, when I searched for a product, this one works for me, but I need them to be on the Home Page.
![imagen](https://user-images.githubusercontent.com/48737385/200956590-bf9c1a3f-f40a-4120-a22a-d6bc466519f9.png)
![imagen](https://user-images.githubusercontent.com/48737385/200956636-e3753ac4-5ea8-4385-a51e-165b1345c8de.png)
![imagen](https://user-images.githubusercontent.com/48737385/200956678-421ac656-ad24-4c64-aa85-c591cbc897e6.png)

**Expected result**
I would expect to see something like this on the Home Page, since it is the same PWA, only deployed separately for testing, and we can see the products and categories, although I know they are from a Magento Remote Server
![imagen](https://user-images.githubusercontent.com/48737385/200958709-57edb0ff-dfd6-4591-a95b-992a07e5dd8b.png)

**Versions**
- ScandiPWA: 6.0.1 version
- Magento 2.4.4 Open Source
- Ubuntu Linux 22.04

**Comment by AleksandrsKondratjevs** [comment]
Hello!
Unfortunately magento sample data is not setting menu items for ScandiPWA theme. It means that categories and products exists and works, but you need to manually add them into menu manager. Here is documentation for it https://manual.scandipwa.com/progressive-web-app/menu-manager .
On other hand if downloading ScandiPWA sample data it will automatically set menu as it is on expected screenshot. Here is module: https://github.com/scandipwa/sample-data

**Comment by ErikssonHerlo** [comment]
I really appreciate your help. Could you tell me if the installation of ScandiPWA Sample Data is done through NPM, Composer or bin/magento. Because in the repository it does not indicate how to install it, or if I only have to download it and include it in the root folder. Again thank you very much for your help.

**Comment by AleksandrsKondratjevs** [comment]
It is available as composer dependency, same as magento sample data.
