### ISSUE TITLE
Can not add product to cart when user is logged in

### ISSUE THREAD

**Issue by johanroberthson** [scandipwa/scandipwa#5306]
**Steps to reproduce:**
1. Login as a user
2. Try to add product to cart. Error message "The requested qty is not available."
3. Its working for not logged in user.

**Actual result**
Error message, instead of adding product to cart.

**Expected result**
Product should be added to cart.

**Testing details**
**Screenshot/Screencast**
If applicable, add screenshots or screen-capture to help explain your problem. If you would like to share logs - please use [fenced code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).

**Versions**
- ScandiPWA: 6.0.2
- Tested with MSI enabled, not working there either.

**Comment by Elena-Evsa** [comment]
Hey, @johanroberthson 
Could you, please, provide more details to us? Right now we can not reproduce the bug:
> Screenshot, video
> Which type product, settings of product
> Any additional conditions

**Comment by johanroberthson** [comment]
Related to only one product. work when stock was updated.
