### ISSUE TITLE
Override Demo in Tutorial

### ISSUE THREAD

**Issue by fvlasie** [scandipwa/scandipwa#5310]
I am working through the Getting Started tutorial (https://docs.scandipwa.com/quick-start-guide) and in the override example it says to issue this command: `scandipwa override component Footer`

I get the message back:

`NOTE! No files have been generated.`

**Comment by fvlasie** [comment]
When attempting to copy the files manually I get the following error:
`Failed to compile.

./src/component/Footer/Footer.component.tsx
Attempted import error: 'Footer' is not exported from '/Users/admin/Documents/scandi/my-first-app/node_modules/@scandipwa/scandipwa/src/component/Footer/Footer.component' (imported as 'SourceFooter').
`

**Comment by val089** [comment]
I have got the same message when I try to override component.

![image](https://user-images.githubusercontent.com/30775271/205269888-3b064eef-389e-4fb7-a259-4afa86d245f9.png)

**Comment by fvlasie** [comment]
This is now working in the latest version. Thank you!
