### ISSUE TITLE
Error message shown if user unselect USD currency from 'Allowed Currencies'

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#5355]
**Steps to reproduce:**
in Admin:
1. Click Stores > Configuration > General > Currency Setup > Currency Options > Allowed Currencies
2. Unselect USD
3. Set :
Base Currency = EUR
Default Display Currency = EUR
Allowed Currencies = EUR, AUD, and any except USD
4. Flush cache
on FE:
5. Open website in incognito

**Actual result**
message: "Please correct the target currency"
Error message shown if user unselect USD currency from 'Allowed Currencies'

**Expected result**
Error message is not shown

**Testing details**
**Screenshot/Screencast**
![image](https://user-images.githubusercontent.com/84388061/207267573-dc705224-de34-456f-9854-4b628e5b7b94.png)

**Comment by websuits** [comment]
@AleksandrsKondratjevs i can still reproduce this issue. Can someone retest ? Default installation 2.4.4-p2 with 6.1.0
