### ISSUE TITLE
Development build on refresh page is empty

### ISSUE THREAD

**Issue by websuits** [scandipwa/scandipwa#5392]
**Steps to reproduce:**
1. Open local development build ( Storefront mode )
2. Click on any category or page, product
3. Refresh page

**Actual result**
Page refreshes, header and footer are loaded, but main content (product details for example) is not loaded, breadcrumbs keeps loading.

<img width="400" alt="Screenshot 2023-01-22 at 03 40 14" src="https://user-images.githubusercontent.com/42982977/213896841-bbef75fd-279d-461b-8610-6de6aee58a6c.png">

**Expected result**
I should see the exact, or updated (if changes), content i previously had on my page before refreshing.

**Testing details**
While using this version as a magento theme, page are reloaded corectly. This happens only in Storefront mode. No errors.
If you click on the same link while having the blank page, page remains blank, you must go in homepage (click logo) and then click again on the specific page to have it working.

**Versions**
- ScandiPWA: 6.1.0
- Magento 2.4.4-p2
- NPM 6.14.13
- NODE v14.17.0

**Additional context**
Default set-up, no changes, npm install, npm start.

**Comment by Santheepkumarr** [comment]
HI @websuits ,
Facing same issue,
Found any workaround for this ?
