### ISSUE TITLE
Zoomed image is not shown in popup 

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#5405]
**Steps to reproduce:**
1. Open any PDP with image
2. Click on image to zoom in

**Actual result**
Zoomed image is not shown in popup 

**Expected result**
Zoomed image is shown in popup 

**Testing details**
**Screenshot/Screencast**
https://vimeo.com/801905698/10e93c07a5

**Comment by Ylmzef** [comment]
which version?

**Comment by Ylmzef** [comment]
@fvlasie they are not updated.

**Comment by fvlasie** [comment]
@Ylmzef Elena's example is from the 40ksku demo...

**Comment by Ylmzef** [comment]
@fvlasie i see but which version :)

**Comment by fvlasie** [comment]
Maybe here: https://40kskudemo.scandipwa.com/default/leitz-234610-lamination-film-a-3591274.html

😅 Or perhaps I am misunderstanding something...
