### ISSUE TITLE
Mixed content issue on homepage

### ISSUE THREAD

**Issue by Ylmzef** [scandipwa/scandipwa#5437]
**Steps to reproduce:**
1. Open (https://40kskudemo.scandipwa.com/)
2. Click on any CMS page link from footer.
3. Go back to the homepage by clicking the logo in the header.

**Actual result**
The content of the last visited CMS page is loaded on the homepage.

**Versions**
ScandiPWA ver. 6.2.1
Magento ver. 2.4.6

**Comment by Andrii-Antoniuk** [comment]
I have a fix for this

**Comment by EagleSH** [comment]
![2023-06-26_15-02-59](https://github.com/scandipwa/scandipwa/assets/9654096/d50efaf0-9658-4b0d-8f4a-8b63c7a3aa5c)
![2023-06-26_15-00-45](https://github.com/scandipwa/scandipwa/assets/9654096/a1dfd24e-2b43-42d9-b585-741a52442cbd)
![2023-06-26_14-58-10](https://github.com/scandipwa/scandipwa/assets/9654096/0522e450-4873-4d28-a0dd-0453454ac5b5)

hey, you also having checkout issues as i have too, order summary section most of time endless loading, billing step all the time is broken also available this problem if you do f5 on shipping or billing step

did you saw it?

**Comment by EagleSH** [comment]
also if cms block/page having category link via widget its not working, a tag got removed
also, example, slider, working in dev mode, but not working in compiled mode (production)
