### ISSUE TITLE
Magento 2.4.7 support

### ISSUE THREAD

**Issue by jbruni** [scandipwa/scandipwa#5573]
### Is your feature request related to a problem?

ScandiPWA fails to run in Magento 2.4.7 install.

### Describe the solution you'd like to see

I would like to see Magento 2.4.7 compatibility.

### Additional context

![image](https://github.com/scandipwa/scandipwa/assets/69181/940fe960-7947-4707-803f-2b99388b5122)

![image](https://github.com/scandipwa/scandipwa/assets/69181/c7e2dfe4-566d-4468-8351-5ba55b0acbf3)

![image](https://github.com/scandipwa/scandipwa/assets/69181/7453c7f3-1acf-4302-84c0-26c0e9f022bb)

**Comment by jbruni** [comment]
For the specific issue seen in the screenshot above, a pull request has already been submitted at https://github.com/scandipwa/quote-graphql/pull/108

**Comment by jbruni** [comment]
For the issue shown in the second screenshot, there is also a pull request, submitted by the very same contributor: https://github.com/scandipwa/catalog-graphql/pull/155 🙏

**Comment by AleksandrsKondratjevs** [comment]
Support for 2.4.7 is released in ScandiPWA 6.4.0 version.
