### ISSUE TITLE
OOTB Magento settings items per page

### ISSUE THREAD

**Issue by rihardsratke** [scandipwa/scandipwa#681]
**Description**:
OOTB magneto show items per page being ignored

**Expected behavior**:
Configuration under Store -> Configuration -> Catalog -> Catalog -> Store front -> Products per page default value, taken in account

**To Reproduce**:
1. Go to Store -> Configuration -> Catalog -> Catalog -> Store front -> Products per page default value
2. Set value 10
3. Flush cache
4. Visit store front

**Comment by aleksandrakorolova** [comment]
This is duplicate #1483
