### ISSUE TITLE
Custom theme always takes `html` and `phtml` templates from vendor

### ISSUE THREAD

**Issue by yeegor** [scandipwa/scandipwa#800]
**Description**:
Custom theme always takes `html` and `phtml` templates from vendor. The only way to use the custom template is to rename it.

**Expected behavior**:
`html` and `phtml` templates are always taken from custom theme, until they are not present there.

**To Reproduce**:
1. Bootstrap the theme
2. Compile it in either dev or prod mode
3. Make a noticeable change in the (HTML for dev, PHTML for prod) template
4. Recompile the theme
5. Notice that nothing changed
6. Rename the template
7. Change the reference from config to template, use its relevant name
8. Recompile the theme
9. Notice your changes got applied

**Versions**:
- ScandiPWA: 2.x + 3.x

**Comment by yeegor** [comment]
TODO TEST

**Comment by yeegor** [comment]
Fixed by https://github.com/scandipwa/base-theme/commit/8cf7d93075641850c46cb9886393453b51e5f7ce#diff-c4a6ca78cbfaeecd22de546d2916ab02

**Comment by yeegor** [comment]
Re-reported again for 3.1.5, needs investigation.

**Comment by Elena-Evsa** [comment]
Closing after communication with developers as not actual
