### ISSUE TITLE
attributes type swatch visual show on category filter

### ISSUE THREAD

**Issue by bahramdavodi** [scandipwa/scandipwa#822]
**Description**:
options attribute type swatch is appending into other attributes

**Expected behavior**:
add an attribute with visuals watch (Color, Image)

**Screenshots, Video, Logs**

![Screenshot 2020-08-04 at 15 15 30](https://user-images.githubusercontent.com/18647834/89303959-2a703f00-d66d-11ea-87e9-b08fb88c2bbd.png)

![Screenshot 2020-08-04 at 14 32 01](https://user-images.githubusercontent.com/18647834/89304041-42e05980-d66d-11ea-96d3-ee5631df6e89.png)

![Screenshot 2020-08-04 at 14 33 31](https://user-images.githubusercontent.com/18647834/89304046-44118680-d66d-11ea-8dd1-ea1505cbfbe5.png)

**To Reproduce**:
1. Go to ' a category has swatch attribute'

**2.15.0**:
- src/Model/Resolver/Aggregations/SwatchData.php

**Comment by ejnshtein** [comment]
Unable to reproduce on 3.0.2.

![Screenshot_20200918_111502](https://user-images.githubusercontent.com/18352350/93573712-2a6b9a80-f9a0-11ea-85d2-7938e354df89.png)
![Screenshot_20200918_112106](https://user-images.githubusercontent.com/18352350/93574370-02306b80-f9a1-11ea-8a65-b21a1903ccf6.png)

**Comment by bahramdavodi** [comment]
the issue is not fixed. this problem happening when the swatch option id and category id is the same.
