### ISSUE TITLE
Bundles are cached in-memory

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/scandipwa#836]
**Description**:
For some reason the bundle is cached in memory. We should add hash to it.

**Expected behavior**:
No bundles should be cached in memory.

**Comment by ejnshtein** [comment]
Bundles are cached in-memory:
Browser caches bundles in memory.

Because of that after running npm run build and a new version is available on the server browser will not cache it because of old service-worker.

**Comment by Elena-Evsa** [comment]
Closing after communication with developers
