### ISSUE TITLE
I wish to build Scandi-menu from category tree

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/scandipwa#844]
**Description**:
Currently, we are forced to manually enter categories into the menu. Ideally, it would respect the Magento category tree. The details are however, unclear, needs some cool UI, or migration to Magento default menu (category tree only).

**Additional context**:
Originally reported by Andrey Kucheryavyy in community Slack.

**Comment by carinadues** [comment]
"Duplicate" of https://github.com/scandipwa/scandipwa/issues/3703
