### ISSUE TITLE
Translation function: allow JSX in variables

### ISSUE THREAD

**Issue by rMazeiks** [scandipwa/scandipwa#851]
# Description
Currently, the `__` translation function allows only variables that have a string representation:

```js
__('You have %s new messages', 42)
```

It would be nice if it could also accept JSX as arguments (and return a Fragment). For example,

```jsx
__('You have %s new messages', <b>42</b>)
```

Would return

```jsx
<>
  You have
  <b>42</b>
  new messages
</>
```

# Use cases:
- Adding special styling to part of the translation string
- Adding interactive elements such as links within a translation string

As it is now, this would require splitting up the source string into multiple parts:
```jsx
__('You have')
<b>42</b>
__('new messages')
```

This is not ideal because:
- Spaces are easy to miss and look ugly
- Translators might get confused if they have to translate incomplete strings such as "You have"

# Disadvantages
- It might be confusing if the same function can return either a string or an element depending on what the arguments are. This could also introduce bugs as JSX can't be used everywhere strings can. Possible alternative: keep `__` but add another `__jsx` translation function as described above.
- Increased complexity in the implementation

**Comment by yeegor** [comment]
This should be revisited after the new i18n (#1901) is approved.

**Comment by lianastaskevica** [comment]
Hey @rMazeiks! By design of our translation mechanism, unfortunately, it is impossible to implement it. The issue is that we cannot know in which places these translations will be used.
