### ISSUE TITLE
ESLint plugin for translation function usage

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/scandipwa#869]
**Description**:
Let's enforce translation functions, otherwise we miss them sometimes.

**Comment by alfredsgenkins** [comment]
I would also add a check to see if translation function is included in translations files (lookup in en_US.json) in i18n folder.

**Comment by winniepukki** [comment]
@carinadues It appears that [scandipwa eslint](https://github.com/scandipwa/eslint) package is archived and the quotes check will end up with the whole file being yellow warned. Should this be closed?
