### ISSUE TITLE
On Mobile in the cart header even if one item is added it says "Items".

### ISSUE THREAD

**Issue by lion152** [scandipwa/scandipwa#874]
**Description**:

In the cart header even if one item is added it says "Items"

**Expected behavior**:

When there is only one item in the cart it should say "Item"

Correct plural forms must be selected for every language depending on the number of items in the cart

**To Reproduce**:
1. Go to demo.scandipwa on mobile
2. Click on add 1 item to the cart
3. Click on the cart
4. Cart header says "1 Items"

**Screenshots, Video, Logs**

<img width="462" alt="Screenshot 2020-08-25 at 14 18 19" src="https://user-images.githubusercontent.com/4339464/91168294-15bc1f80-e6de-11ea-982f-4d2d2116930f.png">

**Additional context**:

Tested on mobile on Chrome.

Furthermore, some languages have more than 2 plural forms or only one plural form.

**Comment by aleksandrakorolova** [comment]
It was fixed after redesign #1624
![image](https://user-images.githubusercontent.com/73526235/103620916-075bfb00-4f3d-11eb-9d3d-682933de3dda.png)
