### ISSUE TITLE
Show checkout steps and progress

### ISSUE THREAD

**Issue by lion152** [scandipwa/scandipwa#889]
**Description**:

Show checkout steps and checkout progress above the fillable fields in the checkout page like in default Magento 2.

Requires designer input.

**Additional context**:

- Use the image in comments!
- Please, implement smooth animated transitions between the steps.

**Comment by yeegor** [comment]
I think this one is a good option!
![image](https://user-images.githubusercontent.com/46347627/97552113-83394480-19dc-11eb-8455-fbb4c693b477.png)

**Comment by yeegor** [comment]
This is done.

**Comment by yeegor** [comment]
Also, please make the transitions between the steps animated!

**Comment by snigo** [comment]
To achieve the option shown in the pictures ☝️ one will have to go either destructive way or implement "hacky" injection, as you want stepper to be a child of the `Checkout` component, but sibling of the whole checkout section and there are no render functionality that could be easily overridden in that spot

**Comment by aleksandrakorolova** [comment]
Closed task because it was implemented after redesign 
![Screenshot 2021-09-15 at 10 34 42](https://user-images.githubusercontent.com/73526235/133390879-6bd753d4-f7f5-4d7a-bf41-f07392257fa6.png)

**Comment by zans-laksa** [comment]
Mandatory requirements for the test day assignment:
1. Progressbar must match the website design colors.
2. The last step checkpoint doesn't render, you fill the progressbar to the end instead. So when you have shipping, billing and success steps, you render two checkpoints for shipping and billing, but on the last (third) step you fill the progressbar to the end so it becomes completed.
3. Components should be reusable. It should support any amount of steps.
4. When you complete a step, progressbar should fill the next segment with animation. For more details please see the comment above.
