### ISSUE TITLE
Enabling Show Company field in Admin does not add field in FE.

### ISSUE THREAD

**Issue by lion152** [scandipwa/scandipwa#905]
**Description**:

Enabling company in Stores>Configuration>Customers>Customer Configuration> Name and Adress options> Show Company, Company field still does not appear on FE

**Expected behavior**:

Enabling Show company field displays Company field in Checkout.

**Comment by aleksandrakorolova** [comment]
It isn't an issue. 
This feature not supported yet. Task for it #1497
