### ISSUE TITLE
Service worker updates in PWA

### ISSUE THREAD

**Issue by ioanmeri** [scandipwa/scandipwa#937]
**Description**:
Would be nice to see theme changes (after npm run build) without having to full page reload the SPA. 

**Additional context**:
Maybe by using push events would be a nice user experience as well.

**Comment by ioanmeri** [comment]
I 'm not sure that staleWhileRevalidate cache strategy and broadcast updates work as expected. Because, If I there are two categories and I start clicking quite fast each other, I end up seeing products of category 1 in category 2, or the titles do not correspond. So, data get out of sync.

We consider updates to instantly show up as a main requirement, more important than the ux (won't happen that often anyway).
For that, as a workaround, we periodically check the deployd_version.txt. of magento. If it's different than the one stored locally while SPA started, we trigger the showPopup action, the same in ```NewVersionPopup.container.js```, to force user to reload and get the latest assets.

**Comment by alfredsgenkins** [comment]
This is related to "OLDEST" issue in ScandiPWA - https://github.com/scandipwa/scandipwa/issues/425 We will address it someday :D It is pretty simple to do, thus we have not got our hands on it just yet!
