### ISSUE TITLE
[Multu Language store] Long FREEZ on theme compilation

### ISSUE THREAD

**Issue by RoboLV** [scandipwa/scandipwa#958]
**Description**:
When I compile Theme with 1 language, it took 5m to compile. But if I enable 6 languages in webpack, compilation goes for 1h. I'm using Docker setup.
On local setup: theme compilation with 1 language - 4m, 2 languages 10m, 3 languages 17m... 

**Expected behavior**:
Theme compilation with multiple languages should compile faster.

**Screenshots, Video, Logs**
<img width="1153" alt="изображение" src="https://user-images.githubusercontent.com/4116979/92619359-12be5300-f2ca-11ea-8bd9-df916e2bc3fa.png">

**To Reproduce**:
1. Add 6 languages to your theme
2. Build a theme with 6 languages

**Versions**:
- ScandiPWA: * 3.0.0-beta.7

**Additional context**:
Please Fix this

**Comment by yeegor** [comment]
This indeed is an issue, but the situation may already be improved with `create-scandipwa-app`.
If not, using [this package](https://github.com/trivago/parallel-webpack) should be considered.

**Comment by RoboLV** [comment]
Hey @yeegor, thanks for your reply.

The parallel build will not help, because the server has limited memory amount. Only to build single store it requires ~2gb of ram. it will be parallel, guess wi will run into memory limit. 

And how create-scandipwa-app will help us if we already have a project set up, And we have exact Magento backed?

**Comment by yeegor** [comment]
See https://github.com/scandipwa/scandipwa/issues/1901
