### ISSUE TITLE
"Add To Home Screen" button on homepage not triggering popup

### ISSUE THREAD

**Issue by lihaojin** [scandipwa/scandipwa#966]
**Description**:
- `Add To Home Screen` button on homepage does not trigger any popup on certain Android devices (Galaxy)

**Expected behavior**:
- `Add To Home Screen` should trigger a popup to allow user to add the site to home screen

**Screenshots, Video, Logs**
<img width="358" alt="Screen Shot 2020-09-10 at 9 15 46 AM" src="https://user-images.githubusercontent.com/35249237/92734109-3e7f1e80-f346-11ea-839d-6aaa840ebf70.png">

**To Reproduce**:
1. Go to homepage on https://demo.scandipwa.com/ using a Samsung galaxy device
2. Tap on `Add To Home Screen`
3. See that nothing happens

**Versions**:
- ScandiPWA: 2.17.0
- (Tested on Google Chrome)

**Comment by lion152** [comment]
Hello @lihaojin, can you please provide a Specific browser version and specific device you have issues on?

I have tested on about 10 different Galaxy devices on Chrome and I did not have any problems with the "Add to Home Screen" button popup

**Comment by lihaojin** [comment]
> Hello @lihaojin, can you please provide a Specific browser version and specific device you have issues on?
> 
> I have tested on about 10 different Galaxy devices on Chrome and I did not have any problems with the "Add to Home Screen" button popup

Device: Samsung Galaxy Note 3
OS: Android 5.0; SM-N900 Build/LRX21V
Chrome Version: 85.0.4183.81

**Comment by lion152** [comment]
We can't retrieve a Galaxy Note S3 or find a working emulator. 
We can't recreate this issue on any other Galaxy phone that is available to us. 
Could you please provide logs, videos, anything that will help us research this Issue.

**Comment by lihaojin** [comment]
> We can't retrieve a Galaxy Note S3 or find a working emulator.
> We can't recreate this issue on any other Galaxy phone that is available to us.
> Could you please provide logs, videos, anything that will help us research this Issue.

Is there an email I can send a file to? We have a recording of the test

**Comment by lion152** [comment]
You can attach files to GitHub comments and Issues

**Comment by lihaojin** [comment]
> You can attach files to GitHub comments and Issues

.MOV file types are not supported

**Comment by lion152** [comment]
Can you upload it somewhere and send a link to it, please?

**Comment by lihaojin** [comment]
> Can you upload it somewhere and send a link to it, please?
https://somethingdigital-my.sharepoint.com/:v:/p/pli/ERxfJ_M6AhRGlZ4aslnHBAYBac7R7Yk6hZDavUMsE5c1-Q?e=2GzkB7

**Comment by santosh-gaggle** [comment]
Getting the same issue with OnePlus 8 pro device 

video attached.

[WhatsApp Video 2020-09-21 at 2.37.28 PM.mp4.zip](https://github.com/scandipwa/base-theme/files/5254417/WhatsApp.Video.2020-09-21.at.2.37.28.PM.mp4.zip)

**Comment by lion152** [comment]
Recreated on OnePlus 8, when entering directly into category page. Seems to work for me on the homepage, need further investigation.

**Comment by santosh-gaggle** [comment]
@lion152 I checked it many devices like mi a1 and onePlus 8 pro but it does not trigger at any page even it category or home page
I also send the video file .you can see the issue there

**Comment by aleksandrakorolova** [comment]
Closed because can't reproduce
https://drive.google.com/file/d/1QG4hvI6g_4pUYAgpuuwyagclR-usjGIx/view?usp=sharing
@lihaojin you can recheck this on demo site
